### ISSUE TITLE
NFC Tag Issues with Internal URL

### ISSUE THREAD

**Issue by jaxonstagecrew** [home-assistant/android#1078]
**Is your feature request related to a problem? Please describe.**
Yes

**Describe the solution you'd like.**
Quicker response time for NFC using internal address.

**Describe alternatives you've considered, if any**
None.

**Additional context**
I just got my hands on some new NFC stickers and have successfully been able to read and write the tags.
However, when setting up the external URL for my duckdns domain, and an internal URL for my house, I am having issues with NFC
When connected to duckdns outside of my home, I am able to quickly read an NFC tag and it will run the automation, when I read the NFC tag from the internal URL, home assistant takes about 30 seconds on the "Processing Tag" screen, then runs the automation.
Is there anyway to speed up response time?

Thanks to all the developers for their hard work and I have been enjoying these new features!

**Comment by dshokouhi** [comment]
There really isnt anything special the app does when it comes to internal and external URL.  The logic in sending out the data is the same we just use a different URL.  This is more than likely a internal network issue on your end.  Also you may not even need to use the internal URL if it works locally and your router supports NAT loopback.

**Comment by jaxonstagecrew** [comment]
> There really isnt anything special the app does when it comes to internal and external URL. The logic in sending out the data is the same we just use a different URL. This is more than likely a internal network issue on your end. Also you may not even need to use the internal URL if it works locally and your router supports NAT loopback.

My router does not support NAT loopback and when I'm connected to just the home network without setting an external address, everything works perfect with no latency.  
The problem persists if I add the external address.  It also crashes the app if I have both set

**Comment by dshokouhi** [comment]
its impossible to setup the app without having the external URL set in App configuration.  Are you talking about the HA core configuration here?  You may need ot be a lil more descriptive about what you have set where and the URL format used.  Getting a little confusing here.

**Comment by jaxonstagecrew** [comment]
Thanks for the reply,
I am currently on version beta-406-ae25e7f-full, I have also attempted this on the most recent stable version and continue to have issues

I apologize for my description, been working from my phone recently, just got to a computer.

When setting up the app, I set my home assistant URL to https://xxxxx.duckdns.org/ If I use just this address alone, the app works perfectly and I am able to quickly read and write NFC tags and the app configuration button works perfectly.
This also works perfectly if I change the home assistant URL to http://192.168.0.101:8123.

The problem arises when I set my Home assistant URL to htttps://xxxx.duckdns.org/ and my internal URL to http://192.168.0.101:8123.
When doing this, whenever I try to open app configuration, I get a timeout error and closes the app.  This also has made it for NFC tags to take quicker to run automations

**Comment by dshokouhi** [comment]
What is your HA setup like? do you have SSL defined or is that from your proxy?

**Comment by jaxonstagecrew** [comment]
SSL is being defined through nginx proxy manager.

I do not have my internal and external address set in my HA core configuration

**Comment by dshokouhi** [comment]
what device is this happening on?

**Comment by dshokouhi** [comment]
also please double check the recommendations on this page to see if it is helpful <https://companion.home-assistant.io/docs/troubleshooting/networking>

Also when you say the app crashes does that mean you get an error pop-up or its force closed?

**Comment by jaxonstagecrew** [comment]
This is happening on a Google Pixel 4A
Throws a timeout error and asks if you want to close the app, when you click wait, the app will sit on a black screen.

**Comment by drinfernoo** [comment]
I can confirm this same behavior. I am in a similar situation (with no loopback), and using my external DuckDNS address along with my internal IP.

For me, it consistently takes 10s of "Processing tag" when I'm *inside* my network, and 3s when I'm *outside* of my network. Not sure why, but the results are the same for any tag I scan, or even with different devices.

**Comment by dshokouhi** [comment]
@drinfernoo can you install the latest beta and get us the ADB logs? https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs

lets look and see what the logs say when you scan it, we have some new debugging statements in the beta to help diagnose

**Comment by drinfernoo** [comment]
Sure, with version `beta-547-e604ad8-full` from GitHub:

https://drive.google.com/file/d/1fzL8bffD00Lc_fVevZxPAOe2EfaLplqR/view?usp=drivesdk

**Comment by dshokouhi** [comment]
@drinfernoo i have now requested access to the logs

**Comment by drinfernoo** [comment]
I gave access, my apologies. Didn't realize I shared the wrong link.

**Comment by dshokouhi** [comment]
Looks like there is some failure happening on your device from the scan, I see this same error several times:

```
[01-02 22:21:42.669 1305:5480 D/OpQuickReply]
setQuickReplyResumed focusedApp AppWindowToken{ac3b944 token=Token{e52a57 ActivityRecord{f9e37d6 u0 com.android.nfc/.NfcRootActivity t81768}}} pkgName com.android.nfc

[01-02 22:21:42.669 1305:1403 W/ContextImpl]
Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1084 com.android.server.am.AppStateBroadcaster.broadcastAppState:136 com.android.server.am.AppStateBroadcaster.sendApplicationFocusGain:52 com.android.server.am.ActivityManagerServiceInjector$4.run:481 android.os.Handler.handleCallback:883 

[01-02 22:21:42.669 1305:5480 W/System.err]
android.provider.Settings$SettingNotFoundException: driving_mode_state

[01-02 22:21:42.670 1305:5480 W/System.err]
	at android.provider.Settings$Secure.getIntForUser(Settings.java:6092)

[01-02 22:21:42.670 1305:5480 W/System.err]
	at com.android.server.fto.nl(Unknown Source:10)

[01-02 22:21:42.670 1305:5480 W/System.err]
	at com.android.server.fto.frontPackageChanged(Unknown Source:3)

[01-02 22:21:42.670 1305:5480 W/System.err]
	at com.android.server.OnePlusUtil$zta.zta(Unknown Source:61)

[01-02 22:21:42.670 1305:5480 W/System.err]
	at com.android.server.OnePlusUtil$zta.setFront(Unknown Source:25)

[01-02 22:21:42.670 1305:5480 W/System.err]
	at com.android.server.OnePlusUtil.setFront(Unknown Source:4)

[01-02 22:21:42.670 1305:5480 W/System.err]
	at com.android.server.wm.OpUtilInjector.setFront(OpUtilInjector.java:56)

[01-02 22:21:42.670 1305:5480 W/System.err]
	at com.android.server.wm.ActivityTaskManagerService.setResumedActivityUncheckLocked(ActivityTaskManagerService.java:5798)

[01-02 22:21:42.670 1305:5480 W/System.err]
	at com.android.server.wm.ActivityStack.onActivityStateChanged(ActivityStack.java:647)

[01-02 22:21:42.670 1305:5480 W/System.err]
	at com.android.server.wm.TaskRecord.onActivityStateChanged(TaskRecord.java:1916)

[01-02 22:21:42.670 1305:5480 W/System.err]
	at com.android.server.wm.ActivityRecord.setState(ActivityRecord.java:1997)

[01-02 22:21:42.670 1305:5480 W/System.err]
	at com.android.server.wm.ActivityStack.minimalResumeActivityLocked(ActivityStack.java:1618)

[01-02 22:21:42.670 1305:5480 W/System.err]
	at com.android.server.wm.ActivityStackSupervisor.realStartActivityLocked(ActivityStackSupervisor.java:958)

[01-02 22:21:42.670 1305:5480 W/System.err]
	at com.android.server.wm.ActivityStackSupervisor.startSpecificActivityLocked(ActivityStackSupervisor.java:1020)

[01-02 22:21:42.670 1305:5480 W/System.err]
	at com.android.server.wm.ActivityStack.resumeTopActivityInnerLocked(ActivityStack.java:3316)

[01-02 22:21:42.670 1305:5480 W/System.err]
	at com.android.server.wm.ActivityStack.resumeTopActivityUncheckedLocked(ActivityStack.java:2779)

[01-02 22:21:42.670 1305:5480 W/System.err]
	at com.android.server.wm.RootActivityContainer.resumeFocusedStacksTopActivities(RootActivityContainer.java:1169)

[01-02 22:21:42.670 1305:5480 W/System.err]
	at com.android.server.wm.ActivityStack.completePauseLocked(ActivityStack.java:1993)

[01-02 22:21:42.670 1305:5480 W/System.err]
	at com.android.server.wm.ActivityStack.activityPausedLocked(ActivityStack.java:1920)

[01-02 22:21:42.670 1305:5480 W/System.err]
	at com.android.server.wm.ActivityTaskManagerService.activityPaused(ActivityTaskManagerService.java:1767)

[01-02 22:21:42.670 1305:5480 W/System.err]
	at android.app.IActivityTaskManager$Stub.onTransact(IActivityTaskManager.java:2000)

[01-02 22:21:42.670 1305:5480 W/System.err]
	at android.os.Binder.execTransactInternal(Binder.java:1032)

[01-02 22:21:42.670 1305:5480 W/System.err]
	at android.os.Binder.execTransact(Binder.java:1005)

[01-02 22:21:42.678 1305:1406 D/OpPowerConsumpStatsInjector]
notifyPkgEvent

[01-02 22:21:42.678 1305:1403 W/ContextImpl]
Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1084 com.android.server.am.AppStateBroadcaster.broadcastAppState:136 com.android.server.am.AppStateBroadcaster.sendApplicationFocusGain:58 com.android.server.am.ActivityManagerServiceInjector$4.run:481 android.os.Handler.handleCallback:883 

[01-02 22:21:42.679 8888:8888 W/DiagSdk]
Main thread abused, please check stack trace below.
```

This device is also apparently trying to kill the app which can definitely cause a delay:

```
[01-02 22:21:53.626 1305:1413 W/UsageStatsService]
Failed to note usage stop
java.lang.IllegalArgumentException: Unable to stop usage for io.homeassistant.companion.android, not in use
	at com.android.server.usage.AppTimeLimitController.noteUsageStop(AppTimeLimitController.java:955)
	at com.android.server.usage.UsageStatsService.reportEvent(UsageStatsService.java:568)
	at com.android.server.usage.UsageStatsService$H.handleMessage(UsageStatsService.java:889)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.os.HandlerThread.run(HandlerThread.java:67)
```

There are lots of failures during this time as well that don't seem to be caused by the app.

```
[01-02 22:21:48.891 1305:4952 W/ActivityManager]
Exception when unbinding service com.chrome.dev/org.chromium.content.app.PrivilegedProcessService0
android.os.DeadObjectException
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:547)
	at android.app.IApplicationThread$Stub$Proxy.scheduleUnbindService(IApplicationThread.java:1672)
	at com.android.server.am.ActiveServices.removeConnectionLocked(ActiveServices.java:3628)
	at com.android.server.am.ActiveServices.unbindServiceLocked(ActiveServices.java:2222)
	at com.android.server.am.ActivityManagerService.unbindService(ActivityManagerService.java:15285)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2314)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3006)
	at android.os.Binder.execTransactInternal(Binder.java:1032)
	at android.os.Binder.execTransact(Binder.java:1005)
```

```
[01-02 22:21:47.787 29423:13570 W/ConnectionTracker]
Exception thrown while unbinding
java.lang.IllegalArgumentException: Service not registered: com.google.android.gms.measurement.internal.zzjr@66dbde
	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1766)
	at android.app.ContextImpl.unbindService(ContextImpl.java:1810)
	at android.content.ContextWrapper.unbindService(ContextWrapper.java:741)
	at com.google.android.gms.common.stats.ConnectionTracker.zza(com.google.android.gms:play-services-basement@@17.3.0:55)
	at com.google.android.gms.common.stats.ConnectionTracker.unbindService(com.google.android.gms:play-services-basement@@17.3.0:50)
	at com.google.android.gms.measurement.internal.zziz.zzah(com.google.android.gms:play-services-measurement-impl@@17.3.0:248)
	at com.google.android.gms.measurement.internal.zziz.zzam(com.google.android.gms:play-services-measurement-impl@@17.3.0:265)
	at com.google.android.gms.measurement.internal.zziz.zzc(com.google.android.gms:play-services-measurement-impl@@17.3.0:332)
	at com.google.android.gms.measurement.internal.zzjc.zza(com.google.android.gms:play-services-measurement-impl@@17.3.0:2)
	at com.google.android.gms.measurement.internal.zzai.run(com.google.android.gms:play-services-measurement-impl@@17.3.0:7)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.google.android.gms.measurement.internal.zzgn.run(com.google.android.gms:play-services-measurement-impl@@17.3.0:21)
```

At the same time I can see things like location working but not everything seems to be allowed.

The external log only shows a couple of these errors but not all.  This honestly seems like something with the system halting operation, its tough to tell whats going on.  Curious to see if @jaxonstagecrew has similar errors on his pixel device since a lot of the lines in the logs seem to be OnePlus specific.

**Comment by jaxonstagecrew** [comment]
I went ahead and moved over to NabuCasa cloud.  I had many issues with the ISP once I port forwarded so I decided that it would just be worth it to pay the subscription.  I recently changed to a new ISP and can do further testing with duckdns if you would like

**Comment by dshokouhi** [comment]
this issue seems to only happen over internal URL, are you still seeing it internally? I dont think it matters what ISP you are using if its only an internal URL thing.

**Comment by jaxonstagecrew** [comment]
No, after the switch to Nabu Casa, both internal and external tags are resolved quickly

**Comment by jaxonstagecrew** [comment]
What I find odd is how that on my duckdns setup, tags would resolve slowly over internal network.  While quickly on the external address.  I wonder if I had something different in my setup.  I'm going to try and replicate the issue

**Comment by dshokouhi** [comment]
Personally I dont use internal IP my router supports NAT loopback and I have my own domain name and SSL.  My tags scan within the second home or away.  The logic for the app doesn't change we just hit the URL's we have and send the data if possible.  Thats why when I hear about slowness it makes me wonder what could be causing it to be slow unrelated to the app.

**Comment by jaxonstagecrew** [comment]
My old router didn't support loopback, I recently went through and upgraded all of the networking equipment so It will just be easy for me to use my duckdns address for everything.  I believe that my problem was more related to either a network or hardware issue.  Not sure about @drinfernoo

**Comment by drinfernoo** [comment]
It just seems quite odd that everything else in my system works fine, internally or externally, except for tags 🤔

**Comment by dshokouhi** [comment]
you are seeing a delay, how do you know the other calls are also not delayed by 10 seconds? Have you tested something like an actionable notification to see if the event is delayed under the same circumstances?

**Comment by drinfernoo** [comment]
They are not. I regularly use actionable notifications to open into different Lovelace views or trigger automations.

**Comment by dshokouhi** [comment]
I see during the time of the logs you sent even the location report was delayed.

```
[01-02 22:21:47.191 29423:29423 D/LocBroadcastReceiver]
Received location that is 2391 milliseconds old, 1609654904800 compared to 1609654907191 with source fused
```

There should be another log line for either evaluating and not sending the location report or a log line for the report being sent, none of which exist after this line.

Its possible your device is trying to kill the app when its woken up by a scanned NFC tag.  We see the tag scanned successfully as the ID mentioned below. 

```
[01-02 22:21:42.740 29423:29423 D/TagReaderActivity]
nfcTagId: 5460ef49-328a-4814-ab9e-4fd6f169d1c6
```

During this time period we can see a series of things being killed or just outright denied access, take a look and see how many things are going on at this time.  Here is a small example of what I see:

```
[01-02 22:21:48.786 572:572 E/SELinux]
avc:  denied  { find } for interface=vendor.qti.hardware.servicetracker::IServicetracker sid=u:r:system_server:s0 pid=1305 scontext=u:r:system_server:s0 tcontext=u:object_r:default_android_hwservice:s0 tclass=hwservice_manager permissive=0

[01-02 22:21:48.806 1305:1849 I/ActivityManager]
Killing 24000:com.chrome.dev:privileged_process0/u0a172 (adj 995): empty #31

[01-02 22:21:48.873 23910:23945 W/chromium]
[WARNING:gpu_process_host.cc(1279)] The GPU process has crashed 1 time(s)

[01-02 22:21:48.875 572:572 E/SELinux]
avc:  denied  { find } for interface=vendor.qti.hardware.servicetracker::IServicetracker sid=u:r:system_server:s0 pid=1305 scontext=u:r:system_server:s0 tcontext=u:object_r:default_android_hwservice:s0 tclass=hwservice_manager permissive=0

[01-02 22:21:48.884 572:572 E/SELinux]
avc:  denied  { find } for interface=vendor.qti.hardware.servicetracker::IServicetracker sid=u:r:system_server:s0 pid=1305 scontext=u:r:system_server:s0 tcontext=u:object_r:default_android_hwservice:s0 tclass=hwservice_manager permissive=0
```

```
[01-02 22:21:52.845 29423:29423 D/TagReaderActivity]
Tag scanned to HA successfully
```

This is when the call is successful

Try to double and triple check every device setting you have to let the HA app run in the background without any battery optimizations or anything.  This site offers some tips: https://dontkillmyapp.com/

**Comment by drinfernoo** [comment]
Here's the same logs, with the same tag, from my wife's phone:

Internal: https://drive.google.com/file/d/1-YC95Xh-3nNfPMKNS8Par9_fTih0NRvK/view?usp=sharing

External: https://drive.google.com/file/d/1X-XCkDqYc8CHXOpDoMJ79ZSI0BCFgPmq/view?usp=sharing

I also went through and made sure that all of the battery and background optimizations are off for my phone, but still see similar results.

**Comment by dshokouhi** [comment]
I have a potential fix here if anyone wants to test it out.  Please load the debug APK from https://github.com/home-assistant/android/actions/runs/472903018 and make sure to setup the debug APK with the same URLs as production including the home SSID, we want a apples to apples test here please :).   You can install this app side by side the production version.  The changes here I think might fix/alleviate the situation so feedback is appreciate.  If you still experience an issue please grab the debug logs however be mindful the debug logs from the debug APK does contain sensitive information such as the URL and your auth token so make sure to sanitize it completely before posting.

**Comment by drinfernoo** [comment]
I will test this tomorrow. Here's hoping!

**Comment by drinfernoo** [comment]
I can confirm that your changes seem to have fixed it! Scanning tags (and actionable notifications, for good measure) are now just as fast for me internally as they are externally 😀

**Comment by dshokouhi** [comment]
thanks for testing @drinfernoo 😃

**Comment by drinfernoo** [comment]
Thanks for hearing me out 😅
