### ISSUE TITLE
Widgets issue with Https and the same internal/external url

### ISSUE THREAD

**Issue by PoVPoV29** [home-assistant/android#1157]
**Home Assistant Android version:3.0.1

**Android version:10

**Phone model:Samsung S10e

**Home Assistant version:0.117.4

**Last working Home Assistant release (if known):not sure but previous majour version of before activate HTTPS

**Description of problem: after some time (minutes I think) widget can't be used.(error message at the bottom of the android laucher : unabkle to fetch data from configured entity) and When I activate the widget (error message : unable to send service call)
The only way to use widget is to launch the app first and then I can use widget for a moment.

**Additional information: I am not sure if the issue is related to the version of the HTTPS activation.

**Comment by dshokouhi** [comment]
These errors show up when the call to your home assistant instance fails. Can you double check the app has permission to run in the background? It sounds like your system is killing the app and not allowing it to run in the background.

**Comment by PoVPoV29** [comment]
Hello,
In the app parameters it seems to be ok:
![Screenshot_20201107-213332_Home Assistant.jpg](https://user-images.githubusercontent.com/69581008/98450894-f7908800-2140-11eb-88ca-ed9acf38eff6.jpg)

**Comment by PoVPoV29** [comment]
The issue wasn't happening one week ago and I didn't change anything else than https

**Comment by PoVPoV29** [comment]
The issue is not happening with WiFi in local network. I can reproduce the issue in 4G after some time

**Comment by dshokouhi** [comment]
Do you have data saver enabled?

**Comment by PoVPoV29** [comment]
What do you mean by data server? Data through 4G? Yes

**Comment by dshokouhi** [comment]
> What do you mean by data server? Data through 4G? Yes

Data saver, not server

https://www.samsung.com/au/support/mobile-devices/what-is-the-data-saver-feature/

**Comment by PoVPoV29** [comment]
Data server is disabled

**Comment by PoVPoV29** [comment]
Maybe related to #1158

**Comment by dshokouhi** [comment]
You say this issue started after you enabled HTTPS on your HA server? Does it go away when you disable that?

**Comment by PoVPoV29** [comment]
I will try that but the timestamp is the same as the release of the 3.0.0 version. #1158 
I will keep you updated

**Comment by PoVPoV29** [comment]
Hello,
I confirm the issue is about https and not   release 3.0. how can I diagnose this issue?

**Comment by PoVPoV29** [comment]
I haven't any issue without https

**Comment by dshokouhi** [comment]
@PoVPoV29 I hope you are not attempting to use `https` over a local IP that would be the issue right there.  We need more data to go by to help you out.

**Comment by PoVPoV29** [comment]
No I use synology ddns. I have to launch the app to make widgets working. Which data do you need and how can I get it?

**Comment by PoVPoV29** [comment]
Hello,
I think about a dns cache issue so I decide to don't use the same url for internal and external ( ddns synology for internal and duckdns for external) but I can't connect from external now. Is there a relationship between certificate name  and url for the android app ? In a web browser it's working fine from external but no from the app. Any idea ?

**Comment by PoVPoV29** [comment]
Anybody to help me diagnose and fix this issue? I don't know how to take log on an Android device.
Thanks

**Comment by dshokouhi** [comment]
@PoVPoV29 you can get the device logs using Android Studio but if you don't feel comfortable doing that just wait until someone else can come and help. Please have patience your bug ticket is only 9 days old.  More than likely your issue may not be with the app since you said when you disable `https` it is working.  There are some tips here:

https://companion.home-assistant.io/docs/troubleshooting/networking

If those don't help you will want to be more specific about your particular setup and wait for someone to help.

**Comment by PoVPoV29** [comment]
Hello,
First thanks @dshokouhi , I read the doc but it seems I respect the specs.
I am not a developper but here the logs I find on my HA when I use one of my widgets from external AND internal network : 
`2020-11-16` 21:35:26 ERROR (MainThread) [homeassistant.components.mobile_app.webhook] Error when calling service during mobile_app webhook (device name: Alain_HA): not a valid value for dictionary value @ data['entity_id']
2020-11-16 21:35:26 ERROR (MainThread) [homeassistant.components.webhook] Error processing webhook 27a4641b246ee56f39b09b9d282ace2bc460b7baaba1d51ae43e33d9f64713bb
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mobile_app/webhook.py", line 221, in webhook_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1402, in async_call
    processed_data = handler.schema(service_data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 218, in __call__
    return self._exec((Schema(val) for val in self.validators), v)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 340, in _exec

    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 336, in _exec
    v = func(v)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: not a valid value for dictionary value @ data['entity_id']
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/webhook/__init__.py", line 96, in async_handle_webhook
    response = await webhook["handler"](hass, webhook_id, request)
  File "/usr/src/homeassistant/homeassistant/components/mobile_app/webhook.py", line 205, in handle_webhook
    return await asyncio.shield(
  File "/usr/src/homeassistant/homeassistant/components/mobile_app/webhook.py", line 140, in validate_and_run
    return await func(hass, config_entry, data)
  File "/usr/src/homeassistant/homeassistant/components/mobile_app/webhook.py", line 235, in webhook_call_service
    raise HTTPBadRequest() from ex
aiohttp.web_exceptions.HTTPBadRequest: Bad `Request`

My config is very simple : I generate a certificat from my synology Nas with letsencrypt. I imported it on my HA and write the config in http:
HTTPS is working find from app and web browser in internal and external network. Only widgets are impacted in external network.
I am available to provide logs or give more informations on my setup.
Thanks to anyone for the helps.

**Comment by PoVPoV29** [comment]
``

**Comment by PoVPoV29** [comment]
Here the logs I take from my android device : 
2020-11-19 12:07:39.768 31336-31336/? D/ButtonWidget: Service Call Data loaded:
    domain: cover
    service: close_cover
    service_data: {"entity_id":["cover.portail"]}
2020-11-19 12:07:39.798 31336-31354/? I/mpanion.androi: Waiting for a blocking GC ProfileSaver
2020-11-19 12:07:39.830 31336-31354/? I/mpanion.androi: WaitForGcToComplete blocked ProfileSaver on HeapTrim for 32.479ms
2020-11-19 12:07:39.917 2769-2769/? I/io_stats: !@   8,0 r 1346597 46990332 w 455881 8391668 d 112267 57954560 f 126150 170390 iot 606388 487784 th 102400 0 0 pt 0 inp 0 0 36742.847
2020-11-19 12:07:39.928 1051-2067/? D/CustomFrequencyManagerService: FrequencyrequestList.getNextSchedTuneBoostRequest, index: 0
2020-11-19 12:07:39.961 31336-17083/? E/CONSCRYPT: ------------------Untrusted chain: ----------------------
2020-11-19 12:07:39.961 31336-17083/? E/CONSCRYPT: == Chain0 == 
     Version:   3
2020-11-19 12:07:39.962 31336-17083/? E/CONSCRYPT:  AuthorityKeyIdentifier:   XXXXXX
2020-11-19 12:07:39.962 31336-17083/? E/CONSCRYPT:  SubjectKeyIdentifier:   XXXXXX
2020-11-19 12:07:39.962 31336-17083/? E/CONSCRYPT:  Serial Number:   XXXXXXX
2020-11-19 12:07:39.962 31336-17083/? E/CONSCRYPT:  SubjectDN:   CN=XXXXX.synology.me
2020-11-19 12:07:39.962 31336-17083/? E/CONSCRYPT:  IssuerDN:   CN=Let's Encrypt Authority X3, O=Let's Encrypt, C=US
2020-11-19 12:07:39.962 31336-17083/? E/CONSCRYPT:  Get not before:   Sun Nov 01 15:04:10 GMT+01:00 2020
2020-11-19 12:07:39.963 31336-17083/? E/CONSCRYPT:  Get not after:   Sat Jan 30 15:04:10 GMT+01:00 2021
2020-11-19 12:07:39.963 31336-17083/? E/CONSCRYPT:  Sig ALG name:   SHA256withRSA
2020-11-19 12:07:39.963 31336-17083/? E/CONSCRYPT:  Signature:   -XXXXXXXX
2020-11-19 12:07:39.979 31336-17083/? E/CONSCRYPT:  Public key:
     
    XXXXXXXXX
 
2020-11-19 12:07:40.002 1051-1280/? D/SensorHubManager: onGetSensorHubDataLocked: library(22) = 1, 1, 44, 1, 1, 1, 2, 99, 21, 51, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 39, 56
2020-11-19 12:07:40.003 1051-1281/? D/CAE: onGetSensorHubData(SensorHubParserProvider.java:91) - onGetSensorHubData Event [event buffer len :22], AP_WAKEUP
2020-11-19 12:07:40.003 1051-1281/? I/CAE: parse(SensorHubParserProvider.java:192) - buffer size = 22
2020-11-19 12:07:40.003 1051-1281/? I/CAE: parse(SensorHubParserProvider.java:203) - 1, 1, 44, 1, 1, 1, 2, 99, 21, 51, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 39, 56,
2020-11-19 12:07:40.004 1051-1281/? I/CAE: parse(SLMonitorRunner.java:301) - parse:4
2020-11-19 12:07:40.004 1051-1281/? D/CAE: parse(SLMonitorRunner.java:323) - dataSize:1
2020-11-19 12:07:40.004 1051-1281/? D/CAE: display(SLMonitorRunner.java:604) - ================= STEP_LEVEL_MONITOR =================
2020-11-19 12:07:40.005 1051-1281/? I/CAE: display(SLMonitorRunner.java:721) - DT=[1], DC=[1], TS=[1605784047923], ST=[SE], SC=[0], DI=[0.0], CA=[0.0], DU=[10040]
2020-11-19 12:07:40.005 1051-1286/? D/SemContextService: Service.updateContext() : service = Step Level Monitor
2020-11-19 12:07:40.006 24483-24483/? D/SemContextManager: onSemContextChanged() : event = Step Level Monitor
2020-11-19 12:07:40.006 24483-6648/? I/Sensor[0x06]: [0x01] 33
2020-11-19 12:07:40.006 24483-6648/? I/Sensor[0x04]: [0x01] 1605784047923[0x02] 0[0x03] 2[0x04] 10040
2020-11-19 12:07:40.030 31336-17083/? E/CONSCRYPT: ------------------Untrusted chain: ----------------------
2020-11-19 12:07:40.030 31336-17083/? E/CONSCRYPT: == Chain0 == 
     Version:   3
2020-11-19 12:07:40.030 31336-17083/? E/CONSCRYPT:  AuthorityKeyIdentifier:   XXXXX
2020-11-19 12:07:40.030 31336-17083/? E/CONSCRYPT:  SubjectKeyIdentifier:   XXXX
2020-11-19 12:07:40.031 31336-17083/? E/CONSCRYPT:  Serial Number:   XXXXXX
2020-11-19 12:07:40.031 31336-17083/? E/CONSCRYPT:  SubjectDN:   CN=XXXXX.synology.me
2020-11-19 12:07:40.031 31336-17083/? E/CONSCRYPT:  IssuerDN:   CN=Let's Encrypt Authority X3, O=Let's Encrypt, C=US
2020-11-19 12:07:40.031 31336-17083/? E/CONSCRYPT:  Get not before:   Sun Nov 01 15:04:10 GMT+01:00 2020
2020-11-19 12:07:40.031 31336-17083/? E/CONSCRYPT:  Get not after:   Sat Jan 30 15:04:10 GMT+01:00 2021
2020-11-19 12:07:40.031 31336-17083/? E/CONSCRYPT:  Sig ALG name:   SHA256withRSA
2020-11-19 12:07:40.031 31336-17083/? E/CONSCRYPT:  Signature:   -XXXXXXXXXXXXXX
2020-11-19 12:07:40.044 31336-17083/? E/CONSCRYPT:  Public key:
     
     XXXXXXX


2020-11-19 12:07:40.048 31336-31336/? E/ButtonWidget: Could not send service call.
    io.homeassistant.companion.android.common.data.integration.IntegrationException
        at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl.callService(IntegrationRepositoryImpl.kt:209)
        at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl$callService$1.invokeSuspend(Unknown Source:12)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:55)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
2020-11-19 12:07:40.059 31336-31336/? D/Toast: show: focusDisplayId = 0, isFocusInDesktop = false mCustomDisplayId=-1
2020-11-19 12:07:40.064 1051-2067/? I/EdgeLightingManager: isCallingUserSupported : callingUserId=0, mUserId=0, isDualAppId=false
2020-11-19 12:07:40.064 1051-2067/? I/EdgeLightingManager: showForToast : packageName = io.homeassistant.companion.android
2020-11-19 12:07:40.064 1051-2067/? I/EdgeLightingClientManager: isAvailableEdgeLighting: condition=1 mCondition=3 mIsConnected=false0
2020-11-19 12:07:40.064 1051-2067/? I/EdgeLightingPolicyManager: isAcceptableApplication:  pkg=io.homeassistant.companion.android , range=512 , includeAllApp=false , userId=0 , infoRange=0 , infoCategory=0
2020-11-19 12:07:40.064 1051-2067/? I/EdgeLightingManager: showForToast : return false by isAcceptableApplication.
2020-11-19 12:07:40.065 1051-2067/? W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1088 com.android.server.notification.DisplayToast.sendIntentForToastDumpLog:156 com.android.server.notification.DisplayToast.outFile:106 com.android.server.notification.DisplayToast.out:62 com.android.server.notification.NotificationManagerService$12.enqueueToastForLog:2709 
2020-11-19 12:07:40.066 568-1944/? I/SurfaceFlinger: id=2675 createSurf (0x0),-1 flag=80004, WindowToken{b63d1ad android.os.Binder@8582ec4}#0
2020-11-19 12:07:40.075 31336-31353/? V/Toast: SHOW: android.widget.Toast$TN@2e3bc5b
2020-11-19 12:07:40.082 1051-1051/? D/AppWidgetServiceImpl: handleNotifyUpdateAppWidget, appWidgetId = 43
2020-11-19 12:07:40.084 31336-31336/? V/Toast: HANDLE SHOW: android.widget.Toast$TN@2e3bc5b mView=null mNextView=android.widget.LinearLayout{7bd1cf8 V.E...... ......I. 0,0-0,0}
2020-11-19 12:07:40.084 31336-31336/? V/Toast: HANDLE HIDE: android.widget.Toast$TN@2e3bc5b mView=null
2020-11-19 12:07:40.084 1887-1887/? I/AppWidgetHost: updateAppWidgetView, appWidgetId = 43, v = com.android.launcher3.widget.LauncherAppWidgetHostView{f68915a VFE....L. R....... 0,668-251,1003 #c0}
2020-11-19 12:07:40.093 1051-3345/? D/InputTransport: Input channel constructed: '5692873', fd=788
2020-11-19 12:07:40.093 1051-3345/? D/InputTransport: Input channel constructed: '5692873', fd=789
2020-11-19 12:07:40.094 1051-1135/? V/MARsPolicyManager: onAlertToastWindowStarted pkgName = io.homeassistant.companion.android, userId = 0
2020-11-19 12:07:40.094 568-615/? I/SurfaceFlinger: id=2676 createSurf (0x0),-1 flag=80004, 5692873 Toast#0
2020-11-19 12:07:40.095 1051-3345/? D/InputTransport: Input channel destroyed: '5692873', fd=789
2020-11-19 12:07:40.096 31336-31336/? I/ViewRootImpl@617c337[Toast]: setView = android.widget.LinearLayout@7bd1cf8 TM=true MM=false
2020-11-19 12:07:40.096 31336-31336/? V/Toast: Text: Vnab in android.widget.Toast$TN@2e3bc5b
2020-11-19 12:07:40.103 1051-3345/? V/WindowManager: Relayout Window{5692873 u0 Toast}: viewVisibility=0 req=645x132
2020-11-19 12:07:40.104 1887-1887/? D/LauncherAppWidgetHostView: setResizeScaleResult() 251/ 335 scaleToResize = 0.98406374(widget id = 46) ee69b6f 504,668-755,1003
2020-11-19 12:07:40.104 1887-1887/? D/LauncherAppWidgetHostView: setResizeScaleResult() 251/ 335 scaleToResize = 0.98406374(widget id = 45) 266307c 0,1002-251,1337
2020-11-19 12:07:40.104 1887-1887/? D/LauncherAppWidgetHostView: setResizeScaleResult() 251/ 335 scaleToResize = 0.98406374(widget id = 44) 4309d05 252,668-503,1003
2020-11-19 12:07:40.104 1887-1887/? D/LauncherAppWidgetHostView: setResizeScaleResult() 251/ 335 scaleToResize = 0.98406374(widget id = 43) f68915a 0,668-251,1003
2020-11-19 12:07:40.104 1887-1887/? D/LauncherAppWidgetHostView: setResizeScaleResult() 507/ 335 scaleToResize = 0.9842209(widget id = 2) 16b7f8b 504,0-1011,335
2020-11-19 12:07:40.104 1887-1887/? D/LauncherAppWidgetHostView: setResizeScaleResult() 251/ 335 scaleToResize = 0.98406374(widget id = 48) ac03296 0,334-251,669
2020-11-19 12:07:40.106 568-1944/? I/SurfaceFlinger: id=2677 createSurf (645x132),1 flag=4, Toast$_31336#0
2020-11-19 12:07:40.107 1051-3345/? D/WindowManager: makeSurface duration=1 name=Toast$_31336
2020-11-19 12:07:40.109 1051-3345/? V/WindowManager: Relayout 31336: mAttrs={(0,192)(wrapxwrap) gr=BOTTOM CENTER sim={adjust=pan} ty=TOAST fmt=TRANSLUCENT wanim=0x1030004
      fl=1040098 naviIconColor=0}, display=0




For information, I test with another andrdoid device and the issue is the same.
I installed my certificate in the android user certificate store on my device but nothing change.

**Comment by edenhaus** [comment]
I use the same URL for external and internal with HTTPS without any problems. All widgets works correctly.
My DNS Server redirect the traffic within my network directly to HA without leaving my network.
I have only set the external URL in the app and in the HA (Config->Core).

@PoVPoV29 installing the certificate should not be required.
Have you set only the external url or also the internal url for the app and HA?

**Comment by PoVPoV29** [comment]
Hello,
Yes I do.

**Comment by johngianni** [comment]
Any solutions to this issue, yet? My widgets are not working. tried everything!

**Comment by dshokouhi** [comment]
@johngianni If the service call is not successful not much the app can do unfortunately.  Unless something else in the logs stick out.  The exception that I see is one that is handled by the app and only happens when the call is not successful.  Look at the logs on your device to see if anything is different compared to above.  The logs above indicate a SSL cert error I think.

https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs

**Comment by johngianni** [comment]
Thx for coming back to quicky. strangely the logcat does not contain any evidence of any homeassistant crash. Tried with logcat reader app, but also with adb command. 

.\adb logcat | findstr homeass

**Comment by dshokouhi** [comment]
@johngianni make sure to enable verbose logging as per above, you will definitely see logs for making a service call.  You can expect to see the service data before the call gets sent. Try to not use a filter if you don't see it.

The logs will start like the one up above.

```
2020-11-19 12:07:39.768 31336-31336/? D/ButtonWidget: Service Call Data loaded:
domain: cover
service: close_cover
service_data: {"entity_id":["cover.portail"]}
```

then afterwards the failure will appear.

**Comment by johngianni** [comment]
Thx, managed to get the log (cleaned it a bit): 

`
Service Call Data loaded:
domain: homeassistant
service: toggle
service_data: {"entity_id":["switch.cancello"]}
Sending service call to Home Assistant
Could not send service call.
ButtonWidget: io.homeassistant.companion.android.common.data.integration.IntegrationException
ButtonWidget:  at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl.callService(IntegrationRepositoryImpl.kt:210)
ButtonWidget:  at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl$callService$1.invokeSuspend(Unknown Source:12)
ButtonWidget:  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
ButtonWidget:  at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
ButtonWidget:  at android.os.Handler.handleCallback(Handler.java:900)
ButtonWidget:  at android.os.Handler.dispatchMessage(Handler.java:103)
ButtonWidget:  at android.os.Looper.loop(Looper.java:219)
ButtonWidget:  at android.app.ActivityThread.main(ActivityThread.java:8387)
ButtonWidget:  at java.lang.reflect.Method.invoke(Native Method)
ButtonWidget:  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
ButtonWidget:  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
InputEventReceiver: dispatchInputInterval 1000000`

On Huawei P40 Pro Android 10

**Comment by dshokouhi** [comment]
Are you using any kind of filter in the logs? Try to take that out and see if Android complains about the same thing up above. You can change the filter to the date and time to make it easier

**Comment by andriej** [comment]
@johngianni sorry for OT but I can see you're using P40 Pro. how do you solve no-notifications since google services are missing? 

Regarding the topic - I have same domain and address for internal and  external (https) and has no issues.

**Comment by johngianni** [comment]
@dshokouhi calling .\adb logcat *:V > dump.txt . I have no evidence of the above SSL errors. Only the one I've attached.

@andriej I've managed to sideload GMS on my P40 with the IZPlay app. No issues with notifications. 

Could the error be related to Huawei environment?

**Comment by dshokouhi** [comment]
> @dshokouhi calling .\adb logcat *:V > dump.txt . I have no evidence of the above SSL errors. Only the one I've attached.

We still would like to see the logs around the time it happened to see what else can be the cause.  As of now all we know is that the call to HA is failing as this error is caught and handled by the app.  Are there any errors in the HA logs when you send it?  What is your  network setup like?  Have you tried [starting fresh](https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app) to see if it clears up the issue?  Have you tested other app functionality such as actionable notifications or a template widget?

**Comment by johngianni** [comment]
Morning all... so... just to let you know, I've fixed the issue. My steps:

1) Clean install of the app as by [starting fresh](https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app) docs
2) changed the SSL certificate of the HA server from the one obtained automatically through Duck DNS to a newly issued Letsencrypt cert on my own domain, created through certbot.
3) recreated the widgets.

Thanks for helping.
