### ISSUE TITLE
Login impossible (Error: Something went wrong)

### ISSUE THREAD

**Issue by metodidavidovic** [home-assistant/android#1221]
**Home Assistant Android version:**
3.0.2-full

**Android version:**
5.1

**Phone model:**
Moto G (XT1032)

**Home Assistant version:**
0.118.4

**Last working Home Assistant release (if known):**
0.107.5

**Description of problem:**
Fresh install of HA for Android cannot pass initial configuration. After entering URL (http, not an https), instead of asking for username and password, new activity (screen) displays notice about logging in with Home Assistant Local and "Next" button. Clicking on it results in message "Error: Something went wrong". Nothing else in app is possible except going back and repeating everything.

**Traceback (if applicable):**
```
2020-11-29 23:51:01 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 60, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 83, in handle_req
    resp = await func(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/components/auth/login_flow.py", line 242, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 153, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 201, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/usr/src/homeassistant/homeassistant/auth/providers/homeassistant.py", line 327, in async_step_init
    user_input["username"], user_input["password"]
KeyError: 'username'
```

**Screenshot of problem:**
![Screenshot_2020-11-29-23-53-29](https://user-images.githubusercontent.com/75225635/100556323-e8b17700-32a1-11eb-83f0-791476bc7d41.png)

**Additional information:**
HA works fine on Raspberry Pi3 and is accessible from various browsers. Logout and login as well. Also from Chrome in Android. 
HA app for Android worked fine for 1+ year. Issue appeared after bundle of changes (switching to server docker install, HA server upgrade of configuration and database, Android app upgrade to the latest version, ...). 
Various actions does not help: clearing app data and cache in Android, downgrading app, clearing all tokens through web UI, entering FQDN or IP in URL field, setting up external_url and internal_url in configuration.yml, ...

I would like to avoid removing .storage and existing users or starting server configuration from scratch.

Thank you for any hint or advice what to try next.

**Comment by dshokouhi** [comment]
Can you check that android system webview is up to date?

**Comment by metodidavidovic** [comment]
Thank you, that was the cause. After WebView upgrade to latest version, HA for Android displays username/password login form and works ok.

If developers find time, please code some meaningfull error message about minimal required Webview version. Probably there are more people with an idea to use old phones or tablets as "HA dashboard device".

**Comment by SlavikS-PL** [comment]
I had the same problem on Android 4.2.2. I tried Chrome browser but WebView can't be installed. 
I found that Opera browser works well on Android 4.2.2 :)
