### ISSUE TITLE
Android 11 Power Menu controls not working with Tuya integration enabled

### ISSUE THREAD

**Issue by torbjornaxelsson** [home-assistant/android#1258]
**Home Assistant Android version:** 3.0.2-full

**Android version:** 11

**Phone model:** Google Pixel 4a

**Home Assistant version:** 2020.12.1

**Last working Home Assistant release (if known):**

**Description of problem:**

If I add the Tuya integration to Home Assistant I can no longer add more controls to the Android Power menu. It says "Loading..." for about 20 seconds, followed by "Controls could not be loaded. Check the Home Assistant app to make sure that the app settings haven't changed."

Previously added controls still work. If I remove the Tuya integration, I can add controls again.

There is nothing in the Home Assistant log. Please advice if there is anything else I can do to aid troubleshooting.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
@torbjornaxelsson please get us the crash logs as indicated by the link in the traceback section.  We need those to fix this issue.

https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs

**Comment by torbjornaxelsson** [comment]
> @torbjornaxelsson please get us the crash logs as indicated by the link in the traceback section. We need those to fix this issue.
> 
> https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs

Thank you! Here is what I get:

`
<<< log_count = 12 >>>
[12-27 10:10:23.953 10798:10823 D/ControlsProviderLifecycleManager]
Binding service Intent { cmp=io.homeassistant.companion.android/.controls.HaControlsProviderService (has extras) }

[12-27 10:10:23.962 1676:2306 W/AppOps]
Noting op not finished: uid 10291 pkg io.homeassistant.companion.android code 79 startTime of in progress event=1609092623956

[12-27 10:10:23.987 10798:10798 D/ControlsProviderLifecycleManager]
onServiceConnected ComponentInfo{io.homeassistant.companion.android/io.homeassistant.companion.android.controls.HaControlsProviderService}

[12-27 10:10:23.989 10798:10798 D/ControlsProviderLifecycleManager]
subscribe ComponentInfo{io.homeassistant.companion.android/io.homeassistant.companion.android.controls.HaControlsProviderService} - [input_number.slider, input_boolean.garage_toggle]

[12-27 10:10:31.294 10798:10798 D/ControlsProviderLifecycleManager]
load ComponentInfo{io.homeassistant.companion.android/io.homeassistant.companion.android.controls.HaControlsProviderService}

[12-27 10:10:31.397 12769:12912 E/HaConProService]
Error getting list of entities
java.lang.IllegalArgumentException: currentValue=125.490204 > maxValue=100.000000
	at android.service.controls.templates.RangeTemplate.validate(RangeTemplate.java:181)
	at android.service.controls.templates.RangeTemplate.<init>(RangeTemplate.java:83)
	at io.homeassistant.companion.android.controls.LightControl$Companion.createControl(LightControl.kt:53)
	at io.homeassistant.companion.android.controls.HaControlsProviderService$createPublisherForAllAvailable$1$1.invokeSuspend(HaControlsProviderService.kt:94)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

[12-27 10:10:51.298 10798:10823 D/ControlsProviderLifecycleManager]
Timeout waiting onLoad for ComponentInfo{io.homeassistant.companion.android/io.homeassistant.companion.android.controls.HaControlsProviderService}

[12-27 10:10:51.299 10798:10823 E/ControlsBindingControllerImpl]
onError receive from 'ComponentInfo{io.homeassistant.companion.android/io.homeassistant.companion.android.controls.HaControlsProviderService}': Timeout waiting onLoad

[12-27 10:10:51.299 10798:10823 D/ControlsProviderLifecycleManager]
Unbinding service Intent { cmp=io.homeassistant.companion.android/.controls.HaControlsProviderService (has extras) }

[12-27 10:10:52.559 10798:10823 D/ControlsProviderLifecycleManager]
Binding service Intent { cmp=io.homeassistant.companion.android/.controls.HaControlsProviderService (has extras) }

[12-27 10:10:52.612 10798:10798 D/ControlsProviderLifecycleManager]
onServiceConnected ComponentInfo{io.homeassistant.companion.android/io.homeassistant.companion.android.controls.HaControlsProviderService}

[12-27 10:10:52.612 10798:10798 D/ControlsProviderLifecycleManager]
subscribe ComponentInfo{io.homeassistant.companion.android/io.homeassistant.companion.android.controls.HaControlsProviderService} - [input_number.slider, input_boolean.garage_toggle]
`

**Comment by dshokouhi** [comment]
For some reason one of your lights is at 125% or more rather larger than the standard `255` value for the brightness attribute, that doesn't make sense.  Are we sure this is not a bug in the Tuya integration?

https://developers.home-assistant.io/docs/core/entity/light

**Comment by torbjornaxelsson** [comment]
I adjusted all my dimmers to 100 and now it works. I think you are right that it's a Tuya bug, so we can close this issue. Thank you for the quick feedback!

**Comment by dshokouhi** [comment]
@torbjornaxelsson thanks for reporting anyways though.  As this is the second integration we found that has caused this issue we are going to add a sanity check anyways to ensure we never exceed the min and max value.

Ref: https://github.com/home-assistant/android/issues/1179#issuecomment-725708689
