### ISSUE TITLE
Devices do not appear in Samsung implementation of Device Control

### ISSUE THREAD

**Issue by seanmccabe** [home-assistant/android#1429]
**Home Assistant Android version:**
2021.3.1-full

**Android version:**
11 (1 Feb 2021 Patch version)
(Samsung One UI 3.1)

**Phone model:**
Samsung Galaxy Note20 Ultra

**Home Assistant version:**
2021.2.2

**Description of problem:**
Devices from Home Assistant do not appear available in the Samsung implementation of the Android 11 Power Menu Device Control implementation.

The app appears in the list of apps available to provide devices, but nothing appears.

Other apps such as Google Home and Tasker work as expected.

Have left it open (perhaps loading in background), for 2 minutes and nothing.

**Screenshot of problem:**

https://user-images.githubusercontent.com/12243212/110857235-77ac4180-831d-11eb-8be7-a987894a3d0a.mp4

**Comment by dshokouhi** [comment]
can you please get us the crash logs as indicated in the issue template that you had removed?  Otherwise we can't fix this.

**Comment by seanmccabe** [comment]
Any ideas what log I maybe looking for?

**Comment by dshokouhi** [comment]
What I suspect is happening is that there is probably some error with some entity and the device logs are the only way to find out whats causing the issue precisely.

**Comment by seanmccabe** [comment]
Will try and get these over the weekend.

**Comment by dshokouhi** [comment]
So for this one more than likely the following `TAG` can be used to filter down the search `HaConProService` may also want to provide the full logs during the same time too in case this doesn't capture it.

**Comment by skynetua** [comment]
It works ok on my s20.

**Comment by dshokouhi** [comment]
yea probably an entity/domain that we need to find out what its failing on to guard it, the logs will tell us what to look at here :)

**Comment by PaulAnnekov** [comment]
I have the same bug for my Samsung Galaxy S10. I have different home network url in app configuration, like:
HA url: `https://smart.home:47364`
HA url for home network: `https://smart.home`
So when I'm connected to home wifi SSID app uses home network url. When I'm outside - HA url is used.

When I'm connected to home wifi SSID - no entities listed, like for topic starter. Logs contain the following error:

```
HaConProService
Unable to get entity information
java.net.ConnectException: Failed to connect to smart.home/192.168.0.1:47364
 at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297)
 at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
 at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
 at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
 at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
 at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
 at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
 at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
 at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
 at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
 at io.homeassistant.companion.android.common.data.HomeAssistantRetrofit$$special$$inlined$-addInterceptor$1.intercept(OkHttpClient.kt:1087)
 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
 at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
 at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 at java.lang.Thread.run(Thread.java:923)
Caused by: java.net.ConnectException: failed to connect to smart.home.annekov.com/192.168.0.12 (port 36957) from /192.168.0.13 (port 41670) after 10000ms: isConnected failed: ECONNREFUSED (Connection refused)
 at libcore.io.IoBridge.isConnected(IoBridge.java:287)
 at libcore.io.IoBridge.connectErrno(IoBridge.java:192)
 at libcore.io.IoBridge.connect(IoBridge.java:134)
 at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
 at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
 at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
 at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
 at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
 at java.net.Socket.connect(Socket.java:621)
 at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:120)
 at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
 ... 20 more
Caused by: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
 at libcore.io.IoBridge.isConnected(IoBridge.java:274)
 ... 30 more
```

When I'm outside - everything is fine. All entities are listed.

So it looks like for some reason this feature doesn't take app configuration into account and tries to connect via HA url, not HA url for home network.

**Comment by dshokouhi** [comment]
@PaulAnnekov please make sure location is enabled, permissions are granted for the app and GPS is on.  Otherwise the URL switching will not happen.  I assume your issue isn't tied to just this but everything else with the app as the logic is the same with sensor updates and events etc.... The app is unable to get the SSID without location and there should also be a notification posted on the device stating this as well assuming you are on the latest version.  Please also keep in mind that if the SSL cert is not valid locally then you will see the same error, a valid SSL cert is required for this app in which case suggests location is not the issue but the certificate.

**Comment by PaulAnnekov** [comment]
@dshokouhi you're right. Location permission was granted, but only when using an app. When I granted Location permission even when app is in background, bug disappeared. Thank you ;).
> there should also be a notification posted on the device stating this 

I'm using `beta-613-f38ec60-full` and it doesn't show any notification regarding wrong grant level.

**Comment by dshokouhi** [comment]
> I'm using `beta-613-f38ec60-full` and it doesn't show any notification regarding wrong grant level.

The API only reports if permissions were granted or not.

**Comment by seanmccabe** [comment]
I've gone to do the log check a few times now, and in each case, everything appears to be working. All devices are there as far as I can tell as well.
Not sure why it occured the first few times.

**Comment by dshokouhi** [comment]
Are we good to close this issue now? Sounds like you can no longer reproduce it?

**Comment by seanmccabe** [comment]
Yes
