### ISSUE TITLE
High Accuracy mode notification lingers

### ISSUE THREAD

**Issue by uphillbattle** [home-assistant/android#1509]
**Home Assistant Android version:**
2021.4.1-full

**Android version:**
11

**Phone model:**
Samsung Galaxy S21 5G

**Home Assistant version:**
2021.4.4

**Last working Home Assistant release (if known):**

**Description of problem:**
I'm using High Accuracy tracking when I enter an expanded home zone (300 m). The home zone itself has a radius of 60 m. 

The High Accuracy mode often does not seem to be disabled when I enter the home zone and stay there. At any rate, the High Accuracy notification does not disappear. I can click the "Disable" button in the notification. That disables future High Accuracy tracking to occur, it seems, but the notification lingers.

Checking the app logs (see below), it does seem that the app is aware that it should not do High Accuracy tracking, but as I said, the notification sticks.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```
04-13 10:25:37.464 32362 32362 D ForegrndServiceLauncher: Check if service HighAccuracyLocationService is running. Service running = false
04-13 10:25:37.520 32362 32362 D LocBroadcastReceiver: Not requesting accurate location, last accurate location was too recent
04-13 10:25:37.664 32362  6921 D LocBroadcastReceiver: High accuracy mode disabled, because bluetooth device(s) (false) not connected
04-13 10:25:37.664 32362  6921 D LocBroadcastReceiver: High accuracy mode disabled, because not in zone [zone.home_expanded]

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
I would be curious to see the actual error when it fails to be removed.  That would give us more insight into the error.  Are you able to reproduce the issue consistently with the steps provided?

**Comment by chriss158** [comment]
Can you upload logs around the time the high accuracy mode should be turned off?

**Comment by uphillbattle** [comment]
So, this morning the notification disappeared as it should. I will keep looking out for the problem I reported yesterday and attempt to capture the log at that time; you have to do it there and then, it seems, as the log only covers about 5 minutes although it is huge (7600 lines and close to a MB).

Anyway, below is (a small part of) the log from arriving home this morning. As I said, the notification disappeared as it should. However, I noted that at the start of the snip below, the log says High Accuracy mode should be enabled because I'm in `zone.home_expanded`, while at the end of the snip the log says it is not in `zone.home_expanded`. This is strange (to me) because the two points are only 11 m apart (according to http://boulter.com/gps/distance/ and also checked with Google Maps) and both are well inside `zone.home`. If I understand the [documentation](https://companion.home-assistant.io/docs/core/location#high-accuracy-mode) correctly, High Accuracy mode should be disabled when `zone.home` has been entered (and thus `zone.home_expanded` has been left).

As I said, when I see the notification failing to disappear, I will attempt to capture the logs at that time and then upload here.

```
04-14 08:16:04.576 29532 29532 D LocBroadcastReceiver: Got single accurate location update: Location[fused **REDACTED**256,**REDACTED**664 hAcc=12 et=+9d23h20m51s223ms alt=276.94304498660006 vel=0.38626775 bear=336.32538 vAcc=3 sAcc=20 bAcc=??? {Bundle[mParcelledData.dataSize=52]}]
04-14 08:16:04.576 29532 29532 D LocBroadcastReceiver: Location accurate enough, all done with high accuracy.
04-14 08:16:04.576 29532 29532 D LocBroadcastReceiver: Last Location: 
04-14 08:16:04.576 29532 29532 D LocBroadcastReceiver: Coords:(**REDACTED**2563, **REDACTED**6639)
04-14 08:16:04.576 29532 29532 D LocBroadcastReceiver: Accuracy: 12.266
04-14 08:16:04.576 29532 29532 D LocBroadcastReceiver: Bearing: 336.32538
04-14 08:16:04.576 29532 29532 D LocBroadcastReceiver: Begin evaluating if location update should be skipped
04-14 08:16:04.576 29532 29532 D LocBroadcastReceiver: Received location that is 2577 milliseconds old, 1618380961999 compared to 1618380964576 with source fused
04-14 08:16:04.576 29532 29532 D LocBroadcastReceiver: New location update not possible within 5 seconds, not sending to HA
04-14 08:16:04.581 29532 29598 I WM-WorkerWrapper: Work [ id=fda3d4e6-16be-42f4-874b-1859b7944763, tags={ io.homeassistant.companion.android.sensors.SensorWorker } ] was cancelled
04-14 08:16:04.581 29532 29598 I WM-WorkerWrapper: java.util.concurrent.CancellationException: Task was cancelled.
04-14 08:16:04.581 29532 29598 I WM-WorkerWrapper: 	at androidx.work.impl.utils.futures.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:1184)
04-14 08:16:04.581 29532 29598 I WM-WorkerWrapper: 	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:514)
04-14 08:16:04.581 29532 29598 I WM-WorkerWrapper: 	at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:475)
04-14 08:16:04.581 29532 29598 I WM-WorkerWrapper: 	at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:300)
04-14 08:16:04.581 29532 29598 I WM-WorkerWrapper: 	at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
04-14 08:16:04.581 29532 29598 I WM-WorkerWrapper: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
04-14 08:16:04.581 29532 29598 I WM-WorkerWrapper: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
04-14 08:16:04.581 29532 29598 I WM-WorkerWrapper: 	at java.lang.Thread.run(Thread.java:923)
04-14 08:16:04.582 29532 14197 D SensorWorker: Updating all Sensors.
04-14 08:16:04.585 29532 29598 I WM-Processor: Moving WorkSpec (0f5b9bc8-6e3f-483a-8f09-d2720acc3d7e) to the foreground
04-14 08:16:04.596 29532 14197 D LastUpdate: Last update is SensorWorker
04-14 08:16:04.607 29532 14197 D ActivitySM: Unregistering for activity updates.
04-14 08:16:04.607 29532 14197 D ActivitySM: Registering for activity updates.
04-14 08:16:05.394 29532 29632 D LocBroadcastReceiver: High accuracy mode disabled, because bluetooth device(s) (false) not connected
04-14 08:16:05.394 29532 29632 D LocBroadcastReceiver: High accuracy mode enabled, because in zone [zone.home_expanded]
04-14 08:16:05.582 29532 14197 D NextAlarm: Next alarm is scheduled by com.samsung.android.app.reminder with trigger time 1742195940000
04-14 08:16:05.766 29532 14197 D SensorManager: registerListener :: 6, LPS22HHTR Barometer, 200000, 0, io.homeassistant.companion.android.sensors.PressureSensorManager@bfb087
04-14 08:16:05.766 29532 14197 D PressureSensor: Pressure sensor listener registered
04-14 08:16:05.782 29532 14197 D SensorManager: registerListener :: 1600479602, Palm Proximity Sensor version 2, 200000, 0, io.homeassistant.companion.android.sensors.ProximitySensorManager@61ab3dd
04-14 08:16:05.782 29532 14197 D ProximitySensor: Proximity sensor listener registered
04-14 08:16:05.829 29532 14197 D StorageSensor: PATHS SD 1
04-14 08:16:05.835 29532 14197 D StorageSensor: PATH /storage/emulated/0/Android/data/io.homeassistant.companion.android/files is mounted true and removable is false
04-14 08:16:05.856 29532 29532 D SensorManager: TYPE_PROXIMITY (8): 5.000000
04-14 08:16:05.866 29532 29532 D SensorManager: unregisterListener :: io.homeassistant.companion.android.sensors.ProximitySensorManager@61ab3dd
04-14 08:16:05.866 29532 29532 D ProximitySensor: Proximity sensor listener unregistered
04-14 08:16:05.930 29532 14197 D UrlRepository: localUrl is: false and usesInternalSsid is: false
04-14 08:16:06.033 29532 29532 D SensorManager: unregisterListener :: io.homeassistant.companion.android.sensors.PressureSensorManager@bfb087
04-14 08:16:06.033 29532 29532 D PressureSensor: Pressure sensor listener unregistered
04-14 08:16:06.043 29532 29532 I WM-SystemFgDispatcher: Started foreground service Intent { act=ACTION_START_FOREGROUND cmp=io.homeassistant.companion.android/androidx.work.impl.foreground.SystemForegroundService (has extras) }
04-14 08:16:06.561 29532 29532 I Choreographer: Skipped 158 frames!  The application may be doing too much work on its main thread.
04-14 08:16:06.564 29532 29532 D ForegrndServiceLauncher: Check if service HighAccuracyLocationService is running. Service running = true
04-14 08:16:07.760 29532 29532 D LocBroadcastReceiver: Not requesting accurate location, last accurate location was too recent
04-14 08:16:07.768 29532 29532 D LocBroadcastReceiver: Not requesting accurate location, last accurate location was too recent
04-14 08:16:07.885 29532 29532 D LocBroadcastReceiver: Not requesting accurate location, last accurate location was too recent
04-14 08:16:07.941 29532 29532 D LocBroadcastReceiver: Received location update.
04-14 08:16:07.947 29532 29532 D LocBroadcastReceiver: Last Location: 
04-14 08:16:07.947 29532 29532 D LocBroadcastReceiver: Coords:(**REDACTED**2228, **REDACTED**8127)
04-14 08:16:07.947 29532 29532 D LocBroadcastReceiver: Accuracy: 17.699
04-14 08:16:07.947 29532 29532 D LocBroadcastReceiver: Bearing: 0.0
04-14 08:16:07.947 29532 29532 D LocBroadcastReceiver: Begin evaluating if location update should be skipped
04-14 08:16:07.947 29532 29532 D LocBroadcastReceiver: Skipping old location update since time is before the last one we sent, received: 1618380941785 last sent: 1618380961203
04-14 08:16:07.979 29532 29532 D ForegrndServiceLauncher: Check if service HighAccuracyLocationService is running. Service running = true
04-14 08:16:08.013 29532 29532 D LocBroadcastReceiver: Not requesting accurate location, last accurate location was too recent
04-14 08:16:08.045 29532 29532 D LocBroadcastReceiver: Not requesting accurate location, last accurate location was too recent
04-14 08:16:08.614 29532 29532 D LocBroadcastReceiver: Not requesting accurate location, last accurate location was too recent
04-14 08:16:08.617 29532 29532 D LocBroadcastReceiver: Received location update.
04-14 08:16:08.622 29532 29532 D LocBroadcastReceiver: Last Location: 
04-14 08:16:08.622 29532 29532 D LocBroadcastReceiver: Coords:(**REDACTED**2255, **REDACTED**8894)
04-14 08:16:08.622 29532 29532 D LocBroadcastReceiver: Accuracy: 6.0
04-14 08:16:08.622 29532 29532 D LocBroadcastReceiver: Bearing: 99.31054
04-14 08:16:08.622 29532 29532 D LocBroadcastReceiver: Begin evaluating if location update should be skipped
04-14 08:16:08.622 29532 29532 D LocBroadcastReceiver: Skipping old location update since time is before the last one we sent, received: 1618380951784 last sent: 1618380961203
04-14 08:16:08.644 29532 29532 D ForegrndServiceLauncher: Check if service HighAccuracyLocationService is running. Service running = true
04-14 08:16:08.673 29532 29532 D LocBroadcastReceiver: Not requesting accurate location, last accurate location was too recent
04-14 08:16:08.728 29532 29532 D LocBroadcastReceiver: Not requesting accurate location, last accurate location was too recent
04-14 08:16:08.783 29532 29532 D LocBroadcastReceiver: Not requesting accurate location, last accurate location was too recent
04-14 08:16:08.791 29532 29532 D LocBroadcastReceiver: Not requesting accurate location, last accurate location was too recent
04-14 08:16:08.793 29532 29532 D LocBroadcastReceiver: Received location update.
04-14 08:16:08.797 29532 29532 D LocBroadcastReceiver: Last Location: 
04-14 08:16:08.797 29532 29532 D LocBroadcastReceiver: Coords:(**REDACTED**2518, **REDACTED**6473)
04-14 08:16:08.797 29532 29532 D LocBroadcastReceiver: Accuracy: 12.857
04-14 08:16:08.797 29532 29532 D LocBroadcastReceiver: Bearing: 294.28687
04-14 08:16:08.797 29532 29532 D LocBroadcastReceiver: Begin evaluating if location update should be skipped
04-14 08:16:08.797 29532 29532 D LocBroadcastReceiver: Skipping old location update since time is before the last one we sent, received: 1618380959999 last sent: 1618380961203
04-14 08:16:08.814 29532 29532 D LocBroadcastReceiver: Not requesting accurate location, last accurate location was too recent
04-14 08:16:08.817 29532 29532 D ForegrndServiceLauncher: Check if service HighAccuracyLocationService is running. Service running = true
04-14 08:16:09.954 29532 29532 D LocBroadcastReceiver: Received location update.
04-14 08:16:09.965 29532 29532 D LocBroadcastReceiver: Last Location: 
04-14 08:16:09.965 29532 29532 D LocBroadcastReceiver: Coords:(**REDACTED**2576, **REDACTED**7622)
04-14 08:16:09.965 29532 29532 D LocBroadcastReceiver: Accuracy: 12.0
04-14 08:16:09.965 29532 29532 D LocBroadcastReceiver: Bearing: 99.19735
04-14 08:16:09.965 29532 29532 D LocBroadcastReceiver: Begin evaluating if location update should be skipped
04-14 08:16:09.965 29532 29532 D LocBroadcastReceiver: Received location that is 1966 milliseconds old, 1618380967999 compared to 1618380969965 with source fused
04-14 08:16:09.974 29532 14197 D UrlRepository: localUrl is: false and usesInternalSsid is: false
04-14 08:16:10.002 29532 29532 D ForegrndServiceLauncher: Check if service HighAccuracyLocationService is running. Service running = true
04-14 08:16:15.541 29532 29532 D ActivitySM: Received activity update.
04-14 08:16:15.674 29532 29532 D ActivitySM: Received activity update.
04-14 08:16:17.816 29532 29532 D LocBroadcastReceiver: Received location update.
04-14 08:16:17.828 29532 29532 D LocBroadcastReceiver: Last Location: 
04-14 08:16:17.828 29532 29532 D LocBroadcastReceiver: Coords:(**REDACTED**2526, **REDACTED**7779)
04-14 08:16:17.828 29532 29532 D LocBroadcastReceiver: Accuracy: 112.159
04-14 08:16:17.828 29532 29532 D LocBroadcastReceiver: Bearing: 111.51599
04-14 08:16:17.828 29532 29532 D LocBroadcastReceiver: Begin evaluating if location update should be skipped
04-14 08:16:17.828 29532 29532 D LocBroadcastReceiver: Received location that is 212 milliseconds old, 1618380977616 compared to 1618380977828 with source fused
04-14 08:16:17.831 29532 14197 D UrlRepository: localUrl is: false and usesInternalSsid is: false
04-14 08:16:17.855 29532 29532 D ForegrndServiceLauncher: Check if service HighAccuracyLocationService is running. Service running = true
04-14 08:16:27.245 29532 29642 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=0f5b9bc8-6e3f-483a-8f09-d2720acc3d7e, tags={ io.homeassistant.companion.android.sensors.SensorWorker } ]
04-14 08:16:27.254 29532 29532 I WM-SystemFgDispatcher: Stopping foreground service
04-14 08:16:28.637 29532 14197 D LocBroadcastReceiver: Location update sent successfully
04-14 08:16:28.948 29532 29632 D LocBroadcastReceiver: Location update sent successfully
04-14 08:16:32.677 29532 29532 D LocBroadcastReceiver: Received location update.
04-14 08:16:32.681 29532 29532 D LocBroadcastReceiver: Last Location: 
04-14 08:16:32.681 29532 29532 D LocBroadcastReceiver: Coords:(**REDACTED**1852, **REDACTED**8085)
04-14 08:16:32.681 29532 29532 D LocBroadcastReceiver: Accuracy: 14.801
04-14 08:16:32.681 29532 29532 D LocBroadcastReceiver: Bearing: 165.28284
04-14 08:16:32.681 29532 29532 D LocBroadcastReceiver: Begin evaluating if location update should be skipped
04-14 08:16:32.682 29532 29532 D LocBroadcastReceiver: Received location that is 153 milliseconds old, 1618380992528 compared to 1618380992681 with source fused
04-14 08:16:32.684 29532 14197 D UrlRepository: localUrl is: false and usesInternalSsid is: false
04-14 08:16:32.727 29532 29532 D ForegrndServiceLauncher: Check if service HighAccuracyLocationService is running. Service running = true
04-14 08:16:33.546 29532 14197 D LocBroadcastReceiver: Location update sent successfully
04-14 08:16:34.834 29532 29532 D ActivitySM: Received activity update.
04-14 08:16:38.667 29532 29532 D LocBroadcastReceiver: Received geofence update.
04-14 08:16:38.674 29532 29532 D UrlRepository: localUrl is: false and usesInternalSsid is: false
04-14 08:16:39.833 29532 29532 D LocBroadcastReceiver: Event sent to Home Assistant
04-14 08:16:39.838 29532 29532 D LocBroadcastReceiver: Last Location: 
04-14 08:16:39.838 29532 29532 D LocBroadcastReceiver: Coords:(**REDACTED**1852, **REDACTED**8085)
04-14 08:16:39.838 29532 29532 D LocBroadcastReceiver: Accuracy: 14.801
04-14 08:16:39.838 29532 29532 D LocBroadcastReceiver: Bearing: 165.28284
04-14 08:16:39.838 29532 29532 D LocBroadcastReceiver: Begin evaluating if location update should be skipped
04-14 08:16:39.838 29532 29532 D LocBroadcastReceiver: Skipping old location update since time is before the last one we sent, received: 1618380992528 last sent: 1618380992681
04-14 08:16:39.887 29532 14197 D LocBroadcastReceiver: High accuracy mode disabled, because bluetooth device(s) (false) not connected
04-14 08:16:39.887 29532 14197 D LocBroadcastReceiver: High accuracy mode disabled, because not in zone [zone.home_expanded]
04-14 08:16:39.893 29532 14197 D LocBroadcastReceiver: High accuracy mode parameters changed. Disable high accuracy mode.
04-14 08:16:39.893 29532 14197 D HighAccLocService: Try stopping high accuracy location service...
04-14 08:16:39.926 29532 14197 D ForegrndServiceLauncher: Stop service HighAccuracyLocationService
04-14 08:16:39.926 29532 14197 D LocBroadcastReceiver: Registering for location updates.
04-14 08:16:39.934 29532 29532 D ForegrndServiceLauncher: Service HighAccuracyLocationService was destroyed. Stop service
04-14 08:16:39.954 29532 29532 D HighAccLocService: High accuracy location service stopped -> onDestroy
04-14 08:16:40.360 29532 29532 D LocBroadcastReceiver: Received location update.
04-14 08:16:40.364 29532 29532 D LocBroadcastReceiver: Last Location: 
04-14 08:16:40.364 29532 29532 D LocBroadcastReceiver: Coords:(**REDACTED**1852, **REDACTED**8085)
04-14 08:16:40.364 29532 29532 D LocBroadcastReceiver: Accuracy: 14.801
04-14 08:16:40.364 29532 29532 D LocBroadcastReceiver: Bearing: 165.28284
04-14 08:16:40.365 29532 29532 D LocBroadcastReceiver: Begin evaluating if location update should be skipped
04-14 08:16:40.365 29532 29532 D LocBroadcastReceiver: Received location that is 307 milliseconds old, 1618381000058 compared to 1618381000365 with source fused
04-14 08:16:40.365 29532 29532 D LocBroadcastReceiver: Duplicate location received, not sending to HA
04-14 08:16:40.378 29532 29532 D LocBroadcastReceiver: Received location update.
04-14 08:16:40.408 29532 29532 D ForegrndServiceLauncher: Check if service HighAccuracyLocationService is running. Service running = false
```

**Comment by crowedavid** [comment]
this issue also occurs for me except i use BT connected devices to trigger the High Accuracy mode.  i haven't tracked down the sequence to make the sticky notification recur but it definitely started happening with the most recent app update (2021.4.1-full).  i have noticed the notification will sometimes clear after a connection/disconnection cycle (or two) to a BT device on the list.

i'll try to catch logs when it happens the next time to be more useful.

pixel 3xl, android 11
currently Home Assistant v 2021.4.4 (was also happening on previous 2021.03.4 before i upgraded yesterday)

**Comment by callifo** [comment]
Same issue, Pixel 2 Android 10. I happens pretty much constantly for me except tonight, so I'll try and grab a log. Happens for both extended zone and Bluetooth.

**Comment by chriss158** [comment]
Let me get this understood correctly. Only the notification remains, but GPS is deactivated correctly?

**Comment by dshokouhi** [comment]
I would imagine that when the notification gets stuck the dismissed button would probably trigger the same error message right?

One strange thing I see in the logs above is all the repeated lines.  Seems like maybe we have subscribed too many times to updates?

```
04-14 08:16:08.013 29532 29532 D LocBroadcastReceiver: Not requesting accurate location, last accurate location was too recent
04-14 08:16:08.045 29532 29532 D LocBroadcastReceiver: Not requesting accurate location, last accurate location was too recent
04-14 08:16:08.614 29532 29532 D LocBroadcastReceiver: Not requesting accurate location, last accurate location was too recent
```

```
04-14 08:16:28.637 29532 14197 D LocBroadcastReceiver: Location update sent successfully
04-14 08:16:28.948 29532 29632 D LocBroadcastReceiver: Location update sent successfully
```

**Comment by uphillbattle** [comment]
Sorry that I’ve been quiet for a couple of days. I haven’t seen the notification getting stuck since I reported it in the original post. At that time I had seen it two days in a row. I’m still carefully watching the notification, and will report back if it gets stuck again, but it’s been well-behaved the last couple of days.

**Comment by crowedavid** [comment]
> I would imagine that when the notification gets stuck the dismissed button would probably trigger the same error message right?

i do not see an error message.  when i press "Disable" on the notification it does disable the High Accuracy mode itself which isn't what i would like.

@chriss158, i do not know for sure if the GPS mode it triggered was turned off (haven't caught it with logs yet) but judging from battery usage trend i would say it was.

> One strange thing I see in the logs above is all the repeated lines. Seems like maybe we have subscribed too many times to updates?
> 
> ```
> 04-14 08:16:08.013 29532 29532 D LocBroadcastReceiver: Not requesting accurate location, last accurate location was too recent
> 04-14 08:16:08.045 29532 29532 D LocBroadcastReceiver: Not requesting accurate location, last accurate location was too recent
> 04-14 08:16:08.614 29532 29532 D LocBroadcastReceiver: Not requesting accurate location, last accurate location was too recent
> ```
> 
> ```
> 04-14 08:16:28.637 29532 14197 D LocBroadcastReceiver: Location update sent successfully
> 04-14 08:16:28.948 29532 29632 D LocBroadcastReceiver: Location update sent successfully
> ```

my logs have some similar repeated lines but i'm not familiar with the code to know what is important or not.

below are two logs - the first is with the situation of the sticky notification active but without a BT device connected to trigger it, second is from just after the first when i go through the process of connecting one BT device to trigger High Accuracy mode and then disconnect with the notification then going away correctly.

[homeassistant_companion_log_3-15-2021_12-35-5.txt](https://github.com/home-assistant/android/files/6320836/homeassistant_companion_log_3-15-2021_12-35-5.txt)
[homeassistant_companion_log_3-15-2021_12-37-2.txt](https://github.com/home-assistant/android/files/6320837/homeassistant_companion_log_3-15-2021_12-37-2.txt)

i notice the logs only capture a minute or so of time on my app so the second log may not have captured the whole sequence of events.  is there a way to increase the log retention if needed?

**Comment by chriss158** [comment]
I had this problem a while ago. At that time I had used a workaround to remove the notification. I actually thought it was solved by the current implementation. But I guess not. I will probably implement the workaround again.

About the repeated log entries: 
I think that is caused by this method `requestSingleAccurateLocation`. Are you using the Single Accurate Sensor actively (via the command `request_location_update`)? Maybe even with the option `Include in sensor update`?

**Comment by uphillbattle** [comment]
No, I have not requested location updates outside of those generated by the app itself. 

I have turned on High Accuracy mode when connected to BT devices (my family's two cars) and in the home_expanded zone. That's it.

**Comment by chriss158** [comment]
You can test the version in the attached PR. It should fix the remaining notification and hopefully also the multiple registration of location requests. :+1:

**Comment by crowedavid** [comment]
> About the repeated log entries:
> I think that is caused by this method `requestSingleAccurateLocation`. Are you using the Single Accurate Sensor actively (via the command `request_location_update`)? Maybe even with the option `Include in sensor update`?

i have "Single Accurate Sensor" enabled on my phone but do no currently have any requests enabled to trigger it.  I do also have the "Include in sensor update" option set though so that might be the source and why it is so variable.

now that i'm watching it like a hawk it hasn't happened in my few trips in the last day. :-\  i'll try the debug version and let you know. is there any debug/log info you'd like to see to know if your fix is working?

**Comment by dshokouhi** [comment]
> I do also have the "Include in sensor update" option set though so that might be the source and why it is so variable.

So this setting means that any time another sensor on the device has an update the app will make a new location request for 5 updates and that is a GPS based request only.  This used to be the default but we had converted it into an opt in setting to prevent really bad battery drain like the location icon being fixed.  I personally recommend turning off this setting and trying the latest location updates with high accuracy mode alone and see if it works the same.  We had a lot of location improvements over time and I think you may find better results :)

Depending on the amount of sensors you have enabled with this setting then yea that would be the source of multiple requests.
