### ISSUE TITLE
The "entityId" clickAction doesn't open up the More Info panel

### ISSUE THREAD

**Issue by kylehendricks** [home-assistant/android#1583]
**Home Assistant Android version:**
`beta-685-16f06a3-full`
**Android version:**
`11`
**Phone model:**
Pixel 3 XL
**Home Assistant version:**
`2021.6.2`
**Last working Home Assistant release (if known):**

**Description of problem:**
When I call the `notify.mobile_app_*` service with a `clickAction` set to `entityId:ENTITY` and click the notification, the app is opened but it opens to the main page instead of the "More Info" page for the provided entity.

YAML for notify service call:
```yaml
service: notify.mobile_app_pixel_3_xl
data:
  message: test message
  data:
    clickAction: 'entityId:sun.sun'

```

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```
06-06 11:58:20.223 15301 16790 D MessagingService: From: 331041709873
06-06 11:58:20.224 15301 16790 D MessagingService: Message data payload: {clickAction=entityId:sun.sun, message=test message}
06-06 11:58:20.232 15301 15301 D MessagingService: Creating notification with following data: {clickAction=entityId:sun.sun, message=test message}
06-06 11:58:20.258 15301 15301 D MessagingService: Show notification with tag "null" and id "-502537656"
06-06 11:58:21.003 15301 15301 D SensorReceiver: Sensor is_interactive corresponding to received event android.intent.action.SCREEN_ON is disabled, skipping sensors update
06-06 11:58:21.018 15301 15301 D ButtonWidget: Broadcast received: 
06-06 11:58:21.018 15301 15301 D ButtonWidget: Broadcast action: android.intent.action.SCREEN_ON
06-06 11:58:21.018 15301 15301 D ButtonWidget: AppWidgetId: -1
06-06 11:58:21.021 15301 15301 D ButtonWidget: Updating all widgets
06-06 11:58:21.022 15301 15301 D StaticWidget: Broadcast received: 
06-06 11:58:21.022 15301 15301 D StaticWidget: Broadcast action: android.intent.action.SCREEN_ON
06-06 11:58:21.022 15301 15301 D StaticWidget: AppWidgetId: -1
06-06 11:58:21.032 15301 15301 D StaticWidget: Updating all widgets
06-06 11:58:21.033 15301 15301 D MediaPlayCtrlsWidget: Broadcast received: 
06-06 11:58:21.033 15301 15301 D MediaPlayCtrlsWidget: Broadcast action: android.intent.action.SCREEN_ON
06-06 11:58:21.033 15301 15301 D MediaPlayCtrlsWidget: AppWidgetId: -1
06-06 11:58:21.038 15301 15301 D MediaPlayCtrlsWidget: Updating all widgets
06-06 11:58:21.040 15301 15301 D TemplateWidget: Broadcast received: 
06-06 11:58:21.040 15301 15301 D TemplateWidget: Broadcast action: android.intent.action.SCREEN_ON
06-06 11:58:21.040 15301 15301 D TemplateWidget: AppWidgetId: -1
06-06 11:58:21.044 15301 15301 D TemplateWidget: Updating all widgets
06-06 11:58:25.789 15301 15301 D NotifManagerCompat: Cancel notification with tag "null" and id "0"
06-06 11:58:25.790 15301 15301 D NotifManagerCompat: Check if the notification is in a group...
06-06 11:58:25.790 15301 15301 D NotifManagerCompat: Notification is not in a group. Cancel notification...
06-06 11:58:25.983 15301 15301 D WebviewActivity: Current webview package com.google.android.webview and version 91.0.4472.88
06-06 11:58:25.999 15301 15866 E WM-WorkerWrapper: Didn't find WorkSpec for id bab63b34-4452-472a-838d-9658fd2a8bfc
06-06 11:58:26.020 15301 15864 I WM-WorkerWrapper: Work [ id=bab63b34-4452-472a-838d-9658fd2a8bfc, tags={ io.homeassistant.companion.android.sensors.SensorWorker } ] was cancelled
06-06 11:58:26.020 15301 15864 I WM-WorkerWrapper: java.util.concurrent.CancellationException: Task was cancelled.
06-06 11:58:26.020 15301 15864 I WM-WorkerWrapper: 	at androidx.work.impl.utils.futures.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:1184)
06-06 11:58:26.020 15301 15864 I WM-WorkerWrapper: 	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:514)
06-06 11:58:26.020 15301 15864 I WM-WorkerWrapper: 	at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:475)
06-06 11:58:26.020 15301 15864 I WM-WorkerWrapper: 	at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:300)
06-06 11:58:26.020 15301 15864 I WM-WorkerWrapper: 	at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
06-06 11:58:26.020 15301 15864 I WM-WorkerWrapper: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
06-06 11:58:26.020 15301 15864 I WM-WorkerWrapper: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
06-06 11:58:26.020 15301 15864 I WM-WorkerWrapper: 	at java.lang.Thread.run(Thread.java:923)
06-06 11:58:26.023 15301 15402 D SensorWorker: Updating all Sensors.
06-06 11:58:26.024 15301 15391 I WM-Processor: Moving WorkSpec (71439e8a-bd34-4db3-aca0-775a55fe707e) to the foreground
06-06 11:58:26.058 15301 15301 I WM-SystemFgDispatcher: Started foreground service Intent { act=ACTION_START_FOREGROUND cmp=io.homeassistant.companion.android/androidx.work.impl.foreground.SystemForegroundService (has extras) }
06-06 11:58:26.089 15301 15301 D UrlRepository: localUrl is: false and usesInternalSsid is: false
06-06 11:58:26.089 15301 15301 D UrlRepository: Using external URL
06-06 11:58:26.103 15301 15402 D UrlRepository: localUrl is: false and usesInternalSsid is: false
06-06 11:58:26.196 15301 15864 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=71439e8a-bd34-4db3-aca0-775a55fe707e, tags={ io.homeassistant.companion.android.sensors.SensorWorker } ]
06-06 11:58:26.199 15301 15301 I WM-SystemFgDispatcher: Stopping foreground service
06-06 11:58:26.408 15301 15301 D WebviewActivity: More info entity: sun.sun
06-06 11:58:26.645 15301 15904 D WebviewActivity: External bus {"type":"connection-status","payload":{"event":"connected"},"id":1}
06-06 11:58:26.647 15301 15301 D UrlRepository: localUrl is: false and usesInternalSsid is: false
06-06 11:58:26.912 15301 15904 D WebviewActivity: External bus {"type":"config/get","id":2}
06-06 11:58:26.912 15301 15301 D WebviewActivity: externalBus({"id":2,"type":"result","success":true,"result":{"hasSettingsScreen":true,"canWriteTag":true,"hasExoPlayer":true}});
06-06 11:58:26.968 15301 15301 D WebviewActivity: Callback null
06-06 11:58:26.968 15301 15401 D WebViewPresenterImpl: Try getting status bar/navigation bar color from webviews color ""#101e24""
06-06 11:58:26.968 15301 15401 D WebViewPresenterImpl: Color from webview is "#101e24"
06-06 11:58:26.969 15301 15401 I WebViewPresenterImpl: Found color -15720924 for status bar/navigation bar
06-06 11:58:27.438 15301 15301 D ButtonWidget: Broadcast received: 
06-06 11:58:27.438 15301 15301 D ButtonWidget: Broadcast action: android.appwidget.action.APPWIDGET_UPDATE
06-06 11:58:27.438 15301 15301 D ButtonWidget: AppWidgetId: -1
```

**Screenshot of problem:**

**Additional information:**

When I test with full URLs and Home Assistant relative paths ('/lovelace/cameras'), it works as intended.

**Comment by dshokouhi** [comment]
what troubleshooting steps ahve you tried? have you tried disabling any and all custom cards? have you tried clearing data and logging back in? can we get the requested debug logs that you skipped over?

**Comment by kylehendricks** [comment]
Sorry about that.  Didn't realize how low effort my report was until you spelled it out.

I just tried clearing all data and logging back in.  Same result.  To my knowledge, I don't have any custom cards.

**Comment by dshokouhi** [comment]
looks like this is a regression of HA 2021.6 as it was working in prior releases
