### ISSUE TITLE
Quick Settings Tile: Error processign webhook

### ISSUE THREAD

**Issue by Timson15** [home-assistant/android#1663]
**Home Assistant Android version:**
2021.6.2-full

**Android version:**
Android 11 Oxygen OS 11.0.7.7.IN21BA

**Phone model:**
Oneplus 8

**Home Assistant version:**
core-2021.7.4

**Last working Home Assistant release (if known):**

**Description of problem:**
Tile created in Quick Settings -> Manage Tiles, throws error below. Tile created before dragging it into the quick settings menu on phone and was made with icon/label/selected scene according to the documentation. The scene simply turns on some lights, and works everywhere else.  

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/mobile_app/webhook.py", line 220, in webhook_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1438, in async_call
raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Unable to find service scene.normal
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/webhook/__init__.py", line 96, in async_handle_webhook
response = await webhook["handler"](hass, webhook_id, request)
File "/usr/src/homeassistant/homeassistant/components/mobile_app/webhook.py", line 204, in handle_webhook
return await asyncio.shield(
File "/usr/src/homeassistant/homeassistant/components/mobile_app/webhook.py", line 139, in validate_and_run
return await func(hass, config_entry, data)
File "/usr/src/homeassistant/homeassistant/components/mobile_app/webhook.py", line 234, in webhook_call_service
raise HTTPBadRequest() from ex
aiohttp.web_exceptions.HTTPBadRequest: Bad Request
```

**Screenshot of problem:**

**Additional information:**
Server logs:
```
2021-08-01 22:10:59 ERROR (MainThread) [homeassistant.components.mobile_app.webhook] Error when calling service during mobile_app webhook (device name: Phone): Unable to find service scene.normal
2021-08-01 22:10:59 ERROR (MainThread) [homeassistant.components.webhook] Error processing webhook 8d2e92c064efb6fb80473594ec6ed16fe5685f20e4b528c82a05eda5a2dd7976
```
Message in app log:
```
UrlRepository: localUrl is: false and usesInternalSsid is: false
```
Screenshot of tile configuration: 
![2021_0802_201449](https://user-images.githubusercontent.com/5841122/127905741-3ac1cc63-870a-489d-b1bc-a5941fa27d57.png)

**Comment by dshokouhi** [comment]
Looks like the service call should be identical to what we do in power menu, currently the code works for `script` but not `scene`.  Will get an update in soon.
