### ISSUE TITLE
Unable to authenticate Wear OS app with local connection

### ISSUE THREAD

**Issue by dshokouhi** [home-assistant/android#1786]
**Home Assistant Android version:**

latest master

**Android version:**

9

**Phone model:**

Fossil Julianna HR

**Home Assistant version:**

2021.10.x

**Last working Home Assistant release (if known):**

N/A

**Description of problem:**

When I attempt to authenticate with a local URL I get an error otherwise if I use my domain name with SSL I am able to authenticate just fine.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```
2021-10-14 19:14:50.667 8543-8543/io.homeassistant.companion.android.debug E/ManualSetupPresenter: Unable to initiate login flow
    java.net.UnknownServiceException: CLEARTEXT communication to 192.168.1.19 not permitted by network security policy
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:188)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
        at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at io.homeassistant.companion.android.common.data.HomeAssistantRetrofit$special$$inlined$-addInterceptor$1.intercept(OkHttpClient.kt:1087)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:221)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

**Screenshot of problem:**

![screen (1)](https://user-images.githubusercontent.com/1634145/137422233-a32ea9c7-da55-4b28-9bdf-1d49109cc261.png)

**Additional information:**

Reported on discord too: https://discord.com/channels/330944238910963714/562408603345092636/898389412038193182

**Comment by dshokouhi** [comment]
For anyone seeing this issue for now use an external address with SSL
