### ISSUE TITLE
Wear OS app crashes if you are not signed in as the WebSocket cannot find a URL

### ISSUE THREAD

**Issue by SkechyWolf** [home-assistant/android#1916]
**Home Assistant Android version:**  home-assistant-wear-beta-1666-1e5534d (Newest Release as of 11/13/2021)

**Android version:** Wear OS 3

**Phone model:** Galaxy Watch 4

**Home Assistant version:** 2021.11.3

**Last working Home Assistant release (if known):** N/A

**Description of problem:** If you are not already signed in the app crashes as the WebSocket cannot find a URL

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```
2021-11-13 16:41:21.298 26212-26212/io.homeassistant.companion.android.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.homeassistant.companion.android.debug, PID: 26212
    java.lang.Exception: Unable to get URL for WebSocket
        at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl.connect(WebSocketRepositoryImpl.kt:164)
        at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl.sendMessage(WebSocketRepositoryImpl.kt:189)
        at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl.getStateChanges(WebSocketRepositoryImpl.kt:127)
        at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl.getEntityUpdates(IntegrationRepositoryImpl.kt:468)
        at io.homeassistant.companion.android.home.HomePresenterImpl.getEntityUpdates(HomePresenterImpl.kt:61)
        at io.homeassistant.companion.android.home.MainViewModel$loadEntities$1.invokeSuspend(MainViewModel.kt:43)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:367)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
        at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
        at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
        at io.homeassistant.companion.android.home.MainViewModel.loadEntities(MainViewModel.kt:35)
        at io.homeassistant.companion.android.home.MainViewModel.init(MainViewModel.kt:20)
        at io.homeassistant.companion.android.home.HomeActivity.onCreate(HomeActivity.kt:49)
        at android.app.Activity.performCreate(Activity.java:8009)
        at android.app.Activity.performCreate(Activity.java:7993)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3429)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3612)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2073)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:7690)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:593)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)

```

**Screenshot of problem:**

**Additional information:**

**Comment by alexd321** [comment]
I was previously signed in and app crashed on start-up. Tried to re-install and now I get the same error message (I think, I tried to use logcat, I am new to debugging).

Unfortunately I didn't get the logs before re-installing but app on watch immediately closed on start-up.

Android version: Wear OS 3

Phone model: Galaxy Watch 4 Classic

Home Assistant version: 2021.11.3


Section of logcat:
`11-14 17:52:09.265   730   730 E AndroidRuntime: FATAL EXCEPTION: main
11-14 17:52:09.265   730   730 E AndroidRuntime: Process: io.homeassistant.companion.android, PID: 730
11-14 17:52:09.265   730   730 E AndroidRuntime: java.lang.Exception: Unable to get URL for WebSocket
11-14 17:52:09.265   730   730 E AndroidRuntime: 	at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl.connect(WebSocketRepositoryImpl.kt:164)
11-14 17:52:09.265   730   730 E AndroidRuntime: 	at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl.sendMessage(WebSocketRepositoryImpl.kt:189)
11-14 17:52:09.265   730   730 E AndroidRuntime: 	at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl.getStateChanges(WebSocketRepositoryImpl.kt:127)
11-14 17:52:09.265   730   730 E AndroidRuntime: 	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl.getEntityUpdates(IntegrationRepositoryImpl.kt:468)
11-14 17:52:09.265   730   730 E AndroidRuntime: 	at io.homeassistant.companion.android.home.HomePresenterImpl.getEntityUpdates(HomePresenterImpl.kt:61)
11-14 17:52:09.265   730   730 E AndroidRuntime: 	at io.homeassistant.companion.android.home.MainViewModel$loadEntities$1.invokeSuspend(MainViewModel.kt:43)
11-14 17:52:09.265   730   730 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
11-14 17:52:09.265   730   730 E AndroidRuntime: 	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:367)
11-14 17:52:09.265   730   730 E AndroidRuntime: 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
11-14 17:52:09.265   730   730 E AndroidRuntime: 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
11-14 17:52:09.265   730   730 E AndroidRuntime: 	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
11-14 17:52:09.265   730   730 E AndroidRuntime: 	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
11-14 17:52:09.265   730   730 E AndroidRuntime: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
11-14 17:52:09.265   730   730 E AndroidRuntime: 	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
11-14 17:52:09.265   730   730 E AndroidRuntime: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
11-14 17:52:09.265   730   730 E AndroidRuntime: 	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
11-14 17:52:09.265   730   730 E AndroidRuntime: 	at io.homeassistant.companion.android.home.MainViewModel.loadEntities(MainViewModel.kt:35)
11-14 17:52:09.265   730   730 E AndroidRuntime: 	at io.homeassistant.companion.android.home.MainViewModel.init(MainViewModel.kt:20)
11-14 17:52:09.265   730   730 E AndroidRuntime: 	at io.homeassistant.companion.android.home.HomeActivity.onCreate(HomeActivity.kt:49)`

**Comment by dshokouhi** [comment]
@alexd321 you'll need to install a previous version to get past this error until it is resolved: https://github.com/home-assistant/android/releases/tag/beta-1662-3d909c6

after installing you can login and then update and it should work fine
