### ISSUE TITLE
SSLHandshakeException with OCSP ``must staple``

### ISSUE THREAD

**Issue by Kariton** [home-assistant/android#1934]
**Home Assistant Android version:** 2021.10.0-minimal (F-Droid version)

**Android version:** LineageOS 18.1 (Android 11)

**Phone model:** Samsung Galaxy S9+ Exynos

**Home Assistant version:** 2021.11.1

**Last working Home Assistant release (if known):** -

**Description of problem:**
Related setup:
>Let's Encrypt certificate which ``must staple``. Obtained with certbot and the ``--must-staple`` flag.
>NGINX as reverse proxy with following config block:
>```
>    ssl_certificate /etc/pki/tls/certs/example.com-rsa/example.com-rsa-fullchain.pem;
>    ssl_certificate /etc/pki/tls/certs/example.com-p-384/example.com-p-384-fullchain.pem;
>    ssl_certificate_key /etc/pki/tls/private/example.com-rsa/example.com-rsa.key;
>    ssl_certificate_key /etc/pki/tls/private/example.com-p-384/example.com-p-384.key;
>    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
>    ssl_dhparam /etc/pki/tls/misc/dhparam.crt;
>    ssl_ecdh_curve secp521r1:secp384r1;
>    ssl_prefer_server_ciphers off;
>    ssl_protocols TLSv1.2 TLSv1.3;
>    ssl_session_cache shared:SSL:10m;
>    ssl_session_tickets on;
>    ssl_session_timeout 1d;
>    ssl_stapling on;
>    ssl_stapling_file /etc/pki/tls/misc/example.com-p-384-ocsp.der;
>    ssl_stapling_verify on;
>    ssl_trusted_certificate /etc/pki/tls/certs/example.com-p-384/example.com-p-384-fullchain.pem;
>
>```
> with and without ``ssl_stapling_file`` - changed nothing.
>
> valid OCSP response
>``` 
># openssl s_client -connect example.com:443 -status |  grep 'OCSP response' -A7
>OCSP response:
>======================================
>OCSP Response Data:
>    OCSP Response Status: successful (0x0)
>    Response Type: Basic OCSP Response
>    Version: 1 (0x0)
>    Responder Id: C = US, O = Let's Encrypt, CN = R3
>```

If I disable ``ssl_stapling_verify`` / ``ssl_stapling`` everything work as expected.
Firefox (is _very picky_ with OSCP) does accept my OCSP stapling settings - Chrome does not care. :)

It does (did) work _sometimes_.
But ATM I cant reproduce it _working_.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

<details>
  <summary>Click to expand!</summary>
  
```
11-16 15:41:48.731  6806  6806 D WebviewActivity: Authentication successful, unlocking app
11-16 15:41:49.197  6806  8922 I mali_egl: eglDestroySurface() in
11-16 15:41:49.199  6806  8922 I mali_winsys: delete_surface() [1318x792] return
11-16 15:41:49.199  6806  8922 I mali_egl: eglDestroySurface() out
11-16 15:41:49.199  6806  8922 W libEGL  : EGLNativeWindowType 0x7a768f7060 disconnect failed
11-16 15:41:49.199  6806  8922 D OpenGLRenderer: endAllActiveAnimators on 0x79f6860540 (RippleDrawable) with handle 0x79168a9160
11-16 15:41:49.286  6806  6806 D UrlRepository: Using external URL
11-16 15:41:49.286  6806  6806 I chatty  : uid=10158(io.homeassistant.companion.android.minimal) identical 2 lines
11-16 15:41:49.287  6806  6806 D UrlRepository: Using external URL
11-16 15:41:49.291  6806  6806 D UrlRepository: localUrl is: false and usesInternalSsid is: false
11-16 15:41:49.366  6806  6806 E SettingsPresenter: Unable to get core version.
11-16 15:41:49.366  6806  6806 E SettingsPresenter: io.homeassistant.companion.android.common.data.integration.IntegrationException: javax.net.ssl.SSLHandshakeException: Chain validation failed
11-16 15:41:49.366  6806  6806 E SettingsPresenter: 	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl.getHomeAssistantVersion(IntegrationRepositoryImpl.kt:398)
11-16 15:41:49.366  6806  6806 E SettingsPresenter: 	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl$getHomeAssistantVersion$1.invokeSuspend(Unknown Source:14)
11-16 15:41:49.366  6806  6806 E SettingsPresenter: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
11-16 15:41:49.366  6806  6806 E SettingsPresenter: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
11-16 15:41:49.366  6806  6806 E SettingsPresenter: 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
11-16 15:41:49.366  6806  6806 E SettingsPresenter: 	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
11-16 15:41:49.366  6806  6806 E SettingsPresenter: 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
11-16 15:41:49.366  6806  6806 E SettingsPresenter: 	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
11-16 15:41:49.366  6806  6806 E SettingsPresenter: 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
11-16 15:41:49.366  6806  6806 E SettingsPresenter: 	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
11-16 15:41:49.366  6806  6806 E SettingsPresenter: 	at io.homeassistant.companion.android.settings.SettingsPresenterImpl.nfcEnabled(SettingsPresenterImpl.kt:193)
11-16 15:41:49.366  6806  6806 E SettingsPresenter: 	at io.homeassistant.companion.android.settings.SettingsFragment.onCreatePreferences(SettingsFragment.kt:129)
11-16 15:41:49.366  6806  6806 E SettingsPresenter: 	at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:160)
11-16 15:41:49.366  6806  6806 E SettingsPresenter: 	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2949)
11-16 15:41:49.366  6806  6806 E SettingsPresenter: 	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
11-16 15:41:49.366  6806  6806 E SettingsPresenter: 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)
11-16 15:41:49.366  6806  6806 E SettingsPresenter: 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
11-16 15:41:49.366  6806  6806 E SettingsPresenter: 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
11-16 15:41:49.366  6806  6806 E SettingsPresenter: 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
11-16 15:41:49.366  6806  6806 E SettingsPresenter: 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3138)
11-16 15:41:49.366  6806  6806 E SettingsPresenter: 	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3072)
11-16 15:41:49.366  6806  6806 E SettingsPresenter: 	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
11-16 15:41:49.366  6806  6806 E SettingsPresenter: 	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:502)
11-16 15:41:49.366  6806  6806 E SettingsPresenter: 	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
11-16 15:41:49.366  6806  6806 E SettingsPresenter: 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
11-16 15:41:49.366  6806  6806 E SettingsPresenter: 	at android.app.Activity.performStart(Activity.java:8018)
11-16 15:41:49.366  6806  6806 E SettingsPresenter: 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3457)
11-16 15:41:49.366  6806  6806 E SettingsPresenter: 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
11-16 15:41:49.366  6806  6806 E SettingsPresenter: 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
11-16 15:41:49.366  6806  6806 E SettingsPresenter: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
11-16 15:41:49.366  6806  6806 E SettingsPresenter: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
11-16 15:41:49.366  6806  6806 E SettingsPresenter: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
11-16 15:41:49.366  6806  6806 E SettingsPresenter: 	at android.os.Handler.dispatchMessage(Handler.java:106)
11-16 15:41:49.366  6806  6806 E SettingsPresenter: 	at android.os.Looper.loop(Looper.java:223)
11-16 15:41:49.366  6806  6806 E SettingsPresenter: 	at android.app.ActivityThread.main(ActivityThread.java:7664)
11-16 15:41:49.366  6806  6806 E SettingsPresenter: 	at java.lang.reflect.Method.invoke(Native Method)
11-16 15:41:49.366  6806  6806 E SettingsPresenter: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
11-16 15:41:49.366  6806  6806 E SettingsPresenter: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
11-16 15:41:49.366  6806  6806 E SettingsPresenter: Caused by: javax.net.ssl.SSLHandshakeException: Chain validation failed
11-16 15:41:49.366  6806  6806 E SettingsPresenter: 	at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:362)
11-16 15:41:49.366  6806  6806 E SettingsPresenter: 	at com.android.org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1134)
11-16 15:41:49.366  6806  6806 E SettingsPresenter: 	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1089)
11-16 15:41:49.366  6806  6806 E SettingsPresenter: 	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:876)
11-16 15:41:49.366  6806  6806 E SettingsPresenter: 	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747)
11-16 15:41:49.366  6806  6806 E SettingsPresenter: 	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712)
11-16 15:41:49.369  6806  6806 E SettingsPresenter: 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:849)
11-16 15:41:49.369  6806  6806 E SettingsPresenter: 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.access$100(ConscryptEngineSocket.java:722)
11-16 15:41:49.369  6806  6806 E SettingsPresenter: 	at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:238)
11-16 15:41:49.369  6806  6806 E SettingsPresenter: 	at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:217)
11-16 15:41:49.369  6806  6806 E SettingsPresenter: 	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
11-16 15:41:49.369  6806  6806 E SettingsPresenter: 	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
11-16 15:41:49.369  6806  6806 E SettingsPresenter: 	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
11-16 15:41:49.369  6806  6806 E SettingsPresenter: 	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
11-16 15:41:49.369  6806  6806 E SettingsPresenter: 	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
11-16 15:41:49.369  6806  6806 E SettingsPresenter: 	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
11-16 15:41:49.369  6806  6806 E SettingsPresenter: 	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
11-16 15:41:49.369  6806  6806 E SettingsPresenter: 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
11-16 15:41:49.369  6806  6806 E SettingsPresenter: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
11-16 15:41:49.369  6806  6806 E SettingsPresenter: 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
11-16 15:41:49.369  6806  6806 E SettingsPresenter: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
11-16 15:41:49.369  6806  6806 E SettingsPresenter: 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
11-16 15:41:49.369  6806  6806 E SettingsPresenter: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
11-16 15:41:49.369  6806  6806 E SettingsPresenter: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
11-16 15:41:49.369  6806  6806 E SettingsPresenter: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
11-16 15:41:49.369  6806  6806 E SettingsPresenter: 	at io.homeassistant.companion.android.common.data.HomeAssistantRetrofit$special$$inlined$-addInterceptor$1.intercept(OkHttpClient.kt:1089)
11-16 15:41:49.369  6806  6806 E SettingsPresenter: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
11-16 15:41:49.369  6806  6806 E SettingsPresenter: 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
11-16 15:41:49.369  6806  6806 E SettingsPresenter: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
11-16 15:41:49.369  6806  6806 E SettingsPresenter: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
11-16 15:41:49.369  6806  6806 E SettingsPresenter: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
11-16 15:41:49.369  6806  6806 E SettingsPresenter: 	at java.lang.Thread.run(Thread.java:923)
11-16 15:41:49.369  6806  6806 E SettingsPresenter: Caused by: java.security.cert.CertificateException: Chain validation failed
11-16 15:41:49.369  6806  6806 E SettingsPresenter: 	at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:724)
11-16 15:41:49.369  6806  6806 E SettingsPresenter: 	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:554)
11-16 15:41:49.369  6806  6806 E SettingsPresenter: 	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:575)
11-16 15:41:49.369  6806  6806 E SettingsPresenter: 	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:643)
11-16 15:41:49.369  6806  6806 E SettingsPresenter: 	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:510)
11-16 15:41:49.369  6806  6806 E SettingsPresenter: 	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:428)
11-16 15:41:49.369  6806  6806 E SettingsPresenter: 	at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:356)
11-16 15:41:49.369  6806  6806 E SettingsPresenter: 	at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
11-16 15:41:49.369  6806  6806 E SettingsPresenter: 	at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:90)
11-16 15:41:49.369  6806  6806 E SettingsPresenter: 	at com.android.org.conscrypt.ConscryptEngineSocket$2.checkServerTrusted(ConscryptEngineSocket.java:161)
11-16 15:41:49.369  6806  6806 E SettingsPresenter: 	at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:250)
11-16 15:41:49.369  6806  6806 E SettingsPresenter: 	at com.android.org.conscrypt.ConscryptEngine.verifyCertificateChain(ConscryptEngine.java:1644)
11-16 15:41:49.369  6806  6806 E SettingsPresenter: 	at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
11-16 15:41:49.369  6806  6806 E SettingsPresenter: 	at com.android.org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:568)
11-16 15:41:49.369  6806  6806 E SettingsPresenter: 	at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1095)
11-16 15:41:49.369  6806  6806 E SettingsPresenter: 	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1079)
11-16 15:41:49.369  6806  6806 E SettingsPresenter: 	... 29 more
11-16 15:41:49.369  6806  6806 E SettingsPresenter: Caused by: java.security.cert.CertPathValidatorException: OCSP response does not include a response for a certificate supplied in the OCSP request
11-16 15:41:49.370  6806  6806 E SettingsPresenter: 	at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)
11-16 15:41:49.370  6806  6806 E SettingsPresenter: 	at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:222)
11-16 15:41:49.370  6806  6806 E SettingsPresenter: 	at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:140)
11-16 15:41:49.370  6806  6806 E SettingsPresenter: 	at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:79)
11-16 15:41:49.370  6806  6806 E SettingsPresenter: 	at java.security.cert.CertPathValidator.validate(CertPathValidator.java:301)
11-16 15:41:49.370  6806  6806 E SettingsPresenter: 	at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:720)
11-16 15:41:49.370  6806  6806 E SettingsPresenter: 	... 44 more
11-16 15:41:49.370  6806  6806 E SettingsPresenter: Caused by: java.security.cert.CertPathValidatorException: OCSP response does not include a response for a certificate supplied in the OCSP request
11-16 15:41:49.370  6806  6806 E SettingsPresenter: 	at sun.security.provider.certpath.OCSPResponse.verify(OCSPResponse.java:416)
11-16 15:41:49.370  6806  6806 E SettingsPresenter: 	at sun.security.provider.certpath.RevocationChecker.checkOCSP(RevocationChecker.java:709)
11-16 15:41:49.370  6806  6806 E SettingsPresenter: 	at sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:363)
11-16 15:41:49.370  6806  6806 E SettingsPresenter: 	at sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:337)
11-16 15:41:49.370  6806  6806 E SettingsPresenter: 	at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
11-16 15:41:49.370  6806  6806 E SettingsPresenter: 	... 49 more
11-16 15:41:49.370  6806  6806 E SettingsPresenter: 	Suppressed: java.security.cert.CertPathValidatorException: Could not determine revocation status
11-16 15:41:49.370  6806  6806 E SettingsPresenter: 		at sun.security.provider.certpath.RevocationChecker.buildToNewKey(RevocationChecker.java:1092)
11-16 15:41:49.370  6806  6806 E SettingsPresenter: 		at sun.security.provider.certpath.RevocationChecker.verifyWithSeparateSigningKey(RevocationChecker.java:910)
11-16 15:41:49.370  6806  6806 E SettingsPresenter: 		at sun.security.provider.certpath.RevocationChecker.checkCRLs(RevocationChecker.java:577)
11-16 15:41:49.370  6806  6806 E SettingsPresenter: 		at sun.security.provider.certpath.RevocationChecker.checkCRLs(RevocationChecker.java:465)
11-16 15:41:49.370  6806  6806 E SettingsPresenter: 		at sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:394)
11-16 15:41:49.370  6806  6806 E SettingsPresenter: 		... 51 more
11-16 15:41:49.430  6806  6961 D SensorWorker: Updating all Sensors.
11-16 15:41:49.433  6806  9003 I WM-Processor: Moving WorkSpec (5d30944c-69ea-415a-8b2b-69134df0bab8) to the foreground
11-16 15:41:49.459  6806  8922 I mali_winsys: new_window_surface() [1440x2960] return: 0x3000
11-16 15:41:49.611  6806  6806 I WM-SystemFgDispatcher: Started foreground service Intent { act=ACTION_START_FOREGROUND cmp=io.homeassistant.companion.android.minimal/androidx.work.impl.foreground.SystemForegroundService (has extras) }
11-16 15:41:49.615  6806  6961 D SensorReceiver: Nothing to update
11-16 15:41:49.617  6806  9005 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=5d30944c-69ea-415a-8b2b-69134df0bab8, tags={ io.homeassistant.companion.android.sensors.SensorWorker } ]
11-16 15:41:49.628  6806  6806 I WM-SystemFgDispatcher: Stopping foreground service
11-16 15:41:50.009  6806  8922 I mali_egl: eglDestroySurface() in
11-16 15:41:50.011  6806  8922 I mali_winsys: delete_surface() [1440x2960] return
11-16 15:41:50.012  6806  8922 I mali_egl: eglDestroySurface() out
11-16 15:41:50.012  6806  8922 W libEGL  : EGLNativeWindowType 0x7a7688a730 disconnect failed
```
</details>

**Screenshot of problem:** -

**Additional information:**
First issue with OCSP:
https://github.com/home-assistant/android/issues/1753

**Comment by dshokouhi** [comment]
This error does not appear to be one the app can solve as it's an SSL error. You will probably have to fix the validation error message.

`11-16 15:41:49.366  6806  6806 E SettingsPresenter: io.homeassistant.companion.android.common.data.integration.IntegrationException: javax.net.ssl.SSLHandshakeException: Chain validation failed`

These errors are not ones for the app to solve.

**Comment by Kariton** [comment]
Okay - if I follow you...

Why does every browser accept this?
Chrome, Brave, Edge (all basically the same) and Firefox and Fennec are working.

It does not matter what device I use.
Laptop, Tower, Mobile, Tablet, Work Laptop...

**Comment by dshokouhi** [comment]
The app isn't like a browser in this sense. Browsers don't make REST API calls or anything else the app does. SSL certificates must be valid and without errors. The app does not bypass any error.

**Comment by Kariton** [comment]
I dont think that ANY browser is automatically bypassing SSL validation errors.
HOLY just imagen this...

Anyway. What can i do to proof that the cert IS valid?

```
#openssl verify -no-CAfile -no-CApath -CAfile /etc/pki/tls/certs/example.com-p-384/example.com-p-384-root.pem -untrusted /etc/pki/tls/certs/example.com-p-384/example.com-p-384-chain.pem  /etc/pki/tls/certs/example.com-p-384/example.com-p-384.pem
/etc/pki/tls/certs/example.com-p-384/example.com-p-384.pem: OK
```

**Comment by dshokouhi** [comment]
> What can i do to proof that the cert IS valid?

Provide a SSL cert that android likes to use, you said it yourself if you turn off stapling its accepted right?

**Comment by dshokouhi** [comment]
Regarding the CA, android is very very picky about it. Even some LE providers are not good enough as I have seen in some closed issues. Here is a page from google's developer site that should hopefully explain the issue regarding CA

https://developer.android.com/training/articles/security-ssl#CommonProblems

The thing to remember is that the app is more than just a browser as it makes API calls using REST and websockets etc... it communicates to HA in a way that a browser does not.

**Comment by Kariton** [comment]
I understand "basically" that API calls differ from WEB-Browsing.
It would be fine if you explained it better.

In this context my understanding is  that "RAW" API connections rely on the system trust store?
This would be an answer that had helped me more then just "(REST) API is not the same as browsing".

After looking at https://letsencrypt.org/certificates/ I found the `OCSP Signing Certificate` - which does not solved my problem...
I know that cert. trust errors are not easy to debug remotely.
But this is also a resource that cold be in your response.

Nevertheless https://developer.android.com/training/articles/security-ssl#CommonProblems helped me a lot to understand the core problem.

Now Im tying to find what needs to be added to my system trust store / NGINX configuration to make Android happy.

**Comment by dshokouhi** [comment]
Closing as this is not an error the app will be able to solve, SSL errors are for the user to solve (the app just expects a valid SSL certificate)
