### ISSUE TITLE
Websockets crash due to missing property old_state

### ISSUE THREAD

**Issue by dshokouhi** [home-assistant/android#1969]
**Home Assistant Android version:**
latest master
**Android version:**
12
**Phone model:**
Pixel 6 pro
**Home Assistant version:**
2021.11.4
**Last working Home Assistant release (if known):**
N/A
**Description of problem:**

Noticed a random crash from the app when I opened it and came to find the following traceback

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```
2021-11-26 17:14:54.512 21774-21816/io.homeassistant.companion.android.debug E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-2
    Process: io.homeassistant.companion.android.debug, PID: 21774
    java.lang.IllegalArgumentException: Instantiation of [simple type, class io.homeassistant.companion.android.common.data.websocket.impl.entities.StateChangedEvent] value failed for JSON property old_state due to missing (therefore NULL) value for creator parameter oldState which is a non-nullable type
        at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: io.homeassistant.companion.android.common.data.websocket.impl.entities.EventResponse["data"]->io.homeassistant.companion.android.common.data.websocket.impl.entities.StateChangedEvent["old_state"])
        at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4394)
        at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:4335)
        at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl.handleEvent(WebSocketRepositoryImpl.kt:239)
        at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl.access$handleEvent(WebSocketRepositoryImpl.kt:46)
        at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl$onMessage$1.invokeSuspend(WebSocketRepositoryImpl.kt:284)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
     Caused by: com.fasterxml.jackson.module.kotlin.MissingKotlinParameterException: Instantiation of [simple type, class io.homeassistant.companion.android.common.data.websocket.impl.entities.StateChangedEvent] value failed for JSON property old_state due to missing (therefore NULL) value for creator parameter oldState which is a non-nullable type
        at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: io.homeassistant.companion.android.common.data.websocket.impl.entities.EventResponse["data"]->io.homeassistant.companion.android.common.data.websocket.impl.entities.StateChangedEvent["old_state"])
        at com.fasterxml.jackson.module.kotlin.KotlinValueInstantiator.createFromObjectWith(KotlinValueInstantiator.kt:116)
        at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:202)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:443)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:351)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:184)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:563)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:438)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:351)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:184)
        at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4389)
        at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:4335) 
        at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl.handleEvent(WebSocketRepositoryImpl.kt:239) 
        at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl.access$handleEvent(WebSocketRepositoryImpl.kt:46) 
        at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl$onMessage$1.invokeSuspend(WebSocketRepositoryImpl.kt:284) 
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) 
```

**Screenshot of problem:**

**Additional information:**

**Comment by JBassett** [comment]
Need to configure the mapper with this: 
https://fasterxml.github.io/jackson-databind/javadoc/2.6/com/fasterxml/jackson/databind/DeserializationFeature.html#FAIL_ON_UNKNOWN_PROPERTIES

Not sure why I didn't to begin with.

**Comment by dshokouhi** [comment]
@JBassett  looking at sentry I can see this error is still persisting in the production release. The error message looks slightly different now. 

```
com.fasterxml.jackson.module.kotlin.MissingKotlinParameterException: Instantiation of [simple type, class io.homeassistant.companion.android.common.data.websocket.impl.entities.StateChangedEvent] value failed for JSON property old_state due to missing (therefore NULL) value for creator parameter oldState which is a non-nullable type
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: io.homeassistant.companion.android.common.data.websocket.impl.entities.EventResponse["data"]->io.homeassistant.companion.android.common.data.websocket.impl.entities.StateChangedEvent["old_state"])
    at com.fasterxml.jackson.module.kotlin.KotlinValueInstantiator.createFromObjectWith(KotlinValueInstantiator.kt:116)
    at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:202)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:443)
    at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:351)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:184)
    at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:563)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:438)
    at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:351)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:184)
    at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4389)
    at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:4335)
    at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl.handleEvent(WebSocketRepositoryImpl.kt:241)
    at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl.access$handleEvent(WebSocketRepositoryImpl.kt:47)
    at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl$onMessage$1.invokeSuspend(WebSocketRepositoryImpl.kt:286)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
java.lang.IllegalArgumentException: Instantiation of [simple type, class io.homeassistant.companion.android.common.data.websocket.impl.entities.StateChangedEvent] value failed for JSON property old_state due to missing (therefore NULL) value for creator parameter oldState which is a non-nullable type
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: io.homeassistant.companion.android.common.data.websocket.impl.entities.EventResponse["data"]->io.homeassistant.companion.android.common.data.websocket.impl.entities.StateChangedEvent["old_state"])
    at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4394)
    at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:4335)
    at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl.handleEvent(WebSocketRepositoryImpl.kt:241)
    at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl.access$handleEvent(WebSocketRepositoryImpl.kt:47)
    at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl$onMessage$1.invokeSuspend(WebSocketRepositoryImpl.kt:286)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

I will reopen for now unless you feel this should be a new issue :)
