### ISSUE TITLE
Impossible to add widget with Android 7

### ISSUE THREAD

**Issue by uowis** [home-assistant/android#2064]
**Home Assistant Android version: 2021.12.0-full**

**Android version: 7**

**Phone model: Huawai P9 SLA-L22**

**Home Assistant version: Home Assistant 2021.12.4**

**Last working Home Assistant release (if known): unknow**

**Description of problem: Widget don't drop when i want to add it **

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```
E/HwLauncher: Launcher startActivityForResult is failed,the intent = Intent { act=android.appwidget.action.APPWIDGET_CONFIGURE cmp=io.homeassistant.companion.android/.widgets.button.ButtonWidgetConfigureActivity (has extras) }
    java.lang.SecurityException: Permission Denial: starting Intent { act=android.appwidget.action.APPWIDGET_CONFIGURE cmp=io.homeassistant.companion.android/.widgets.button.ButtonWidgetConfigureActivity (has extras) } from ProcessRecord{3140339 3011:com.huawei.android.launcher/u0a64} (pid=3011, uid=10064) not exported from uid 10134
        at android.os.Parcel.readException(Parcel.java:1673)
        at android.os.Parcel.readException(Parcel.java:1626)
        at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:3097)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1539)
        at android.app.Activity.startActivityForResult(Activity.java:4391)
        at android.app.Activity.startActivityForResult(Activity.java:4335)
        at com.huawei.android.launcher.Launcher.startActivityForResult(Launcher.java:4309)
        at com.huawei.android.launcher.Launcher.startActivityForResultSafely(Launcher.java:5548)
        at com.huawei.android.launcher.Launcher.addAppWidgetImpl(Launcher.java:4441)
        at com.huawei.android.launcher.Launcher.addAppWidgetFromDrop(Launcher.java:4521)
        at com.huawei.android.launcher.Workspace.addPendingAddItemInfoToDesktop(Workspace.java:10389)
        at com.huawei.android.launcher.Workspace$9.run(Workspace.java:5898)
        at com.huawei.android.launcher.DragLayer$3.onAnimationEnd(DragLayer.java:1150)
        at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1149)
        at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1309)
        at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
        at android.animation.AnimationHandler.-wrap2(AnimationHandler.java)
        at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:931)
        at android.view.Choreographer.doCallbacks(Choreographer.java:742)
        at android.view.Choreographer.doFrame(Choreographer.java:671)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:919)
        at android.os.Handler.handleCallback(Handler.java:761)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6617)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
```

**Screenshot of problem:**

**Additional information: I have recently change SSL algo to RSA, because Android 7 don"t accept secp384r1 **

**Comment by dshokouhi** [comment]
This looks like a device specific error. It says permission denial. Try to check if Huawei added some weird specific permission for adding a widget because that is not part of stock android. It could be a launcher setting.

What troubleshooting steps have you tried? Maybe give these steps a shot: https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app

**Comment by dbalazuc** [comment]
I have had similar issues on another application. 

Android apps targeting 12 or up now require to have the ["exported" attribute](https://developer.android.com/guide/topics/manifest/activity-element#exported) of each activity explicitly set in AndroidManifest.xml. The activities for the APPWIDGET_CONFIGURE actions with "exported" set to "false" work for most deployments but custom launchers require the "exported" flag set to "true' or the provided error occurs. 

Since the app does not export APPWIDGET_CONFIGURE activities and the provided stacktrace indicates that the request is from a custom launcher (`com.huawei.android.launcher.Launcher`), this is most likely the cause of the issue.

Now, exporting activities should be considered with caution and there is probably a better fix than setting "exported" to "true" for those widget configuration activities, but I am not aware of it. 

eg:
```
 <activity android:name=".widgets.button.ButtonWidgetConfigureActivity"
    android:exported="true">
    <intent-filter>
        <action android:name="android.appwidget.action.APPWIDGET_CONFIGURE" />
    </intent-filter>
</activity>
```

**Comment by dshokouhi** [comment]
> I have had similar issues on another application. 
> 
> Android apps targeting 12 or up now require to have the ["exported" attribute](https://developer.android.com/guide/topics/manifest/activity-element#exported) of each activity explicitly set in AndroidManifest.xml. The activities for the APPWIDGET_CONFIGURE actions with "exported" set to "false" work for most deployments but custom launchers require the "exported" flag set to "true' or the provided error occurs. 
> 
> Since the app does not export APPWIDGET_CONFIGURE activities and the provided stacktrace indicates that the request is from a custom launcher (`com.huawei.android.launcher.Launcher`), this is most likely the cause of the issue.
> 
> Now, exporting activities should be considered with caution and there is probably a better fix than setting "exported" to "true" for those widget configuration activities, but I am not aware of it. 
> 
> eg:
> ```
>  <activity android:name=".widgets.button.ButtonWidgetConfigureActivity"
>     android:exported="true">
>     <intent-filter>
>         <action android:name="android.appwidget.action.APPWIDGET_CONFIGURE" />
>     </intent-filter>
> </activity>
> ```

If we were required to have the export feature set to true then nobody would be able to add widgets but that is not the case. I can add widgets using pixel launcher. Export flag does not trigger a permission denial, the error message would actually mention the export issue as we have seen already.

**Comment by JBassett** [comment]
It might only be applicable in older versions of Android with newer launchers that I'm on implement the newer functionality.  I don't see any issue exporting the activities.

**Comment by dshokouhi** [comment]
Ugh why cant they just make things more consistent :) ok lets just make the export to `true` then.

**Comment by dbalazuc** [comment]
> If we were required to have the export feature set to true then nobody would be able to add widgets but that is not the case. I can add widgets using pixel launcher. Export flag does not trigger a permission denial, the error message would actually mention the export issue as we have seen already.

It is not reproducible on stock Android and as I mention, only with a custom launcher, maybe some old ones only (APEX Launcher is one that used to cause this issue in my experience)

**Comment by uowis** [comment]
Thanks and good jobs, widgets works now !
