### ISSUE TITLE
Android widget switch is very slow while app is not

### ISSUE THREAD

**Issue by coloco21** [home-assistant/android#2107]
Hi,

I just set up Home Assistant on a Raspberry Pi Zero 2 W with a custom install. I have a few Shelly plugs I use to control the lights of my living room.
When I am in the android app and I turn on/off the lights, the reaction time is almost instantaneous. However, when I use an android widget to do the same thing, it takes ~3 to 7s before I hear the plugs turning on/off, and sometimes it doesn't even do anything.

I went to see the logs and they didn't show anything unusual, even when the button didn't work. Here are the app logs from a successful button press (that took 3s) :

```
01-04 01:47:00.347 24355 24355 D ButtonWidget: Broadcast received: 
01-04 01:47:00.347 24355 24355 D ButtonWidget: Broadcast action: io.homeassistant.companion.android.widgets.button.ButtonWidget.CALL_SERVICE
01-04 01:47:00.347 24355 24355 D ButtonWidget: AppWidgetId: 77
01-04 01:47:00.349 24355 24355 D ButtonWidget: Calling widget service
01-04 01:47:01.774 24355 24355 D ButtonWidget: Service Call Data loaded:
01-04 01:47:01.774 24355 24355 D ButtonWidget: domain: switch
01-04 01:47:01.774 24355 24355 D ButtonWidget: service: toggle
01-04 01:47:01.774 24355 24355 D ButtonWidget: service_data: {"entity_id":["switch.bibliotheque","switch.guirlande","switch.piano","switch.tv"]}
01-04 01:47:01.783 24355 24355 D ButtonWidget: Sending service call to Home Assistant
01-04 01:47:01.787 24355 24355 D UrlRepository: localUrl is: false and usesInternalSsid is: false
01-04 01:47:02.035 24355 24355 D ButtonWidget: Service call sent successfully
01-04 01:47:02.731 24355 24355 D ButtonWidget: Broadcast received: 
01-04 01:47:02.731 24355 24355 D ButtonWidget: Broadcast action: io.homeassistant.companion.android.widgets.button.ButtonWidget.CALL_SERVICE
01-04 01:47:02.731 24355 24355 D ButtonWidget: AppWidgetId: 77
01-04 01:47:02.735 24355 24355 D ButtonWidget: Calling widget service
01-04 01:47:04.159 24355 24355 D ButtonWidget: Service Call Data loaded:
01-04 01:47:04.159 24355 24355 D ButtonWidget: domain: switch
01-04 01:47:04.159 24355 24355 D ButtonWidget: service: toggle
01-04 01:47:04.159 24355 24355 D ButtonWidget: service_data: {"entity_id":["switch.bibliotheque","switch.guirlande","switch.piano","switch.tv"]}
01-04 01:47:04.170 24355 24355 D ButtonWidget: Sending service call to Home Assistant
01-04 01:47:04.173 24355 24355 D UrlRepository: localUrl is: false and usesInternalSsid is: false
01-04 01:47:04.287 24355 24355 D ButtonWidget: Service call sent successfully
```

Here's some info from the app:

## System Health

version | core-2021.12.7
-- | --
installation_type | Home Assistant Core
dev | false
hassio | false
docker | false
user | homeassistant
virtualenv | true
python_version | 3.9.2
os_name | Linux
os_version | 5.10.63-v7+
arch | armv7l
timezone | Europe/Paris

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 0
views | 1
mode | storage

</details>

I use a Huawei Mate 10 pro with Android 10. Huawei is notorious for closing apps in background and that might explain the bug where the widget does nothing, although I doubt it cause the logs in the app still updated and were supposedly successful when that happened.

However I also have this error a bunch of times and that might explain it : 

```
Logger: homeassistant.components.webhook
Source: components/mobile_app/webhook.py:239
Integration: Webhook (documentation, issues)
First occurred: 01:23:44 (7 occurrences)
Last logged: 01:36:39

Error processing webhook 5febadb15e0ca00c40e78b6f11b1371d09b28c63f6b2c100e79706c4f87fbbbc
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/mobile_app/webhook.py", line 225, in webhook_call_service
    await hass.services.async_call(
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/core.py", line 1449, in async_call
    processed_data = handler.schema(service_data)
  File "/srv/homeassistant/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/srv/homeassistant/lib/python3.9/site-packages/voluptuous/validators.py", line 215, in _run
    return self._exec(self._compiled, value, path)
  File "/srv/homeassistant/lib/python3.9/site-packages/voluptuous/validators.py", line 341, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/srv/homeassistant/lib/python3.9/site-packages/voluptuous/validators.py", line 339, in _exec
    v = func(path, v)
  File "/srv/homeassistant/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/srv/homeassistant/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/srv/homeassistant/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/srv/homeassistant/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: not a valid value for dictionary value @ data['entity_id']

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/webhook/__init__.py", line 104, in async_handle_webhook
    response = await webhook["handler"](hass, webhook_id, request)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/mobile_app/webhook.py", line 209, in handle_webhook
    return await asyncio.shield(
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/mobile_app/webhook.py", line 144, in validate_and_run
    return await func(hass, config_entry, data)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/mobile_app/webhook.py", line 239, in webhook_call_service
    raise HTTPBadRequest() from ex
aiohttp.web_exceptions.HTTPBadRequest: Bad Request
```

Thanks for your help.

**Comment by dshokouhi** [comment]
> I use a Huawei Mate 10 pro with Android 10. Huawei is notorious for closing apps in background and that might explain the bug where the widget does nothing,

you need to make sure to grant the app background permissions and you also need to double check all settings to ensure the app can run in the background.



> When I am in the android app and I turn on/off the lights, the reaction time is almost instantaneous. However, when I use an android widget to do the same thing, it takes ~3 to 7s before I hear the plugs turning on/off, and sometimes it doesn't even do anything.

The HA frontend has a different communication method than features such as widgets which relies on the HA REST API to send data. Any delay here is either device related or network related. All we do is connect to the server and send the data.



> However I also have this error a bunch of times and that might explain it :

Try: https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app

**Comment by dshokouhi** [comment]
Closing due to lack of response
