### ISSUE TITLE
Cant connect to HomeAssistant with WearOS App

### ISSUE THREAD

**Issue by windowslucker1121** [home-assistant/android#2114]
**Home Assistant Android version:**
( i am in the Beta Program in the PlayStore)
WearOS: 2022.1.1 
Android: 2022.1.1-full

**Android version:**
Phone: Android 11
WearOS: 2.33

**Phone model:**
Phone: OnePlus 9
Wear: TicWatch 3 Pro

**Home Assistant version:**

core-2021.12.8
**Last working Home Assistant release (if known):**
core-2021.12.8

**Description of problem:**
I cant connect to my Home Assistant with my WearOS Smartwatch ( TicWatch 3 Pro).
It is unnecessary if im trying to connect to it vio IP or remote URL. (My HomeAssistant is avaiable from outside through an ReverseProxy). And yes i saw the other open Issue where a active bluetooth connection was the issue, i have same behaviour - doesnt matter if bluetooth is on or off or if the watch is connected to wifi.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**
I used filter "homeass" and Verbose in Android Studio to gain the Logs. They first is the process of fully installing, opening and trying to connect 2 times.

```
2022-01-05 19:12:25.828 13428-13428/? W/Finsky: [2] com.google.android.finsky.g.c.b(105): No everExternallyHosted provided for io.homeassistant.companion.android
2022-01-05 19:12:25.856 13428-13428/? I/Finsky: [2] com.google.android.finsky.installer.a.aj.a(117): Request install of io.homeassistant.companion.android v=1891 pri=2 mods=[] for single_install
2022-01-05 19:12:25.894 13428-13428/? I/Finsky: [2] com.google.android.finsky.installer.a.aj.a(523): Installer kick - starting io.homeassistant.companion.android
2022-01-05 19:12:26.376 13428-13594/? I/Finsky: [1086] com.google.android.finsky.dl.f.a(40): Created session 1577485406 for io.homeassistant.companion.android
2022-01-05 19:12:26.395 13428-13428/? I/Finsky: [2] com.google.android.finsky.installer.a.bi.a(506): Required downloads: [io.homeassistant.companion.android, ..split.config.xhdpi, ..split.config.de]
2022-01-05 19:12:26.397 13428-13594/? I/Finsky: [1086] com.google.android.finsky.dl.p.run(8): Session for io.homeassistant.companion.android already exists, skipping creation
2022-01-05 19:12:26.434 13428-13428/? I/Finsky: [2] com.google.android.finsky.installer.a.bs.onPostExecute(43): Downloading compressed for io.homeassistant.companion.android (adid: io.homeassistant.companion.android , isid: 9vG_vlUrQsiE7H8Fx9dSTg)
2022-01-05 19:12:26.435 13428-13428/? I/Finsky: [2] com.google.android.finsky.download.e.a(45): Duplicate state set for 'io.homeassistant.companion.android' (0). Already in that state
2022-01-05 19:12:26.436 13428-13428/? I/Finsky: [2] com.google.android.finsky.download.n.a(22): Download io.homeassistant.companion.android added to DownloadQueue
2022-01-05 19:12:26.437 13428-13428/? I/Finsky: [2] com.google.android.finsky.download.e.a(47): io.homeassistant.companion.android from 0 to 1.
2022-01-05 19:12:26.457 13428-13428/? I/Finsky: [2] com.google.android.finsky.download.w.a(18): Download io.homeassistant.companion.android starting
2022-01-05 19:12:26.541 13428-13428/? I/Finsky: [2] com.google.android.finsky.download.u.onPostExecute(3): Enqueued io.homeassistant.companion.android as content://downloads/my_downloads/23
2022-01-05 19:12:26.541 13428-13428/? I/Finsky: [2] com.google.android.finsky.download.e.a(47): io.homeassistant.companion.android from 1 to 2.
2022-01-05 19:12:26.542 13428-13428/? I/Finsky: [2] com.google.android.finsky.download.n.g(106): io.homeassistant.companion.android: onStart
2022-01-05 19:12:26.581 13428-13428/? I/Finsky: [2] com.google.android.finsky.download.n.a(82): io.homeassistant.companion.android: onProgress 0/-1 Status: 192 URI: content://downloads/my_downloads/23.
2022-01-05 19:12:41.862 13428-13428/? I/Finsky: [2] com.google.android.finsky.api.a.fc.a(243): Not delivering second response for request=[[ ] https://android.clients.google.com/fdfe/details?doc=io.homeassistant.companion.android&nocache_qos=lt 0xe8d195d1 NORMAL 7]
2022-01-05 19:12:42.976 13428-13428/? I/Finsky: [2] com.google.android.finsky.api.a.fc.a(243): Not delivering second response for request=[[ ] https://android.clients.google.com/fdfe/rev?doc=io.homeassistant.companion.android&n=20&sort=4&nocache_qos=lt 0xe8d195d1 NORMAL 9]
2022-01-05 19:13:21.095 13428-13428/? I/Finsky: [2] com.google.android.finsky.download.n.a(82): io.homeassistant.companion.android: onProgress 11013690/11013690 Status: 200 URI: content://downloads/my_downloads/23.
2022-01-05 19:13:21.115 13428-13428/? I/Finsky: [2] com.google.android.finsky.download.e.a(47): io.homeassistant.companion.android from 2 to 3.
2022-01-05 19:13:21.138 13428-13428/? I/Finsky: [2] com.google.android.finsky.download.n.e(98): io.homeassistant.companion.android: onComplete
2022-01-05 19:13:21.138 13428-13428/? I/Finsky: [2] com.google.android.finsky.download.n.i(65): Download io.homeassistant.companion.android removed from DownloadQueue
2022-01-05 19:13:21.163 13428-13428/? I/Finsky: [2] com.google.android.finsky.installer.a.bi.b(342): Prepare to copy io.homeassistant.companion.android (adid: io.homeassistant.companion.android , isid: 9vG_vlUrQsiE7H8Fx9dSTg) from content://downloads/my_downloads/23 (expect 11672047 bytes, isCompressed: true)
2022-01-05 19:13:21.192 13428-13696/? I/Finsky: [1105] com.google.android.finsky.apkprocessor.h.a(11): Decompressing io.homeassistant.companion.android (io.homeassistant.companion.android) format 1
2022-01-05 19:13:22.063 13428-13696/? I/Finsky: [1105] com.google.android.finsky.apkprocessor.h.a(22): io.homeassistant.companion.android (io.homeassistant.companion.android) (11672047 bytes) copied successfully in 531 ms
2022-01-05 19:13:22.533 13428-13428/? I/Finsky: [2] com.google.android.finsky.installer.a.bn.a(10): Successfully copied APK to update io.homeassistant.companion.android (adid: io.homeassistant.companion.android , isid: 9vG_vlUrQsiE7H8Fx9dSTg)
2022-01-05 19:13:22.606 13428-13428/? I/Finsky: [2] com.google.android.finsky.installer.a.bs.onPostExecute(43): Downloading compressed for io.homeassistant.companion.android (adid: ..split.config.xhdpi , isid: 9vG_vlUrQsiE7H8Fx9dSTg)
2022-01-05 19:13:22.614 13428-13428/? I/Finsky: [2] com.google.android.finsky.download.e.a(45): Duplicate state set for 'io.homeassistant.companion.android' (0). Already in that state
2022-01-05 19:13:22.615 13428-13428/? I/Finsky: [2] com.google.android.finsky.download.n.a(22): Download io.homeassistant.companion.android added to DownloadQueue
2022-01-05 19:13:22.616 13428-13428/? I/Finsky: [2] com.google.android.finsky.download.e.a(47): io.homeassistant.companion.android from 0 to 1.
2022-01-05 19:13:22.619 13428-13428/? I/Finsky: [2] com.google.android.finsky.download.w.a(18): Download io.homeassistant.companion.android starting
2022-01-05 19:13:22.690 13428-13428/? I/Finsky: [2] com.google.android.finsky.download.u.onPostExecute(3): Enqueued io.homeassistant.companion.android as content://downloads/my_downloads/24
2022-01-05 19:13:22.690 13428-13428/? I/Finsky: [2] com.google.android.finsky.download.e.a(47): io.homeassistant.companion.android from 1 to 2.
2022-01-05 19:13:22.691 13428-13428/? I/Finsky: [2] com.google.android.finsky.download.n.g(106): io.homeassistant.companion.android: onStart
2022-01-05 19:13:22.713 13428-13428/? I/Finsky: [2] com.google.android.finsky.download.n.a(82): io.homeassistant.companion.android: onProgress 0/-1 Status: 192 URI: content://downloads/my_downloads/24.
2022-01-05 19:13:24.662 13428-13428/? I/Finsky: [2] com.google.android.finsky.download.e.a(47): io.homeassistant.companion.android from 2 to 3.
2022-01-05 19:13:24.663 13428-13428/? I/Finsky: [2] com.google.android.finsky.download.n.e(98): io.homeassistant.companion.android: onComplete
2022-01-05 19:13:24.663 13428-13428/? I/Finsky: [2] com.google.android.finsky.download.n.i(65): Download io.homeassistant.companion.android removed from DownloadQueue
2022-01-05 19:13:24.670 13428-13428/? I/Finsky: [2] com.google.android.finsky.installer.a.bi.b(342): Prepare to copy io.homeassistant.companion.android (adid: ..split.config.xhdpi , isid: 9vG_vlUrQsiE7H8Fx9dSTg) from content://downloads/my_downloads/24 (expect 72000 bytes, isCompressed: true)
2022-01-05 19:13:24.686 13428-13698/? I/Finsky: [1106] com.google.android.finsky.apkprocessor.h.a(11): Decompressing io.homeassistant.companion.android (..split.config.xhdpi) format 1
2022-01-05 19:13:24.719 13428-13698/? I/Finsky: [1106] com.google.android.finsky.apkprocessor.h.a(22): io.homeassistant.companion.android (..split.config.xhdpi) (72000 bytes) copied successfully in 3 ms
2022-01-05 19:13:24.729 13428-13428/? I/Finsky: [2] com.google.android.finsky.installer.a.bn.a(10): Successfully copied APK to update io.homeassistant.companion.android (adid: ..split.config.xhdpi , isid: 9vG_vlUrQsiE7H8Fx9dSTg)
2022-01-05 19:13:24.737 13428-13428/? I/Finsky: [2] com.google.android.finsky.installer.a.bs.onPostExecute(43): Downloading compressed for io.homeassistant.companion.android (adid: ..split.config.de , isid: 9vG_vlUrQsiE7H8Fx9dSTg)
2022-01-05 19:13:24.737 13428-13428/? I/Finsky: [2] com.google.android.finsky.download.e.a(45): Duplicate state set for 'io.homeassistant.companion.android' (0). Already in that state
2022-01-05 19:13:24.738 13428-13428/? I/Finsky: [2] com.google.android.finsky.download.n.a(22): Download io.homeassistant.companion.android added to DownloadQueue
2022-01-05 19:13:24.739 13428-13428/? I/Finsky: [2] com.google.android.finsky.download.e.a(47): io.homeassistant.companion.android from 0 to 1.
2022-01-05 19:13:24.745 13428-13428/? I/Finsky: [2] com.google.android.finsky.download.w.a(18): Download io.homeassistant.companion.android starting
2022-01-05 19:13:24.764 13428-13428/? I/Finsky: [2] com.google.android.finsky.download.u.onPostExecute(3): Enqueued io.homeassistant.companion.android as content://downloads/my_downloads/25
2022-01-05 19:13:24.764 13428-13428/? I/Finsky: [2] com.google.android.finsky.download.e.a(47): io.homeassistant.companion.android from 1 to 2.
2022-01-05 19:13:24.765 13428-13428/? I/Finsky: [2] com.google.android.finsky.download.n.g(106): io.homeassistant.companion.android: onStart
2022-01-05 19:13:24.790 13428-13428/? I/Finsky: [2] com.google.android.finsky.download.n.a(82): io.homeassistant.companion.android: onProgress 0/-1 Status: 192 URI: content://downloads/my_downloads/25.
2022-01-05 19:13:26.357 13428-13428/? I/Finsky: [2] com.google.android.finsky.download.n.a(82): io.homeassistant.companion.android: onProgress 30572/30572 Status: 200 URI: content://downloads/my_downloads/25.
2022-01-05 19:13:26.374 13428-13428/? I/Finsky: [2] com.google.android.finsky.download.e.a(47): io.homeassistant.companion.android from 2 to 3.
2022-01-05 19:13:26.374 13428-13428/? I/Finsky: [2] com.google.android.finsky.download.n.e(98): io.homeassistant.companion.android: onComplete
2022-01-05 19:13:26.374 13428-13428/? I/Finsky: [2] com.google.android.finsky.download.n.i(65): Download io.homeassistant.companion.android removed from DownloadQueue
2022-01-05 19:13:26.377 13428-13428/? I/Finsky: [2] com.google.android.finsky.installer.a.bi.b(342): Prepare to copy io.homeassistant.companion.android (adid: ..split.config.de , isid: 9vG_vlUrQsiE7H8Fx9dSTg) from content://downloads/my_downloads/25 (expect 98713 bytes, isCompressed: true)
2022-01-05 19:13:26.388 13428-13695/? I/Finsky: [1104] com.google.android.finsky.apkprocessor.h.a(11): Decompressing io.homeassistant.companion.android (..split.config.de) format 1
2022-01-05 19:13:26.425 13428-13695/? I/Finsky: [1104] com.google.android.finsky.apkprocessor.h.a(22): io.homeassistant.companion.android (..split.config.de) (98713 bytes) copied successfully in 4 ms
2022-01-05 19:13:26.439 13428-13428/? I/Finsky: [2] com.google.android.finsky.installer.a.bn.a(10): Successfully copied APK to update io.homeassistant.companion.android (adid: ..split.config.de , isid: 9vG_vlUrQsiE7H8Fx9dSTg)
2022-01-05 19:13:26.457 13428-13428/? I/Finsky: [2] com.google.android.finsky.installer.a.bi.b(278): Begin install of io.homeassistant.companion.android (isid: 9vG_vlUrQsiE7H8Fx9dSTg)
2022-01-05 19:13:28.178 13428-13428/? I/Finsky: [2] com.google.android.finsky.verifier.impl.fh.c(170): Verification complete: id=3, package_name=io.homeassistant.companion.android
2022-01-05 19:13:28.329 926-979/? I/PackageManager.DexOptimizer: Running dexopt (dexoptNeeded=1) on: /data/app/io.homeassistant.companion.android-9G3y8BPkDqKqckifHJ4_Ag==/base.apk pkg=io.homeassistant.companion.android isa=arm dexoptFlags=boot_complete,public,enable_hidden_api_checks targetFilter=verify oatDir=/data/app/io.homeassistant.companion.android-9G3y8BPkDqKqckifHJ4_Ag==/oat classLoaderContext=PCL[/system/framework/com.google.android.wearable.jar]
2022-01-05 19:13:28.330 609-997/? V/installed: DexInv: --- BEGIN '/data/app/io.homeassistant.companion.android-9G3y8BPkDqKqckifHJ4_Ag==/base.apk' ---
2022-01-05 19:13:28.490 13717-13717/? I/dex2oat: /system/bin/dex2oat --input-vdex-fd=-1 --output-vdex-fd=19 --compiler-filter=verify -j2 --classpath-dir=/data/app/io.homeassistant.companion.android-9G3y8BPkDqKqckifHJ4_Ag== --class-loader-context=PCL[/system/framework/com.google.android.wearable.jar] --generate-mini-debug-info --compact-dex-level=none --compilation-reason=install
2022-01-05 19:13:38.851 609-997/? V/installed: DexInv: --- END '/data/app/io.homeassistant.companion.android-9G3y8BPkDqKqckifHJ4_Ag==/base.apk' (success) ---
2022-01-05 19:13:38.896 13428-13594/? I/Finsky: [1086] com.google.android.finsky.dl.f.b(65): Canceling session 1577485406 for io.homeassistant.companion.android
2022-01-05 19:13:38.905 1900-1900/? I/PackageChangeReceiver: onReceive: Intent { act=android.intent.action.PACKAGE_ADDED dat=package:io.homeassistant.companion.android flg=0x4000010 (has extras) }
2022-01-05 19:13:38.992 13428-13428/? I/Finsky: [2] com.google.android.finsky.installer.a.bu.a(5): Successful install of io.homeassistant.companion.android (isid: 9vG_vlUrQsiE7H8Fx9dSTg)
2022-01-05 19:13:39.002 1722-13333/? I/HOME: [DefaultMetadataPreviewProvider]Requesting preview resource for tile ComponentInfo{io.homeassistant.companion.android/io.homeassistant.companion.android.tiles.ShortcutsTile} type 1
2022-01-05 19:13:39.018 10120-10120/? D/NewAvrcpMediaPlayerList: Name of package changed: io.homeassistant.companion.android
2022-01-05 19:13:39.037 1665-1665/? D/HCENfc_RegisteredServicesCache: onReceive() - pkg: io.homeassistant.companion.android
2022-01-05 19:13:39.133 1665-1665/? D/HCENfc_RegisteredServicesCache: invalidateCache() - mLastAddedPackage: io.homeassistant.companion.android
2022-01-05 19:13:39.264 1228-13752/? W/GCM: Unexpected forwarded intent: Intent { act=android.intent.action.PACKAGE_ADDED dat=package:io.homeassistant.companion.android flg=0x4000010 pkg=com.google.android.gms cmp=com.google.android.gms/.chimera.PersistentIntentOperationService (has extras) }
2022-01-05 19:13:39.404 1165-1165/? D/ImsResolver: maybeAddedImsService, packageName: io.homeassistant.companion.android
2022-01-05 19:13:39.483 1228-13751/? W/GCM: Unexpected forwarded intent: Intent { act=android.intent.action.PACKAGE_ADDED dat=package:io.homeassistant.companion.android flg=0x4000010 pkg=com.google.android.gms cmp=com.google.android.gms/.chimera.PersistentIntentOperationService (has extras) }
2022-01-05 19:13:39.545 13428-13428/? I/Finsky: [2] com.google.android.finsky.ax.a.a(23): Selecting account [jEf-i-gsZyXt1GfRv4E05s6-wqg] for package io.homeassistant.companion.android. overriding=[true]
2022-01-05 19:13:39.756 926-1105/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_ADDED dat=package:io.homeassistant.companion.android flg=0x4000010 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
2022-01-05 19:13:39.780 13428-13428/? I/Finsky: [2] com.google.android.finsky.ax.a.a(23): Selecting account [jEf-i-gsZyXt1GfRv4E05s6-wqg] for package io.homeassistant.companion.android. overriding=[true]
2022-01-05 19:13:39.834 13428-13428/? W/Finsky: [2] com.google.android.finsky.notification.h.a(41): Resource for io.homeassistant.companion.android is android.graphics.drawable.AdaptiveIconDrawable of size 144*144
2022-01-05 19:13:42.491 926-1046/? I/ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=io.homeassistant.companion.android cmp=io.homeassistant.companion.android/.splash.SplashActivity} from uid 10035
2022-01-05 19:13:42.718 13428-13428/? I/Finsky: [2] com.google.android.finsky.externalreferrer.u.c(15): Package first launch for io.homeassistant.companion.android
2022-01-05 19:13:42.718 926-961/? I/ActivityManager: Start proc 13782:io.homeassistant.companion.android/u0a75 for activity io.homeassistant.companion.android/.splash.SplashActivity
2022-01-05 19:13:42.757 13428-13428/? I/Finsky: [2] com.google.android.finsky.externalreferrer.f.a(85): Backfilling empty external referrer for io.homeassistant.companion.android
2022-01-05 19:13:43.499 926-4513/? I/ActivityManager: START u0 {cmp=io.homeassistant.companion.android/.home.HomeActivity} from uid 10075
2022-01-05 19:13:44.429 926-4513/? I/ActivityManager: START u0 {cmp=io.homeassistant.companion.android/.onboarding.OnboardingActivity} from uid 10075
2022-01-05 19:13:44.938 926-959/? W/ActivityManager: Activity pause timeout for ActivityRecord{ae4e70f u0 io.homeassistant.companion.android/.home.HomeActivity t114 f}
2022-01-05 19:13:45.016 13782-13797/? I/WM-WorkerWrapper: Work [ id=7ca204c1-4652-41f8-9fc5-b4349b16ab0d, tags={ io.homeassistant.companion.android.sensors.SensorWorker } ] was cancelled
    java.util.concurrent.CancellationException: Task was cancelled.
        at androidx.work.impl.utils.futures.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:1184)
        at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:514)
        at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:475)
        at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:311)
        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
2022-01-05 19:13:45.790 926-973/? I/ActivityManager: Displayed io.homeassistant.companion.android/.onboarding.OnboardingActivity: +839ms (total +1m20s187ms)
2022-01-05 19:13:45.899 549-588/? W/SurfaceFlinger: Attempting to set client state on removed layer: Splash Screen io.homeassistant.companion.android#0
2022-01-05 19:13:45.899 549-588/? W/SurfaceFlinger: Attempting to destroy on removed layer: Splash Screen io.homeassistant.companion.android#0
2022-01-05 19:13:45.975 13782-13782/? I/WM-SystemFgDispatcher: Started foreground service Intent { act=ACTION_START_FOREGROUND cmp=io.homeassistant.companion.android/androidx.work.impl.foreground.SystemForegroundService (has extras) }
2022-01-05 19:13:45.981 13782-13797/? I/WM-WorkerWrapper: Worker result SUCCESS for Work [ id=91ae96e6-b209-4742-9ed8-411e38232783, tags={ io.homeassistant.companion.android.sensors.SensorWorker } ]
2022-01-05 19:13:46.288 1722-13333/? D/DynamicBucketRankerImpl: StreamItemIdAndRevision{notifKey=0|io.homeassistant.companion.android|42|null|10075, packageName=io.homeassistant.companion.android, id=42, revision=5648, originalRevision=5648, updateCount=0} in bucket #0 (ChronologicalBucket)
2022-01-05 19:13:46.297 1722-13641/? D/StreamDatabase: remove. itemId: StreamItemIdAndRevision{notifKey=0|io.homeassistant.companion.android|42|null|10075, packageName=io.homeassistant.companion.android, id=42, revision=5648, originalRevision=5648, updateCount=0}
2022-01-05 19:13:52.851 926-2368/? I/ActivityManager: START u0 {cmp=io.homeassistant.companion.android/androidx.wear.activity.ConfirmationActivity (has extras)} from uid 10075
2022-01-05 19:13:53.061 926-973/? I/ActivityManager: Displayed io.homeassistant.companion.android/androidx.wear.activity.ConfirmationActivity: +176ms
2022-01-05 19:13:53.310 1165-1165/? D/ImsResolver: maybeAddedImsService, packageName: io.homeassistant.companion.android
2022-01-05 19:13:53.316 10120-10120/? D/NewAvrcpMediaPlayerList: Name of package changed: io.homeassistant.companion.android
2022-01-05 19:13:53.317 1665-1665/? D/HCENfc_RegisteredServicesCache: onReceive() - pkg: io.homeassistant.companion.android
2022-01-05 19:13:53.363 1722-13330/? I/HOME: [DefaultMetadataPreviewProvider]Requesting preview resource for tile ComponentInfo{io.homeassistant.companion.android/io.homeassistant.companion.android.tiles.ShortcutsTile} type 1
2022-01-05 19:13:53.897 1228-13851/? I/Fitness: OnPackageChangedOperation got intent: Intent { act=android.intent.action.PACKAGE_CHANGED dat=package:io.homeassistant.companion.android flg=0x45000010 pkg=com.google.android.gms cmp=com.google.android.gms/.chimera.PersistentIntentOperationService (has extras) } [CONTEXT service_id=17 ]
2022-01-05 19:13:53.902 1228-13489/? I/Fitness: Package io.homeassistant.companion.android enabled.  Potentially restarting recording [CONTEXT service_id=17 ]
2022-01-05 19:13:54.090 1228-13489/? I/Fitness: Package io.homeassistant.companion.android enabled.  Potentially restarting recording [CONTEXT service_id=17 ]
2022-01-05 19:14:09.793 926-2368/? I/ActivityManager: START u0 {cmp=io.homeassistant.companion.android/androidx.wear.activity.ConfirmationActivity (has extras)} from uid 10075
2022-01-05 19:14:09.939 926-973/? I/ActivityManager: Displayed io.homeassistant.companion.android/androidx.wear.activity.ConfirmationActivity: +111ms
2022-01-05 19:16:04.337 926-1046/? I/ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=io.homeassistant.companion.android cmp=io.homeassistant.companion.android/.splash.SplashActivity} from uid 10035
2022-01-05 19:16:06.231 926-1856/? I/ActivityManager: START u0 {cmp=io.homeassistant.companion.android/androidx.wear.activity.ConfirmationActivity (has extras)} from uid 10075
2022-01-05 19:16:06.333 926-973/? I/ActivityManager: Displayed io.homeassistant.companion.android/androidx.wear.activity.ConfirmationActivity: +68ms
```

If im retrying to connect to the shown home assistant instance-  only these 2 lines are poping up:

```
2022-01-05 19:16:06.231 926-1856/? I/ActivityManager: START u0 {cmp=io.homeassistant.companion.android/androidx.wear.activity.ConfirmationActivity (has extras)} from uid 10075
2022-01-05 19:16:06.333 926-973/? I/ActivityManager: Displayed io.homeassistant.companion.android/androidx.wear.activity.ConfirmationActivity: +68ms
```

**Screenshot of problem:**
![Watch_Screenshot_220105-152505](https://user-images.githubusercontent.com/59010961/148258168-e44ce21f-cd0a-49a3-a128-f829e21f54af.jpeg)

**Additional information:**

**Comment by dshokouhi** [comment]
Looks like the actual error message is missing from the logs you pulled.



  Have you tried logging in with the Phone App by going to settings > Wear OS?

**Comment by windowslucker1121** [comment]
Yeah i kindly suspected that the actual error is missing, but i couldnt figure out why.

I didnt even know you can login from the App itself - it is hidden in 
Home Assistent App -> Settings -> Mobile App ->Wear OS Settings

This way i could login on my watch - it looks like this is the workaround.
Thanks for your help! If you need more information about the init problem feel free to ask, i will provide as many information as possible.

**Comment by dshokouhi** [comment]
Without the actual error message that gets triggered with this message we cant proceed with a fix. The phone app login was mentioned in the blog post and its also designed for users who are having issues logging in.  Are you able to get the actual traceback?

The message will start with this line: 
https://github.com/home-assistant/android/blob/55e5ae3597ade9af95ada376c120fc3ebecd6171/wear/src/main/java/io/homeassistant/companion/android/onboarding/OnboardingPresenterImpl.kt#L81
