### ISSUE TITLE
Getting a crash while scanning for devices on all of my devices

### ISSUE THREAD

**Issue by kgursu** [home-assistant/android#2141]
**Home Assistant Android version: 2022.1.1 full/minimal**

**Android version: 11**

**Phone model: Xiaomi Pocophone F1**

**Home Assistant version: Not yet installed**

**Last working Home Assistant release (if known): None for me**

**Description of problem: The crash is happening everytime I scan for devices on all installed devices.**

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```
FATAL EXCEPTION: NsdManager
Process: io.homeassistant.companion.android, PID: 10619
java.lang.IllegalArgumentException: listener not registered
	at com.android.internal.util.Preconditions.checkArgument(Preconditions.java:52)
	at android.net.nsd.NsdManager.getListenerKey(NsdManager.java:467)
	at android.net.nsd.NsdManager.stopServiceDiscovery(NsdManager.java:601)
	at io.homeassistant.companion.android.onboarding.discovery.HomeAssistantSearcher.stopSearch(HomeAssistantSearcher.kt:43)
	at io.homeassistant.companion.android.onboarding.discovery.HomeAssistantSearcher.onStartDiscoveryFailed(HomeAssistantSearcher.kt:97)
	at android.net.nsd.NsdManager$ServiceHandler.handleMessage(NsdManager.java:383)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Screenshot of problem: Can't get a screenshot for this, maybe a screen record.**

**Additional information: None yet**

**Comment by dshokouhi** [comment]
Is this device running a custom ROM? I ask because you also mentioned the minimal build

**Comment by kgursu** [comment]
> Is this device running a custom ROM? I ask because you also mentioned the minimal build

This device runs a custom ROM, yes, but for example another one with official ROM gives me the same result.

**Comment by kgursu** [comment]
> There should also be more logging form our application, in particular debug logging....can you grab those too please?

I'm getting Logcat from this new device Samsung Galaxy Tab S7+:

[https://pastebin.com/M7Jr0cKz](Logcat only limited to Home Assistant)

**Comment by dshokouhi** [comment]
Thanks for this, seems discovery is failing to start for some unknown reason.

https://developer.android.com/reference/android/net/nsd/NsdManager#FAILURE_INTERNAL_ERROR

the app should not crash but once a fix is submitted you will probably need to manually enter the URL :)
