### ISSUE TITLE
Template Tile null pointer exception on non-null parameter renderedTemplate

### ISSUE THREAD

**Issue by dshokouhi** [home-assistant/android#2157]
**Home Assistant Android version:**
io.homeassistant.companion.android@beta-1916-8a8772d5

**Android version:**
11

**Phone model:**
SM-G970F

**Home Assistant version:**
Not sure but probably not important here

**Last working Home Assistant release (if known):**
N/A new feature

**Description of problem:**

Looks to be an unhandled exception here according to Sentry so I imagine the app crashes on this device when the user first navigates to the template tile screen in phone settings.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```
java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter renderedTemplate
    at io.homeassistant.companion.android.settings.wear.views.SettingsWearTemplateTileKt.SettingsWearTemplateTile
    at io.homeassistant.companion.android.settings.wear.views.SettingsWearHomeViewKt$LoadSettingsHomeView$1$1$3.invoke(SettingsWearHomeView.kt:35)
    at io.homeassistant.companion.android.settings.wear.views.SettingsWearHomeViewKt$LoadSettingsHomeView$1$1$3.invoke(SettingsWearHomeView.kt:34)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
    at androidx.navigation.compose.NavHostKt$NavHost$4$1.invoke(NavHost.kt:150)
    at androidx.navigation.compose.NavHostKt$NavHost$4$1.invoke(NavHost.kt:149)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
    at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
    at androidx.compose.runtime.saveable.SaveableStateHolderImpl.SaveableStateProvider(SaveableStateHolder.kt:84)
    at androidx.navigation.compose.NavBackStackEntryProviderKt.SaveableStateProvider(NavBackStackEntryProvider.kt:60)
    at androidx.navigation.compose.NavBackStackEntryProviderKt.access$SaveableStateProvider(NavBackStackEntryProvider.kt:1)
    at androidx.navigation.compose.NavBackStackEntryProviderKt$LocalOwnersProvider$1.invoke(NavBackStackEntryProvider.kt:52)
    at androidx.navigation.compose.NavBackStackEntryProviderKt$LocalOwnersProvider$1.invoke(NavBackStackEntryProvider.kt:51)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
    at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
    at androidx.navigation.compose.NavBackStackEntryProviderKt.LocalOwnersProvider(NavBackStackEntryProvider.kt:47)
    at androidx.navigation.compose.NavHostKt$NavHost$4.invoke(NavHost.kt:149)
    at androidx.navigation.compose.NavHostKt$NavHost$4.invoke(NavHost.kt:142)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
    at androidx.compose.animation.CrossfadeKt$Crossfade$4$1.invoke(Crossfade.kt:115)
    at androidx.compose.animation.CrossfadeKt$Crossfade$4$1.invoke(Crossfade.kt:110)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
    at androidx.compose.animation.CrossfadeKt.Crossfade(Crossfade.kt:124)
    at androidx.compose.animation.CrossfadeKt.Crossfade(Crossfade.kt:55)
    at androidx.navigation.compose.NavHostKt.NavHost(NavHost.kt:142)
    at androidx.navigation.compose.NavHostKt$NavHost$5.invoke
    at androidx.navigation.compose.NavHostKt$NavHost$5.invoke
    at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:140)
    at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2158)
    at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2404)
    at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:2585)
    at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:2571)
    at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:247)
    at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations
    at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:2571)
    at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:2547)
    at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:620)
    at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:786)
    at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:105)
    at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:456)
    at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:425)
    at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:34)
    at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
    at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
    at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1008)
    at android.view.Choreographer.doCallbacks(Choreographer.java:809)
    at android.view.Choreographer.doFrame(Choreographer.java:740)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:246)
    at android.app.ActivityThread.main(ActivityThread.java:8633)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Screenshot of problem:**

**Additional information:**
This was taken from sentry and only 1 user as of now but not sure how many other users have started to use the feature. What is odd is that the default should just be a empty string instead of `null` so not sure what happened here. 

CC: @leroyboerefijn

**Comment by dshokouhi** [comment]
Weird I no longer see the exception in sentry, will close this now and we can revisit if a user creates an issue :)  Thank you for checking in to this!!

**Comment by kevinross** [comment]
@dshokouhi adding a data point for this exact traceback, crashed as soon as the final `}` was appended to the text:

    {{ states.laundry_remaining.state }}

I don't have the traceback handy for the crash that happened _when editing_, but it crashes with a very similar traceback when I attempt to edit a second time (ie app exits to home->I open it again->proceed to wear OS settings->attempt to edit template->crash). I can reproduce the initial crash once I'm home (afk right now) although I suspect it'll look more or less identical. In fact, I think I can reproduce on-demand (this isn't the first time, and the first time I followed the exact same sequence of actions as this time).

Full traceback:
```07-25 14:23:35.782 23227 23227 E AndroidRuntime: FATAL EXCEPTION: main
07-25 14:23:35.782 23227 23227 E AndroidRuntime: Process: io.homeassistant.companion.android, PID: 23227
07-25 14:23:35.782 23227 23227 E AndroidRuntime: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter renderedTemplate
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at io.homeassistant.companion.android.settings.wear.views.SettingsWearTemplateTileKt.SettingsWearTemplateTile(Unknown Source:19)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at io.homeassistant.companion.android.settings.wear.views.SettingsWearHomeViewKt$LoadSettingsHomeView$1$1$3.invoke(SettingsWearHomeView.kt:51)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at io.homeassistant.companion.android.settings.wear.views.SettingsWearHomeViewKt$LoadSettingsHomeView$1$1$3.invoke(SettingsWearHomeView.kt:50)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at androidx.navigation.compose.NavHostKt$NavHost$4$1.invoke(NavHost.kt:150)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at androidx.navigation.compose.NavHostKt$NavHost$4$1.invoke(NavHost.kt:149)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at androidx.compose.runtime.saveable.SaveableStateHolderImpl.SaveableStateProvider(SaveableStateHolder.kt:84)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at androidx.navigation.compose.NavBackStackEntryProviderKt.SaveableStateProvider(NavBackStackEntryProvider.kt:60)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at androidx.navigation.compose.NavBackStackEntryProviderKt.access$SaveableStateProvider(NavBackStackEntryProvider.kt:1)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at androidx.navigation.compose.NavBackStackEntryProviderKt$LocalOwnersProvider$1.invoke(NavBackStackEntryProvider.kt:52)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at androidx.navigation.compose.NavBackStackEntryProviderKt$LocalOwnersProvider$1.invoke(NavBackStackEntryProvider.kt:51)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at androidx.navigation.compose.NavBackStackEntryProviderKt.LocalOwnersProvider(NavBackStackEntryProvider.kt:47)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at androidx.navigation.compose.NavHostKt$NavHost$4.invoke(NavHost.kt:149)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at androidx.navigation.compose.NavHostKt$NavHost$4.invoke(NavHost.kt:142)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at androidx.compose.animation.CrossfadeKt$Crossfade$4$1.invoke(Crossfade.kt:115)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at androidx.compose.animation.CrossfadeKt$Crossfade$4$1.invoke(Crossfade.kt:110)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at androidx.compose.animation.CrossfadeKt.Crossfade(Crossfade.kt:124)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at androidx.compose.animation.CrossfadeKt.Crossfade(Crossfade.kt:55)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at androidx.navigation.compose.NavHostKt.NavHost(NavHost.kt:142)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at androidx.navigation.compose.NavHostKt$NavHost$5.invoke(Unknown Source:13)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at androidx.navigation.compose.NavHostKt$NavHost$5.invoke(Unknown Source:8)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:142)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2351)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2611)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3198)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3176)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:252)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:1)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3176)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:3141)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:727)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:876)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:107)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:485)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:454)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:34)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1350)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:1149)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:1040)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1333)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:233)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8010)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
07-25 14:23:35.782 23227 23227 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@1d9e387, androidx.compose.ui.platform.MotionDurationScaleImpl@e8332b4, StandaloneCoroutine{Cancelling}@2879edd, AndroidUiDispatcher@2142a52]```

**Comment by dshokouhi** [comment]
@kevinross  please don't comment on an old closed issue. Please create a new issue with the traceback and make sure to fill out the issue template completely for tracking purposes.
