### ISSUE TITLE
Wear OS app not connecting in any way

### ISSUE THREAD

**Issue by doppiaemme** [home-assistant/android#2199]
**Home Assistant Android version:**
2022.1.1

**Android version:**

**Phone model:**

**Home Assistant version:**
2021.12.10

**Last working Home Assistant release (if known):**

**Description of problem:**
Can't connect, always getting "Cloud not connected" message
Ticwatch Pro 3 Ultra, WearOS app is installed on an iOS device not Android.

Typed the URL manually.
I understand the BT VS WiFi connection.

Other apps work both in BT proxied mode and Wifi direct connection.

I have tried first with BT on, then with BT OFF and Wifi only. nothing changes.
Tried both the external URL and the internal URL to HA, no difference.
The URL work from a browser on the watch and it CAN reach the UI

Am I missing something obvious?

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by doppiaemme** [comment]
Hi, not sure if this is what you are asking exactly....

In this case I had BOTH wifi and BT ON


01-25 23:02:00.037		26461	-	E	io.homeassistant.companion.android	 Unable to initiate login flow	
01-25 23:02:00.037		26461	-	E	io.homeassistant.companion.android	 java.net.ConnectException: Failed to connect to localhost/127.0.0.1:80	
01-25 23:02:00.037		26461	-	E	io.homeassistant.companion.android	 	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297)	
01-25 23:02:00.037		26461	-	E	io.homeassistant.companion.android	 	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)	
01-25 23:02:00.037		26461	-	E	io.homeassistant.companion.android	 	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)	
01-25 23:02:00.037		26461	-	E	io.homeassistant.companion.android	 	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)	
01-25 23:02:00.037		26461	-	E	io.homeassistant.companion.android	 	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)	
01-25 23:02:00.037		26461	-	E	io.homeassistant.companion.android	 	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)	
01-25 23:02:00.037		26461	-	E	io.homeassistant.companion.android	 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)	
01-25 23:02:00.037		26461	-	E	io.homeassistant.companion.android	 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)	
01-25 23:02:00.037		26461	-	E	io.homeassistant.companion.android	 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)	
01-25 23:02:00.037		26461	-	E	io.homeassistant.companion.android	 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)	
01-25 23:02:00.037		26461	-	E	io.homeassistant.companion.android	 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)	
01-25 23:02:00.037		26461	-	E	io.homeassistant.companion.android	 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)	
01-25 23:02:00.037		26461	-	E	io.homeassistant.companion.android	 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)	
01-25 23:02:00.037		26461	-	E	io.homeassistant.companion.android	 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)	
01-25 23:02:00.037		26461	-	E	io.homeassistant.companion.android	 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)	
01-25 23:02:00.037		26461	-	E	io.homeassistant.companion.android	 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)	
01-25 23:02:00.037		26461	-	E	io.homeassistant.companion.android	 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)	
01-25 23:02:00.037		26461	-	E	io.homeassistant.companion.android	 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)	
01-25 23:02:00.037		26461	-	E	io.homeassistant.companion.android	 	at java.lang.Thread.run(Thread.java:764)	
01-25 23:02:00.037		26461	-	E	io.homeassistant.companion.android	 Caused by: java.net.ConnectException: failed to connect to localhost/127.0.0.1 (port 80) from /127.0.0.1 (port 60458) after 10000ms: isConnected failed: ECONNREFUSED (Connection refused)	
01-25 23:02:00.037		26461	-	E	io.homeassistant.companion.android	 	at libcore.io.IoBridge.isConnected(IoBridge.java:278)	
01-25 23:02:00.037		26461	-	E	io.homeassistant.companion.android	 	at libcore.io.IoBridge.connectErrno(IoBridge.java:187)	
01-25 23:02:00.037		26461	-	E	io.homeassistant.companion.android	 	at libcore.io.IoBridge.connect(IoBridge.java:129)	
01-25 23:02:00.037		26461	-	E	io.homeassistant.companion.android	 	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:137)	
01-25 23:02:00.037		26461	-	E	io.homeassistant.companion.android	 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)	
01-25 23:02:00.037		26461	-	E	io.homeassistant.companion.android	 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)	
01-25 23:02:00.037		26461	-	E	io.homeassistant.companion.android	 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)	
01-25 23:02:00.037		26461	-	E	io.homeassistant.companion.android	 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)	
01-25 23:02:00.037		26461	-	E	io.homeassistant.companion.android	 	at java.net.Socket.connect(Socket.java:621)	
01-25 23:02:00.037		26461	-	E	io.homeassistant.companion.android	 	at okhttp3.internal.platform.AndroidPlatform.connectSocket(AndroidPlatform.kt:63)	
01-25 23:02:00.037		26461	-	E	io.homeassistant.companion.android	 	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)	
01-25 23:02:00.037		26461	-	E	io.homeassistant.companion.android	 	... 18 more	
01-25 23:02:00.037		26461	-	E	io.homeassistant.companion.android	 Caused by: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)	
01-25 23:02:00.037		26461	-	E	io.homeassistant.companion.android	 	at libcore.io.IoBridge.isConnected(IoBridge.java:267)	
01-25 23:02:00.037		26461	-	E	io.homeassistant.companion.android	 	... 28 more	
01-25 23:02:00.163		750	868	E	system_server	 App trying to use insecure INPUT_FEATURE_NO_INPUT_CHANNEL flag. Ignoring	
01-25 23:02:03.658	system_server	750	862	E	TaskPersister	 File error accessing recents directory (directory doesn't exist?).

**Comment by dshokouhi** [comment]
can you let us know more about your network setup? Same with HA networking setup like if you use trusted networks etc... We need to get as much information as possible to troubleshoot. The connection refused error is definitely something we want to figure out why and that answer may lie in your network setup.

**Comment by doppiaemme** [comment]
sure...

HA runs on x.x.x.39 (Internal URL)
Wear OS is on x.x.x.150

external URL is https://aaaa.bbbb.dev/  with port forward on the router set to x.x.x.39:8123 (TCP 443 to 8123)
HA runs with an SSL certificate

This URL is opened perfectly fine with a browser on wear OS

do you need something else?

**Comment by doppiaemme** [comment]
If I try the internal URL instead of the external I get a different error (Impossible to connect). I've removed sensitive info.
In this case it seems the internal IP doesn't match the certificate, which makes sense as the certificate refers to the external FQDN

01-25 23:21:42.312		27636	-	E	io.homeassistant.companion.android	 Unable to initiate login flow	
01-25 23:21:42.312		27636	-	E	io.homeassistant.companion.android	 javax.net.ssl.SSLPeerUnverifiedException: Hostname x.x.x.39 not verified:	
01-25 23:21:42.312		27636	-	E	io.homeassistant.companion.android	     certificate: sha256/Ru89Gj+FI8I36or2fxVvgw7f64Bl3JEPndfi+lDzENo=	
01-25 23:21:42.312		27636	-	E	io.homeassistant.companion.android	     DN: CN=*.aaaaaaa	
01-25 23:21:42.312		27636	-	E	io.homeassistant.companion.android	     subjectAltNames: [*.aaaaaa]	
01-25 23:21:42.312		27636	-	E	io.homeassistant.companion.android	 	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:389)	
01-25 23:21:42.312		27636	-	E	io.homeassistant.companion.android	 	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)	
01-25 23:21:42.312		27636	-	E	io.homeassistant.companion.android	 	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)	
01-25 23:21:42.312		27636	-	E	io.homeassistant.companion.android	 	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)	
01-25 23:21:42.312		27636	-	E	io.homeassistant.companion.android	 	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)	
01-25 23:21:42.312		27636	-	E	io.homeassistant.companion.android	 	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)	
01-25 23:21:42.312		27636	-	E	io.homeassistant.companion.android	 	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)	
01-25 23:21:42.312		27636	-	E	io.homeassistant.companion.android	 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)	
01-25 23:21:42.312		27636	-	E	io.homeassistant.companion.android	 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)	
01-25 23:21:42.312		27636	-	E	io.homeassistant.companion.android	 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)	
01-25 23:21:42.312		27636	-	E	io.homeassistant.companion.android	 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)	
01-25 23:21:42.312		27636	-	E	io.homeassistant.companion.android	 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)	
01-25 23:21:42.312		27636	-	E	io.homeassistant.companion.android	 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)	
01-25 23:21:42.312		27636	-	E	io.homeassistant.companion.android	 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)	
01-25 23:21:42.312		27636	-	E	io.homeassistant.companion.android	 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)	
01-25 23:21:42.312		27636	-	E	io.homeassistant.companion.android	 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)	
01-25 23:21:42.312		27636	-	E	io.homeassistant.companion.android	 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)	
01-25 23:21:42.312		27636	-	E	io.homeassistant.companion.android	 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)	
01-25 23:21:42.312		27636	-	E	io.homeassistant.companion.android	 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)	
01-25 23:21:42.312		27636	-	E	io.homeassistant.companion.android	 	at java.lang.Thread.run(Thread.java:764)	
01-25 23:21:42.378		750	3445	E	system_server	 App trying to use insecure INPUT_FEATURE_NO_INPUT_CHANNEL flag. Ignoring	
01-25 23:21:45.454		28140	-	E	com.android.vending	 Not starting debugger since process cannot load the jdwp agent.	
01-25 23:21:45.913	system_server	750	862	E	TaskPersister	 File error accessing recents directory (directory doesn't exist?).

**Comment by dshokouhi** [comment]
Yes `https` will not work on a local IP, the phone app has the same issue. So you are not using a proxy  here? What about things like trusted networks in HA?

**Comment by dshokouhi** [comment]
@Isaksson your issue is unrelated as the error message is completely different. Your issue is taht your SSL certificate is not valid. You need to use a valid certificate and this one has a trust anchor missing. You need to fix your SSL issue in order to continue. Android can be picky so you may need to regenerate or find a new provider.

Some more helpful info here

**Comment by dshokouhi** [comment]
> Would it be possible to maybe add some more error message when trying to connect from the watch?

We could look into it but thats not related to this issue, please feel free to submit a feature request. 

> I had no issues when using the Android app but maybe there is another framework when connecting from the watch that is more picky.

its actually the same library being used but the watch OS version may differ from the phone in how it handles things.

**Comment by dshokouhi** [comment]
Closing as the app cannot resolve the SSL issue.
