### ISSUE TITLE
app crashes while trying to connect, but host is not reeachable

### ISSUE THREAD

**Issue by Micha-Btz** [home-assistant/android#2227]
**Home Assistant Android version:**
2021.12.1-minimal from f-droid store
**Android version:**
11
**Phone model:**
Pixel 5 with LOS 18.1 without gapps
**Home Assistant version:**
supervisor 2022.01.01, core 2021.12.10
**Last working Home Assistant release (if known):**

**Description of problem:**
My network is not reachable directly from the internet. For connection I use a wireguard vpn. So is my phone not connected to the vpn the app crashes with the error shown in the log. I think the app version before doesn't have this behavior, but I'm not sure because other versions changed as well.

In my own network I use a DNS rewrite from my FQDN to a ip to use a let's encrypt certificate.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```
FATAL EXCEPTION: main
Process: io.homeassistant.companion.android.minimal, PID: 4402
java.net.ConnectException: Failed to connect to xxx.dyndns.berlin/xx.xx.121.87:8123
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at io.homeassistant.companion.android.common.data.HomeAssistantApis$configureOkHttpClient$$inlined$-addInterceptor$1.intercept(OkHttpClient.kt:1082)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.net.ConnectException: failed to connect to xxx.dyndns.berlin/xx.xx.121.87:8123 (port 8123) from /10.171.15.83 (port 46584) after 10000ms: isConnected failed: EHOSTUNREACH (No route to host)
	at libcore.io.IoBridge.isConnected(IoBridge.java:287)
	at libcore.io.IoBridge.connectErrno(IoBridge.java:192)
	at libcore.io.IoBridge.connect(IoBridge.java:134)
	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
	at java.net.Socket.connect(Socket.java:621)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
	... 20 more
Caused by: android.system.ErrnoException: isConnected failed: EHOSTUNREACH (No route to host)
	at libcore.io.IoBridge.isConnected(IoBridge.java:274)
	... 30 more

```

I think the app shouldn't crash on a connection error, maybe get a timeout and sleep or so.

TIA Micha

**Comment by dshokouhi** [comment]
Looks like f-droid ss is behind on the actual published version. We don't control the release they have but you should retest this on the latest release first. 2022.1.1 is the latest version.

**Comment by dshokouhi** [comment]
I am unable to reproduce this using the latest changes and shutting down my dev environment....the app remains on the refresh pop-up as expected

![image](https://user-images.githubusercontent.com/1634145/152223223-1c91d786-bdb8-4d5c-a920-60b041fe10a0.png)

```
2022-02-02 11:28:38.132 27365-28208/io.homeassistant.companion.android.minimal.debug E/WebSocketRepository: Websocket: onFailure
    java.net.ConnectException: Failed to connect to /192.168.1.224:8123
```

I am curious if this issue exists for you in the actual latest release.

**Comment by elad-bar** [comment]
Happens for me too,
At the beginning was the continuous pop-up of unable to connect, 
After few days I cleared the data / cache of the app, since then, every time I perform a login the app is crashing

**Comment by dshokouhi** [comment]
> Happens for me too,
> At the beginning was the continuous pop-up of unable to connect, 
> After few days I cleared the data / cache of the app, since then, every time I perform a login the app is crashing 

Can you check the logs and see if the same error shows up?

**Comment by elad-bar** [comment]
No, since I'm not able to login, I have no menu,
BTW, happens on one device out of 6

**Comment by Micha-Btz** [comment]
Sorry, I have not checked if fdroid has the latest release. I swithced to the latest release from github and will test it and report back.

**Comment by dshokouhi** [comment]
> No, since I'm not able to login, I have no menu, BTW, happens on one device out of 6

you will need to look at the logs using android studio or something similar then so we can see the failure

**Comment by elad-bar** [comment]
I switched from HTTPS to HTTP and now it's working,
don't know what it is the issue, but on one device, with HTTPS it's not working, on the other 5 with HTTPS works great

**Comment by dshokouhi** [comment]
> I switched from HTTPS to HTTP and now it's working, don't know what it is the issue, but on one device, with HTTPS it's not working, on the other 5 with HTTPS works great

really depends on the SSL error to see what needs to be done

**Comment by Micha-Btz** [comment]
This version 022.1.1 doesn't crash for me, so closing this.
