### ISSUE TITLE
Integration with "Device Controls" is broken in Android 12

### ISSUE THREAD

**Issue by AuraHerreroRuiz** [home-assistant/android#2230]
**Home Assistant Android version:**
2022.1.1-full
**Android version:**
12
**Phone model:**
Xiaomi Mi9T
**Home Assistant version:**
core-2022.2.0
**Last working Home Assistant release (if known):**

**Description of problem:**
I updated to Android 12, and the power menu smart home controls got moved to a quick settings tile.

However, now it reports "Compatible controls unavailable". This is the case with 2 android 12 phones, same homeassistant instance.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**
I've included what is logged after I attempt to enable the feature.
```
02-03 00:16:48.178 30166 30231 E HaConProService: Error getting list of entities
02-03 00:16:48.178 30166 30231 E HaConProService: java.lang.IllegalArgumentException: Cannot deserialize value of type `java.lang.String` from Array value (token `JsonToken.START_ARRAY`)
02-03 00:16:48.178 30166 30231 E HaConProService:  at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: java.util.ArrayList[37]->io.homeassistant.companion.android.common.data.websocket.impl.entities.DeviceRegistryResponse["sw_version"])
02-03 00:16:48.178 30166 30231 E HaConProService: 	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4393)
02-03 00:16:48.178 30166 30231 E HaConProService: 	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:4334)
02-03 00:16:48.178 30166 30231 E HaConProService: 	at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl.getDeviceRegistry(WebSocketRepositoryImpl.kt:386)
02-03 00:16:48.178 30166 30231 E HaConProService: 	at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl$getDeviceRegistry$1.invokeSuspend(Unknown Source:14)
02-03 00:16:48.178 30166 30231 E HaConProService: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
02-03 00:16:48.178 30166 30231 E HaConProService: 	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
02-03 00:16:48.178 30166 30231 E HaConProService: 	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
02-03 00:16:48.178 30166 30231 E HaConProService: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
02-03 00:16:48.178 30166 30231 E HaConProService: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
02-03 00:16:48.178 30166 30231 E HaConProService: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
02-03 00:16:48.178 30166 30231 E HaConProService: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
02-03 00:16:48.178 30166 30231 E HaConProService: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
02-03 00:16:48.178 30166 30231 E HaConProService: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
02-03 00:16:48.178 30166 30231 E HaConProService: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
02-03 00:16:48.178 30166 30231 E HaConProService: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
02-03 00:16:48.178 30166 30231 E HaConProService: Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.lang.String` from Array value (token `JsonToken.START_ARRAY`)
02-03 00:16:48.178 30166 30231 E HaConProService:  at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: java.util.ArrayList[37]->io.homeassistant.companion.android.common.data.websocket.impl.entities.DeviceRegistryResponse["sw_version"])
02-03 00:16:48.178 30166 30231 E HaConProService: 	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1741)
02-03 00:16:48.178 30166 30231 E HaConProService: 	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1515)
02-03 00:16:48.178 30166 30231 E HaConProService: 	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._deserializeFromArray(StdDeserializer.java:222)
02-03 00:16:48.178 30166 30231 E HaConProService: 	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:46)
02-03 00:16:48.178 30166 30231 E HaConProService: 	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:11)
02-03 00:16:48.178 30166 30231 E HaConProService: 	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542)
02-03 00:16:48.178 30166 30231 E HaConProService: 	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:563)
02-03 00:16:48.178 30166 30231 E HaConProService: 	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:438)
02-03 00:16:48.178 30166 30231 E HaConProService: 	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
02-03 00:16:48.178 30166 30231 E HaConProService: 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:351)
02-03 00:16:48.178 30166 30231 E HaConProService: 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:184)
02-03 00:16:48.178 30166 30231 E HaConProService: 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:355)
02-03 00:16:48.178 30166 30231 E HaConProService: 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
02-03 00:16:48.178 30166 30231 E HaConProService: 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
02-03 00:16:48.178 30166 30231 E HaConProService: 	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4388)
02-03 00:16:48.178 30166 30231 E HaConProService: 	... 14 more
```

**Screenshot of problem:**
https://i.imgur.com/RnNQJwe.jpg
**Additional information:**
Video: https://imgur.com/a/6ebulkI

**Comment by dshokouhi** [comment]
This bug is missing the issue template that gets presented when a new issue is created. We are missing a lot of critical information here. Can you please copy the template from a new issue and fill in the data including the requested logs so we can continue here?

**Comment by AuraHerreroRuiz** [comment]
I apologize. I even searched for the template before posting, I honestly don't know how I missed it. I've now edited the original comment.

**Comment by dshokouhi** [comment]
Thanks for getting the logs and the information filled in, this was actually fixed in a recent beta release. It will be in the production release once we cut a new release but for now its in the beta.

duplicates #2123 #2124
