### ISSUE TITLE
System UI crash when opening/using device controls

### ISSUE THREAD

**Issue by jpelgrom** [home-assistant/android#2251]
**Home Assistant Android version:** 2022.1.1-full, beta-2046-c76248f6

**Android version:** 12, after installing the February 2022 patch (build SQ1A.220205.002)

**Phone model:** Google Pixel 4a

**Home Assistant version:** 2022.2.3 (not relevant)

**Last working Home Assistant release (if known):** it worked with the same versions on the January 2022 patch

**Description of problem:**

When I long press on a device control, the System UI crashes 50% of the time with an exception (see below).
Other apps (Google Home, Cat Controls easter egg) don't cause a crash.
When I've only added 1 control, it doesn't crash when interacting with it.
In testing, if I use `PendingIntent.FLAG_UPDATE_CURRENT` like in the samples instead of `PendingIntent.FLAG_CANCEL_CURRENT` it doesn't crash: https://github.com/home-assistant/android/blob/c76248f6efe8307a073d3b8c1b2e1d74749f7ab6/app/src/main/java/io/homeassistant/companion/android/controls/HaControl.kt#L26

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```
2022-02-08 22:31:20.561 13537-13537/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.android.systemui, PID: 13537
    java.lang.RuntimeException: android.app.PendingIntent$CanceledException
        at com.android.wm.shell.TaskView.startActivity(TaskView.java:152)
        at com.android.systemui.controls.ui.DetailDialog$stateCallback$1.onInitialized(DetailDialog.kt:85)
        at com.android.wm.shell.TaskView.lambda$surfaceCreated$7(TaskView.java:343)
        at com.android.wm.shell.TaskView.$r8$lambda$Qt9euhM2L1QPAFyAHU1Pbi2emQc(Unknown Source:0)
        at com.android.wm.shell.TaskView$$ExternalSyntheticLambda1.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: android.app.PendingIntent$CanceledException
        at android.app.PendingIntent.send(PendingIntent.java:959)
        at com.android.wm.shell.TaskView.startActivity(TaskView.java:148)
        at com.android.systemui.controls.ui.DetailDialog$stateCallback$1.onInitialized(DetailDialog.kt:85) 
        at com.android.wm.shell.TaskView.lambda$surfaceCreated$7(TaskView.java:343) 
        at com.android.wm.shell.TaskView.$r8$lambda$Qt9euhM2L1QPAFyAHU1Pbi2emQc(Unknown Source:0) 
        at com.android.wm.shell.TaskView$$ExternalSyntheticLambda1.run(Unknown Source:2) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7839) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
```

**Screenshot of problem:** Unable to take a screenshot

**Additional information:**

**Comment by dshokouhi** [comment]
I dont remember why I used cancel current instead of update current, if memory serves me right it was not loading properly but that was added over a year ago :)

**Comment by jpelgrom** [comment]
If the app is already open in the background update instead of cancel doesn't immediately show the app for me, only on the second try, perhaps that is why?

**Comment by dshokouhi** [comment]
Yea that could be it, a consistent experience :)

**Comment by jpelgrom** [comment]
I've managed to reproduce this with a [minimal/very simple app](https://github.com/jpelgrom/ControlIntentBug): `PendingIntent.FLAG_UPDATE_CURRENT` for the intent and it works fine, `PendingIntent.FLAG_CANCEL_CURRENT` and it will crash System UI frequently if you have 2+ controls added. Guess it'll have to go to the Google issue tracker, let's hope this is handled by a team that responds quickly...

**Comment by jpelgrom** [comment]
Submitted to the Google issue tracker because I don't see how this is a bug for the HA app: https://issuetracker.google.com/issues/218542096

**Comment by caco3** [comment]
I think I experience the same issue.

- When I tap on the white circle, the action always gets run without an issue.
- When I instead tab on the field itself, it seems to try to open HA but something crashes and I end up on the lock screen.

See attached 2 screenshots, one with success and one with the crash.
I am aware that this most likely is an Android issue but though I share my captures.

https://user-images.githubusercontent.com/1783586/167316916-278cd06f-ffdd-40f0-a5ce-03cd0b707376.mp4

https://user-images.githubusercontent.com/1783586/167316921-178e2a5f-2f99-4b73-90dc-fb0cee97cdc7.mp4

**Comment by jpelgrom** [comment]
@caco3 Thanks for the videos, it looks similar but without logs it's hard to confirm it is crashing for the same reason.

I recently started looking at the issue and believe I've found the solution, would you be able to install a test version to see if it helps for you? Download the file `app-full-debug.apk` from [here](https://github.com/home-assistant/android/actions/runs/2294853655) (you need to be logged in), you can install it alongside the existing app and will need to re-add the controls for the test version of the app. Let me know if it still crashes with that version!

**Comment by caco3** [comment]
Dear @jpelgrom 

Thanks for investigating this further! I installed your debug app and indeed I no longer can cause it to crash!

N.B. Maybe you know this: As is now, one has to be carefully to tap on the white circle to trigger the action. most of the time I miss it and tap on the bigger field which leads to the HA settings. IMO that is not intuitive at all. It should be the other way around.
Looking on [https://www.theverge.com/22638325/android-12-device-control-panel-google-how-to](https://cdn.vox-cdn.com/thumbor/l6LqKpGC1NyK4T75DbHCkxcXPGg=/0x0:1080x2280/920x0/filters:focal(0x0:1080x2280):format(webp):no_upscale()/cdn.vox-cdn.com/uploads/chorus_asset/file/22801019/android_12_device_controls_2.jpg) it seems that it would be possible as expected by me.

**Comment by jpelgrom** [comment]
Good to hear it's working now!

> IMO that is not intuitive at all. It should be the other way around.

I agree, but how the controls are presented is decided by the manufacturer. The app only tells what is available to control and the current status. The example you've linked is Google's implementation and is also what I see on my Pixel 4a, I believe your screen recordings are for a Samsung device who has decided to use a different layout.

**Comment by caco3** [comment]
Thanks for the explanation! Indeed it seems that Samsung is to blame here :(

I found a similar screenshot on a Samsung presentation: https://images.samsung.com/is/image/samsung/assets/uk/support/mobile-devices/delightful-experiences-from-one-ui-3-with-android-11-of-galaxy-s21-series/galaxy-s21-device-control.jpg?$ORIGIN_JPG$
