### ISSUE TITLE
One of my companion apps floods my logs with errors

### ISSUE THREAD

**Issue by Pirol62** [home-assistant/android#2276]
**Home Assistant Android version:**
2022.2
**Android version:**
12
**Phone model:**
Samsung SGS20
**Home Assistant version:**
2021.12.10
**Last working Home Assistant release (if known):**
Last working Android was the previous one
**Description of problem:**
We have 3 devices running the latest version of companion app.
In all apps the new web socket connect is deactivated
My tablet and my SGS10 are running normal
My wifes S20 floods the log with errors, as soon as the app was activated.
Running in background, the app provides all activated sensors as expected.
But as soon as the app is activated regardless of doing something in it, the errors start.

As described above, the new web socket connection is set to never.

All companion apps are connected through Nabu Casa Link.

A restart of HA and the mobile didn't solve the issue

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```
2022-02-13 08:31:53 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [281473099910208] Error handling message: Unknown error
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 100, in async_handle
handler(self.hass, self, schema(msg))
File "/config/custom_components/browser_mod/connection.py", line 44, in handle_update
devices[deviceID].update(msg.get("data", None))
File "/config/custom_components/browser_mod/connection.py", line 94, in update
self.sensor.data = data.get("browser")
File "/config/custom_components/browser_mod/helpers.py", line 106, in data
self.updated()
File "/config/custom_components/browser_mod/sensor.py", line 27, in updated
self.schedule_update_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 643, in schedule_update_ha_state
self.hass.add_job(self.async_update_ha_state(force_refresh)) # type: ignore
AttributeError: 'NoneType' object has no attribute 'add_job'
```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
What troubleshooting steps have you tried? Did you try starting fresh? 

https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app

**Comment by Pirol62** [comment]
ok, had the possibility to follow starting-freh and it solved it.
Thanks
