### ISSUE TITLE
Device controls nullpointerexception for a few domains

### ISSUE THREAD

**Issue by dshokouhi** [home-assistant/android#2337]
**Home Assistant Android version:**
beta-2124-3de19889

**Android version:**
12 and others

**Phone model:**

Redmi Note 9 Pro and others

**Home Assistant version:**
unknown

**Last working Home Assistant release (if known):**
unknown

**Description of problem:**

Looking at sentry we have a few new bugs coming in that all have the same error message, seems like this was introduced in the latest beta (at least according to sentry)

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```
java.lang.NullPointerException: null cannot be cast to non-null type kotlin.Int
    at java.util.Objects.requireNonNull(Objects.java:245)
    at io.homeassistant.companion.android.controls.VacuumControl$Companion.provideControlFeatures(VacuumControl.kt:30)
    at io.homeassistant.companion.android.controls.HaControl$DefaultImpls.createControl(HaControl.kt:43)
    at io.homeassistant.companion.android.controls.VacuumControl$Companion.createControl(VacuumControl.kt:20)
    at io.homeassistant.companion.android.controls.HaControlsProviderService.sendEntitiesToSubscriber(HaControlsProviderService.kt:216)
    at io.homeassistant.companion.android.controls.HaControlsProviderService.access$sendEntitiesToSubscriber(HaControlsProviderService.kt:28)
    at io.homeassistant.companion.android.controls.HaControlsProviderService$createPublisherFor$1$1$request$1.invokeSuspend(HaControlsProviderService.kt:138)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
    at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

```
java.lang.NullPointerException: null cannot be cast to non-null type kotlin.Int
    at java.util.Objects.requireNonNull(Objects.java:245)
    at io.homeassistant.companion.android.controls.CoverControl$Companion.provideControlFeatures(CoverControl.kt:50)
    at io.homeassistant.companion.android.controls.HaControl$DefaultImpls.createControl(HaControl.kt:43)
    at io.homeassistant.companion.android.controls.CoverControl$Companion.createControl(CoverControl.kt:23)
    at io.homeassistant.companion.android.controls.HaControlsProviderService.sendEntitiesToSubscriber(HaControlsProviderService.kt:216)
    at io.homeassistant.companion.android.controls.HaControlsProviderService.access$sendEntitiesToSubscriber(HaControlsProviderService.kt:28)
    at io.homeassistant.companion.android.controls.HaControlsProviderService$createPublisherFor$1$1$request$1.invokeSuspend(HaControlsProviderService.kt:138)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
    at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
    at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

```
java.lang.NullPointerException: null cannot be cast to non-null type kotlin.Int
    at java.util.Objects.requireNonNull(Objects.java:245)
    at io.homeassistant.companion.android.controls.FanControl$Companion.provideControlFeatures(FanControl.kt:31)
    at io.homeassistant.companion.android.controls.HaControl$DefaultImpls.createControl(HaControl.kt:43)
    at io.homeassistant.companion.android.controls.FanControl$Companion.createControl(FanControl.kt:23)
    at io.homeassistant.companion.android.controls.HaControlsProviderService.sendEntitiesToSubscriber(HaControlsProviderService.kt:216)
    at io.homeassistant.companion.android.controls.HaControlsProviderService.access$sendEntitiesToSubscriber(HaControlsProviderService.kt:28)
    at io.homeassistant.companion.android.controls.HaControlsProviderService$createPublisherFor$1$1$request$1.invokeSuspend(HaControlsProviderService.kt:138)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
    at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
    at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```
**Screenshot of problem:**

**Additional information:**
CC: @jpelgrom as I believe this may be related to a recent PR?

**Comment by jpelgrom** [comment]
Based on the traceback it appears that `entity.attributes["supported_features"]` is `null`.

@dshokouhi Did the third exception for `FanControl` also happen on beta 2124, or on a different version? Beta 2126 and newer started using an extension function to get the supported features for a fan with an explicit try/catch (via #2332), so I wouldn't expect it to throw an exception on that >= 2126.

I think the only other recent change to device controls and the entity class that might be relevant are extension functions, but they are resolved statically so it shouldn't create exceptions when accessing `attributes`; the extensions aren't used here and if they had any impact I'd expect the exception to be thrown from `HaControl`  when setting name etc..

**Comment by dshokouhi** [comment]
> Did the third exception for `FanControl` also happen on beta 2124, or on a different version?

all 3 issues were first seen in beta 2124 according to sentry

**Comment by jpelgrom** [comment]
How many users are affected according to Sentry?

After comparing code with the stable version (2022.2.1), I don't think this is related to a recent change but simply an unexpected or invalid response we haven't seen before, which was triggered by a new user and/or a core change. The only changes that seem related are the extension functions which move feature detection for lights/fans, but as mentioned it shouldn't affect all of these domains and otherwise should have thrown the exception earlier.

**Comment by dshokouhi** [comment]
Not too many users but as of now only the beta build from 2124 is reporting it. I don't see reports for any other previous builds and if it was a core change I would expect to see it more than just this build which makes it odd.

![image](https://user-images.githubusercontent.com/1634145/156825557-9ae77864-feb0-4649-8452-610f7d95170a.png)

Honestly I wasn't certain as to the actual cause of the issue but I figured you would have a better idea since it only points to the build.

**Comment by jpelgrom** [comment]
To fix this I would add a null check to the supported features comparisons (for example `(entity.attributes["supported_features"] as? Int)?.and(SUPPORT_SET_POSITION) == SUPPORT_SET_POSITION`), but given that it is affecting more than a few people and the cause is unclear I'm actually interested in whether the amount grows in the next few days, and if other controls and app versions are affected as well.

**Comment by dshokouhi** [comment]
I think thats a good idea to wait and see if other app versions encounter the issue after Saturdays beta push, hopefully we hear from an actual user on whats happening too :)

**Comment by jpelgrom** [comment]
@dshokouhi Any relevant changes now that a new beta's been out for a few days?

**Comment by dshokouhi** [comment]
@jpelgrom doesn't seem like its that wide of an impact

![image](https://user-images.githubusercontent.com/1634145/157764790-1cbb8821-4f8c-4f1b-ab51-932862c47b4f.png)

**Comment by jpelgrom** [comment]
Were there no more crashes in `FanControl`, or did you filter on the latest beta (in which case it is expected that it no longer shows up)?

**Comment by dshokouhi** [comment]
Fan control also saw a small bump.

![image](https://user-images.githubusercontent.com/1634145/157922360-2d45b7a7-8fb3-45a6-8902-ddf5f5722fbf.png)

Also no reports from older builds either, seems to only be new betas.
