### ISSUE TITLE
App doesn't always connect using external address - works fine in browser

### ISSUE THREAD

**Issue by surge919** [home-assistant/android#2369]
**Home Assistant Android version:**
beta-2162-2de85151-full

**Android version:**
12

**Phone model:**
Pixel 5a

**Home Assistant version:**
2022.3.4

**Last working Home Assistant release (if known):**
don't remember

**Description of problem:**
I’m seeing intermittent weirdness.

If I connect locally and turn off wifi , it works and I get this in the log

```
2022-03-13 18:51:29 ERROR (MainThread) [frontend.js.latest.202203011] https://<external_ip>/lovelace/home?external_auth=1:0:0 Uncaught
```

When I’m away for a period of time, I’m unable to connect externally and this is in the log
I can also replicate this by restarting HASS and then trying to connect using the app

```
2022-03-13 19:04:36 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 172.xx.xx.xx (172.xx.xx.xx). (HomeAssistant/Android Pixel 5a beta-2162-2de58151-2162)
```

I searched all folders and can’t find any ip_bans.yaml so it doesn’t seem to actually be banning the IP.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

This is from the app log and seems to be the only mention of not being able to connect to the external URL

```
03-13 19:06:18.704 24736 24736 E WebViewPresenterImpl: Unable to retrieve external auth
03-13 19:06:18.704 24736 24736 E WebViewPresenterImpl: io.homeassistant.companion.android.common.data.authentication.AuthorizationException
03-13 19:06:18.704 24736 24736 E WebViewPresenterImpl: 	at io.homeassistant.companion.android.common.data.authentication.impl.AuthenticationRepositoryImpl.ensureValidSession(AuthenticationRepositoryImpl.kt:231)
03-13 19:06:18.704 24736 24736 E WebViewPresenterImpl: 	at io.homeassistant.companion.android.common.data.authentication.impl.AuthenticationRepositoryImpl.access$ensureValidSession(AuthenticationRepositoryImpl.kt:27)
03-13 19:06:18.704 24736 24736 E WebViewPresenterImpl: 	at io.homeassistant.companion.android.common.data.authentication.impl.AuthenticationRepositoryImpl$ensureValidSession$1.invokeSuspend(Unknown Source:15)
03-13 19:06:18.704 24736 24736 E WebViewPresenterImpl: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
03-13 19:06:18.704 24736 24736 E WebViewPresenterImpl: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
03-13 19:06:18.704 24736 24736 E WebViewPresenterImpl: 	at android.os.Handler.handleCallback(Handler.java:938)
03-13 19:06:18.704 24736 24736 E WebViewPresenterImpl: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-13 19:06:18.704 24736 24736 E WebViewPresenterImpl: 	at android.os.Looper.loopOnce(Looper.java:201)
03-13 19:06:18.704 24736 24736 E WebViewPresenterImpl: 	at android.os.Looper.loop(Looper.java:288)
03-13 19:06:18.704 24736 24736 E WebViewPresenterImpl: 	at android.app.ActivityThread.main(ActivityThread.java:7839)
03-13 19:06:18.704 24736 24736 E WebViewPresenterImpl: 	at java.lang.reflect.Method.invoke(Native Method)
03-13 19:06:18.704 24736 24736 E WebViewPresenterImpl: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
03-13 19:06:18.704 24736 24736 E WebViewPresenterImpl: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
03-13 19:06:18.707 24736 24736 D UrlRepository: localUrl is: true and usesInternalSsid is: false
03-13 19:06:18.707 24736 24736 D UrlRepository: Using external URL
03-13 19:06:18.709 24736 24736 D UrlRepository: localUrl is: true and usesInternalSsid is: false
03-13 19:06:21.094 24736 24791 D OpenGLRenderer: endAllActiveAnimators on 0xb40000766d42b310 (RippleDrawable) with handle 0xb40000757d3e9480

```

**Screenshot of problem:**

**Additional information:**
I'm not using a proxy.   I have pfSense and my HASS instance is NAT'd

**Comment by dshokouhi** [comment]
are there any other app log errors? and or debug messages printed? would be good to see a bigger picture of whats going on

**Comment by surge919** [comment]
Here's are a few more lines referencing the IP address from my phone at the time of failure

```
2022-03-14 16:12:55 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [139935267021344] Received {'type': 'persistent_notification/get', 'id': 59}
2022-03-14 16:12:55 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [139935267021344] Sending {"id":59,"type":"result","success":true,"result":[{"notification_id":"invalid_config","message":"The following integrations and platforms could not be set up:\n\n - automation\n\nPlease check your config and [logs](/config/logs).","status":"unread","title":"Invalid config","created_at":"2022-03-14T20:10:37.718568+00:00"},{"notification_id":"config_entry_reconfigure","message":"At least one of your integrations requires reconfiguration to continue functioning. [Check it out](/config/integrations).","status":"unread","title":"Integration requires reconfiguration","created_at":"2022-03-14T20:10:40.535769+00:00"},{"notification_id":"http-login","message":"Login attempt or request with invalid authentication from 172.58.5.121 (172.58.5.121). See the log for details.","status":"unread","title":"Login attempt failed","created_at":"2022-03-14T20:12:55.546592+00:00"}]}

2022-03-14 16:12:57 DEBUG (MainThread) [homeassistant.components.http.view] Serving /auth/token to 172.58.5.121 (auth: False)
2022-03-14 16:12:57 DEBUG (MainThread) [homeassistant.components.http.view] Serving /api/websocket to 172.58.5.121 (auth: False)
2022-03-14 16:12:57 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [139935089061696] Connected from 172.58.5.121
2022-03-14 16:12:57 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [139935089061696] Sending {"type":"auth_required","ha_version":"2022.3.4"}
2022-03-14 16:12:59 WARNING (MainThread) [homeassistant.components.websocket_api.http.connection] [139935000369424] Disconnected: Did not receive auth message within 10 seconds
```

**Comment by dshokouhi** [comment]
These are HA core logs, I was looking for Companion App Logs which are on the device only.

**Comment by surge919** [comment]
in case it matters, here is my auth section

```
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 10.0.0.0/24
```

here are some more logs from the app

```
03-14 16:22:15.198 27741 29118 D WebSocketRepository: Websocket: onClosing code: 1000, reason: 
03-14 16:22:16.397 27741 27751 W System  : A resource failed to call end. 
03-14 16:22:16.397 27741 27751 W System  : A resource failed to call end. 
03-14 16:24:00.148 27741 27741 D SensorReceiver: Received intent: android.app.action.NEXT_ALARM_CLOCK_CHANGED
03-14 16:24:00.148 27741 27741 D SensorReceiver: Sensor next_alarm corresponding to received event android.app.action.NEXT_ALARM_CLOCK_CHANGED is disabled, skipping sensors update
03-14 16:24:00.198 27741 27768 D UrlRepository: localUrl is: true and usesInternalSsid is: false
03-14 16:24:00.198 27741 27768 D WebSockManager: Starting to listen to Websocket
03-14 16:24:00.203 27741 27777 I WM-Processor: Moving WorkSpec (424e3105-c655-4b92-8076-8e0e5880d145) to the foreground
03-14 16:24:00.211 27741 27741 I WM-SystemFgDispatcher: Started foreground service Intent { act=ACTION_START_FOREGROUND cmp=io.homeassistant.companion.android/androidx.work.impl.foreground.SystemForegroundService (has extras) }
03-14 16:24:00.217 27741 27768 D UrlRepository: localUrl is: true and usesInternalSsid is: false
03-14 16:24:00.217 27741 27768 D UrlRepository: Using external URL
03-14 16:24:00.220 27741 27768 D UrlRepository: localUrl is: true and usesInternalSsid is: false
03-14 16:24:00.220 27741 27768 D UrlRepository: Using external URL
03-14 16:24:00.235 27741 27741 D SensorReceiver: Received intent: android.app.action.NEXT_ALARM_CLOCK_CHANGED
03-14 16:24:00.236 27741 27741 D SensorReceiver: Sensor next_alarm corresponding to received event android.app.action.NEXT_ALARM_CLOCK_CHANGED is disabled, skipping sensors update
03-14 16:24:00.528 27741 27841 W okhttp.OkHttpClient: A connection to https://hassURL:23453/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
03-14 16:24:00.528 27741 27841 W okhttp.OkHttpClient: A connection to https://hassURL:23453/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
03-14 16:24:00.664 27741 29118 D WebSocketRepository: Websocket: onOpen
03-14 16:24:00.664 27741 29118 D WebSocketRepository: Websocket: onMessage (text)
03-14 16:24:00.665 27741 29118 D WebSocketRepository: Message number null received: {"type":"auth_required","ha_version":"2022.3.4"}
03-14 16:24:00.666 27741 27768 D WebSocketRepository: Auth Requested
03-14 16:24:05.633 27741 27784 E WM-WorkerWrapper: Work [ id=424e3105-c655-4b92-8076-8e0e5880d145, tags={ io.homeassistant.companion.android.websocket.WebsocketManager } ] failed because it threw an exception/error
03-14 16:24:05.633 27741 27784 E WM-WorkerWrapper: java.util.concurrent.ExecutionException: io.homeassistant.companion.android.common.data.authentication.AuthorizationException
03-14 16:24:05.633 27741 27784 E WM-WorkerWrapper: 	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:516)
03-14 16:24:05.633 27741 27784 E WM-WorkerWrapper: 	at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:475)
03-14 16:24:05.633 27741 27784 E WM-WorkerWrapper: 	at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:311)
03-14 16:24:05.633 27741 27784 E WM-WorkerWrapper: 	at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
03-14 16:24:05.633 27741 27784 E WM-WorkerWrapper: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
03-14 16:24:05.633 27741 27784 E WM-WorkerWrapper: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
03-14 16:24:05.633 27741 27784 E WM-WorkerWrapper: 	at java.lang.Thread.run(Thread.java:920)
03-14 16:24:05.633 27741 27784 E WM-WorkerWrapper: Caused by: io.homeassistant.companion.android.common.data.authentication.AuthorizationException
03-14 16:24:05.633 27741 27784 E WM-WorkerWrapper: 	at io.homeassistant.companion.android.common.data.authentication.impl.AuthenticationRepositoryImpl.ensureValidSession(AuthenticationRepositoryImpl.kt:231)
03-14 16:24:05.633 27741 27784 E WM-WorkerWrapper: 	at io.homeassistant.companion.android.common.data.authentication.impl.AuthenticationRepositoryImpl.access$ensureValidSession(AuthenticationRepositoryImpl.kt:27)
03-14 16:24:05.633 27741 27784 E WM-WorkerWrapper: 	at io.homeassistant.companion.android.common.data.authentication.impl.AuthenticationRepositoryImpl$ensureValidSession$1.invokeSuspend(Unknown Source:15)
03-14 16:24:05.633 27741 27784 E WM-WorkerWrapper: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
03-14 16:24:05.633 27741 27784 E WM-WorkerWrapper: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
03-14 16:24:05.633 27741 27784 E WM-WorkerWrapper: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
03-14 16:24:05.633 27741 27784 E WM-WorkerWrapper: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
03-14 16:24:05.633 27741 27784 E WM-WorkerWrapper: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
03-14 16:24:05.633 27741 27784 E WM-WorkerWrapper: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
03-14 16:24:05.633 27741 27784 E WM-WorkerWrapper: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
03-14 16:24:05.633 27741 27784 E WM-WorkerWrapper: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
03-14 16:24:05.634 27741 27784 I WM-WorkerWrapper: Worker result FAILURE for Work [ id=424e3105-c655-4b92-8076-8e0e5880d145, tags={ io.homeassistant.companion.android.websocket.WebsocketManager } ]
03-14 16:24:05.643 27741 27741 I WM-SystemFgDispatcher: Stopping foreground service
03-14 16:24:05.700 27741 27741 D LocBroadcastReceiver: Received location update.
03-14 16:24:05.703 27741 27741 D ForegrndServiceLauncher: Check if service HighAccuracyLocationService is running. Service running = false
03-14 16:24:05.703 27741 27741 D LocBroadcastReceiver: Last Location: 
03-14 16:24:05.703 27741 27741 D LocBroadcastReceiver: Coords:(34.0680964, -84.2478193)
03-14 16:24:05.703 27741 27741 D LocBroadcastReceiver: Accuracy: 10.294
03-14 16:24:05.703 27741 27741 D LocBroadcastReceiver: Bearing: 83.62188
03-14 16:24:05.703 27741 27741 D LocBroadcastReceiver: Begin evaluating if location update should be skipped
03-14 16:24:05.704 27741 27741 D LocBroadcastReceiver: Received location that is 703 milliseconds old, 1647289445000 compared to 1647289445703 with source fused
03-14 16:24:05.708 27741 27770 D UrlRepository: localUrl is: true and usesInternalSsid is: false
03-14 16:24:05.823 27741 27741 D LocBroadcastReceiver: Received location update.
03-14 16:24:05.825 27741 27741 D ForegrndServiceLauncher: Check if service HighAccuracyLocationService is running. Service running = false
03-14 16:24:05.825 27741 27741 D LocBroadcastReceiver: Last Location: 
03-14 16:24:05.825 27741 27741 D LocBroadcastReceiver: Coords:(34.0680928, -84.2478963)
03-14 16:24:05.825 27741 27741 D LocBroadcastReceiver: Accuracy: 6.985
03-14 16:24:05.825 27741 27741 D LocBroadcastReceiver: Bearing: 269.25266
03-14 16:24:05.826 27741 27741 D LocBroadcastReceiver: Begin evaluating if location update should be skipped
03-14 16:24:05.826 27741 27741 D LocBroadcastReceiver: Received location that is -174 milliseconds old, 1647289446000 compared to 1647289445826 with source fused
03-14 16:24:05.826 27741 27741 D LocBroadcastReceiver: New location update not possible within 5 seconds, not sending to HA
03-14 16:24:05.964 27741 27770 D LocBroadcastReceiver: Location update sent successfully
03-14 16:24:06.866 27741 27741 D LocBroadcastReceiver: Received location update.
03-14 16:24:06.886 27741 27741 D ForegrndServiceLauncher: Check if service HighAccuracyLocationService is running. Service running = false
```

**Comment by dshokouhi** [comment]
ok so I can see the authorization exception is occurring in a couple different places, follow these steps in order and lets see if that can clear up the issue

https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app

**Comment by surge919** [comment]
I've reset it (clearing data in the app) before but I've never removed the app in the integration.
Once i reset, it works for a bit and then gives trouble.

This time I've reset everything as per the instructions you linked and I'll keep an eye on it.

**Comment by strelniece** [comment]
Have the exact same problem, when still at home I can connect via Nabu Casa, but when away for a while it doesn't work. No problem connect via web and download  Ariela and that works fine.

Followed the above steps "starting clear..." but doesn't seems to help.

**Comment by dshokouhi** [comment]
> Have the exact same problem, when still at home I can connect via Nabu Casa, but when away for a while it doesn't work. No problem connect via web and download Ariela and that works fine.
> 
> Followed the above steps "starting clear..." but doesn't seems to help.

do you see the exact same error as above in your logs?

**Comment by dnestico** [comment]
I seem to be having the same issue too, I restarted my phone and even re input the internal URL. Only the android app is doing this, strange as it was working perfect just hours ago.

**Comment by dshokouhi** [comment]
> I think I have this issue too, as soon as I disable \"Prioritize internal URL\", that fixes the android app.

Unrelated to this issue. You should only enable that setting if you leave location off as it mentions in the setting description.

**Comment by dnestico** [comment]
Oh alright, so I have wifi tracking enabled which I think means it's using location GPS, I've turned the setting off.

I'm also not home right now and when I turned it off the page loaded, nice.

One question I have though is, it would switch from nabu casa URL to my internal URL if I was on local connection right if let's say the wifi went down?

**Comment by dshokouhi** [comment]
> One question I have though is, it would switch from nabu casa URL to my internal URL if I was on local connection right if let's say the wifi went down, even though the setting you just said is turned off now?

Prioritize internal always tries the internal URL first, exactly as it says. Otherwise the internal  URL will be used when the app detected the home wifi SSID which was required to be setup before the user can enter the internal URL.

**Comment by dnestico** [comment]
Ok, thank you.

**Comment by b-neufeld** [comment]
I've had a similar issue in the same timeframe, and had even opened an issue with Nabu Casa to see if it was related to their remote access service. We could not find anything wrong. 

I was able to link some of the behaviour to being connected to my work VPN, both on my work laptop and Android phone. Anecdotally, the behaviour started around the time I started a new job (Feb 14) and created a Work Profile on my Pixel 3. 

I still suspect there is some faulty logic somewhere, as my experience is: 

- No access on laptop on work VPN (fine) 
- OK web access on phone 
- Intermittent application access on phone as I enable/disable the Work profile. Was failing a few hours ago, but is currently working. 

@surge919 any chance it is related to a new or updated VPN or work profile?

**Comment by strelniece** [comment]
> > Have the exact same problem, when still at home I can connect via Nabu Casa, but when away for a while it doesn't work. No problem connect via web and download Ariela and that works fine.
> > Followed the above steps "starting clear..." but doesn't seems to help.
> 
> do you see the exact same error as above in your logs?

Sorry for not replying, been ill so not away from home...

What in the logs is of interest? Just E(rror)?

**Comment by dshokouhi** [comment]
> What in the logs is of interest? Just E(rror)?

I was asking if you saw the same error mentioned earlier in this thread as you said you have the same problem. We just want to confirm the error message is the same.

https://github.com/home-assistant/android/issues/2369#issuecomment-1067385718

**Comment by dshokouhi** [comment]
Closing due to lack of responses
