### ISSUE TITLE
Enabling Second SIM sensor crashes the app on S22 Ultra

### ISSUE THREAD

**Issue by atulalvenkar** [home-assistant/android#2386]
**Home Assistant Android version:**
2022.3.0-full
**Android version:**
Android 12 One UI 4.1
**Phone model:**
Samsung Galaxy S22 Ultra
**Home Assistant version:**
2022.3.5
**Last working Home Assistant release (if known):**

**Description of problem:**
I converted my secondary SIM from a physical SIM to an eSIM couple days back. Today I saw the the second sim sensor was reporting unavailable in HA. I tried to toggle the sensor and the app crashed when turning it back on. I don't remember this happening when I had the physical SIM.

**Comment by dshokouhi** [comment]
Thanks for reporting this issue, looking at sentry I believe this is the error. Seems like we are unable to get the display name which is used for the state of the sensor.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
    at io.homeassistant.companion.android.sensors.PhoneStateSensorManager.updateSimSensor(PhoneStateSensorManager.kt:124)
    at io.homeassistant.companion.android.sensors.PhoneStateSensorManager.requestSensorUpdate(PhoneStateSensorManager.kt:68)
    at io.homeassistant.companion.android.sensors.SensorDetailFragment.onCreatePreferences$lambda-2$lambda-1(SensorDetailFragment.kt:143)
    at io.homeassistant.companion.android.sensors.SensorDetailFragment.$r8$lambda$XMUSI_7loU7HvSZWwY4Z9mlnm0Y
    at io.homeassistant.companion.android.sensors.SensorDetailFragment$$ExternalSyntheticLambda5.onPreferenceChange
    at androidx.preference.Preference.callChangeListener(Preference.java:1118)
    at androidx.preference.TwoStatePreference.onClick(TwoStatePreference.java:67)
    at androidx.preference.Preference.performClick(Preference.java:1182)
    at androidx.preference.Preference.performClick(Preference.java:1166)
    at androidx.preference.SwitchPreference.performClick(SwitchPreference.java:195)
    at androidx.preference.Preference$1.onClick(Preference.java:181)
    at android.view.View.performClick(View.java:7792)
    at android.view.View.performClickInternal(View.java:7769)
    at android.view.View.access$3800(View.java:910)
    at android.view.View$PerformClick.run(View.java:30213)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8646)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

So the `unavailable` state will be correct if the display name has no value which is what the error is saying.
