### ISSUE TITLE
Android Wear App Crashes when trying to connect to Home Assistant instance

### ISSUE THREAD

**Issue by amikofalvy** [home-assistant/android#2465]
**Home Assistant Android version:**
beta-2234-6c64b31f-full

**Android version:**
Android 12

**Phone model:**
Google Pixel 4 XL

**Home Assistant version:**
2022.4.0

**Last working Home Assistant release (if known):**
N/A

**Description of problem:**
Android Wear Home Assistant app cannot connect to home assistant instance: either local home assistant domain (http://homeassistant.local) or nabucasa hosted domain. I can configure the home assistant instance from my phone, but the wear app crashes a few seconds after I select the instance from the instance selection screen. I briefly can see the "Connecting..." loading message before the app fatally crashes. Consistently reproduced after fresh installs on both Android Phone and Wear devices.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```
04-19 00:39:57.913  8600  8600 D UrlRepository: localUrl is: false and usesInternalSsid is: false
04-19 00:39:57.954  8600  8600 D UrlRepository: localUrl is: false and usesInternalSsid is: false
04-19 00:39:57.955  8600  8600 D UrlRepository: Using external URL
--------- beginning of crash
04-19 00:39:59.085  8600  8600 E AndroidRuntime: FATAL EXCEPTION: main
04-19 00:39:59.085  8600  8600 E AndroidRuntime: Process: io.homeassistant.companion.android, PID: 8600
04-19 00:39:59.085  8600  8600 E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method getParameterCount()I in class Ljava/lang/reflect/Method; or its super classes (declaration of 'java.lang.reflect.Method' appears in /system/framework/core-oj.jar)
04-19 00:39:59.085  8600  8600 E AndroidRuntime: 	at com.fasterxml.jackson.databind.introspect.AnnotatedMethodCollector._isIncludableMemberMethod(AnnotatedMethodCollector.java:187)
04-19 00:39:59.085  8600  8600 E AndroidRuntime: 	at com.fasterxml.jackson.databind.introspect.AnnotatedMethodCollector._addMemberMethods(AnnotatedMethodCollector.java:118)
04-19 00:39:59.085  8600  8600 E AndroidRuntime: 	at com.fasterxml.jackson.databind.introspect.AnnotatedMethodCollector.collect(AnnotatedMethodCollector.java:49)
04-19 00:39:59.085  8600  8600 E AndroidRuntime: 	at com.fasterxml.jackson.databind.introspect.AnnotatedMethodCollector.collectMethods(AnnotatedMethodCollector.java:40)
04-19 00:39:59.085  8600  8600 E AndroidRuntime: 	at com.fasterxml.jackson.databind.introspect.AnnotatedClass._methods(AnnotatedClass.java:387)
04-19 00:39:59.085  8600  8600 E AndroidRuntime: 	at com.fasterxml.jackson.databind.introspect.AnnotatedClass.memberMethods(AnnotatedClass.java:327)
04-19 00:39:59.085  8600  8600 E AndroidRuntime: 	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._addMethods(POJOPropertiesCollector.java:680)
04-19 00:39:59.085  8600  8600 E AndroidRuntime: 	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.collectAll(POJOPropertiesCollector.java:422)
04-19 00:39:59.085  8600  8600 E AndroidRuntime: 	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getJsonValueAccessor(POJOPropertiesCollector.java:270)
04-19 00:39:59.085  8600  8600 E AndroidRuntime: 	at com.fasterxml.jackson.databind.introspect.BasicBeanDescription.findJsonValueAccessor(BasicBeanDescription.java:258)
04-19 00:39:59.085  8600  8600 E AndroidRuntime: 	at com.fasterxml.jackson.databind.ser.BasicSerializerFactory.findSerializerByAnnotations(BasicSerializerFactory.java:391)
04-19 00:39:59.085  8600  8600 E AndroidRuntime: 	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory._createSerializer2(BeanSerializerFactory.java:224)
04-19 00:39:59.085  8600  8600 E AndroidRuntime: 	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:173)
04-19 00:39:59.085  8600  8600 E AndroidRuntime: 	at com.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer(SerializerProvider.java:1495)
04-19 00:39:59.085  8600  8600 E AndroidRuntime: 	at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1463)
04-19 00:39:59.085  8600  8600 E AndroidRuntime: 	at com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:585)
04-19 00:39:59.085  8600  8600 E AndroidRuntime: 	at com.fasterxml.jackson.databind.SerializerProvider.findTypedValueSerializer(SerializerProvider.java:867)
04-19 00:39:59.085  8600  8600 E AndroidRuntime: 	at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.forRootType(ObjectWriter.java:1481)
04-19 00:39:59.085  8600  8600 E AndroidRuntime: 	at com.fasterxml.jackson.databind.ObjectWriter.<init>(ObjectWriter.java:115)
04-19 00:39:59.085  8600  8600 E AndroidRuntime: 	at com.fasterxml.jackson.databind.ObjectMapper._newWriter(ObjectMapper.java:785)
04-19 00:39:59.085  8600  8600 E AndroidRuntime: 	at com.fasterxml.jackson.databind.ObjectMapper.writerFor(ObjectMapper.java:3952)
04-19 00:39:59.085  8600  8600 E AndroidRuntime: 	at retrofit2.converter.jackson.JacksonConverterFactory.requestBodyConverter(JacksonConverterFactory.java:71)
04-19 00:39:59.085  8600  8600 E AndroidRuntime: 	at retrofit2.Retrofit.nextRequestBodyConverter(Retrofit.java:315)
04-19 00:39:59.085  8600  8600 E AndroidRuntime: 	at retrofit2.Retrofit.requestBodyConverter(Retrofit.java:293)
04-19 00:39:59.085  8600  8600 E AndroidRuntime: 	at retrofit2.RequestFactory$Builder.parseParameterAnnotation(RequestFactory.java:778)
04-19 00:39:59.085  8600  8600 E AndroidRuntime: 	at retrofit2.RequestFactory$Builder.parseParameter(RequestFactory.java:325)
04-19 00:39:59.085  8600  8600 E AndroidRuntime: 	at retrofit2.RequestFactory$Builder.build(RequestFactory.java:206)
04-19 00:39:59.085  8600  8600 E AndroidRuntime: 	at retrofit2.RequestFactory.parseAnnotations(RequestFactory.java:67)
04-19 00:39:59.085  8600  8600 E AndroidRuntime: 	at retrofit2.ServiceMethod.parseAnnotations(ServiceMethod.java:26)
04-19 00:39:59.085  8600  8600 E AndroidRuntime: 	at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:202)
04-19 00:39:59.085  8600  8600 E AndroidRuntime: 	at retrofit2.Retrofit$1.invoke(Retrofit.java:160)
04-19 00:39:59.085  8600  8600 E AndroidRuntime: 	at java.lang.reflect.Proxy.invoke(Proxy.java:813)
04-19 00:39:59.085  8600  8600 E AndroidRuntime: 	at $Proxy1.initializeLogin(Unknown Source)
04-19 00:39:59.085  8600  8600 E AndroidRuntime: 	at io.homeassistant.companion.android.common.data.authentication.impl.AuthenticationRepositoryImpl.initiateLoginFlow(AuthenticationRepositoryImpl.kt:48)
04-19 00:39:59.085  8600  8600 E AndroidRuntime: 	at io.homeassistant.companion.android.onboarding.OnboardingPresenterImpl$onAdapterItemClick$1.invokeSuspend(OnboardingPresenterImpl.kt:76)
04-19 00:39:59.085  8600  8600 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
04-19 00:39:59.085  8600  8600 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
04-19 00:39:59.085  8600  8600 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
04-19 00:39:59.085  8600  8600 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
04-19 00:39:59.085  8600  8600 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
04-19 00:39:59.086  8600  8600 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6119)
04-19 00:39:59.086  8600  8600 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-19 00:39:59.086  8600  8600 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
04-19 00:39:59.086  8600  8600 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
04-19 00:39:59.489  8600  8600 I Process : Sending signal. PID: 8600 SIG: 9

```

**Screenshot of problem:**
N/A

**Additional information:**
I can investigate a little bit myself, but I'm posting this here in case others have seen the same and can contribute to the solution.

**Comment by dshokouhi** [comment]
what device is this issue happening on? Error suggests malformed JSON may also be helpful to understand your networking setup too.

**Comment by amikofalvy** [comment]
Android Wear Device is a Moto 360 running Android Wear 2.35.0.325323493, Android OS 7.1.1

**Comment by amikofalvy** [comment]
As a follow-up. I just noticed you asked for networking setup as well. I've tried connecting the wear device to the home assistant instance through both http://homeassistant.local:8213 as well as the nabu casa external link. Both return the same error. I'm running Home Assistant OS on the Raspberry Pi. Let me know if there is additional information I can provide to help diagnose.

**Comment by paultbarrett** [comment]
I too have experienced the same issue as the OP. Huawei Watch. Wear 2.35.0.325323493

Phone is realme 7 pro running Android 11.

Companion app beta-2234-6c64b31f-full

**Comment by saniho** [comment]
Same issue on my Galaxy Tab 2 10.0

**Comment by dshokouhi** [comment]
> Same issue on my Galaxy Tab 2 10.0

This issue is specifically related to Wear OS. Please open a new issue for your issue as the sign in process is completely different on a mobile device compared to a wearable. Make sure to fill out the issue template completely as well, the logs will be most helpful.

**Comment by amikofalvy** [comment]
I installed and tested the pre-release package and confirmed that this fixed my issue.
