### ISSUE TITLE
Initial setup crash after entering connection data

### ISSUE THREAD

**Issue by jprates** [home-assistant/android#2519]
Upon fresh install the app detects the server on the network, it asks for login credentials and 2FA, then on the connect/finish no matter if I switch location on or off, as soon as I press “Finish” it tries to connect and fails with “Home Assistant has stopped” error, and an option to restart the app.

I have no logs on the server side, at least with the default log level, not on Core, not on supervisor.
[Android app logs can be found here on CodePile](https://www.codepile.net/pile/NApR39q9).

Please note this phone is without any OS updates for years now, but it was working fine for at least 2 years till some couple of months ago after an update on HASS (don't know if server side or app side) it became unresponsive, and upon uninstall and reinstall I got to the point I am now.

I’m running Android 8.0 build 41.3.A.2.192 on a Sony Xperia XZ and my HASS server info is:

## System Health

version | core-2022.5.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.10.108
arch | x86_64
timezone | Europe/Lisbon

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.6
-- | --
update_channel | stable
supervisor_version | supervisor-2022.05.1
docker_version | 20.10.9
disk_total | 30.8 GB
disk_used | 7.4 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.3.3), SSH & Web Terminal (10.1.3), Samba share (9.6.1), Check Home Assistant configuration (3.10.0), Z-Wave JS (0.1.58), Signal Messenger (0.59.0), Home Assistant Google Drive Backup (0.107.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 2
views | 24
mode | storage

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Comment by dshokouhi** [comment]
Looks like your SSL certificate is not correct. You may need to re-generate it or use a different provider.  This is not an error the app can solve.  Although we shouldn't be crashing you still should not have any SSL handshake errors, those errors are to be resolved by the user actually as the app and HA does not provide the certificate.

```
[05-10 20:42:01.958 31900:31900 E/AndroidRuntime]
FATAL EXCEPTION: main
Process: io.homeassistant.companion.android, PID: 31900
javax.net.ssl.SSLHandshakeException: Handshake failed
	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:423)
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x6fd6929440: Failure in SSL library, usually a protocol error
error:1000042e:SSL routines:OPENSSL_internal:TLSV1_ALERT_PROTOCOL_VERSION (external/boringssl/src/ssl/tls_record.c:504 0x6fec72a900:0x00000001)
	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:351)
	... 20 more

```

**Comment by dshokouhi** [comment]
Android itself can be more picky than the browser, I won't be able to resolve your issues by looking at the certificate if Android does not want to accept it we can't force it. You may need to recreate the certificate or use a new provider.

We normally refer users to this page when it comes to SSL errors as they are out of scope for the app to resolve.

https://developer.android.com/training/articles/security-ssl#CommonProblems

**Comment by jprates** [comment]
OK, thanks, I'll take a look to see if it helps, but please do remember that the app was working fine up to a point in time.

It was one particular app update, don't know unfortunately which version, that broke the app.

**Comment by jprates** [comment]
Hey @dshokouhi , I was just thinking, if the problem was the certificate, wouldn't every single android app fail on every other phone?

Why is this behavior only affecting my phone?
All other phones on my family connect without any problem to my server.

I'm thinking of something more in the likes of the server side on hass refusing some older SSL protocols from my old Android 8 phone... could this be? Could HASS be refusing the protocol used by my phone because it has fallen into some kind of "non-safe" category lately?

Is there an easy way to test this?
I'm really not a java developer, not by far, and I do not grasp the contents of these logs, but I can follow instructions easily if someone gives me directions on how to debug this.

A big thanks to the dev team for this.

**Comment by jprates** [comment]
Hi,

FYI I went down the TLS protocol version path following the reasoning above, and confirmed the problem is my phone is still using TLS 1.2 while trying to connect to my server, while my server is setup to require TLS 1.3.

Customizing my reverse proxy address security to allow TLS 1.2 for the hass internet url alone in particular was sufficient for the app to succeed in setting up the connection and it is working fine now.

Of course I would prefer to have my Android 8 phone using more recent TLS 1.3 but I don't know how to achieve that.
If anyone here knows how to, I would appreciate the info.

Thanks again to @dshokouhi for identifying the issue as an TLS/SSL connection problem, it was fundamental in leading me in the right direction and solving it.

Hope this helps you handling the java error code and giving out a message for the user instead of just letting the app just crash.

**Comment by jpelgrom** [comment]
TLS 1.3 is only natively supported by [Android 10 and newer](https://developer.android.com/reference/javax/net/ssl/SSLSocket#protocols), and the library the app uses to directly communicate with your server (OkHttp) uses the system's implementation by default. This means that right now, the app cannot handle TLS 1.3 only connections on Android <10.

We should probably change that, but let's start with error handling first :)

**Comment by dshokouhi** [comment]
Closing as we now catch the exception so we won't crash
