### ISSUE TITLE
App crashes when certain notification is received

### ISSUE THREAD

**Issue by dshokouhi** [home-assistant/android#2580]
**Home Assistant Android version:**
Beta 2376

**Android version:**
12

**Phone model:**
Pixel 6 pro

**Home Assistant version:**
2022.3.x

**Last working Home Assistant release (if known):**
N/A

**Description of problem:**

Yesterday I noticed that the app had a random crash and when I went to look in the logs it seems like a notification from youtube music caused a crash

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```
java.lang.ClassNotFoundException: com.google.android.libraries.youtube.logging.interaction.InteractionLoggingScreen
    at java.lang.Class.classForName(Class.java)
    at java.lang.Class.forName(Class.java:454)
    at android.os.Parcel.readParcelableCreator(Parcel.java:3390)
    at android.os.Parcel.readParcelable(Parcel.java:3324)
    at android.os.Parcel.readValue(Parcel.java:3226)
    at android.os.Parcel.readArrayMapInternal(Parcel.java:3623)
    at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
    at android.os.BaseBundle.unparcel(BaseBundle.java:236)
    at android.os.BaseBundle.keySet(BaseBundle.java:569)
    at io.homeassistant.companion.android.sensors.NotificationSensorManager.mappedBundle(NotificationSensorManager.kt:288)
    at io.homeassistant.companion.android.sensors.NotificationSensorManager.mappedBundle$default(NotificationSensorManager.kt:287)
    at io.homeassistant.companion.android.sensors.NotificationSensorManager.mappedBundle(NotificationSensorManager.kt:295)
    at io.homeassistant.companion.android.sensors.NotificationSensorManager.mappedBundle$default(NotificationSensorManager.kt:287)
    at io.homeassistant.companion.android.sensors.NotificationSensorManager.onNotificationPosted(NotificationSensorManager.kt:136)
    at android.service.notification.NotificationListenerService.onNotificationPosted(NotificationListenerService.java:445)
    at android.service.notification.NotificationListenerService$MyHandler.handleMessage(NotificationListenerService.java:2306)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7870)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
java.lang.ClassNotFoundException: com.google.android.libraries.youtube.logging.interaction.InteractionLoggingScreen
    at java.lang.Class.classForName(Class.java)
    at java.lang.Class.forName(Class.java:454)
    at android.os.Parcel.readParcelableCreator(Parcel.java:3390)
    at android.os.Parcel.readParcelable(Parcel.java:3324)
    at android.os.Parcel.readValue(Parcel.java:3226)
    at android.os.Parcel.readArrayMapInternal(Parcel.java:3623)
    at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
    at android.os.BaseBundle.unparcel(BaseBundle.java:236)
    at android.os.BaseBundle.keySet(BaseBundle.java:569)
    at io.homeassistant.companion.android.sensors.NotificationSensorManager.mappedBundle(NotificationSensorManager.kt:288)
    at io.homeassistant.companion.android.sensors.NotificationSensorManager.mappedBundle$default(NotificationSensorManager.kt:287)
    at io.homeassistant.companion.android.sensors.NotificationSensorManager.mappedBundle(NotificationSensorManager.kt:295)
    at io.homeassistant.companion.android.sensors.NotificationSensorManager.mappedBundle$default(NotificationSensorManager.kt:287)
    at io.homeassistant.companion.android.sensors.NotificationSensorManager.onNotificationPosted(NotificationSensorManager.kt:136)
    at android.service.notification.NotificationListenerService.onNotificationPosted(NotificationListenerService.java:445)
    at android.service.notification.NotificationListenerService$MyHandler.handleMessage(NotificationListenerService.java:2306)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7870)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.google.android.libraries.youtube.logging.interaction.InteractionLoggingScreen
    at android.os.Parcel.readParcelableCreator(Parcel.java:3416)
    at android.os.Parcel.readParcelable(Parcel.java:3324)
    at android.os.Parcel.readValue(Parcel.java:3226)
    at android.os.Parcel.readArrayMapInternal(Parcel.java:3623)
    at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
    at android.os.BaseBundle.unparcel(BaseBundle.java:236)
    at android.os.BaseBundle.keySet(BaseBundle.java:569)
    at io.homeassistant.companion.android.sensors.NotificationSensorManager.mappedBundle(NotificationSensorManager.kt:288)
    at io.homeassistant.companion.android.sensors.NotificationSensorManager.mappedBundle$default(NotificationSensorManager.kt:287)
    at io.homeassistant.companion.android.sensors.NotificationSensorManager.mappedBundle(NotificationSensorManager.kt:295)
    at io.homeassistant.companion.android.sensors.NotificationSensorManager.mappedBundle$default(NotificationSensorManager.kt:287)
    at io.homeassistant.companion.android.sensors.NotificationSensorManager.onNotificationPosted(NotificationSensorManager.kt:136)
    at android.service.notification.NotificationListenerService.onNotificationPosted(NotificationListenerService.java:445)
    at android.service.notification.NotificationListenerService$MyHandler.handleMessage(NotificationListenerService.java:2306)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7870)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Screenshot of problem:**

**Additional information:**
I only see 2 notifications posted from this app: a new song and background music downloads. Seems something it doesn't like but I am not sure what.  The only missing notification out of the 2 was from a new song being posted.

**Comment by dshokouhi** [comment]
On Sentry I see the following error which looks similar but not identical. However it does point to the same line.

```
java.lang.ClassNotFoundException: com.idm.fotaagent.enabler.ui.notification.manager.NotificationType
    at java.lang.Class.classForName(Class.java)
    at java.lang.Class.forName(Class.java:454)
    at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:682)
    at android.os.Parcel$2.resolveClass(Parcel.java:3516)
    at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1703)
    at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1594)
    at java.io.ObjectInputStream.readEnum(ObjectInputStream.java:1824)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1409)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:427)
    at android.os.Parcel.readSerializable(Parcel.java:3519)
    at android.os.Parcel.readValue(Parcel.java:3289)
    at android.os.Parcel.readArrayMapInternal(Parcel.java:3635)
    at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
    at android.os.BaseBundle.unparcel(BaseBundle.java:236)
    at android.os.BaseBundle.keySet(BaseBundle.java:569)
    at io.homeassistant.companion.android.sensors.NotificationSensorManager.mappedBundle(NotificationSensorManager.kt:288)
    at io.homeassistant.companion.android.sensors.NotificationSensorManager.mappedBundle$default(NotificationSensorManager.kt:287)
    at io.homeassistant.companion.android.sensors.NotificationSensorManager.mappedBundle(NotificationSensorManager.kt:295)
    at io.homeassistant.companion.android.sensors.NotificationSensorManager.mappedBundle$default(NotificationSensorManager.kt:287)
    at io.homeassistant.companion.android.sensors.NotificationSensorManager.onNotificationPosted(NotificationSensorManager.kt:136)
    at android.service.notification.NotificationListenerService.onNotificationPosted(NotificationListenerService.java:444)
    at android.service.notification.NotificationListenerService$MyHandler.handleMessage(NotificationListenerService.java:2337)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8633)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
java.lang.ClassNotFoundException: com.idm.fotaagent.enabler.ui.notification.manager.NotificationType
    at java.lang.Class.classForName(Class.java)
    at java.lang.Class.forName(Class.java:454)
    at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:682)
    at android.os.Parcel$2.resolveClass(Parcel.java:3516)
    at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1703)
    at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1594)
    at java.io.ObjectInputStream.readEnum(ObjectInputStream.java:1824)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1409)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:427)
    at android.os.Parcel.readSerializable(Parcel.java:3519)
    at android.os.Parcel.readValue(Parcel.java:3289)
    at android.os.Parcel.readArrayMapInternal(Parcel.java:3635)
    at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
    at android.os.BaseBundle.unparcel(BaseBundle.java:236)
    at android.os.BaseBundle.keySet(BaseBundle.java:569)
    at io.homeassistant.companion.android.sensors.NotificationSensorManager.mappedBundle(NotificationSensorManager.kt:288)
    at io.homeassistant.companion.android.sensors.NotificationSensorManager.mappedBundle$default(NotificationSensorManager.kt:287)
    at io.homeassistant.companion.android.sensors.NotificationSensorManager.mappedBundle(NotificationSensorManager.kt:295)
    at io.homeassistant.companion.android.sensors.NotificationSensorManager.mappedBundle$default(NotificationSensorManager.kt:287)
    at io.homeassistant.companion.android.sensors.NotificationSensorManager.onNotificationPosted(NotificationSensorManager.kt:136)
    at android.service.notification.NotificationListenerService.onNotificationPosted(NotificationListenerService.java:444)
    at android.service.notification.NotificationListenerService$MyHandler.handleMessage(NotificationListenerService.java:2337)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8633)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
java.lang.RuntimeException: Parcelable encountered ClassNotFoundException reading a Serializable object (name = com.idm.fotaagent.enabler.ui.notification.manager.NotificationType$8)
    at android.os.Parcel.readSerializable(Parcel.java:3525)
    at android.os.Parcel.readValue(Parcel.java:3289)
    at android.os.Parcel.readArrayMapInternal(Parcel.java:3635)
    at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
    at android.os.BaseBundle.unparcel(BaseBundle.java:236)
    at android.os.BaseBundle.keySet(BaseBundle.java:569)
    at io.homeassistant.companion.android.sensors.NotificationSensorManager.mappedBundle(NotificationSensorManager.kt:288)
    at io.homeassistant.companion.android.sensors.NotificationSensorManager.mappedBundle$default(NotificationSensorManager.kt:287)
    at io.homeassistant.companion.android.sensors.NotificationSensorManager.mappedBundle(NotificationSensorManager.kt:295)
    at io.homeassistant.companion.android.sensors.NotificationSensorManager.mappedBundle$default(NotificationSensorManager.kt:287)
    at io.homeassistant.companion.android.sensors.NotificationSensorManager.onNotificationPosted(NotificationSensorManager.kt:136)
    at android.service.notification.NotificationListenerService.onNotificationPosted(NotificationListenerService.java:444)
    at android.service.notification.NotificationListenerService$MyHandler.handleMessage(NotificationListenerService.java:2337)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8633)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
```
