### ISSUE TITLE
Editing service button widget might change/break service call

### ISSUE THREAD

**Issue by jpelgrom** [home-assistant/android#2604]
**Home Assistant Android version:** beta-2330-7b872096 and newer (stable: 2022.6.0-full)

**Android version:** 12, 13 beta 3.1

**Phone model:** emulator, Google Pixel 4a

**Home Assistant version:** 2022.6.5

**Last working Home Assistant release (if known):** beta-2328-b7428d45 (stable: 2022.3.0-full)

**Description of problem:**

When editing a service button widget from the home screen, the information stored for the service call data is sometimes incorrectly changed which can result in unusable service calls / unexpected changes. Interestingly enough, this does not happen when editing the widget from the app's settings.

Steps to reproduce:

1. Add a service button widget to the home screen with the service `light.toggle` and an entity ID as a target. (the widget now works)
2. Tap and hold on the widget to edit it, either using the pencil icon or by dragging it to the settings option at the top of the launcher.
3. Tap 'Update widget' without making any changes. (the widget no longer works as expected, the service call includes extra data)

The changes are the easiest to spot in the logs:

<details>
<summary>Initial widget saving/creation.</summary>

```
io.homeassistant.companion.android.debug D/ButtonWidget: Saving service call config data:
    domain: light
    service: toggle
    service_data: {"entity_id":["light.stoel"]}
    label: 
```
</details>

<details>
<summary>Updating the widget from the app settings or on beta-2328 and earlier.</summary>

```
io.homeassistant.companion.android.debug D/ButtonWidget: Saving service call config data:
    domain: light
    service: toggle
    service_data: {"entity_id":"light.stoel"}
    label: 
```
</details>

<details>
<summary>Updating the widget from the home screen on beta-2330 and later. The entity ID is now also in "profile" which it shouldn't be. Repeat this step to see the entity ID spread to even more fields!</summary>

```
io.homeassistant.companion.android.debug D/ButtonWidget: Saving service call config data:
    domain: light
    service: toggle
    service_data: {"profile":["light.stoel"],"entity_id":"light.stoel"}
    label: 
```
</details>

<details>
<summary>When opening the widget edit screen from the home screen I see the following error in logcat which doesn't appear when editing the widget from the app's settings, maybe it is relevant?</summary>

```
2022-06-11 21:18:40.497 16942-16942/io.homeassistant.companion.android.debug D/WidgetField: Unable to get service field list
    java.lang.ClassCastException: java.util.Collections$SingletonList cannot be cast to java.lang.String
        at io.homeassistant.companion.android.widgets.common.WidgetDynamicFieldAdapter.onBindViewHolder(WidgetDynamicFieldAdapter.kt:131)
        at io.homeassistant.companion.android.widgets.common.WidgetDynamicFieldAdapter.onBindViewHolder(WidgetDynamicFieldAdapter.kt:16)
        at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7254)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7337)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6194)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6460)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6300)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6296)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2330)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1631)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
        at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3686)
        at android.view.View.measure(View.java:26381)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:26381)
        at androidx.core.widget.NestedScrollView.measureChildWithMargins(NestedScrollView.java:1656)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at androidx.core.widget.NestedScrollView.onMeasure(NestedScrollView.java:601)
        at android.view.View.measure(View.java:26381)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:145)
        at android.view.View.measure(View.java:26381)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:26381)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:26381)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:26381)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:758)
        at android.view.View.measure(View.java:26381)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3819)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2562)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2830)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2278)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8933)
2022-06-11 21:18:40.497 16942-16942/io.homeassistant.companion.android.debug D/WidgetField:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1230)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1238)
        at android.view.Choreographer.doCallbacks(Choreographer.java:898)
        at android.view.Choreographer.doFrame(Choreographer.java:831)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1213)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7892)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```
</details>

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):** see above

**Screenshot of problem:** n/a

**Additional information:** I don't really see any relevant changes in this commit but I can reliably reproduce it happening when switching to it

**Comment by soccerarenadev** [comment]
I'm having a similar or the same issue.

I have several issues:
- When changing a "Service Call", when changing the "Service" input, it doesn't autocomplete.
- If I edit for instance the brightness, several inputs are duplicated in different and wrong inputs, getting an unusable widget.
- If I delete the widget from the UI pressing the "Widget Settings", it doesn't disappear from the launcher.

**Comment by jpelgrom** [comment]
> If I delete the widget from the UI pressing the "Widget Settings", it doesn't disappear from the launcher

This is correct, you can only actually remove the widget from the launcher by dragging and removing it in the launcher. The 'Delete widget' button in configuration exists only for removing widgets from the app's manage widgets list for widgets that are still in the database, but no longer displayed in the launcher.
