### ISSUE TITLE
Restarts always on connecting/disconnecting a keyboard

### ISSUE THREAD

**Issue by changwoo** [home-assistant/android#2622]
**Home Assistant Android version:**
2022.6.0-full
**Android version:**
12
**Phone model:**
Galaxy S10
**Home Assistant version:**
Coer 2022.6.6
Supervisor 2022.05.3
OS 8.2

**Last working Home Assistant release (if known):**

**Description of problem:**
When I connect or disconnect a BT keyboard to my phone with the companion app on the screen, the companion app always restarts.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
Can you share a recording of the app restarting I would expect it to stop instead of restarting? Also can you please get the logs too?

**Comment by changwoo** [comment]
Here's the log:

[homeassistant_companion_log_5-20-2022_12-50-32.txt](https://github.com/home-assistant/android/files/8937414/homeassistant_companion_log_5-20-2022_12-50-32.txt)

I'm not sure which are the log lines related to the restart..  I did conect a keyboard on about 12:50:00 and disconnect it on about 12:50:10.


There is not much thing to record..  it just starts again with this screen when I connect the keyboard:

![Screenshot_20220620-130740_Home Assistant](https://user-images.githubusercontent.com/47143/174523672-2e076276-3490-4832-b454-690cb11408b9.jpg)

**Comment by dshokouhi** [comment]
Hmm interesting this looks to be some generic failure that causes the webview activity to restart, almost seems like a device specific issue.

Only stack trace I see that appears to be relevant is
```
06-20 12:50:06.697 24578 24662 D ConnectivityManager: StackLog: [android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:3925)] [android.net.ConnectivityManager.registerDefaultNetworkCallbackForUid(ConnectivityManager.java:4489)] [android.net.ConnectivityManager.registerDefaultNetworkCallback(ConnectivityManager.java:4456)] [android.net.ConnectivityManager.registerDefaultNetworkCallback(ConnectivityManager.java:4430)] [androidx.work.impl.constraints.trackers.NetworkStateTracker.startTracking(NetworkStateTracker.java:89)] [androidx.work.impl.constraints.trackers.ConstraintTracker.addListener(ConstraintTracker.java:71)] [androidx.work.impl.constraints.controllers.ConstraintController.replace(ConstraintController.java:99)] [androidx.work.impl.constraints.WorkConstraintsTracker.replace(WorkConstraintsTracker.java:106)] [androidx.work.impl.background.greedy.GreedyScheduler.schedule(GreedyScheduler.java:157)] [androidx.work.impl.Schedulers.schedule(Schedulers.java:119)] [androidx.work.impl.utils.EnqueueRunnable.scheduleWorkInBackground(EnqueueRunnable.java:135)] [androidx.work.impl.utils.EnqueueRunnable.run(EnqueueRunnable.java:95)] [androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)] [java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)] [java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)] [java.lang.Thread.run(Thread.java:920)]
```

We can see that our worker skips the intent update properly as the sensor is turned off, so this appears to be a device issue. Do you have any other webview based apps on your device you can try to test with to see if it occurs there?

**Comment by jpelgrom** [comment]
I don't think this is a device specific issue, when plugging in a USB dongle with a keyboard the activity also restarts for me on a Google Pixel 4a. It is a [documented configuration change](https://developer.android.com/guide/topics/resources/runtime-changes?hl=en#:~:text=as%20screen%20orientation%2C-,keyboard%20availability,-%2C%20and%20when%20the), and by default this will cause the activity to restart. The 'issue' is just more apparent with Home Assistant because the frontend is reloaded. 

This config change is only overruled in onboarding (`keyboardHidden` in manifest).

Relevant log:
```
2022-06-20 15:40:28.704 1204-3777/? I/android.hardware.usb.aidl-service: port0
2022-06-20 15:40:28.706 1204-3777/? I/android.hardware.usb.aidl-service: 0:port0 connected:0 canChangeMode:1 canChagedata:0 canChangePower:0 usbDataEnabled:1
2022-06-20 15:40:28.706 1204-3777/? I/android.hardware.usb.aidl-service: ContaminantDetectionStatus:2 ContaminantProtectionStatus:0
2022-06-20 15:40:28.706 1204-3777/? I/android.hardware.usb.aidl-service: powerTransferLimited:0
(...)
2022-06-20 15:40:29.169 1949-2555/? D/EventHub: No input device configuration file found for device 'Logitech USB Receiver'.
2022-06-20 15:40:29.175 1949-2555/? I/EventHub: usingClockIoctl=true
2022-06-20 15:40:29.175 1949-2555/? I/EventHub: New device: id=33, fd=554, path='/dev/input/event6', name='Logitech USB Receiver', classes=KEYBOARD | ALPHAKEY | EXTERNAL, configuration='', keyLayout='/system/usr/keylayout/Generic.kl', keyCharacterMap='/system/usr/keychars/Generic.kcm', builtinKeyboard=false, 
2022-06-20 15:40:29.175 1949-2555/? I/InputReader: Device added: id=33, eventHubId=33, name='Logitech USB Receiver', descriptor='6dc166bb9105a09b4af455800f7b9eafa8e88f88',sources=0x00000101
(...)
2022-06-20 15:40:29.177 1949-2554/? I/ActivityTaskManager: Config changes=30 {1.0 204mcc16mnc [en_US,nl_NL] ldltr sw411dp w411dp h815dp 420dpi nrml long hdr widecg port finger qwerty/v/v -nav/h winConfig={ mBounds=Rect(0, 0 - 1080, 2340) mAppBounds=Rect(0, 136 - 1080, 2277) mMaxBounds=Rect(0, 0 - 1080, 2340) mDisplayRotation=ROTATION_0 mWindowingMode=fullscreen mDisplayWindowingMode=fullscreen mActivityType=undefined mAlwaysOnTop=undefined mRotation=ROTATION_0} as.2 s.6734 fontWeightAdjustment=0}
(...)
2022-06-20 15:40:29.207 1949-2555/? D/EventHub: No input device configuration file found for device 'Logitech USB Receiver'.
2022-06-20 15:40:29.211 1949-2555/? W/EventHub: Unable to disable kernel key repeat for /dev/input/event7: Function not implemented
2022-06-20 15:40:29.211 1949-2555/? I/EventHub: usingClockIoctl=true
2022-06-20 15:40:29.211 1949-2555/? I/EventHub: New device: id=34, fd=577, path='/dev/input/event7', name='Logitech USB Receiver', classes=KEYBOARD | CURSOR | DPAD | JOYSTICK | EXTERNAL, configuration='', keyLayout='/system/usr/keylayout/Generic.kl', keyCharacterMap='/system/usr/keychars/Generic.kcm', builtinKeyboard=false, 
(...)
2022-06-20 15:40:29.212 1949-2554/? I/WindowManager: Override config changes=30 {1.0 204mcc16mnc [en_US,nl_NL] ldltr sw411dp w411dp h815dp 420dpi nrml long hdr widecg port finger qwerty/v/v -nav/h winConfig={ mBounds=Rect(0, 0 - 1080, 2340) mAppBounds=Rect(0, 136 - 1080, 2277) mMaxBounds=Rect(0, 0 - 1080, 2340) mDisplayRotation=ROTATION_0 mWindowingMode=fullscreen mDisplayWindowingMode=fullscreen mActivityType=undefined mAlwaysOnTop=undefined mRotation=ROTATION_0} as.2 s.6734 fontWeightAdjustment=0} for displayId=0
(...)
2022-06-20 15:40:29.224 1949-2555/? I/InputReader: Device added: id=34, eventHubId=34, name='Logitech USB Receiver', descriptor='ba865588b7fa5b43a560ab5d830fab516a90bbb0',sources=0x01002313
(...)
2022-06-20 15:40:29.288 7442-26942/io.homeassistant.companion.android.debug V/FA: Activity paused, time: 307212278
2022-06-20 15:40:29.290 7442-26941/io.homeassistant.companion.android.debug V/FA: onActivityCreated
(...)
2022-06-20 15:40:29.330 7442-7442/io.homeassistant.companion.android.debug I/System.out: recordForce value 6
2022-06-20 15:40:29.331 7442-7442/io.homeassistant.companion.android.debug D/WebviewActivity: Current webview package com.google.android.webview and version 102.0.5005.125
2022-06-20 15:40:29.335 7442-26942/io.homeassistant.companion.android.debug V/FA: Activity resumed, time: 307212363
```

When plugging in the dongle I also see multiple `android.intent.action.BATTERY_CHANGED` broadcasts in the logs and WorkManager starting and a few hundred ms later cancelling the SensorWorker job, perhaps this is also causing the stack trace you're seeing @dshokouhi ?

```
2022-06-20 15:40:29.451 7442-7483/io.homeassistant.companion.android.debug I/WM-WorkerWrapper: Work [ id=f0d4f857-17e6-4365-a618-c30de0a36ca6, tags={ io.homeassistant.companion.android.sensors.SensorWorker } ] was cancelled
    java.util.concurrent.CancellationException: Task was cancelled.
        at androidx.work.impl.utils.futures.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:1184)
        at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:514)
        at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:475)
        at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:311)
        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
        at java.lang.Thread.run(Thread.java:1012)
```

**Comment by changwoo** [comment]
I ran the app from source with changing the "configChanges" value in `AndroidManifest.xml`. And I have found the value which worked.

```diff
diff --git a/app/src/main/AndroidManifest.xml b/app/src/main/AndroidManifest.xml
index 376d74d8..b40d8dca 100644
--- a/app/src/main/AndroidManifest.xml
+++ b/app/src/main/AndroidManifest.xml
@@ -315,7 +315,7 @@
             android:supportsPictureInPicture="true"
             android:resizeableActivity="true"
             android:exported="false"
-            android:configChanges="orientation|screenSize|smallestScreenSize|screenLayout" />
+            android:configChanges="orientation|screenSize|smallestScreenSize|screenLayout|keyboard|keyboardHidden|navigation" />
 
         <activity
             android:name=".settings.SettingsActivity"

```

I needed all three of `keyboard|keyboardHidden|navigation`. [The documentation](https://developer.android.com/reference/android/R.attr#configChanges) says the `navigation` config "Should never normally happen", but it actually happened with keyboard connection.

**Comment by dshokouhi** [comment]
> perhaps this is also causing the stack trace you're seeing @dshokouhi ?

I believe the cancellation is caused by the restarted activity because we can see the webview package log statement again shortly after the log I mentioned which is just before the cancellation.



> I needed all three of `keyboard|keyboardHidden|navigation`. [The documentation](https://developer.android.com/reference/android/R.attr#configChanges) says the `navigation` config "Should never normally happen", but it actually happened with keyboard connection.

Awesome thank you for testing that! Please feel free to submit the PR so we can get that corrected :)
