### ISSUE TITLE
Android app repeatedly crashes

### ISSUE THREAD

**Issue by goaliedude3919** [home-assistant/android#2647]
I get a pop up on my Pixel 6 saying that the HA app has crashed, but when I open the app, it's fine. I have the following crash log from the app.

```
2022-06-28 16:12:43.716: java.lang.IllegalArgumentException: width and height must be > 0
	at android.graphics.Bitmap.createBitmap(Bitmap.java:1095)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:1062)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:1012)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:973)
	at androidx.core.graphics.drawable.DrawableKt.toBitmap(Drawable.kt:68)
	at androidx.core.graphics.drawable.DrawableKt.toBitmap$default(Drawable.kt:46)
	at io.homeassistant.companion.android.widgets.button.ButtonWidget.getWidgetRemoteViews(ButtonWidget.kt:193)
	at io.homeassistant.companion.android.widgets.button.ButtonWidget.access$getWidgetRemoteViews(ButtonWidget.kt:41)
	at io.homeassistant.companion.android.widgets.button.ButtonWidget$updateAllWidgets$1.invokeSuspend(ButtonWidget.kt:93)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@f6079f6, Dispatchers.Main]
```

**Comment by dshokouhi** [comment]
Looks like the issue template was missing here, the user who experienced this issue is on `beta-2432-4a59a20d-full`

**Comment by jpelgrom** [comment]
This is probably caused by the changes in #2625

**Comment by jpelgrom** [comment]
More info from a continued discussion [on Discord](https://discord.com/channels/330944238910963714/562408603345092636/991443515647217705):

 - manage widgets shows 10 widgets; 4 button widgets and 6 entity state widgets
 - only the entity state widgets are actually used

Possible reason for crash: if the widget isn't actually on the home screen, there is no associated size? [AppWidgetManager.getAppWidgetOptions](https://developer.android.com/reference/kotlin/android/appwidget/AppWidgetManager?hl=en#getappwidgetoptions) will always return a Bundle according to the documentation (note the `!`), so the null check from the linked PR won't be used and the default for `getInt` is `0`...
