### ISSUE TITLE
Deep sleep request by phone due to frequent crashes

### ISSUE THREAD

**Issue by lancer1991** [home-assistant/android#2669]
**Home Assistant Android version:**
2022.6.0-full
**Android version:**
12
**Phone model:**
Samsung Galaxy S22 Ultra
**Home Assistant version:**
2022.7.2
**Last working Home Assistant release (if known):**
Unkown
**Description of problem:**
phones battery optimization system telling me to place Home Assistant app into deep sleep due to frequent crashes
**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**
![MQLSfvF](https://user-images.githubusercontent.com/74466678/178298564-d15e6a77-df52-4a21-8a8d-216bc2adeddb.jpeg)

**Additional information:**

**Comment by dshokouhi** [comment]
HI this does not seem to contain the information in the Recent Crash tab which is needed as was mentioned in the forums.

Reference: https://community.home-assistant.io/t/deep-sleep-alert/438084

If there is no Recent Crash then we need to get the crash data from Logcat Reader or a similar app.

**Comment by dshokouhi** [comment]
ok without that actual crash it will be impossible for us to tell what happened

**Comment by lancer199135** [comment]
Not sure is this is helpful. It was a WM-WorkerWrapper error. If this isn't right then I'm not sure how to get more info from the Logcat Reader.

```
Work [ id=03291447-254e-497e-b575-bd539ec07afa, tags={ io.homeassistant.companion.android.sensors.SensorWorker } ] failed because it threw an exception/error
java.util.concurrent.ExecutionException: android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service io.homeassistant.companion.android/androidx.work.impl.foreground.SystemForegroundService
	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:516)
	at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:475)
	at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:311)
	at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
Caused by: android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service io.homeassistant.companion.android/androidx.work.impl.foreground.SystemForegroundService
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
	at android.os.Parcel.readParcelable(Parcel.java:3345)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2432)
	at android.os.Parcel.createException(Parcel.java:2421)
	at android.os.Parcel.readException(Parcel.java:2404)
	at android.os.Parcel.readException(Parcel.java:2346)
	at android.app.IActivityManager$Stub$Proxy.startService(IActivityManager.java:6968)
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1927)
	at android.app.ContextImpl.startForegroundService(ContextImpl.java:1893)
	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:798)
	at androidx.core.content.ContextCompat$Api26Impl.startForegroundService(ContextCompat.java:931)
	at androidx.core.content.ContextCompat.startForegroundService(ContextCompat.java:703)
	at androidx.work.impl.Processor.startForeground(Processor.java:161)
	at androidx.work.impl.utils.WorkForegroundUpdater$1.run(WorkForegroundUpdater.java:100)
	... 4 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActiveServices.startServiceLocked(ActiveServices.java:771)
	at com.android.server.am.ActiveServices.startServiceLocked(ActiveServices.java:679)
	at com.android.server.am.ActivityManagerService.startService(ActivityManagerService.java:14102)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2960)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3036)
```

**Comment by dshokouhi** [comment]
This is an error that gets shown when the app has not been granted background access, in Companion App settings there is a tile for background access, make sure it says the app has proper permission.  There may be more power settings you need to adjust as well if you continue to experience the issue.

**Comment by lancer199135** [comment]
StaticWidget
Unable to fetch entity
io.homeassistant.companion.android.common.data.authentication.AuthorizationException
	at io.homeassistant.companion.android.common.data.authentication.impl.AuthenticationRepositoryImpl.ensureValidSession(AuthenticationRepositoryImpl.kt:231)
	at io.homeassistant.companion.android.common.data.authentication.impl.AuthenticationRepositoryImpl.access$ensureValidSession(AuthenticationRepositoryImpl.kt:27)
	at io.homeassistant.companion.android.common.data.authentication.impl.AuthenticationRepositoryImpl$ensureValidSession$1.invokeSuspend(Unknown Source:15)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

StaticWidget
Unable to fetch entity
io.homeassistant.companion.android.common.data.authentication.AuthorizationException
	at io.homeassistant.companion.android.common.data.authentication.impl.AuthenticationRepositoryImpl.ensureValidSession(AuthenticationRepositoryImpl.kt:231)
	at io.homeassistant.companion.android.common.data.authentication.impl.AuthenticationRepositoryImpl.access$ensureValidSession(AuthenticationRepositoryImpl.kt:27)
	at io.homeassistant.companion.android.common.data.authentication.impl.AuthenticationRepositoryImpl$ensureValidSession$1.invokeSuspend(Unknown Source:15)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

AndroidRuntime
FATAL EXCEPTION: main
Process: io.homeassistant.companion.android, PID: 32676
io.homeassistant.companion.android.common.data.authentication.AuthorizationException
	at io.homeassistant.companion.android.common.data.authentication.impl.AuthenticationRepositoryImpl.ensureValidSession(AuthenticationRepositoryImpl.kt:231)
	at io.homeassistant.companion.android.common.data.authentication.impl.AuthenticationRepositoryImpl.access$ensureValidSession(AuthenticationRepositoryImpl.kt:27)
	at io.homeassistant.companion.android.common.data.authentication.impl.AuthenticationRepositoryImpl$ensureValidSession$1.invokeSuspend(Unknown Source:15)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@5a3fdc6, Dispatchers.Main]

ActivityManager
crash : io.homeassistant.companion.android,10552

ActivityManager
Process io.homeassistant.companion.android has crashed too many times, killing! Reason: crashed quickly

**Comment by dshokouhi** [comment]
Interesting and the app does not ask you to reauthenticate when you open right? 

Unfortunately there is not much to go by here in terms of the cause of this exception, I assume there are no other logs above or below this log statement?

I wonder if we need to add some more debug logs in here: https://github.com/home-assistant/android/blob/050d449ef29b2cdf96918191ec49b13c7cd204b0/common/src/main/java/io/homeassistant/companion/android/common/data/authentication/impl/AuthenticationRepositoryImpl.kt#L216-L231

Although I have a feeling this won't be easy to reproduce, I also imagine that if we start fresh here the error would go away but we won't know the cause of it. Tough decision on how to proceed here.

Lets see if any other developers have an idea on whats going on here.

**Comment by lancer199135** [comment]
From the companion app log, no that was the entire log. As to Logcat Reader I didn't look to see if there were any more errors before.

The only odd thing this morning I noticed was I was getting a no connect from the app and trying external it internal didn't resolve.

**Comment by jpelgrom** [comment]
Is this issue still happening with the latest version of the app? If so, could you provide an up to date fatal exception log as a lot has changed?

**Comment by lancer199135** [comment]
> Is this issue still happening with the latest version of the app? If so, could you provide an up to date fatal exception log as a lot has changed?

No, haven't had issues lately.
