### ISSUE TITLE
KeyChainException: Failed to obtain information about key

### ISSUE THREAD

**Issue by dshokouhi** [home-assistant/android#2707]
**Home Assistant Android version:**
beta-2500-f8d0d461

**Android version:**

10

**Phone model:**

HUAWEI CLT-L29

**Home Assistant version:**

unknown

**Last working Home Assistant release (if known):**

N/A

**Description of problem:**

Found the following crash on sentry, not sure if its an actual issue but filing it anyways

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```
android.security.KeyStoreException: Key not found
    at android.security.KeyStore.getKeyStoreException(KeyStore.java:1296)
    at android.security.keystore.AndroidKeyStoreProvider.getKeyCharacteristics(AndroidKeyStoreProvider.java:244)
    at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStoreKeyPairFromKeystore(AndroidKeyStoreProvider.java:308)
    at android.security.KeyChain.getKeyPair(KeyChain.java:594)
    at android.security.KeyChain.getPrivateKey(KeyChain.java:561)
    at io.homeassistant.companion.android.common.data.keychain.KeyChainRepositoryImpl.doLoad(KeyChainRepositoryImpl.kt:57)
    at io.homeassistant.companion.android.common.data.keychain.KeyChainRepositoryImpl.access$doLoad(KeyChainRepositoryImpl.kt:12)
    at io.homeassistant.companion.android.common.data.keychain.KeyChainRepositoryImpl$load$3.invokeSuspend(KeyChainRepositoryImpl.kt:35)
    at io.homeassistant.companion.android.common.data.keychain.KeyChainRepositoryImpl$load$3.invoke
    at io.homeassistant.companion.android.common.data.keychain.KeyChainRepositoryImpl$load$3.invoke
    at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
    at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:169)
    at kotlinx.coroutines.BuildersKt.withContext
    at io.homeassistant.companion.android.common.data.keychain.KeyChainRepositoryImpl.load(KeyChainRepositoryImpl.kt:30)
    at io.homeassistant.companion.android.HomeAssistantApplication$onCreate$3.invokeSuspend(HomeAssistantApplication.kt:65)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
    at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
java.security.UnrecoverableKeyException: Failed to obtain information about key
    at android.security.keystore.AndroidKeyStoreProvider.getKeyCharacteristics(AndroidKeyStoreProvider.java:242)
    at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStoreKeyPairFromKeystore(AndroidKeyStoreProvider.java:308)
    at android.security.KeyChain.getKeyPair(KeyChain.java:594)
    at android.security.KeyChain.getPrivateKey(KeyChain.java:561)
    at io.homeassistant.companion.android.common.data.keychain.KeyChainRepositoryImpl.doLoad(KeyChainRepositoryImpl.kt:57)
    at io.homeassistant.companion.android.common.data.keychain.KeyChainRepositoryImpl.access$doLoad(KeyChainRepositoryImpl.kt:12)
    at io.homeassistant.companion.android.common.data.keychain.KeyChainRepositoryImpl$load$3.invokeSuspend(KeyChainRepositoryImpl.kt:35)
    at io.homeassistant.companion.android.common.data.keychain.KeyChainRepositoryImpl$load$3.invoke
    at io.homeassistant.companion.android.common.data.keychain.KeyChainRepositoryImpl$load$3.invoke
    at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
    at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:169)
    at kotlinx.coroutines.BuildersKt.withContext
    at io.homeassistant.companion.android.common.data.keychain.KeyChainRepositoryImpl.load(KeyChainRepositoryImpl.kt:30)
    at io.homeassistant.companion.android.HomeAssistantApplication$onCreate$3.invokeSuspend(HomeAssistantApplication.kt:65)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
    at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
android.security.KeyChainException: java.security.UnrecoverableKeyException: Failed to obtain information about key
    at android.security.KeyChain.getKeyPair(KeyChain.java:597)
    at android.security.KeyChain.getPrivateKey(KeyChain.java:561)
    at io.homeassistant.companion.android.common.data.keychain.KeyChainRepositoryImpl.doLoad(KeyChainRepositoryImpl.kt:57)
    at io.homeassistant.companion.android.common.data.keychain.KeyChainRepositoryImpl.access$doLoad(KeyChainRepositoryImpl.kt:12)
    at io.homeassistant.companion.android.common.data.keychain.KeyChainRepositoryImpl$load$3.invokeSuspend(KeyChainRepositoryImpl.kt:35)
    at io.homeassistant.companion.android.common.data.keychain.KeyChainRepositoryImpl$load$3.invoke
    at io.homeassistant.companion.android.common.data.keychain.KeyChainRepositoryImpl$load$3.invoke
    at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
    at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:169)
    at kotlinx.coroutines.BuildersKt.withContext
    at io.homeassistant.companion.android.common.data.keychain.KeyChainRepositoryImpl.load(KeyChainRepositoryImpl.kt:30)
    at io.homeassistant.companion.android.HomeAssistantApplication$onCreate$3.invokeSuspend(HomeAssistantApplication.kt:65)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
    at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Screenshot of problem:**

**Additional information:**

We can close this if we feel no user will hit the issue but I think maybe at a minimum we should add a try/catch to avoid a crash? Not sure how to proceed so figured I'd start with an issue.

**Comment by jpelgrom** [comment]
Looking at the code, this happened during launch. Maybe the user previously selected a certificate that is no longer available / restored app settings to another device?

> at a minimum we should add a try/catch to avoid a crash

Probably, the app should continue and prompt the user to select a certificate like on a fresh install in my opinion.

**Comment by jpelgrom** [comment]
This does not appear to be related to deleting the key as I suggested, that will show the following warning in the logs on my device and continue to the prompt as expected.

```
2022-08-06 17:23:23.568 11680-17520/? W/KeyChain: uid 10451 doesn't have permission to access the requested alias 15b637440e319e67ebf5dfc055e7ded9d9e48fab
```
