### ISSUE TITLE
Unable to Download Automation Trace 

### ISSUE THREAD

**Issue by Danny2100** [home-assistant/android#2711]
**Home Assistant Android version:**
2022.6.0-full
**Android version:**
Android 12
**Phone model:**
Galaxy s22 Ultra
**Home Assistant version:**
2022.7.6
**Last working Home Assistant release (if known):**
N/A
**Description of problem:**
Unable to Download Automation Trace in the app. It works on Chrome browser on the same device.
```
2022-07-25 06:02:37.732: java.lang.IllegalArgumentException: Can only download HTTP/HTTPS URIs: data:application/json;charset=utf-8,%7B%0A%20%20%22trace%22:%20%7B%0A%20%20%20%20%22last_step%22:%20%22condition/0%22,%0A%20%20%20%20%22run_id%22:%20%2269381b96dafab10d2efb1074c7af493a%22,%0A%20%20%20%20%22state%22:%20%22stopped%22,%0A%20%20%20%20%22script_execution%22:%20%22failed_conditions%22,%0A%20%20%20%20%22timestamp%22:%20%7B%0A%20%20%20%20%20%20%22start%22:%20%222022-07-25T10:00:41.555023+00:00%22,%0A%20%20%20%20%20%20%22finish%22:%20%222022-07-25T10:00:41.557087+00:00%22%0A%20%20%20%20%7D,%0A%20%20%20%20%22domain%22:%20%22automation%22,%0A%20%20%20%20%22item_id%22:%20%221658702493599%22,%0A%20%20%20%20%22trigger%22:%20%22state%20of%20binary_sensor.daniels_bathroom_presence_detector%22,%0A%20%20%20%20%22trace%22:%20%7B%0A%20%20%20%20%20%20%22trigger/0%22:%20%5B%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%22path%22:%20%22trigger/0%22,%0A%20%20%20%20%20%20%20%20%20%20%22timestamp%22:%20%222022-07-25T10:00:41.556830+00:00%22,%0A%20%20%20%20%20%20%20%20%20%20%22changed_variables%22:%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%22this%22:%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22entity_id%22:%20%22automation.daniels_bathroom_prescence_detection_beta%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22state%22:%20%22on%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22attributes%22:%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22last_triggered%22:%20%222022-07-25T09:50:01.871829+00:00%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22mode%22:%20%22single%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22current%22:%200,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22id%22:%20%221658702493599%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22friendly_name%22:%20%22Daniels%20Bathroom%20Prescence%20Detection%20Beta%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22last_changed%22:%20%222022-07-25T09:50:01.614957+00:00%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22last_updated%22:%20%222022-07-25T09:50:02.543770+00:00%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22context%22:%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22id%22:%20%2201G8TC6Y4D2YV3YE3FRWX7XK1K%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22parent_id%22:%20%2201G8TC6VP881AV8Q41P7B6MEV6%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22user_id%22:%20null%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D,%0A%20%20%20%20%20%20%20%20%20%20%20%20%22trigger%22:%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22id%22:%20%220%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22idx%22:%20%220%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22platform%22:%20%22state%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22entity_id%22:%20%22binary_sensor.daniels_bathroom_presence_detector%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22from_state%22:%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22entity_id%22:%20%22binary_sensor.daniels_bathroom_presence_detector%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22state%22:%20%22on%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22attributes%22:%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22device_class%22:%20%22occupancy%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22friendly_name%22:%20%22Daniels%20Bathroom%20Presence%20Detector%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22last_changed%22:%20%222022-07-25T10:00:39.292307+00:00%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22last_updated%22:%20%222022-07-25T10:00:39.292307+00:00%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22context%22:%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22id%22:%20%2201G8TCTCKWJVMW5B7S63F9EBVY%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22parent_id%22:%20null,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22user_id%22:%20%2225afe1fbb7b74963bc4bd4b154e27b4a%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22to_state%22:%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22entity_id%22:%20%22binary_sensor.daniels_bathroom_presence_detector%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22state%22:%20%22off%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22attributes%22:%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22device_class%22:%20%22occupancy%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22friendly_name%22:%20%22Daniels%20Bathroom%20Presence%20Detector%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22last_changed%22:%20%222022-07-25T10:00:41.551255+00:00%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22last_updated%22:%20%222022-07-25T10:00:41.551255+00:00%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22context%22:%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22id%22:%20%2201G8TCTETF46EW3GP4KDG268PV%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22parent_id%22:%20null,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22user_id%22:%20%2225afe1fbb7b74963bc4bd4b154e27b4a%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22for%22:%20null,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22attribute%22:%20null,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22description%22:%20%22state%20of%20binary_sensor.daniels_bathroom_presence_detector%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D,%0A%20%20%20%20%20%20%20%20%20%20%20%20%22condition%22:%20false,%0A%20%20%20%20%20%20%20%20%20%20%20%20%22lights_script%22:%20%22script.morning_daniels_bathroom_lights%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%22service%22:%20%22script.off_daniels_bathroom_lights%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%22lights_status%22:%20%22on%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%22switch_status%22:%20%22off%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%22set_lights%22:%20%22off%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%22set_switch%22:%20%22on%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%22input_boolean%22:%20%22input_boolean.daniels_bathroom_fan_automation_running%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%22switch%22:%20%22switch.daniels_bathroom_fan_switch%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%22target_entity%22:%20%22%5C%22input_boolean.daniels_bathroom_fan_automation_running%5C%22%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%22target_data%22:%20%22%5C%22%7B%7D%5C%22%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%22target_condition%22:%20%7B%7D%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%5D,%0A%20%20%20%20%20%20%22condition/0%22:%20%5B%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%22path%22:%20%22condition/0%22,%0A%20%20%20%20%20%20%20%20%20%20%22timestamp%22:%20%222022-07-25T10:00:41.556898+00:00%22,%0A%20%20%20%20%20%20%20%20%20%20%22result%22:%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%22result%22:%20false,%0A%20%20%20%20%20%20%20%20%20%20%20%20%22entities%22:%20%5B%5D%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%5D%0A%20%20%20%20%7D,%0A%20%20%20%20%22config%22:%20%7B%0A%20%20%20%20%20%20%22id%22:%20%221658702493599%22,%0A%20%20%20%20%20%20%22alias%22:%20%22Daniels%20Bathroom%20Prescence%20Detection%20Beta%22,%0A%20%20%20%20%20%20%22description%22:%20%22%22,%0A%20%20%20%20%20%20%22trigger%22:%20%5B%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%22platform%22:%20%22state%22,%0A%20%20%20%20%20%20%20%20%20%20%22entity_id%22:%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20%22binary_sensor.daniels_bathroom_presence_detector%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%22binary_sensor.daniels_bathroom_motion_sensor_1_home_security_motion_detection%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%22binary_sensor.daniels_bathroom_door_sensor%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%22sensor.daniels_bathroom_fan_off%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%22sensor.daniels_bathroom_fan_on%22%0A%20%20%20%20%20%20%20%20%20%20%5D%0A%20%20%20%20%20%20%20%20%7D,%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%22platform%22:%20%22event%22,%0A%20%20%20%20%20%20%20%20%20%20%22event_type%22:%20%22zha_event%22,%0A%20%20%20%20%20%20%20%20%20%20%22event_data%22:%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%22unique_id%22:%20%2254:ef:44:10:00:4d:32:27%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%22command%22:%20%22Away%22%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D,%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%22platform%22:%20%22event%22,%0A%20%20%20%20%20%20%20%20%20%20%22event_type%22:%20%22automation_reloaded%22%0A%20%20%20%20%20%20%20%20%7D,%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%22platform%22:%20%22homeassistant%22,%0A%20%20%20%20%20%20%20%20%20%20%22event%22:%20%22start%22%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%5D,%0A%20%20%20%20%20%20%22condition%22:%20%5B%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%22condition%22:%20%22template%22,%0A%20%20%20%20%20%20%20%20%20%20%22value_template%22:%20%22%7B%7B%20condition%20%7D%7D%22%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%5D,%0A%20%20%20%20%20%20%22action%22:%20%5B%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%22service%22:%20%22%7B%7B%20service%20%7D%7D%22,%0A%20%20%20%20%20%20%20%20%20%20%22data%22:%20%7B%7D,%0A%20%20%20%20%20%20%20%20%20%20%22target%22:%20%22%7B%7B%20target_condition%20%7D%7D%22%0A%20%20%20%20%20%20%20%20%7D,%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%22condition%22:%20%22template%22,%0A%20%20%20%20%20%20%20%20%20%20%22value_template%22:%20%22%7B%7B%20trigger.entity_id%20==%20'sensor.daniels_bathroom_fan_off'%20and%20trigger.to_state.state%20==%20'True'%20%7D%7D%22%0A%20%20%20%20%20%20%20%20%7D,%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%22service%22:%20%22input_boolean.turn_off%22,%0A%20%20%20%20%20%20%20%20%20%20%22data%22:%20%7B%7D,%0A%20%20%20%20%20%20%20%20%20%20%22target%22:%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%22entity_id%22:%20%22input_boolean.daniels_bathroom_fan_automation_running%22%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%5D,%0A%20%20%20%20%20%20%22variables%22:%20%7B%0A%20%20%20%20%20%20%20%20%22condition%22:%20%22%7B%25%20set%20lights%20=%20trigger.entity_id%20in%20%5B'binary_sensor.daniels_bathroom_presence_detector','binary_sensor.daniels_bathroom_motion_sensor_1_home_security_motion_detection'%5D%20and%20lights_status%20!=%20set_lights%20%25%7D%20%7B%25%20set%20switch%20=%20trigger.platform%20==%20'event'%20and%20trigger.event.data.command%20==%20'Away'%20and%20switch_status%20!=%20set_switch%20%25%7D%20%7B%25%20set%20event_lights%20=%20trigger.platform%20==%20'event'%20and%20trigger.event.event_type%20==%20'automation_reloaded'%20or%20trigger.event%20==%20'start'%20and%20states('binary_sensor.daniels_bathroom_presence_detector')%20==%20'off'%20and%20lights_status%20==%20'on'%20%25%7D%20%7B%25%20set%20event_switch%20=%20trigger.platform%20==%20'event'%20and%20trigger.event.event_type%20==%20'automation_reloaded'%20or%20trigger.event%20==%20'start'%20and%20states('sensor.daniels_bathroom_fan_off')%20==%20'True'%20%25%7D%20%7B%7B%20lights%20or%20switch%20or%20event_lights%20or%20event_switch%20%7D%7D%22,%0A%20%20%20%20%20%20%20%20%22lights_script%22:%20%22%7B%25%20if%20(now()%20%3E=%20today_at('05:50')%20and%20now()%20%3C=%20today_at('18:30'))%20%25%7D%20script.morning_daniels_bathroom_lights%20%7B%25%20elif%20(now()%20%3E=%20today_at('18:30')%20or%20now()%20%3C=%20today_at('05:50'))%20%25%7D%20script.night_daniels_bathroom_lights%20%7B%25%20endif%20%25%7D%22,%0A%20%20%20%20%20%20%20%20%22service%22:%20%22%7B%25%20if%20trigger.entity_id%20==%20'binary_sensor.daniels_bathroom_presence_detector'%20and%20%20trigger.to_state.state%20==%20'off'%20%25%7D%20script.off_daniels_bathroom_lights%20%7B%25%20elif%20trigger.entity_id%20==%20'binary_sensor.daniels_bathroom_motion_sensor_1_home_security_motion_detection'%20and%20trigger.to_state.state%20==%20'off'%20and%20states('binary_sensor.daniels_bathroom_presence_detector')%20==%20'off'%20and%20states('light.daniels_bathroom_lights')%20==%20'on'%20%25%7D%20script.off_daniels_bathroom_lights%20%7B%25%20elif%20trigger.platform%20==%20'event'%20and%20trigger.event.event_type%20==%20'automation_reloaded'%20or%20trigger.event%20==%20'start'%20and%20states('binary_sensor.daniels_bathroom_presence_detector')%20==%20'off'%20%25%7D%20script.off_daniels_bathroom_lights%20%7B%25%20elif%20trigger.entity_id%20==%20'binary_sensor.daniels_bathroom_motion_sensor_1_home_security_motion_detection'%20and%20trigger.to_state.state%20==%20'on'%20%25%7D%20%7B%7B%20lights_script%20%7D%7D%20%7B%25%20elif%20trigger.entity_id%20==%20'binary_sensor.daniels_bathroom_door_sensor'%20and%20trigger.to_state.state%20==%20'on'%20or%20trigger.entity_id%20==%20'sensor.daniels_bathroom_fan_off'%20and%20trigger.to_state.state%20==%20'True'%20%25%7D%20switch.turn_off%20%7B%25%20elif%20trigger.plaform%20==%20'event'%20and%20trigger.event.data.command%20==%20'Away'%20and%20states('binary_sensor.daniels_bathroom_door_sensor')%20==%20'off'%20%25%7D%20switch.turn_on%20%7B%25%20elif%20trigger.entity_id%20==%20'sensor.daniels_bathroom_fan_on'%20and%20trigger.to_state.state%20==%20'True'%20and%20lights_status%20==%20'on'%20%25%7D%20input_boolean.turn_on%20%7B%25%20endif%20%25%7D%22,%0A%20%20%20%20%20%20%20%20%22lights_status%22:%20%22%7B%7B%20states('light.daniels_bathroom_lights')%20%7D%7D%22,%0A%20%20%20%20%20%20%20%20%22switch_status%22:%20%22%7B%7B%20states('switch.daniels_bathroom_fan_switch')%20%7D%7D%22,%0A%20%20%20%20%20%20%20%20%22set_lights%22:%20%22%7B%7B%20iif(service%20!=%20'script.off_daniels_bathroom_lights','on','off')%20%7D%7D%22,%0A%20%20%20%20%20%20%20%20%22set_switch%22:%20%22%7B%7B%20iif(service%20!=%20'switch.turn_off','on','off')%20%7D%7D%22,%0A%20%20%20%20%20%20%20%20%22input_boolean%22:%20%22input_boolean.daniels_bathroom_fan_automation_running%22,%0A%20%20%20%20%20%20%20%20%22switch%22:%20%22switch.daniels_bathroom_fan_switch%22,%0A%20%20%20%20%20%20%20%20%22target_entity%22:%20%22%5C%22%7B%7B%20iif(%20service%20in%20%5B'switch.turn_off','switch.turn_on'%5D,switch,input_boolean)%20%7D%7D%5C%22%22,%0A%20%20%20%20%20%20%20%20%22target_data%22:%20%22%5C%22%7B%7B%20iif(target_entity%20in%20%5B'switch.daniels_bathroom_fan_switch','input_boolean.daniels_bathroom_fan_automation_running'%5D,target_entity,'%7B%7D')%20%7D%7D%5C%22%22,%0A%20%20%20%20%20%20%20%20%22target_condition%22:%20%22%7B%7B%20%7Bentity_id:%20target_entity%20%7D%20if%20target_entity%20in%20%20%5B'switch.daniels_bathroom_fan_switch','input_boolean.daniels_bathroom_fan_automation_running'%5D%20else%20%7B%7D%20%7D%7D%5Cn%22%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D,%0A%20%20%20%20%22blueprint_inputs%22:%20null,%0A%20%20%20%20%22context%22:%20%7B%0A%20%20%20%20%20%20%22id%22:%20%2201G8TCTETJT5GM233SX4P8SP5D%22,%0A%20%20%20%20%20%20%22parent_id%22:%20%2201G8TCTETF46EW3GP4KDG268PV%22,%0A%20%20%20%20%20%20%22user_id%22:%20null%0A%20%20%20%20%7D%0A%20%20%7D,%0A%20%20%22logbookEntries%22:%20%5B%5D%0A%7D
	at android.app.DownloadManager$Request.<init>(DownloadManager.java:634)
	at io.homeassistant.companion.android.webview.WebViewActivity.downloadFile(WebViewActivity.kt:1305)
	at io.homeassistant.companion.android.webview.WebViewActivity.onCreate$lambda-6$lambda-5(WebViewActivity.kt:409)
	at io.homeassistant.companion.android.webview.WebViewActivity.$r8$lambda$7PVv7s3al6_xmoAmb2JtzHMgPNM(Unknown Source:0)
	at io.homeassistant.companion.android.webview.WebViewActivity$$ExternalSyntheticLambda8.onDownloadStart(Unknown Source:9)
	at Wa.handleMessage(chromium-TrichromeWebViewGoogle6432.aab-stable-506007134:867)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
> Still happening.

please confirm the app version you are on, the fix is in the beta only and not the production build.

**Comment by dshokouhi** [comment]
correct you need to be on the beta to see the change, issues get closed as PRs get merged. I am not sure when a new release will be cut to production.
