### ISSUE TITLE
External url fails after a few minutes

### ISSUE THREAD

**Issue by fallingcats** [home-assistant/android#2725]
**Home Assistant Android version:**
home-assistant-full-beta-2510-f9ceeb0d.apk

**Android version:**
Android 11

**Phone model:**
OnePlus 7

**Home Assistant version:**
core-2022.7.5

**Last working Home Assistant release (if known):**
The bug has occured since using the app (more than a year).

**Description of problem:**
When accessing the external url, home assistant sometimes shows "Unable to connect to Home Assistant". With remote debugging enabled, I can see that all requests get a 200 response (and websocket 101), as they should.

Weirdly, the external connection usually works if the internal connection was used seconds prior (and then disconnected from wifi). After a few minutes the external connection usually fails again.

It the frontend always works fine in a webbrowser.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**
The console shows
```
Uncaught TypeError: Cannot read properties of null (reading '0')
    at <anonymous>:1:98
```
with "anonymous" being: 
```
[document.getElementsByTagName('html')[0].computedStyleMap().get('--app-header-background-color')[0],document.getElementsByTagName('html')[0].computedStyleMap().get('--primary-background-color')[0]].join('-SPACER-')
```

Followed by
```
Uncaught (in promise) 1
Promise.then (async)
(anonymous) @ core.2895f1d4.js:1
(anonymous) @ core.2895f1d4.js:1
(anonymous) @ core.2895f1d4.js:1
```

**Screenshot of problem:**
![Screenshot_20220729-055359](https://user-images.githubusercontent.com/12884838/181679697-b9744dc0-8804-4a93-a39b-16fc3c3795af.jpg)

**Additional information:**

**Comment by dshokouhi** [comment]
Please go to settings then show and share logs and grab the logs when the error is shown. We need in app logs for this like the link mentioned.

**Comment by fallingcats** [comment]
> Please go to settings then show and share logs and grab the logs when the error is shown. We need in app logs for this like the link mentioned.

Show and share logs loads indefinitely

**Comment by dshokouhi** [comment]
> > Please go to settings then show and share logs and grab the logs when the error is shown. We need in app logs for this like the link mentioned.
> 
> Show and share logs loads indefinitely 

Are you using a custom ROM ? We need on device logcat in order to continue here. As it stands now we cannot solve a SSL handshake issue. So if that is the actual issue Android is reporting then we won't be of help.

**Comment by dshokouhi** [comment]
Might also be a good idea to start fresh in case something funky is going on

https://companion.home-assistant.io/docs/troubleshooting/faqs#starting-fresh-with-the-android-app

**Comment by fallingcats** [comment]
This is the stock rom with Magisk. Apparently sharing logs does not work while a chrome remote debugger is connected.

[homeassistant_companion_log_6-29-2022_6-13-24.txt](https://github.com/home-assistant/android/files/9216008/homeassistant_companion_log_6-29-2022_6-13-24.txt)

**Comment by fallingcats** [comment]
> Might also be a good idea to start fresh in case something funky is going on
> 
> https://companion.home-assistant.io/docs/troubleshooting/faqs#starting-fresh-with-the-android-app

Done that multiple times in the past without success

**Comment by dshokouhi** [comment]
Yes this appears to be an issue with your SSL certificate. This is not an error the app can solve.   You'll wnat to make sure to use a valid SSL certificate, Android can be very picky about this and it varies from device to device. Maybe try to regenerate the certificate or use a different provider. Closing as we cannot fix SSL errors like this one.

```
07-29 06:13:11.698 21969  6663 E SensorReceiver: Issue re-registering sensor steps_sensor
07-29 06:13:11.698 21969  6663 E SensorReceiver: io.homeassistant.companion.android.common.data.integration.IntegrationException: javax.net.ssl.SSLHandshakeException: Chain validation failed
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl.registerSensor(IntegrationRepositoryImpl.kt:630)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl$registerSensor$1.invokeSuspend(Unknown Source:15)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
07-29 06:13:11.698 21969  6663 E SensorReceiver: Caused by: javax.net.ssl.SSLHandshakeException: Chain validation failed
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:362)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at com.android.org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1134)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1089)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:876)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:858)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.access$100(ConscryptEngineSocket.java:731)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:241)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:220)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at java.lang.Thread.run(Thread.java:923)
07-29 06:13:11.698 21969  6663 E SensorReceiver: Caused by: java.security.cert.CertificateException: Chain validation failed
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:724)
07-29 06:13:11.698 21969  7967 D UrlRepository: localUrl is: true and usesInternalSsid is: false
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:554)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:575)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:620)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:643)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:510)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:428)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:356)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:90)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at com.android.org.conscrypt.ConscryptEngineSocket$2.checkServerTrusted(ConscryptEngineSocket.java:163)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:254)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at com.android.org.conscrypt.ConscryptEngine.verifyCertificateChain(ConscryptEngine.java:1644)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at com.android.org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:568)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1095)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1079)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	... 27 more
07-29 06:13:11.698 21969  6663 E SensorReceiver: Caused by: java.security.cert.CertPathValidatorException: Response is unreliable: its validity interval is out-of-date
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:222)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:140)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:79)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at java.security.cert.CertPathValidator.validate(CertPathValidator.java:301)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:720)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	... 43 more
07-29 06:13:11.698 21969  6663 E SensorReceiver: Caused by: java.security.cert.CertPathValidatorException: Response is unreliable: its validity interval is out-of-date
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at sun.security.provider.certpath.OCSPResponse.verify(OCSPResponse.java:619)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at sun.security.provider.certpath.RevocationChecker.checkOCSP(RevocationChecker.java:709)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:363)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:337)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	... 48 more
07-29 06:13:11.698 21969  6663 E SensorReceiver: 	Suppressed: java.security.cert.CertPathValidatorException: Could not determine revocation status
07-29 06:13:11.698 21969  6663 E SensorReceiver: 		at sun.security.provider.certpath.RevocationChecker.buildToNewKey(RevocationChecker.java:1092)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 		at sun.security.provider.certpath.RevocationChecker.verifyWithSeparateSigningKey(RevocationChecker.java:910)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 		at sun.security.provider.certpath.RevocationChecker.checkCRLs(RevocationChecker.java:577)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 		at sun.security.provider.certpath.RevocationChecker.checkCRLs(RevocationChecker.java:465)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 		at sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:394)
07-29 06:13:11.698 21969  6663 E SensorReceiver: 		... 50 more
```
