### ISSUE TITLE
Frequent notification "Unable to open connection to Home Assistant"

### ISSUE THREAD

**Issue by mmiller7** [home-assistant/android#2830]
**Home Assistant Android version:**
2022.8

**Android version:**
9

**Phone model:**
LG V30

**Home Assistant version:**
2022.8.7

**Last working Home Assistant release (if known):**

**Description of problem:**
Frequent notification "Unable to open connection to Home Assistant" but appears to be working correctly connecting in app.  Phone and HA server are on same LAN network when this is happening.
Related thread: https://community.home-assistant.io/t/frequent-unable-to-open-connection-notifications/454858/14
Directed to open issue on GitHub in community forum thread.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```
08-28 18:23:40.774 25358 25411 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=12a8e83b-0d0a-4f01-9e9a-8554e49ba273, tags={ io.homeassistant.companion.android.websocket.WebsocketManager } ]
08-28 18:23:40.780 25358 25358 I WM-SystemFgDispatcher: Stopping foreground service
08-28 18:23:46.135 25358 25370 W System  : A resource failed to call destroy. 
08-28 18:23:50.809 25358  5339 D WebSocketRepository: Websocket: onClosing code: 1000, reason: 
08-28 18:23:50.821 25358  5339 D WebSocketRepository: Websocket: onClosed
08-28 18:24:21.963 25358 25358 D ActivitySM: Received activity update.
08-28 18:25:22.453 25358 25358 D ActivitySM: Received activity update.
08-28 18:28:42.832 25358 25358 D SensorReceiver: Received intent: android.app.action.NEXT_ALARM_CLOCK_CHANGED
08-28 18:28:42.836 25358 25438 D UrlRepository: localUrl is: false and usesInternalSsid is: false
08-28 18:28:42.838 25358 25438 D UrlRepository: localUrl is: false and usesInternalSsid is: false
08-28 18:28:42.889 25358 25358 D SensorReceiver: Received intent: android.intent.action.SCREEN_ON
08-28 18:28:42.893 25358 25438 D ActivitySM: Unregistering for activity updates.
08-28 18:28:42.893 25358 25358 D SensorReceiver: Sensor is_interactive corresponding to received event android.intent.action.SCREEN_ON is disabled, skipping sensors update
08-28 18:28:42.895 25358 25358 D ButtonWidget: Broadcast received: 
08-28 18:28:42.895 25358 25358 D ButtonWidget: Broadcast action: android.intent.action.SCREEN_ON
08-28 18:28:42.895 25358 25358 D ButtonWidget: AppWidgetId: -1
08-28 18:28:42.895 25358 25438 D ActivitySM: Registering for activity updates.
08-28 18:28:42.908 25358 25358 D UrlRepository: localUrl is: false and usesInternalSsid is: false
08-28 18:28:42.909 25358 31057 D UrlRepository: localUrl is: false and usesInternalSsid is: false
08-28 18:28:42.910 25358 25358 D MediaPlayCtrlsWidget: Broadcast received: 
08-28 18:28:42.910 25358 25358 D MediaPlayCtrlsWidget: Broadcast action: android.intent.action.SCREEN_ON
08-28 18:28:42.910 25358 25358 D MediaPlayCtrlsWidget: AppWidgetId: -1
08-28 18:28:42.921 25358 25358 D UrlRepository: localUrl is: false and usesInternalSsid is: false
08-28 18:28:42.941 25358 25358 D UrlRepository: localUrl is: false and usesInternalSsid is: false
08-28 18:28:42.987 25358 31057 E WebSockManager: Unable to setForeground due to restrictions
08-28 18:28:42.987 25358 31057 E WebSockManager: kotlinx.coroutines.JobCancellationException: Job was cancelled; job=JobImpl{Cancelling}@7487fd3
08-28 18:28:42.993 25358 25410 I WM-WorkerWrapper: Work [ id=357196f5-4407-4cfe-abe1-5799077c06d1, tags={ io.homeassistant.companion.android.websocket.WebsocketManager } ] was cancelled
08-28 18:28:42.993 25358 25410 I WM-WorkerWrapper: java.util.concurrent.CancellationException: Task was cancelled.
08-28 18:28:42.993 25358 25410 I WM-WorkerWrapper: 	at androidx.work.impl.utils.futures.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:1184)
08-28 18:28:42.993 25358 25410 I WM-WorkerWrapper: 	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:514)
08-28 18:28:42.993 25358 25410 I WM-WorkerWrapper: 	at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:475)
08-28 18:28:42.993 25358 25410 I WM-WorkerWrapper: 	at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:311)
08-28 18:28:42.993 25358 25410 I WM-WorkerWrapper: 	at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
08-28 18:28:42.993 25358 25410 I WM-WorkerWrapper: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-28 18:28:42.993 25358 25410 I WM-WorkerWrapper: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-28 18:28:42.993 25358 25410 I WM-WorkerWrapper: 	at java.lang.Thread.run(Thread.java:764)
08-28 18:28:42.999 25358 25358 I WM-SystemFgDispatcher: Stopping foreground service
08-28 18:28:43.032 25358 25439 D UrlRepository: localUrl is: false and usesInternalSsid is: false
08-28 18:28:43.044 25358 25391 I WM-Processor: Moving WorkSpec (80b8de54-7035-4021-b7d4-06ac0417b8f8) to the foreground
08-28 18:28:43.056 25358 25358 I WM-SystemFgDispatcher: Started foreground service Intent { act=ACTION_START_FOREGROUND cmp=io.homeassistant.companion.android/androidx.work.impl.foreground.SystemForegroundService (has extras) }
08-28 18:28:43.063 25358 25439 D WebSockManager: Starting to listen to Websocket
08-28 18:28:43.070 25358 25439 D UrlRepository: localUrl is: false and usesInternalSsid is: false
08-28 18:28:43.070 25358 25439 D UrlRepository: Using external URL
08-28 18:28:43.107 25358 25439 D UrlRepository: localUrl is: false and usesInternalSsid is: false
08-28 18:28:43.109 25358 25439 D UrlRepository: Using external URL
08-28 18:28:43.133 25358  8108 D WebSocketRepository: Websocket: onOpen
08-28 18:28:43.133 25358  8108 D WebSocketRepository: Websocket: onMessage (text)
08-28 18:28:43.134 25358  8108 D WebSocketRepository: Message number null received: {"type":"auth_required","ha_version":"2022.8.7"}
08-28 18:28:43.134 25358 25439 D WebSocketRepository: Auth Requested
08-28 18:28:43.140 25358  8108 D WebSocketRepository: Websocket: onMessage (text)
08-28 18:28:43.141 25358  8108 D WebSocketRepository: Message number null received: {"type":"auth_ok","ha_version":"2022.8.7"}
08-28 18:28:43.144 25358 23631 D WebSocketRepository: Sending message 181: {type=mobile_app/push_notification_channel, webhook_id=1d593964130f24a5380bc6783f564b8ce7267dc47f18fdd05168fab4164b5733, support_confirm=true, id=181}
08-28 18:28:43.149 25358 23631 D WebSocketRepository: Message number 181 sent
08-28 18:28:43.154 25358 25438 D BluetoothManager: getConnectedDevices
08-28 18:28:43.157 25358  8108 D WebSocketRepository: Websocket: onMessage (text)
08-28 18:28:43.161 25358  8108 D WebSocketRepository: Message number 181 received: {"id":181,"type":"result","success":true,"result":null}
08-28 18:28:43.204 25358 25358 D ActivitySM: Received activity update.
08-28 18:28:43.237 25358 25438 I SensorManager: registerListenerImpl() [Sensor: LGE Light, Rate: 200000, SensorEventListener: io.homeassistant.companion.android.sensors.LightSensorManager@dc282f4] by io.homeassistant.companion.android.sensors.LightSensorManager.updateLightSensor():72
08-28 18:28:43.238 25358 25438 D LightSensor: Light sensor listener registered
08-28 18:28:43.244 25358 25358 I SensorManager: removeAllSensors() [Sensor: LGE Light] by io.homeassistant.companion.android.sensors.LightSensorManager.onSensorChanged():96
08-28 18:28:43.244 25358 25358 D LightSensor: Light sensor listener unregistered
08-28 18:28:43.283 25358 25438 D NextAlarm: No alarm is scheduled, sending unavailable
08-28 18:28:43.310 25358 25438 I SensorManager: registerListenerImpl() [Sensor: LGE Pressure, Rate: 200000, SensorEventListener: io.homeassistant.companion.android.sensors.PressureSensorManager@c704a1d] by io.homeassistant.companion.android.sensors.PressureSensorManager.updatePressureSensor():70
08-28 18:28:43.314 25358 25438 D PressureSensor: Pressure sensor listener registered
08-28 18:28:43.315 25358 25438 I SensorManager: registerListenerImpl() [Sensor: LGE Proximity, Rate: 200000, SensorEventListener: io.homeassistant.companion.android.sensors.ProximitySensorManager@1d29492] by io.homeassistant.companion.android.sensors.ProximitySensorManager.updateProximitySensor():69
08-28 18:28:43.316 25358 25438 D ProximitySensor: Proximity sensor listener registered
08-28 18:28:43.318 25358 25358 I SensorManager: removeAllSensors() [Sensor: LGE Proximity] by io.homeassistant.companion.android.sensors.ProximitySensorManager.onSensorChanged():101
08-28 18:28:43.319 25358 25358 D ProximitySensor: Proximity sensor listener unregistered
08-28 18:28:43.320 25358 25438 I SensorManager: registerListenerImpl() [Sensor: LGE Step Counter Sensor, Rate: 200000, SensorEventListener: io.homeassistant.companion.android.sensors.StepsSensorManager@ad9ee63] by io.homeassistant.companion.android.sensors.StepsSensorManager.updateStepsSensor():79
08-28 18:28:43.330 25358 25438 D StepsSensor: Steps sensor listener registered
08-28 18:28:43.337 25358 25358 I SensorManager: removeAllSensors() [Sensor: LGE Step Counter Sensor] by io.homeassistant.companion.android.sensors.StepsSensorManager.onSensorChanged():104
08-28 18:28:43.346 25358 25358 D StepsSensor: Steps sensor listener unregistered
08-28 18:28:43.352 25358 25438 D UrlRepository: localUrl is: false and usesInternalSsid is: false
08-28 18:28:43.547 25358 25358 I SensorManager: removeAllSensors() [Sensor: LGE Pressure] by io.homeassistant.companion.android.sensors.PressureSensorManager.onSensorChanged():96
08-28 18:28:43.549 25358 25358 D PressureSensor: Pressure sensor listener unregistered
08-28 18:28:55.607 25358 25358 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@1fffee6
08-28 18:28:55.692 25358 25358 D PhoneWindow: windowLightStatusBar : true, enable View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR
08-28 18:28:55.743 25358 25358 I TouchFilterInputStageHelper: [needTouchEventFilter] Displayid : 0
08-28 18:28:55.744 25358 25358 D BezellessGripSuppressionFilter: getdisplaysize, x : 1440 y : 2880
08-28 18:28:55.746 25358 25358 D UrlRepository: localUrl is: false and usesInternalSsid is: false
08-28 18:28:55.746 25358 25358 D UrlRepository: Using external URL
08-28 18:28:55.747 25358 25358 D UrlRepository: localUrl is: false and usesInternalSsid is: false
08-28 18:28:55.787 25358 31057 D UrlRepository: localUrl is: false and usesInternalSsid is: false
08-28 18:28:55.901 25358 25358 W mpanion.androi: Accessing hidden method Landroid/view/RenderNode;->getScaleX()F (dark greylist, linking)
08-28 18:28:55.964 25358 25358 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@26ded89
08-28 18:28:56.039 25358 25358 D PhoneWindow: windowLightStatusBar : false, disable View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR
08-28 18:28:56.081 25358 25358 I System.out: recordForce value 6
08-28 18:28:56.082 25358 25358 D WebviewActivity: Current webview package com.android.chrome and version 104.0.5112.97
08-28 18:28:56.146 25358 25358 E LocationManager: [LGNSS] Disable_PrivacyLocation_Information [tOperator : VZW ] , [privacy_check : 0]
08-28 18:28:56.147 25358 25358 D LocationManager: init Cipher success.
08-28 18:28:56.147 25358 25358 E LocationManager: [LGNSS] This device should be enabled location encryption - user build
08-28 18:28:56.218 25358 25358 I TouchFilterInputStageHelper: [needTouchEventFilter] Displayid : 0
08-28 18:28:56.218 25358 25358 D BezellessGripSuppressionFilter: getdisplaysize, x : 1440 y : 2880
08-28 18:28:56.345 25358 31057 D UrlRepository: localUrl is: false and usesInternalSsid is: false
08-28 18:28:56.348 25358 25398 I WM-Processor: Moving WorkSpec (a6b467ff-5b5b-46e2-9b03-8e7be4889a2a) to the foreground
08-28 18:28:56.351 25358 31057 D SensorWorker: Updating all Sensors in foreground.
08-28 18:28:56.353 25358 31057 D UrlRepository: localUrl is: false and usesInternalSsid is: false
08-28 18:28:56.353 25358 31057 D UrlRepository: localUrl is: false and usesInternalSsid is: false
08-28 18:28:56.360 25358 25358 D UrlRepository: localUrl is: false and usesInternalSsid is: false
08-28 18:28:56.360 25358 25358 D UrlRepository: Using external URL
08-28 18:28:56.399 25358 25358 I WM-SystemFgDispatcher: Started foreground service Intent { act=ACTION_START_FOREGROUND cmp=io.homeassistant.companion.android/androidx.work.impl.foreground.SystemForegroundService (has extras) }
08-28 18:28:56.406 25358 31057 D ActivitySM: Unregistering for activity updates.
08-28 18:28:56.406 25358 31057 D ActivitySM: Registering for activity updates.
08-28 18:28:56.406 25358 25358 I Timeline: Timeline: Activity_idle id: android.os.BinderProxy@26ded89 time:131476600
08-28 18:28:56.475 25358 25358 D ActivitySM: Received activity update.
08-28 18:28:56.515 25358 31057 D BluetoothManager: getConnectedDevices
08-28 18:28:56.553 25358 31057 I SensorManager: registerListenerImpl() [Sensor: LGE Light, Rate: 200000, SensorEventListener: io.homeassistant.companion.android.sensors.LightSensorManager@dc282f4] by io.homeassistant.companion.android.sensors.LightSensorManager.updateLightSensor():72
08-28 18:28:56.554 25358 31057 D LightSensor: Light sensor listener registered
08-28 18:28:56.556 25358 25358 I SensorManager: removeAllSensors() [Sensor: LGE Light] by io.homeassistant.companion.android.sensors.LightSensorManager.onSensorChanged():96
08-28 18:28:56.557 25358 25358 D LightSensor: Light sensor listener unregistered
08-28 18:28:56.577 25358 31057 D NextAlarm: No alarm is scheduled, sending unavailable
08-28 18:28:56.604 25358 31057 I SensorManager: registerListenerImpl() [Sensor: LGE Pressure, Rate: 200000, SensorEventListener: io.homeassistant.companion.android.sensors.PressureSensorManager@c704a1d] by io.homeassistant.companion.android.sensors.PressureSensorManager.updatePressureSensor():70
08-28 18:28:56.608 25358 31057 D PressureSensor: Pressure sensor listener registered
08-28 18:28:56.609 25358 31057 I SensorManager: registerListenerImpl() [Sensor: LGE Proximity, Rate: 200000, SensorEventListener: io.homeassistant.companion.android.sensors.ProximitySensorManager@1d29492] by io.homeassistant.companion.android.sensors.ProximitySensorManager.updateProximitySensor():69
08-28 18:28:56.612 25358 31057 D ProximitySensor: Proximity sensor listener registered
08-28 18:28:56.614 25358 25358 I SensorManager: removeAllSensors() [Sensor: LGE Proximity] by io.homeassistant.companion.android.sensors.ProximitySensorManager.onSensorChanged():101
08-28 18:28:56.615 25358 25358 D ProximitySensor: Proximity sensor listener unregistered
08-28 18:28:56.616 25358 31057 I SensorManager: registerListenerImpl() [Sensor: LGE Step Counter Sensor, Rate: 200000, SensorEventListener: io.homeassistant.companion.android.sensors.StepsSensorManager@ad9ee63] by io.homeassistant.companion.android.sensors.StepsSensorManager.updateStepsSensor():79
08-28 18:28:56.622 25358 31057 D StepsSensor: Steps sensor listener registered
08-28 18:28:56.622 25358 25358 I SensorManager: removeAllSensors() [Sensor: LGE Step Counter Sensor] by io.homeassistant.companion.android.sensors.StepsSensorManager.onSensorChanged():104
08-28 18:28:56.628 25358 25358 D StepsSensor: Steps sensor listener unregistered
08-28 18:28:56.632 25358 31057 D UrlRepository: localUrl is: false and usesInternalSsid is: false
08-28 18:28:56.648 25358 25391 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=a6b467ff-5b5b-46e2-9b03-8e7be4889a2a, tags={ io.homeassistant.companion.android.sensors.SensorWorker } ]
08-28 18:28:56.887 25358 25358 I SensorManager: removeAllSensors() [Sensor: LGE Pressure] by io.homeassistant.companion.android.sensors.PressureSensorManager.onSensorChanged():96
08-28 18:28:56.888 25358 25358 D PressureSensor: Pressure sensor listener unregistered
08-28 18:28:57.090 25358 16205 D WebviewActivity: External bus {"type":"config/get","id":1}
08-28 18:28:57.092 25358 25358 D WebviewActivity: externalBus({"id":1,"type":"result","success":true,"result":{"hasSettingsScreen":true,"canWriteTag":true,"hasExoPlayer":true}});
08-28 18:28:57.120 25358 25358 D UrlRepository: localUrl is: false and usesInternalSsid is: false
08-28 18:28:57.120 25358 25358 D UrlRepository: Using external URL
08-28 18:28:57.124 25358 25358 D WebviewActivity: Callback null
08-28 18:28:57.125 25358 25358 D WebviewActivity: Color from webview is "#03a9f4-SPACER- #fafafa"
08-28 18:28:57.125 25358 25358 D WebviewActivity: Color from webview is "#03a9f4-SPACER- #fafafa"
08-28 18:28:57.125 25358 31057 D WebViewPresenterImpl: Try getting color from webview color "#03a9f4".
08-28 18:28:57.125 25358 31057 I WebViewPresenterImpl: Found color -16537100.
08-28 18:28:57.125 25358 31057 D WebViewPresenterImpl: Try getting color from webview color "#fafafa".
08-28 18:28:57.126 25358 31057 I WebViewPresenterImpl: Found color -328966.
08-28 18:28:57.575 25358 16205 D WebviewActivity: External bus {"type":"connection-status","payload":{"event":"connected"},"id":2}
08-28 18:28:57.576 25358 25358 D UrlRepository: localUrl is: false and usesInternalSsid is: false
08-28 18:28:57.706 25358 16205 D WebviewActivity: External bus {"type":"theme-update","id":3}
08-28 18:28:57.721 25358 25358 D WebviewActivity: Color from webview is "#03a9f4-SPACER- #fafafa"
08-28 18:28:57.721 25358 25358 D WebviewActivity: Color from webview is "#03a9f4-SPACER- #fafafa"
08-28 18:28:57.721 25358 25438 D WebViewPresenterImpl: Try getting color from webview color "#03a9f4".
08-28 18:28:57.721 25358 25438 I WebViewPresenterImpl: Found color -16537100.
08-28 18:28:57.721 25358 31057 D WebViewPresenterImpl: Try getting color from webview color "#fafafa".
08-28 18:28:57.721 25358 31057 I WebViewPresenterImpl: Found color -328966.
08-28 18:28:58.903 25358 25358 I ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
08-28 18:28:58.962 25358 25358 I ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
08-28 18:29:00.161 25358 25358 I ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
08-28 18:29:00.209 25358 25358 I ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
08-28 18:29:01.010 25358 25358 I ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
08-28 18:29:01.190 25358 25358 I ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
08-28 18:29:01.832 25358 25358 I ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
08-28 18:29:01.865 25358 25358 I ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
08-28 18:29:01.896 25358 16205 D WebviewActivity: External bus {"type":"config_screen/show","id":4}
08-28 18:29:01.944 25358 25358 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@6321637
08-28 18:29:01.958 25358 25358 D PhoneWindow: windowLightStatusBar : true, enable View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR
08-28 18:29:01.984 25358 25358 D UrlRepository: Using external URL
08-28 18:29:01.984 25358 25358 D UrlRepository: Using external URL
08-28 18:29:02.014 25358 25358 I TouchFilterInputStageHelper: [needTouchEventFilter] Displayid : 0
08-28 18:29:02.014 25358 25358 D BezellessGripSuppressionFilter: getdisplaysize, x : 1440 y : 2880
08-28 18:29:02.122 25358 12461 D UrlRepository: localUrl is: false and usesInternalSsid is: false
08-28 18:29:02.128 25358 25391 I WM-Processor: Moving WorkSpec (d334c520-881d-40f3-a55c-60b5b3802ca4) to the foreground
08-28 18:29:02.131 25358 25358 I WM-SystemFgDispatcher: Started foreground service Intent { act=ACTION_START_FOREGROUND cmp=io.homeassistant.companion.android/androidx.work.impl.foreground.SystemForegroundService (has extras) }
08-28 18:29:02.134 25358 12461 D SensorWorker: Updating all Sensors in foreground.
08-28 18:29:02.134 25358 25358 I Timeline: Timeline: Activity_idle id: android.os.BinderProxy@6321637 time:131482329
08-28 18:29:02.136 25358 12461 D UrlRepository: localUrl is: false and usesInternalSsid is: false
08-28 18:29:02.137 25358 12461 D UrlRepository: localUrl is: false and usesInternalSsid is: false
08-28 18:29:02.149 25358 12461 D ActivitySM: Unregistering for activity updates.
08-28 18:29:02.149 25358 12461 D ActivitySM: Registering for activity updates.
08-28 18:29:02.185 25358 25358 D ActivitySM: Received activity update.
08-28 18:29:02.216 25358 12461 D BluetoothManager: getConnectedDevices
08-28 18:29:02.279 25358 12461 I SensorManager: registerListenerImpl() [Sensor: LGE Light, Rate: 200000, SensorEventListener: io.homeassistant.companion.android.sensors.LightSensorManager@dc282f4] by io.homeassistant.companion.android.sensors.LightSensorManager.updateLightSensor():72
08-28 18:29:02.280 25358 12461 D LightSensor: Light sensor listener registered
08-28 18:29:02.283 25358 25358 I SensorManager: removeAllSensors() [Sensor: LGE Light] by io.homeassistant.companion.android.sensors.LightSensorManager.onSensorChanged():96
08-28 18:29:02.283 25358 25358 D LightSensor: Light sensor listener unregistered
08-28 18:29:02.308 25358 12461 D NextAlarm: No alarm is scheduled, sending unavailable
08-28 18:29:02.330 25358 12461 I SensorManager: registerListenerImpl() [Sensor: LGE Pressure, Rate: 200000, SensorEventListener: io.homeassistant.companion.android.sensors.PressureSensorManager@c704a1d] by io.homeassistant.companion.android.sensors.PressureSensorManager.updatePressureSensor():70
08-28 18:29:02.339 25358 12461 D PressureSensor: Pressure sensor listener registered
08-28 18:29:02.341 25358 12461 I SensorManager: registerListenerImpl() [Sensor: LGE Proximity, Rate: 200000, SensorEventListener: io.homeassistant.companion.android.sensors.ProximitySensorManager@1d29492] by io.homeassistant.companion.android.sensors.ProximitySensorManager.updateProximitySensor():69
08-28 18:29:02.342 25358 12461 D ProximitySensor: Proximity sensor listener registered
08-28 18:29:02.343 25358 25358 I SensorManager: removeAllSensors() [Sensor: LGE Proximity] by io.homeassistant.companion.android.sensors.ProximitySensorManager.onSensorChanged():101
08-28 18:29:02.344 25358 25358 D ProximitySensor: Proximity sensor listener unregistered
08-28 18:29:02.344 25358 12461 I SensorManager: registerListenerImpl() [Sensor: LGE Step Counter Sensor, Rate: 200000, SensorEventListener: io.homeassistant.companion.android.sensors.StepsSensorManager@ad9ee63] by io.homeassistant.companion.android.sensors.StepsSensorManager.updateStepsSensor():79
08-28 18:29:02.350 25358 12461 D StepsSensor: Steps sensor listener registered
08-28 18:29:02.351 25358 25358 I SensorManager: removeAllSensors() [Sensor: LGE Step Counter Sensor] by io.homeassistant.companion.android.sensors.StepsSensorManager.onSensorChanged():104
08-28 18:29:02.354 25358 25358 D StepsSensor: Steps sensor listener unregistered
08-28 18:29:02.359 25358 12461 D UrlRepository: localUrl is: false and usesInternalSsid is: false
08-28 18:29:02.371 25358 25411 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=d334c520-881d-40f3-a55c-60b5b3802ca4, tags={ io.homeassistant.companion.android.sensors.SensorWorker } ]
08-28 18:29:02.618 25358 25358 I SensorManager: removeAllSensors() [Sensor: LGE Pressure] by io.homeassistant.companion.android.sensors.PressureSensorManager.onSensorChanged():96
08-28 18:29:02.621 25358 25358 D PressureSensor: Pressure sensor listener unregistered
08-28 18:29:03.471 25358 25358 I ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
08-28 18:29:03.603 25358 25358 I ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
08-28 18:29:05.359 25358 25358 I ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
08-28 18:29:05.854 25358 25358 I ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
08-28 18:29:06.826 25358 25358 I ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
08-28 18:29:06.863 25358 25358 I ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
08-28 18:29:06.864 25358 25358 E mpanion.androi: Invalid ID 0x00000000.
08-28 18:29:06.983 25358 12461 D LogcatReader: Read logcat for pid 25358
```

**Screenshot of problem:**
![image](https://user-images.githubusercontent.com/606945/187100521-85d55735-3280-404b-af32-25738f2d7cfd.png)

**Additional information:**

**Comment by jpelgrom** [comment]
Did you tap on the notification to fix it?

This happens when you have persistent connection enabled but the app can't start in the background. You can disable the persistent connection, or allow the app to run unrestricted in the background to fix it.
