### ISSUE TITLE
Websocket nullpointerexceptions for subscribeTo

### ISSUE THREAD

**Issue by dshokouhi** [home-assistant/android#2852]
**Home Assistant Android version:**

beta-2646-84aa4454

**Android version:**

12/13

**Phone model:**

Pixel 5

**Home Assistant version:**

unknown

**Last working Home Assistant release (if known):**

unknown

**Description of problem:**

3 very similar null pointer errors in Sentry for the latest beta in the play store

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```
java.lang.NullPointerException: null
    at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl.subscribeTo(WebSocketRepositoryImpl.kt:244)
    at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl.subscribeToEventsForType(WebSocketRepositoryImpl.kt:189)
    at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl.getStateChanges(WebSocketRepositoryImpl.kt:177)
    at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl.getEntityUpdates(IntegrationRepositoryImpl.kt:578)
    at io.homeassistant.companion.android.widgets.BaseWidgetProvider$onScreenOn$1.invokeSuspend(BaseWidgetProvider.kt:86)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7911)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)
```

```
java.lang.NullPointerException: null
    at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl.subscribeTo(WebSocketRepositoryImpl.kt:244)
    at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl.subscribeToEventsForType(WebSocketRepositoryImpl.kt:189)
    at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl.getStateChanges(WebSocketRepositoryImpl.kt:177)
    at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl.getEntityUpdates(IntegrationRepositoryImpl.kt:578)
    at io.homeassistant.companion.android.controls.HaControlsProviderService$createPublisherFor$1$1$request$1$2.invokeSuspend(HaControlsProviderService.kt:160)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
    at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

```
java.lang.NullPointerException: null
    at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl.subscribeTo(WebSocketRepositoryImpl.kt:244)
    at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl.getTemplateUpdates(WebSocketRepositoryImpl.kt:192)
    at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl.getTemplateUpdates(IntegrationRepositoryImpl.kt:180)
    at io.homeassistant.companion.android.widgets.template.TemplateWidget$onScreenOn$1.invokeSuspend(TemplateWidget.kt:143)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8663)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

**Screenshot of problem:**

**Additional information:**

**Comment by jpelgrom** [comment]
It's failing on this line:
https://github.com/home-assistant/android/blob/84aa4454b731e4058cce083d947c27a4d90c5469/common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt#L244

The check before it uses the subscription ID instead of the flow to determine if it needs to create a new flow, so it looks like the subscription ID is still set while the flow is already `null`. I think it's a race condition in the unsubscribe logic because it sends the unsubscribe message in a suspending function and only removes the subscription ID when finished, whereas the flow is removed immediately:
https://github.com/home-assistant/android/blob/84aa4454b731e4058cce083d947c27a4d90c5469/common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt#L226-L239

I'll do some tests to verify this and (hopefully) submit a fix soon.

**Comment by jpelgrom** [comment]
I believe this is the result of changes in #2801 so the latest stable release should be fine, but if you do spot it in other versions please mention it @dshokouhi !

**Comment by dshokouhi** [comment]
> I believe this is the result of changes in #2801 so the latest stable release should be fine, but if you do spot it in other versions please mention it @dshokouhi !

So far only in Beta 2646, lets see what happens after the next beta push on Saturday.

Also I think you are right about the race, most (if not all) of the events are related to screen turning on. I suspect if its not widgets it may be the users who have persistent connection set to Screen On and never changed the setting.

**Comment by jpelgrom** [comment]
> I suspect if its not widgets it may be the users who have persistent connection set to Screen On and never changed the setting.

The persistent connection uses a different function to handle subscribing/unsubscribing (for now), so I would expect a slightly different stacktrace in that case, line 277 for beta-2646: 
https://github.com/home-assistant/android/blob/84aa4454b731e4058cce083d947c27a4d90c5469/common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt#L277

**Comment by dshokouhi** [comment]
Found one more thats similar

```
java.lang.NullPointerException: null
    at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl.subscribeTo(WebSocketRepositoryImpl.kt:244)
    at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl.access$subscribeTo(WebSocketRepositoryImpl.kt:60)
    at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl$subscribeTo$1.invokeSuspend
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
    at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```
