### ISSUE TITLE
Illegal Argument Exception for TemplateUpdatedEvent "result"

### ISSUE THREAD

**Issue by dshokouhi** [home-assistant/android#2865]
**Home Assistant Android version:**

BETA 2646

**Android version:**

11

**Phone model:**

AC2003

**Home Assistant version:**

unknown

**Last working Home Assistant release (if known):**

unknown

**Description of problem:**

Found the following error on Sentry, I guess [this](https://github.com/home-assistant/android/blob/a995d9410b13d914579cd72fbb74d543333f0305/common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/entities/TemplateUpdatedEvent.kt#L7) should also be nullable?

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```
com.fasterxml.jackson.module.kotlin.MissingKotlinParameterException: Instantiation of [simple type, class io.homeassistant.companion.android.common.data.websocket.impl.entities.TemplateUpdatedEvent] value failed for JSON property result due to missing (therefore NULL) value for creator parameter result which is a non-nullable type
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: io.homeassistant.companion.android.common.data.websocket.impl.entities.TemplateUpdatedEvent["result"])
    at com.fasterxml.jackson.module.kotlin.KotlinValueInstantiator.createFromObjectWith(KotlinValueInstantiator.kt:84)
    at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:202)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:443)
    at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:351)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:184)
    at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4388)
    at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:4324)
    at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl.handleEvent(WebSocketRepositoryImpl.kt:411)
    at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl.access$handleEvent(WebSocketRepositoryImpl.kt:60)
    at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl$onMessage$1$1.invokeSuspend(WebSocketRepositoryImpl.kt:518)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
    at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
java.lang.IllegalArgumentException: Instantiation of [simple type, class io.homeassistant.companion.android.common.data.websocket.impl.entities.TemplateUpdatedEvent] value failed for JSON property result due to missing (therefore NULL) value for creator parameter result which is a non-nullable type
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: io.homeassistant.companion.android.common.data.websocket.impl.entities.TemplateUpdatedEvent["result"])
    at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4393)
    at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:4324)
    at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl.handleEvent(WebSocketRepositoryImpl.kt:411)
    at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl.access$handleEvent(WebSocketRepositoryImpl.kt:60)
    at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl$onMessage$1$1.invokeSuspend(WebSocketRepositoryImpl.kt:518)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
    at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Screenshot of problem:**

**Additional information:**

**Comment by jpelgrom** [comment]
Ah yes, looks like it can also change to `null`... Quick template to reproduce this: `{% if is_state('input_boolean.test_toggle', 'on') %} None {% else %} off {% endif %}` -> will return `null` if the toggle is on, and the string "off" when it is off.

Also tested breaking the template (by editing it directly in the database while the screen was off, but this is more likely to happen due to a breaking change in core): in this case subscribing will fail -> the template will try to render the template using the integration API -> this will throw an exception [which is caught in the template widget](https://github.com/home-assistant/android/blob/45cdaeb7646c73afce48c01f42d81470bc96b259/app/src/main/java/io/homeassistant/companion/android/widgets/template/TemplateWidget.kt#L242-L245) -> the widget will show the refresh error icon.
