### ISSUE TITLE
Data roaming sensor security exception due to target SDK change

### ISSUE THREAD

**Issue by dshokouhi** [home-assistant/android#2977]
**Home Assistant Android version:**
latest master

**Android version:**

13

**Phone model:**

Pixel 7 Pro

**Home Assistant version:**

2022.10.3

**Last working Home Assistant release (if known):**

Phone app 2022.10.2

**Description of problem:**

Found the following error in logcat every time there is a sensor update

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```
2022-10-19 14:21:19.646 26179-26557 SensorReceiver          pid-26179                            E  Issue requesting updates for Mobile Data Sensors
                                                                                                    java.lang.SecurityException: Settings key: <data_roaming> is only readable to apps with targetSdkVersion lower than or equal to: 32
                                                                                                    	at android.provider.Settings$NameValueCache.getStringForUser(Settings.java:3081)
                                                                                                    	at android.provider.Settings$Global.getStringForUser(Settings.java:15854)
                                                                                                    	at android.provider.Settings$Global.getString(Settings.java:15837)
                                                                                                    	at android.provider.Settings$Global.getInt(Settings.java:16054)
                                                                                                    	at io.homeassistant.companion.android.sensors.MobileDataManager.checkState(MobileDataManager.kt:72)
                                                                                                    	at io.homeassistant.companion.android.sensors.MobileDataManager.requestSensorUpdate(MobileDataManager.kt:57)
                                                                                                    	at io.homeassistant.companion.android.common.sensors.SensorManager$DefaultImpls.requestSensorUpdate(SensorManager.kt:94)
                                                                                                    	at io.homeassistant.companion.android.sensors.MobileDataManager.requestSensorUpdate(MobileDataManager.kt:12)
                                                                                                    	at io.homeassistant.companion.android.common.sensors.SensorReceiverBase.updateSensors(SensorReceiverBase.kt:184)
                                                                                                    	at io.homeassistant.companion.android.common.sensors.SensorReceiverBase$updateSensors$1.invokeSuspend(Unknown Source:18)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Screenshot of problem:**

**Additional information:**
Seems to be caused by #2682

**Comment by jpelgrom** [comment]
Missed one :(

The relevant AOSP commit suggests we should switch to `TelephonyManager`: https://android.googlesource.com/platform/frameworks/base/+/8335fd51fb8b2da960d4a46c7aa81e55918d302e

**Comment by dshokouhi** [comment]
yea unfortunately the API we can use is on API 29 and up so we still need to have the old way, unless there is another API?

https://developer.android.com/reference/android/telephony/TelephonyManager#isDataRoamingEnabled()

**Comment by jpelgrom** [comment]
I don't see the problem with doing something like this?
```kotlin
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
    // TelephonyManager
} else {
    // Old Settings
}
```

**Comment by dshokouhi** [comment]
oh yea nothing wrong with it, its just not a complete "switch" 😁 

actually working on a PR right now just running a quick test :)

**Comment by jpelgrom** [comment]
I'm actually not able to reproduce this on my Pixel 4a with Android 13, the sensor seems to work fine. Tried both with and without WiFi connected, mobile data active in both cases (not roaming) 🤔

**Comment by dshokouhi** [comment]
hmm thats strange, as soon as I updated to the latest beta I noticed the error on each sensor update.
