### ISSUE TITLE
Recent Crash: Illegal State exception: Already resumed, but proposed with update SocketResponse

### ISSUE THREAD

**Issue by dshokouhi** [home-assistant/android#3018]
**Home Assistant Android version:**

latest master

**Android version:**

13

**Phone model:**

pixel 7 pro

**Home Assistant version:**

2022.10.5

**Last working Home Assistant release (if known):**

n/a

**Description of problem:**

Noticed that the app crashed and found the following error in Recent Crash tab

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```
2022-10-27 21:53:09.293: java.lang.IllegalStateException: Already resumed, but proposed with update SocketResponse(id=52, type=result, success=true, result=null, event=null, haVersion=null)
    at kotlinx.coroutines.CancellableContinuationImpl.alreadyResumedError(CancellableContinuationImpl.kt:482)
    at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:447)
    at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
    at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328)
    at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl.handleMessage(WebSocketRepositoryImpl.kt:421)
    at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl.access$handleMessage(WebSocketRepositoryImpl.kt:64)
    at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl$onMessage$1$1.invokeSuspend(WebSocketRepositoryImpl.kt:554)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
    at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
    Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@b3b80f6, Dispatchers.IO]
```

**Screenshot of problem:**

**Additional information:**

**Comment by jpelgrom** [comment]
Already resumed - any chance you had a connectivity change shortly before this happened? It can either resume with the message result:
https://github.com/home-assistant/android/blob/66bc26037c53d60d8af3ef473e58b8a335a2759d/common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt#L421

or a failure when the connection is closed:
https://github.com/home-assistant/android/blob/66bc26037c53d60d8af3ef473e58b8a335a2759d/common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt#L508

**Comment by dshokouhi** [comment]
Honestly I have no idea I only noticed this crash when the app started up

**Comment by dshokouhi** [comment]
double checked my sensors to see if there was a Wifi change but nothing at the time of this error, not even the screen turning on/off.

**Comment by jpelgrom** [comment]
I don't fully understand why it is crashing on launch, as the websocket message in the stacktrace looks like a (un)subscribe confirmation with just a success message + no content, which isn't something that the app does at that time. It should be fairly easy to prevent a crash though, submitted a PR for it a few minutes ago.
