### ISSUE TITLE
Recent Crash: Websocket IOException during closing socket

### ISSUE THREAD

**Issue by dshokouhi** [home-assistant/android#3038]
**Home Assistant Android version:**

latest master

**Android version:**

13

**Phone model:**

Pixel 7 Pro

**Home Assistant version:**

2022.10.5

**Last working Home Assistant release (if known):**

n/a

**Description of problem:**

Noticed the app had restarted and found the following error in recent crash tab

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```
2022-11-04 08:30:08.908: java.io.IOException
    at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl$handleClosingSocket$1.invokeSuspend(WebSocketRepositoryImpl.kt:511)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
    at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
    Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@9609dea, Dispatchers.IO]
```

**Screenshot of problem:**

**Additional information:**

**Comment by jpelgrom** [comment]
This exception is supposed to be thrown to the function waiting for a response (which has a `catch`), not here 😅. I wonder why this hasn't been seen before, this logic has been in place for some time now.

https://github.com/home-assistant/android/blob/8a50f0d048099e286b0b2b8125f70bfcec1eee1d/common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt#L511

**Comment by dshokouhi** [comment]
Yea I am not sure why it hasn't been seen before either. Personally I have been trying to make sure I file all the recent crashes that I see :)
