### ISSUE TITLE
Firebase notifications: Device not connected to local push notifications

### ISSUE THREAD

**Issue by szerencl** [home-assistant/android#3090]
**Home Assistant Android version:**
2022.10.2-full
**Android version:**
Android 12
**Phone model:**
Samsung S20 FE
**Home Assistant version:**
2022.11.4
**Last working Home Assistant release (if known):**
\-
**Description of problem:**
I have websocket set to never as I want to use Firebase notifications (because websocket: always causes high battery drain). 
But sometimes automations will fail (about every second week) while calling service notify.mobile_app_<device_id> returns error: "Device not connected to local push notifications". 
When this happens the issue is only fixed if I set the websocket to always, then back to never and either force stop HA companion or reboot the phone (last step is only needed to go back to firebase notifications.)

**Screenshot of problem:**
![kép](https://user-images.githubusercontent.com/57007996/202996461-8ad9b07e-2f69-4f05-adeb-136941d4c7fe.png)
**Additional information:**
- Internal URL not configured (issue also happens when not on wifi).
- Everything else works in the app (e.g.: sensors keep updating).
- App is set as 'not optimized' in battery settings.
- Started happening about a month ago.

**Comment by dshokouhi** [comment]
Can you please try teh following steps.

1. Force stop app
2. Open App
3. Settings > Companion App > show and share logs

get us the logs so we can see whats going on.

**Comment by szerencl** [comment]
Currently it's working, and I don't really know how to reproduce the issue.
Anyway here's the log:
[homeassistant_companion_log_10-21-2022_18-44-14.txt](https://github.com/home-assistant/android/files/10059288/homeassistant_companion_log_10-21-2022_18-44-14.txt)

**Comment by dshokouhi** [comment]
Its going to be tough to tell what is going on here. The error you have shown us is from HA core and we have no idea what data the app had sent to the server for it to think it needs to use local push notifications. Sounds like this happens often for you which is strange. Please get us the companion app logs when the issue occurs. Also I would check to see if there are any HA core errors as well.

**Comment by szerencl** [comment]
The issue occurred again.
It only happens on this phone. I tried with an iPhone and an another android device and on those notifications work without issues.

I won't do my workaround fix for it for the time being, so let me know if there is something else I could check.
I'm thinking about doing a reinstall of the companion app on this phone.

Core log:
When trying to send a notification form developer tools:
```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:150
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 10:56:41 (1 occurrences)
Last logged: 10:56:41

[2768580536] Error handling message: Device not connected to local push notifications (unknown_error) from 192.168.42.1 (Mozilla/5.0 (Linux; Android 12; SM-G780G Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/107.0.5304.105 Mobile Safari/537.36 Home Assistant/2022.11.0-2948 (Android 12; SM-G780G))

Logger: homeassistant.helpers.script.websocket_api_script
Source: helpers/script.py:409
First occurred: 10:56:41 (5 occurrences)
Last logged: 11:15:56

websocket_api script: Error executing script. Error for call_service at pos 1: Device not connected to local push notifications
```

Relevant part of full log in Debug mode:
```
2022-11-26 11:08:30.218 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [2560212440] Received {'type': 'execute_script', 'sequence': [{'service': 'notify.mobile_app_sm_g780g', 'data': {'message': 'The garage door has been open for 10 minutes.', 'title': 'Your Garage Door Friend'}}], 'id': 35}
2022-11-26 11:08:30.221 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Running websocket_api script
2022-11-26 11:08:30.221 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Executing step call service
2022-11-26 11:08:30.222 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event call_service[L]: domain=notify, service=mobile_app_sm_g780g, service_data=message=The garage door has been open for 10 minutes., title=Your Garage Door Friend>
2022-11-26 11:08:30.224 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Error for call_service at pos 1: Device not connected to local push notifications
2022-11-26 11:08:30.225 DEBUG (Recorder) [homeassistant.components.recorder.core] Processing task: EventTask(event=<Event call_service[L]: domain=notify, service=mobile_app_sm_g780g, service_data=message=The garage door has been open for 10 minutes., title=Your Garage Door Friend>)
2022-11-26 11:08:30.234 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [2560212440] Error handling message: Device not connected to local push notifications (unknown_error) from 192.168.42.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:107.0) Gecko/20100101 Firefox/107.0)
2022-11-26 11:08:30.236 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [2560212440] Sending {"id":35,"type":"result","success":false,"error":{"code":"unknown_error","message":"Device not connected to local push notifications"}}
2022-11-26 11:08:30.291 DEBUG (MainThread) [async_upnp_client.traffic.ssdp] Received packet from ('[REDACTED:phone_ip]', 56602): b'M-SEARCH * HTTP/1.1\r\nHOST: 239.255.255.250:1900\r\nMAN: "ssdp:discover"\r\nMX: 1\r\nST: urn:dial-multiscreen-org:service:dial:1\r\n\r\n'
2022-11-26 11:08:30.293 DEBUG (MainThread) [async_upnp_client.traffic.ssdp] Received packet from ('[REDACTED:phone_ip]', 56602): b'M-SEARCH * HTTP/1.1\r\nHOST: 239.255.255.250:1900\r\nMAN: "ssdp:discover"\r\nMX: 1\r\nST: urn:dial-multiscreen-org:service:dial:1\r\n\r\n'
2022-11-26 11:08:30.294 DEBUG (MainThread) [async_upnp_client.server] Received M-SEARCH from: ('[REDACTED:phone_ip]', 56602), headers: {'HOST': '239.255.255.250:1900', 'MAN': '"ssdp:discover"', 'MX': '1', 'ST': 'urn:dial-multiscreen-org:service:dial:1', '_timestamp': datetime.datetime(2022, 11, 26, 11, 8, 30, 293713), '_host': '[REDACTED:phone_ip]', '_port': 56602, '_local_addr': ('0.0.0.0', 1900), '_remote_addr': ('[REDACTED:phone_ip]', 56602)}
2022-11-26 11:08:30.294 DEBUG (MainThread) [async_upnp_client.server] Sending search response, ST: upnp:rootdevice, USN: UUID:F9EE5710-C694-48B9-BF1A-541D13160930::upnp:rootdevice,
2022-11-26 11:08:30.295 DEBUG (MainThread) [async_upnp_client.server] Sending SSDP packet, transport: None, socket: <socket.socket fd=22, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 47454)>, target: ('[REDACTED:phone_ip]', 56602)
2022-11-26 11:08:30.295 DEBUG (MainThread) [async_upnp_client.traffic.ssdp] Sending SSDP packet, target: ('[REDACTED:phone_ip]', 56602), data: b'HTTP/1.1 200 OK\r\nCACHE-CONTROL:max-age=1800\r\nDATE:Sat, 26 Nov 2022 10:08:30 GMT\r\nSERVER:async-upnp-client/0.32.2 UPnP/2.0 Server/1.0\r\nST:upnp:rootdevice\r\nUSN:UUID:F9EE5710-C694-48B9-BF1A-541D13160930::upnp:rootdevice\r\nEXT:\r\nLOCATION:http://[REDACTED:home_assistant_ip]:40000/device.xml\r\nBOOTID.UPNP.ORG:1669456490\r\nCONFIGID.UPNP.ORG:1\r\n\r\n'
```

When force stopping companion app and restarting it I noticed this in the core log: ('push_websocket_channel': True)
```
2022-11-26 11:30:10.183 DEBUG (MainThread) [homeassistant.components.webhook] Handling webhook POST payload for 69aa0ddf4ca5a638c4aeccf48b5e9de650a829b14a3579a4eddf8a7612588b2e
2022-11-26 11:30:10.183 DEBUG (MainThread) [homeassistant.components.mobile_app.webhook] Received webhook payload from SM-G780G for type get_config: {}
2022-11-26 11:30:10.186 DEBUG (MainThread) [homeassistant.components.webhook] Handling webhook POST payload for 69aa0ddf4ca5a638c4aeccf48b5e9de650a829b14a3579a4eddf8a7612588b2e
2022-11-26 11:30:10.187 DEBUG (MainThread) [homeassistant.components.mobile_app.webhook] Received webhook payload from SM-G780G for type update_registration: {'app_version': '2022.11.0-full (2948)', 'device_name': 'SM-G780G', 'manufacturer': 'samsung', 'model': 'SM-G780G', 'os_version': '31', 'app_data': {'push_websocket_channel': True}}
```

Companion log:
[homeassistant_companion_log_10-26-2022_10-51-21.txt](https://github.com/home-assistant/android/files/10096037/homeassistant_companion_log_10-26-2022_10-51-21.txt)

**Comment by dshokouhi** [comment]
here is the actual issue:

```
11-26 10:51:12.198 31426 31456 E FirebaseMessaging: Topic sync or token retrieval failed on hard failure exceptions: java.util.concurrent.ExecutionException: java.io.IOException: SERVICE_NOT_AVAILABLE. Won't retry the operation.
11-26 10:51:12.199 31426 31466 E MessagingToken: Issue getting token
11-26 10:51:12.199 31426 31466 E MessagingToken: java.io.IOException: java.util.concurrent.ExecutionException: java.io.IOException: SERVICE_NOT_AVAILABLE
11-26 10:51:12.199 31426 31466 E MessagingToken: 	at com.google.firebase.messaging.FirebaseMessaging.blockingGetToken(FirebaseMessaging.java:625)
11-26 10:51:12.199 31426 31466 E MessagingToken: 	at com.google.firebase.messaging.FirebaseMessaging.lambda$getToken$4$com-google-firebase-messaging-FirebaseMessaging(FirebaseMessaging.java:392)
11-26 10:51:12.199 31426 31466 E MessagingToken: 	at com.google.firebase.messaging.FirebaseMessaging$$ExternalSyntheticLambda10.run(Unknown Source:4)
11-26 10:51:12.199 31426 31466 E MessagingToken: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
11-26 10:51:12.199 31426 31466 E MessagingToken: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
11-26 10:51:12.199 31426 31466 E MessagingToken: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
11-26 10:51:12.199 31426 31466 E MessagingToken: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
11-26 10:51:12.199 31426 31466 E MessagingToken: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
11-26 10:51:12.199 31426 31466 E MessagingToken: 	at com.google.android.gms.common.util.concurrent.zza.run(com.google.android.gms:play-services-basement@@18.1.0:2)
11-26 10:51:12.199 31426 31466 E MessagingToken: 	at java.lang.Thread.run(Thread.java:1012)
11-26 10:51:12.199 31426 31466 E MessagingToken: Caused by: java.util.concurrent.ExecutionException: java.io.IOException: SERVICE_NOT_AVAILABLE
11-26 10:51:12.199 31426 31466 E MessagingToken: 	at com.google.android.gms.tasks.Tasks.zza(com.google.android.gms:play-services-tasks@@18.0.2:5)
11-26 10:51:12.199 31426 31466 E MessagingToken: 	at com.google.android.gms.tasks.Tasks.await(com.google.android.gms:play-services-tasks@@18.0.2:8)
11-26 10:51:12.199 31426 31466 E MessagingToken: 	at com.google.firebase.messaging.FirebaseMessaging.blockingGetToken(FirebaseMessaging.java:623)
11-26 10:51:12.199 31426 31466 E MessagingToken: 	... 9 more
11-26 10:51:12.199 31426 31466 E MessagingToken: Caused by: java.io.IOException: SERVICE_NOT_AVAILABLE
11-26 10:51:12.199 31426 31466 E MessagingToken: 	at com.google.firebase.messaging.GmsRpc.handleResponse(GmsRpc.java:309)
11-26 10:51:12.199 31426 31466 E MessagingToken: 	at com.google.firebase.messaging.GmsRpc.lambda$extractResponseWhenComplete$0$com-google-firebase-messaging-GmsRpc(GmsRpc.java:320)
11-26 10:51:12.199 31426 31466 E MessagingToken: 	at com.google.firebase.messaging.GmsRpc$$ExternalSyntheticLambda0.then(Unknown Source:2)
11-26 10:51:12.199 31426 31466 E MessagingToken: 	at com.google.android.gms.tasks.zzc.run(com.google.android.gms:play-services-tasks@@18.0.2:3)
11-26 10:51:12.199 31426 31466 E MessagingToken: 	at androidx.profileinstaller.ProfileInstallReceiver$$ExternalSyntheticLambda0.execute(Unknown Source:0)
11-26 10:51:12.199 31426 31466 E MessagingToken: 	at com.google.android.gms.tasks.zzd.zzd(com.google.android.gms:play-services-tasks@@18.0.2:1)
11-26 10:51:12.199 31426 31466 E MessagingToken: 	at com.google.android.gms.tasks.zzr.zzb(com.google.android.gms:play-services-tasks@@18.0.2:5)
11-26 10:51:12.199 31426 31466 E MessagingToken: 	at com.google.android.gms.tasks.zzw.zzb(com.google.android.gms:play-services-tasks@@18.0.2:3)
11-26 10:51:12.199 31426 31466 E MessagingToken: 	at com.google.android.gms.tasks.zzc.run(com.google.android.gms:play-services-tasks@@18.0.2:8)
11-26 10:51:12.199 31426 31466 E MessagingToken: 	at com.google.android.gms.cloudmessaging.zzz.execute(Unknown Source:0)
11-26 10:51:12.199 31426 31466 E MessagingToken: 	at com.google.android.gms.tasks.zzd.zzd(com.google.android.gms:play-services-tasks@@18.0.2:1)
11-26 10:51:12.199 31426 31466 E MessagingToken: 	at com.google.android.gms.tasks.zzr.zzb(com.google.android.gms:play-services-tasks@@18.0.2:5)
11-26 10:51:12.199 31426 31466 E MessagingToken: 	at com.google.android.gms.tasks.zzw.zzb(com.google.android.gms:play-services-tasks@@18.0.2:3)
11-26 10:51:12.199 31426 31466 E MessagingToken: 	at com.google.android.gms.tasks.TaskCompletionSource.setResult(com.google.android.gms:play-services-tasks@@18.0.2:1)
11-26 10:51:12.199 31426 31466 E MessagingToken: 	at com.google.android.gms.cloudmessaging.zzp.zzd(com.google.android.gms:play-services-cloud-messaging@@17.0.0:3)
11-26 10:51:12.199 31426 31466 E MessagingToken: 	at com.google.android.gms.cloudmessaging.zzr.zza(com.google.android.gms:play-services-cloud-messaging@@17.0.0:2)
11-26 10:51:12.199 31426 31466 E MessagingToken: 	at com.google.android.gms.cloudmessaging.zzf.handleMessage(com.google.android.gms:play-services-cloud-messaging@@17.0.0:14)
11-26 10:51:12.199 31426 31466 E MessagingToken: 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-26 10:51:12.199 31426 31466 E MessagingToken: 	at android.os.Looper.loopOnce(Looper.java:226)
11-26 10:51:12.199 31426 31466 E MessagingToken: 	at android.os.Looper.loop(Looper.java:313)
11-26 10:51:12.199 31426 31466 E MessagingToken: 	at android.app.ActivityThread.main(ActivityThread.java:8751)
11-26 10:51:12.199 31426 31466 E MessagingToken: 	at java.lang.reflect.Method.invoke(Native Method)
11-26 10:51:12.199 31426 31466 E MessagingToken: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
11-26 10:51:12.199 31426 31466 E MessagingToken: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

```

anything special about your device? Is it stock ROM or custom ROM?

We need to solve this issue but unfortunately the app can't really solve an error that says `SERVICE_NOT_AVAILABLE`.  As you say this doesn't happen all the time maybe try to think of when it does happen? Like when you are on VPN or something for example. Something could be blocked somewhere.

**Comment by szerencl** [comment]
It might be an issue with pihole then. I remember  adding some new adlists, one might be blocking firebase.
But it's weird because the other 2 phones are also using pihole as their DNS.
Firebase goes through google analytics right?

```
pihole -w www.google-analytics.com
pihole -w ssl.google-analytics.com
```

**Comment by dshokouhi** [comment]
run a quick test.....disable pi hole....force stop and open the app....does the issue still occur?

**Comment by szerencl** [comment]
It works both with and without pihole,
