### ISSUE TITLE
App crash in Studio Code Server when downloading

### ISSUE THREAD

**Issue by large** [home-assistant/android#3098]
**Home Assistant Android version:**

**Android version:**
2022-11.0-full

**Phone model: **
Pixel 4a

**Home Assistant version:**
Home Assistant 2022.11.3
Supervisor 2022.11.2
Operating System 9.3
Frontend 20221108.0 - latest

**Last working Home Assistant release (if known):**
Unknown

**Description of problem:**
When you press download on a file in Studio Code Server, the app crash. Works in browser. 

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**
NA

**Screenshot of problem:**
NA

**Additional information:**
Viewing content on mobile does not work well, so download is a nice feature to have.

**Comment by SkechyWolf** [comment]
I was able to reproduce this error
<details>
<summary>Error</summary>
<br>
FATAL EXCEPTION: main
                                                                                                    Process: io.homeassistant.companion.android, PID: 22196
                                                                                                    android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=blob:http://192.168.254.101:8123/4a9c2f07-8874-4f2e-902a-8d1a374cf2a9 }
                                                                                                    	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2080)
                                                                                                    	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1727)
                                                                                                    	at android.app.Activity.startActivityForResult(Activity.java:5377)
                                                                                                    	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:728)
                                                                                                    	at android.app.Activity.startActivityForResult(Activity.java:5335)
                                                                                                    	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:709)
                                                                                                    	at android.app.Activity.startActivity(Activity.java:5721)
                                                                                                    	at android.app.Activity.startActivity(Activity.java:5674)
                                                                                                    	at io.homeassistant.companion.android.webview.WebViewActivity.downloadFile(WebViewActivity.kt:1349)
                                                                                                    	at io.homeassistant.companion.android.webview.WebViewActivity.onCreate$lambda$6$lambda$5(WebViewActivity.kt:430)
                                                                                                    	at io.homeassistant.companion.android.webview.WebViewActivity.$r8$lambda$u2piykWPVf4UoVYNCRav12qSxE4(Unknown Source:0)
                                                                                                    	at io.homeassistant.companion.android.webview.WebViewActivity$$ExternalSyntheticLambda0.onDownloadStart(Unknown Source:9)
                                                                                                    	at la.handleMessage(chromium-TrichromeWebViewGoogle.aab-stable-530410533:522)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:246)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8550)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
</details>

**Comment by jpelgrom** [comment]
So it looks like there's two parts to this:

1. The app crashes when the system doesn't know how to handle the URL. This is easy to fix.

2. This is a blob URL, which only works in the current browser. That means the app can't download it outside the webview like it does for other downloads.
However, I don't think it is possible to download this with JS inside the webview as it counts as a navigation event (which is restricted). Trying to download the file with JS after receiving the event in the listener ([inspired by this](https://stackoverflow.com/questions/72181133/how-to-download-blob-url-in-webview)) results in 404 not found messages- at least for VS Code Server - as the URL is probably revoked by the time the app receives the event.
Adding to that the app also is unable to get filename/filetype information which is usually added as a `download` attribute but not forwarded to the app by the webview. If blob url downloads would work, this would limit the usefulness.

Suggested fix:

1. Add a check to prevent the crash.

2. Don't support blob URLs in the app and display an unsupported message. If it isn't possible to get this to work in the app without workarounds that may not be reliable, it's better to use a browser.
