### ISSUE TITLE
HA on Wear OS not working anymore after domain change

### ISSUE THREAD

**Issue by dd-gamer** [home-assistant/android#3138]
**Home Assistant Android version:**
2022.11.0-full
**Android version:**
13
**Phone model:**
Pixel 6
**Home Assistant version:**
2022.11.5
**Last working Home Assistant release (if known):**
2022.10
**Description of problem:**
I can't connect to HomeAssistant via smartwatch anymore. I own the pixel watch, everything was working fine until I updated HomeAssistant, which is running inside Docker on a Pi 4. At the same time, I canceled my cloud subscription. My instance is running behind a reverse proxy with ssl encryption, so there was no need anymore for the nabu casa service, which was running slower than my normal instance. Anyway, with the switch to a new url, the smartwatch won't update. I tried to reinstall the app on the watch (even on the phone) and it still remembers the nabu casa instance. When I select "enter address manually" it forwards me to my phone, where I can go through the setup. First I select my instance, then it guides me to the login, afterwards it asks for a device name and then goes back to the "wear device settings" page, where it offers me to setup my wear os device. From here on, this can go endless without any change on the watch. 

Since there is no option to delete the device inside HomeAssistant, I first tried to disable the device and run through the process again, then I manually searched for every pixel watch related entry in the database and removed it. Both attempts failed.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**
If you tell me how I can access these on wear os, I'll add them asap.
```

```

**Screenshot of problem:**

**Additional information:**

**Comment by jpelgrom** [comment]
Did you log out of your Home Assistant Cloud account after cancelling? If not, the Wear app will try to switch to it (issue #3074, fixed in core 2022.12).

**Comment by dshokouhi** [comment]
Can you try disablign bluetooth and leaving wifi on to see if it can connect?

**Comment by dd-gamer** [comment]
In doing so, I could enter the url on the watch, but it won't redirect to the login screen. After connecting Bluetooth again, it now remembers the last instance, that guides my phone directly to the login screen, but afterwards still no update on the watch.

**Comment by jpelgrom** [comment]
> it now remembers the last instance

The watch should show the instance your phone is currently logged in to.

Could you try opening the app on your watch first, then opening the phone app and going to Settings > Companion app > Wear OS > Log in, and enter your instance manually? That way it shouldn't automatically try to do anything.

**Comment by dd-gamer** [comment]
Sure thing. When I go that way, it guides me through all steps again (instance, login, device name) and back to the "login on wear os device" page. No change on the watch however..

**Comment by dshokouhi** [comment]
are you familiar with `logcat` ? That would allow us to get logs off the watch to see why it is failing to login. Android studio would probably be the easiest way to get the logs. 

https://developer.android.com/training/wearables/get-started/debugging

Once connected reproduce the issue and you should see the error and we can determine what is going on.

**Comment by dd-gamer** [comment]
It takes a little longer than expected. After installing Android studio, the watch did not wanted to connect to wifi and now its taking ages to restart. Since it's already pretty late in central europe, I'm gonna call it a day and come back to this tomorrow after work. But thanks for the quick responses so far!

**Comment by dd-gamer** [comment]
I got some logs:

`2022-12-07 13:41:52.010 3773-3773/? E/PhoneSettingsListener: Unable to login to Home Assistant
    javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:362)
        at com.android.org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1134)
        at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1089)
        at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:876)
        at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747)
        at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712)
        at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:849)
        at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.access$100(ConscryptEngineSocket.java:722)
        at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:238)
        at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:217)
        at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
        at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
        at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:661)
        at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:510)
        at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:428)
        at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:356)
        at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
        at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:90)
        at com.android.org.conscrypt.ConscryptEngineSocket$2.checkServerTrusted(ConscryptEngineSocket.java:161)
        at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:250)
        at com.android.org.conscrypt.ConscryptEngine.verifyCertificateChain(ConscryptEngine.java:1644)
        at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
        at com.android.org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:568)
        at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1095)
2022-12-07 13:41:52.012 3773-3773/? E/PhoneSettingsListener:     at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1079)
        	... 27 more
     Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        	... 40 more`


As far as I would interpret these logs, it seems there is an issue verifying the certificate.
The certificate is from Let's Encrypt and valid until end of January. HomeAssistant runs under a subdomain, but the certificate includes wildcards.

**Comment by dshokouhi** [comment]
> As far as I would interpret these logs, it seems there is an issue verifying the certificate.
> The certificate is from Let's Encrypt and valid until end of January. HomeAssistant runs under a subdomain, but the certificate includes wildcards.

Yes there is indeed a SSL handshake issue. Unfortunately this is not an issue the app can solve even if the certificate is valid. Android devices can be picky about which certificates they trust, and this is different than what is accepted in a browser.

```
2022-12-07 13:41:52.010 3773-3773/? E/PhoneSettingsListener: Unable to login to Home Assistant
    javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
```

Please refer to this site for some tips on how to overcome this.

https://developer.android.com/training/articles/security-ssl#CommonProblems

I have seen reports from users who either regenerated the certificate or picked a different provider and it started to work for them. Personally I use certbot and never had an issue.

**Comment by dshokouhi** [comment]
Unfortunately teh app will not be able to solve this issue, SSL errors are something that gets resolved on the server end rather than the app end. You may need to research to see how to add the Trust Anchor on your device, each device is going to be different too.

**Comment by dd-gamer** [comment]
Is it possible for home assistant to add the root let's encrypt certificate to it's trusted anchors?

**Comment by dshokouhi** [comment]
no we do not do that, thats the responsibility of the user. We have code to support certificates added by the user, thats about as much as we can do.

**Comment by dd-gamer** [comment]
I fixed it now by using the Cloudflare tunnel.
