### ISSUE TITLE
Sentry websocket null pointer exception

### ISSUE THREAD

**Issue by dshokouhi** [home-assistant/android#3144]
**Home Assistant Android version:**

BETA 2982

**Android version:**

12

**Phone model:**

M2012K11G

**Home Assistant version:**

unknown

**Last working Home Assistant release (if known):**

unknown

**Description of problem:**

Found the following sentry error not sure how the error was produced, only impacting 1 user as of now

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```
java.lang.NullPointerException: null
    at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl.handleMessage(WebSocketRepositoryImpl.kt:471)
    at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl.access$handleMessage(WebSocketRepositoryImpl.kt:66)
    at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl$onMessage$1$1.invokeSuspend(WebSocketRepositoryImpl.kt:617)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
    at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Screenshot of problem:**

**Additional information:**

**Comment by jpelgrom** [comment]
This crash suggests it receives a message without an ID, would be useful to know in response to what command it is 🤔

https://github.com/home-assistant/android/blob/956b26cc99d1d0d4aa574efe0fc7736465f8087b/common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt#L471

**Comment by jpelgrom** [comment]
@dshokouhi Has this issue been reported in Sentry more than once by now? If it is we could add a null check, but otherwise it was probably just a random connection-specific issue.

**Comment by dshokouhi** [comment]
nope still the same device and only 2 reports, Will close this issue now :)
