### ISSUE TITLE
Error Handling Message - Websocket API - Android Beta

### ISSUE THREAD

**Issue by rjenx** [home-assistant/android#3148]
**Home Assistant Android version:**
Version beta 2982-956b26cc-full
**Android version:**
12
**Phone model:**
One+9 
**Home Assistant version:**
Home Assistant 2022.11.5
Supervisor 2022.11.2
Operating System 9.3
Frontend 20221108.0 - latest
**Last working Home Assistant release (if known):**
Unknown
**Description of problem:**
Android app reconnects to HA Server triggering an error in the HA logs 

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**
[android app log.txt](https://github.com/home-assistant/android/files/10205488/android.app.log.txt)

```
Log from Home Assistant Server

Logger: homeassistant.components.websocket_api.http.connection
Source: helpers/entity.py:673
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 11 December 2022 at 14:45:23 (10 occurrences)
Last logged: 07:21:35

[547686716208] Error handling message: Unknown error (unknown_error) from 192.168.1.40 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36)
[547562161152] Error handling message: Unknown error (unknown_error) from 127.0.0.1 (Mozilla/5.0 (Linux; Android 12; LE2123 Build/RKQ1.211119.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/107.0.5304.141 Mobile Safari/537.36 Home Assistant/beta-2982-956b26cc-2982 (Android 12; LE2123))
[548257075200] Error handling message: Unknown error (unknown_error) from 192.168.1.40 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36)
[547661094656] Error handling message: Unknown error (unknown_error) from 192.168.1.40 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36)
[547544671152] Error handling message: Unknown error (unknown_error) from 192.168.1.40 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 102, in async_handle
    handler(self.hass, self, schema(msg))
  File "/config/custom_components/browser_mod/connection.py", line 44, in handle_update
    devices[deviceID].update(msg.get("data", None))
  File "/config/custom_components/browser_mod/connection.py", line 108, in update
    self.screen.data = data.get("screen")
  File "/config/custom_components/browser_mod/helpers.py", line 106, in data
    self.updated()
  File "/config/custom_components/browser_mod/light.py", line 28, in updated
    self.schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 673, in schedule_update_ha_state
    self.hass.add_job(self.async_update_ha_state(force_refresh))
AttributeError: 'NoneType' object has no attribute 'add_job'
```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
This error is related to a custom integration for browser mod. Please open an issue in that repo.
