### ISSUE TITLE
Wear OS app crash when trying to login.

### ISSUE THREAD

**Issue by xrh0905** [home-assistant/android#3242]
**Home Assistant Android version:**
v2022.12.0
**Android version:**
Wear OS by Google 2.27
**Phone model:**
Mi Watch (XMWT01)
**Home Assistant version:**
v2023.01.05
**Last working Home Assistant release (if known):**

**Description of problem:**
App crash after click login.
**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```
01-19 15:22:47.036  3761  3761 E AndroidRuntime: FATAL EXCEPTION: main
01-19 15:22:47.036  3761  3761 E AndroidRuntime: Process: io.homeassistant.companion.android, PID: 3761
01-19 15:22:47.036  3761  3761 E AndroidRuntime: java.lang.IllegalArgumentException: The 'redirect_uri' query param already exists in the authProviderUrl, expect to have the value of 'https://wear.googleapis-cn.com/3p_auth/io.homeassistant.companion.android', but 'https://wear.googleapis.com/3p_auth/io.homeassistant.companion.android' is given. Please correct it,  or leave it out to allow the request builder to append it automatically.
01-19 15:22:47.036  3761  3761 E AndroidRuntime:        at androidx.wear.phone.interactions.authentication.OAuthRequest$Builder.appendQueryParameter(OAuthRequest.kt:183)
01-19 15:22:47.036  3761  3761 E AndroidRuntime:        at androidx.wear.phone.interactions.authentication.OAuthRequest$Builder.composeRequestUrl$wear_phone_interactions_release(OAuthRequest.kt:146)
01-19 15:22:47.036  3761  3761 E AndroidRuntime:        at androidx.wear.phone.interactions.authentication.OAuthRequest$Builder.build(OAuthRequest.kt:197)
01-19 15:22:47.036  3761  3761 E AndroidRuntime:        at io.homeassistant.companion.android.onboarding.manual_setup.ManualSetupPresenterImpl$onNextClicked$1.invokeSuspend(ManualSetupPresenterImpl.kt:52)
01-19 15:22:47.036  3761  3761 E AndroidRuntime:        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
01-19 15:22:47.036  3761  3761 E AndroidRuntime:        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
01-19 15:22:47.036  3761  3761 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:873)
01-19 15:22:47.036  3761  3761 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
01-19 15:22:47.036  3761  3761 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
01-19 15:22:47.036  3761  3761 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6680)
01-19 15:22:47.036  3761  3761 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
01-19 15:22:47.036  3761  3761 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:506)
01-19 15:22:47.036  3761  3761 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:960)
01-19 15:22:47.036  3761  3761 E AndroidRuntime:        Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@7c8892f, Dispatchers.Main]
01-19 15:22:47.055  1641 27777 W ActivityManager:   Force finishing activity io.homeassistant.companion.android/.onboarding.manual_setup.ManualSetupActivity
01-19 15:22:47.067  1641 27777 W ActivityManager:   Force finishing activity io.homeassistant.companion.android/.onboarding.OnboardingActivity
01-19 15:22:47.146  1641  1658 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
01-19 15:22:47.146  1641  1658 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
01-19 15:22:47.180  3761  3761 I Process : Sending signal. PID: 3761 SIG: 9
01-19 15:22:47.253  1641  1729 W InputDispatcher: channel 'c54427d io.homeassistant.companion.android/io.homeassistant.companion.android.onboarding.manual_setup.ManualSetupActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
01-19 15:22:47.253  1641  1729 E InputDispatcher: channel 'c54427d io.homeassistant.companion.android/io.homeassistant.companion.android.onboarding.manual_setup.ManualSetupActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
01-19 15:22:47.254  1641  1729 W InputDispatcher: channel '8e4c20c io.homeassistant.companion.android/io.homeassistant.companion.android.onboarding.OnboardingActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
01-19 15:22:47.254  1641  1729 E InputDispatcher: channel '8e4c20c io.homeassistant.companion.android/io.homeassistant.companion.android.onboarding.OnboardingActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
01-19 15:22:47.263  1641 24353 I WindowManager: WIN DEATH: Window{8e4c20c u0 io.homeassistant.companion.android/io.homeassistant.companion.android.onboarding.OnboardingActivity}
01-19 15:22:47.264  1641 24353 W InputDispatcher: Attempted to unregister already unregistered input channel '8e4c20c io.homeassistant.companion.android/io.homeassistant.companion.android.onboarding.OnboardingActivity (server)'
01-19 15:22:47.265  1641  1661 W libprocessgroup: kill(-3761, 9) failed: No such process
01-19 15:22:47.266   438   438 I Zygote  : Process 3761 exited due to signal (9)
01-19 15:22:47.266  1641  1661 I libprocessgroup: Successfully killed process cgroup uid 10107 pid 3761 in 1ms
01-19 15:22:47.282  1641 24662 I ActivityManager: Process io.homeassistant.companion.android (pid 3761) has died: vis  TOP
01-19 15:22:47.294  1641 27777 I WindowManager: WIN DEATH: Window{c54427d u0 io.homeassistant.companion.android/io.homeassistant.companion.android.onboarding.manual_setup.ManualSetupActivity}
01-19 15:22:47.294  1641 27777 W InputDispatcher: Attempted to unregister already unregistered input channel 'c54427d io.homeassistant.companion.android/io.homeassistant.companion.android.onboarding.manual_setup.ManualSetupActivity (server)'
01-19 15:22:47.327   543  2235 W SurfaceFlinger: Attempting to destroy on removed layer: AppWindowToken{dbca32d token=Token{3335644 ActivityRecord{f0d1b57 u0 io.homeassistant.companion.android/.onboarding.OnboardingActivity t8553}}}#0
01-19 15:22:47.327   543  2235 W SurfaceFlinger: Attempting to destroy on removed layer: AppWindowToken{fe050e6 token=Token{470b341 ActivityRecord{9740a28 u0 io.homeassistant.companion.android/.onboarding.manual_setup.ManualSetupActivity t8553}}}#0
01-19 15:22:47.363  2128  2128 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1005 android.content.ContextWrapper.sendBroadcast:444 android.support.wearable.watchface.c$a.onVisibilityChanged:48 android.support.wearable.watchface.a$a.onVisibilityChanged:0 c.b.a.a.a.j.b$b.onVisibilityChanged:0
01-19 15:22:47.391  1641 27777 E ActivityManager: Sending non-protected broadcast com.google.android.wearable.watchfaces.action.REQUEST_STATE from system 2128:com.xiaomi.wear.watchface.album/1000 pkg com.xiaomi.wear.watchface.album
01-19 15:22:47.391  1641 27777 E ActivityManager: java.lang.Throwable
01-19 15:22:47.391  1641 27777 E ActivityManager:       at com.android.server.am.ActivityManagerService.checkBroadcastFromSystem(ActivityManagerService.java:21450)
01-19 15:22:47.391  1641 27777 E ActivityManager:       at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:21963)
01-19 15:22:47.391  1641 27777 E ActivityManager:       at com.android.server.am.ActivityManagerService.broadcastIntent(ActivityManagerService.java:22232)
01-19 15:22:47.391  1641 27777 E ActivityManager:       at android.app.IActivityManager$Stub.onTransact$broadcastIntent$(IActivityManager.java:10177)
01-19 15:22:47.391  1641 27777 E ActivityManager:       at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:167)
01-19 15:22:47.391  1641 27777 E ActivityManager:       at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3323)
01-19 15:22:47.391  1641 27777 E ActivityManager:       at android.os.Binder.execTransact(Binder.java:731)
01-19 15:22:47.403  1641 27777 E ActivityManager: Sending non-protected broadcast com.google.android.wearable.watchfaces.action.REQUEST_STATE from system 2128:com.xiaomi.wear.watchface.album/1000 pkg com.xiaomi.wear.watchface.album
01-19 15:22:47.403  1641 27777 E ActivityManager: java.lang.Throwable
01-19 15:22:47.403  1641 27777 E ActivityManager:       at com.android.server.am.ActivityManagerService.checkBroadcastFromSystem(ActivityManagerService.java:21450)
01-19 15:22:47.403  1641 27777 E ActivityManager:       at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:22056)
01-19 15:22:47.403  1641 27777 E ActivityManager:       at com.android.server.am.ActivityManagerService.broadcastIntent(ActivityManagerService.java:22232)
01-19 15:22:47.403  1641 27777 E ActivityManager:       at android.app.IActivityManager$Stub.onTransact$broadcastIntent$(IActivityManager.java:10177)
01-19 15:22:47.403  1641 27777 E ActivityManager:       at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:167)
01-19 15:22:47.403  1641 27777 E ActivityManager:       at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3323)
01-19 15:22:47.403  1641 27777 E ActivityManager:       at android.os.Binder.execTransact(Binder.java:731)
01-19 15:22:47.411  1641  1666 W ActivityManager: setHasOverlayUi called on unknown pid: 3761
01-19 15:22:47.419  1641  1658 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
01-19 15:22:47.423  1641  1658 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
01-19 15:22:47.441  1641  1658 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
01-19 15:22:47.441  2128  2128 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1005 android.content.ContextWrapper.sendBroadcast:444 android.support.wearable.watchface.c$a.onVisibilityChanged:48 android.support.wearable.watchface.a$a.onVisibilityChanged:0 c.b.a.a.a.j.b$b.onVisibilityChanged:0
01-19 15:22:47.442  1641  1658 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
01-19 15:22:47.444  1641  2472 E ActivityManager: Sending non-protected broadcast com.google.android.wearable.watchfaces.action.REQUEST_STATE from system 2128:com.xiaomi.wear.watchface.album/1000 pkg com.xiaomi.wear.watchface.album
01-19 15:22:47.444  1641  2472 E ActivityManager: java.lang.Throwable
01-19 15:22:47.444  1641  2472 E ActivityManager:       at com.android.server.am.ActivityManagerService.checkBroadcastFromSystem(ActivityManagerService.java:21450)
01-19 15:22:47.444  1641  2472 E ActivityManager:       at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:21963)
01-19 15:22:47.444  1641  2472 E ActivityManager:       at com.android.server.am.ActivityManagerService.broadcastIntent(ActivityManagerService.java:22232)
01-19 15:22:47.444  1641  2472 E ActivityManager:       at android.app.IActivityManager$Stub.onTransact$broadcastIntent$(IActivityManager.java:10177)
01-19 15:22:47.444  1641  2472 E ActivityManager:       at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:167)
01-19 15:22:47.444  1641  2472 E ActivityManager:       at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3323)
01-19 15:22:47.444  1641  2472 E ActivityManager:       at android.os.Binder.execTransact(Binder.java:731)
01-19 15:22:47.456  1641  2472 E ActivityManager: Sending non-protected broadcast com.google.android.wearable.watchfaces.action.REQUEST_STATE from system 2128:com.xiaomi.wear.watchface.album/1000 pkg com.xiaomi.wear.watchface.album
01-19 15:22:47.456  1641  2472 E ActivityManager: java.lang.Throwable
01-19 15:22:47.456  1641  2472 E ActivityManager:       at com.android.server.am.ActivityManagerService.checkBroadcastFromSystem(ActivityManagerService.java:21450)
01-19 15:22:47.456  1641  2472 E ActivityManager:       at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:22056)
01-19 15:22:47.456  1641  2472 E ActivityManager:       at com.android.server.am.ActivityManagerService.broadcastIntent(ActivityManagerService.java:22232)
01-19 15:22:47.456  1641  2472 E ActivityManager:       at android.app.IActivityManager$Stub.onTransact$broadcastIntent$(IActivityManager.java:10177)
01-19 15:22:47.456  1641  2472 E ActivityManager:       at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:167)
01-19 15:22:47.456  1641  2472 E ActivityManager:       at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3323)
01-19 15:22:47.456  1641  2472 E ActivityManager:       at android.os.Binder.execTransact(Binder.java:731)
01-19 15:22:47.467  1641  1658 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
01-19 15:22:47.467  1641  1658 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
01-19 15:22:47.471  1641  1658 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
01-19 15:22:47.484  1641  1658 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
^C
```

**Screenshot of problem:**
I tried but I can't get a screenshot because it crash immediately after I click login.
**Additional information:**

**Comment by dshokouhi** [comment]
Are you certain this is an actual Wear OS device and not some android fork by Xiaomi? I did not know they made an actual Wear OS device.

This error is very strange, almost seems like an API issue from the watch as the URL I think is taken from the library that we use.

Have you tried logging in using the phone app? Settings > Companion App > Wear OS > login

**Comment by jpelgrom** [comment]
The Wear app currently is hardcoded to use a constant [for OAuth redirects, non-China version](https://developer.android.com/reference/androidx/wear/phone/interactions/authentication/OAuthRequest#WEAR_REDIRECT_URL_PREFIX()):

https://github.com/home-assistant/android/blob/5cd74c0179f13b617de517273ec860215a8259ba/wear/src/main/java/io/homeassistant/companion/android/onboarding/manual_setup/ManualSetupPresenterImpl.kt#L47

I'll see if I can use the builder pattern here where Google automatically inserts the 'correct' URL.

**Comment by xrh0905** [comment]
Thanks!
