### ISSUE TITLE
command_activity fails to send intents

### ISSUE THREAD

**Issue by InseiRobin** [home-assistant/android#3271]
**Home Assistant Android version:**
December 22nd
**Android version:**
11
**Phone model:**
Xiaomi Poco X3 Pro
**Home Assistant version:**
Home Assistant 2022.8.5
Frontend 20220802.0 - latest 
**Last working Home Assistant release (if known):**

**Description of problem:**
I have an automation that makes the companion send intents to android. It is failing, I think it is related to this post:
https://stackoverflow.com/questions/72183885/intent-resolveactivity-returns-null-on-android-intent-action-open-document-in-ap
**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**
```
2023-01-25 23:38:36.122 1846-3669/? W/ActivityTaskManager: aInfo is null for resolve intent: Intent { act=android.intent.action.SET_TIMER flg=0x10000000 pkg=com.google.android.deskclock (has extras) }
2023-01-25 23:38:36.122 1846-3669/? W/ActivityTaskManagerServiceInjector: Intent or aInfo is null!
2023-01-25 23:38:36.122 1846-3669/? I/ActivityTaskManager: START u0 {act=android.intent.action.SET_TIMER flg=0x10000000 pkg=com.google.android.deskclock (has extras)} from uid 10327
2023-01-25 23:38:36.122 1846-2021/? D/EventSequenceValidator: IntentStarted during UNKNOWN. Intent { act=android.intent.action.SET_TIMER flg=0x10000000 pkg=com.google.android.deskclock (has extras) }
    java.lang.Throwable: EventSequenceValidator#getStackTrace
        at com.google.android.startop.iorap.EventSequenceValidator.logWarningWithStackTrace(EventSequenceValidator.java:260)
        at com.google.android.startop.iorap.EventSequenceValidator.onIntentStarted(EventSequenceValidator.java:106)
        at com.android.server.wm.LaunchObserverRegistryImpl.handleOnIntentStarted(LaunchObserverRegistryImpl.java:139)
        at com.android.server.wm.LaunchObserverRegistryImpl.lambda$veRn_GhgLZLlOHOJ0ZYT6KcfYqo(Unknown Source:0)
        at com.android.server.wm.-$$Lambda$LaunchObserverRegistryImpl$veRn_GhgLZLlOHOJ0ZYT6KcfYqo.accept(Unknown Source:10)
        at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:292)
        at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:201)
        at com.android.internal.util.function.pooled.OmniFunction.run(OmniFunction.java:97)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:236)
        at android.os.HandlerThread.run(HandlerThread.java:67)
        at com.android.server.ServiceThread.run(ServiceThread.java:45)
2023-01-25 23:38:36.122 1846-2021/? D/EventSequenceValidator: inc AccIntentStartedEvents to 2
2023-01-25 23:38:36.123 1846-2021/? D/EventSequenceValidator: onIntentFailed during UNKNOWN.
    java.lang.Throwable: EventSequenceValidator#getStackTrace
        at com.google.android.startop.iorap.EventSequenceValidator.logWarningWithStackTrace(EventSequenceValidator.java:260)
        at com.google.android.startop.iorap.EventSequenceValidator.onIntentFailed(EventSequenceValidator.java:130)
        at com.android.server.wm.LaunchObserverRegistryImpl.handleOnIntentFailed(LaunchObserverRegistryImpl.java:147)
        at com.android.server.wm.LaunchObserverRegistryImpl.lambda$KukKmVpn5W_1xSV6Dnp8wW2H2Ks(Unknown Source:0)
        at com.android.server.wm.-$$Lambda$LaunchObserverRegistryImpl$KukKmVpn5W_1xSV6Dnp8wW2H2Ks.accept(Unknown Source:2)
        at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:264)
        at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:201)
        at com.android.internal.util.function.pooled.OmniFunction.run(OmniFunction.java:97)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:236)
        at android.os.HandlerThread.run(HandlerThread.java:67)
        at com.android.server.ServiceThread.run(ServiceThread.java:45)
2023-01-25 23:38:36.123 1846-2021/? D/EventSequenceValidator: dec AccIntentStartedEvents to 1
2023-01-25 23:38:36.124 18921-19018/? E/MessagingService: Unable to send activity intent please check command format
    android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.SET_TIMER flg=0x10000000 pkg=com.google.android.deskclock (has extras) }
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2081)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1737)
        at android.app.ContextImpl.startActivity(ContextImpl.java:1033)
        at android.app.ContextImpl.startActivity(ContextImpl.java:1004)
        at android.content.ContextWrapper.startActivity(ContextWrapper.java:414)
        at io.homeassistant.companion.android.notifications.MessagingManager.processActivityCommand(MessagingManager.kt:2006)
        at io.homeassistant.companion.android.notifications.MessagingManager.handleDeviceCommands(MessagingManager.kt:905)
        at io.homeassistant.companion.android.notifications.MessagingManager.handleMessage(MessagingManager.kt:474)
        at io.homeassistant.companion.android.notifications.FirebaseCloudMessagingService.onMessageReceived(FirebaseCloudMessagingService.kt:38)
        at com.google.firebase.messaging.FirebaseMessagingService.dispatchMessage(FirebaseMessagingService.java:235)
        at com.google.firebase.messaging.FirebaseMessagingService.passMessageIntentToSdk(FirebaseMessagingService.java:185)
        at com.google.firebase.messaging.FirebaseMessagingService.handleMessageIntent(FirebaseMessagingService.java:172)
        at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(FirebaseMessagingService.java:161)
        at com.google.firebase.messaging.EnhancedIntentService.lambda$processIntent$0$com-google-firebase-messaging-EnhancedIntentService(EnhancedIntentService.java:78)
        at com.google.firebase.messaging.EnhancedIntentService$$ExternalSyntheticLambda0.run(Unknown Source:6)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.google.android.gms.common.util.concurrent.zza.run(com.google.android.gms:play-services-basement@@18.1.0:2)
        at java.lang.Thread.run(Thread.java:923)
2023-01-25 23:38:36.137 18921-18921/? D/CompatibilityChangeReporter: Compat change id reported: 147798919; UID 10327; state: ENABLED
2023-01-25 23:38:36.139 1846-3669/? W/AppOps: Noting op not finished: uid 10327 pkg io.homeassistant.companion.android code 1 startTime of in progress event=1674686315536
```

**Screenshot of problem:**

**Additional information:**
The automation is this:

```
alias: Test
description: ""
trigger:
  - platform: time
    at: "21:30:00"
condition: []
action:
  - service: notify.mobile_app_xiaomi_poco_x3_pro
    data:
      message: command_activity
      data:
        intent_package_name: com.google.android.deskclock
        intent_action: android.intent.action.SET_TIMER
        intent_extras: >-
          android.intent.extra.alarm.SKIP_UI:true,android.intent.extra.alarm.LENGTH:1
mode: single
```

**Comment by dshokouhi** [comment]
do you have the google clock app installed on that device? the error suggests you do not and you are targetting that specific application.

https://play.google.com/store/apps/details?id=com.google.android.deskclock&hl=en_US&gl=US

**Comment by InseiRobin** [comment]
So stupid issue... I took for granted that it was the default clock app. I had other clock app. Thank you for your time.
