### ISSUE TITLE
Wear OS home screen occasionally crashes with concurrent modification exception

### ISSUE THREAD

**Issue by dshokouhi** [home-assistant/android#3325]
**Home Assistant Android app version(s):**
latest beta for both

**Android version(s):**

Phone: 13
Watch: 11

**Device model(s):**

Pixel 7 pro
Pixel watch

**Home Assistant version:**

2023.1.x

**Last working Home Assistant release (if known):**

n/a

**Description of problem, include YAML if issue is related to notifications:**

Sometimes the wear OS app will load and then crash within a few seconds after showing the areas.

**Companion App Logs:**

```
2023-02-09 09:40:54.755 16190-16190 AndroidRuntime          io....stant.companion.android.debug  E  FATAL EXCEPTION: main
                                                                                                    Process: io.homeassistant.companion.android.debug, PID: 16190
                                                                                                    java.util.ConcurrentModificationException
                                                                                                    	at androidx.compose.runtime.snapshots.StateListIterator.validateModification(SnapshotStateList.kt:278)
                                                                                                    	at androidx.compose.runtime.snapshots.StateListIterator.next(SnapshotStateList.kt:257)
                                                                                                    	at io.homeassistant.companion.android.home.views.MainViewKt$MainView$1$3$1.invoke(MainView.kt:259)
                                                                                                    	at io.homeassistant.companion.android.home.views.MainViewKt$MainView$1$3$1.invoke(MainView.kt:76)
                                                                                                    	at androidx.wear.compose.material.ScalingLazyColumnKt$ScalingLazyColumn$1$1$2$1.invoke(ScalingLazyColumn.kt:425)
                                                                                                    	at androidx.wear.compose.material.ScalingLazyColumnKt$ScalingLazyColumn$1$1$2$1.invoke(ScalingLazyColumn.kt:410)
                                                                                                    	at androidx.compose.foundation.lazy.LazyListItemProviderKt$rememberLazyListItemProvider$1$itemProviderState$1.invoke(LazyListItemProvider.kt:53)
                                                                                                    	at androidx.compose.foundation.lazy.LazyListItemProviderKt$rememberLazyListItemProvider$1$itemProviderState$1.invoke(LazyListItemProvider.kt:52)
                                                                                                    	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2139)
                                                                                                    	at androidx.compose.runtime.DerivedSnapshotState.currentRecord(DerivedState.kt:161)
                                                                                                    	at androidx.compose.runtime.DerivedSnapshotState.getCurrentValue(DerivedState.kt:231)
                                                                                                    	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.recordInvalidation(SnapshotStateObserver.kt:419)
                                                                                                    	at androidx.compose.runtime.snapshots.SnapshotStateObserver$applyObserver$1.invoke(SnapshotStateObserver.kt:42)
                                                                                                    	at androidx.compose.runtime.snapshots.SnapshotStateObserver$applyObserver$1.invoke(SnapshotStateObserver.kt:38)
                                                                                                    	at androidx.compose.runtime.snapshots.MutableSnapshot.apply(Snapshot.kt:748)
                                                                                                    	at androidx.compose.runtime.Recomposer.applyAndCheck(Recomposer.kt:1108)
                                                                                                    	at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:1476)
                                                                                                    	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:125)
                                                                                                    	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:534)
                                                                                                    	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:503)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:34)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:727)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:223)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7651)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
                                                                                                    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@21b070f, androidx.compose.ui.platform.MotionDurationScaleImpl@642c39c, StandaloneCoroutine{Cancelling}@8af01a5, AndroidUiDispatcher@fa2297a]
```

**Screenshot or video of problem:**

**Additional information:**

This does not occur when Show Only Favorites is enabled. The problem area is suspected to be in [`updateEntityDomains`](https://github.com/home-assistant/android/blob/047abe93ba4cab1347debc5c307c55e7753880ac/wear/src/main/java/io/homeassistant/companion/android/home/MainViewModel.kt#L251) as that method is not used as often when the show only favorites option is enabled.

Using androids layout inspector I can see the recomposition counts for everything increases anytime there is any update which might be a bit inefficient

![image](https://user-images.githubusercontent.com/1634145/217905457-1aafc3d7-dc60-44fc-a84d-42886acbfd6e.png)

**Comment by dshokouhi** [comment]
Looks like this error is also in the play console. We have a few thousand users getting impacted by this. first appearance of this error is Beta 3044

**Comment by dshokouhi** [comment]
Most recent crash log

```
Exception java.util.ConcurrentModificationException:
  at androidx.compose.runtime.snapshots.StateListIterator.validateModification (SnapshotStateList.kt:295)
  at androidx.compose.runtime.snapshots.StateListIterator.next (SnapshotStateList.kt:274)
  at io.homeassistant.companion.android.home.views.MainViewKt$MainView$1$3$1.invoke (MainView.kt:382)
  at io.homeassistant.companion.android.home.views.MainViewKt$MainView$1$3$1.invoke (MainView.kt:77)
  at androidx.wear.compose.material.ScalingLazyColumnKt$ScalingLazyColumn$1$1$2$1.invoke (ScalingLazyColumn.kt:425)
  at androidx.wear.compose.material.ScalingLazyColumnKt$ScalingLazyColumn$1$1$2$1.invoke (ScalingLazyColumn.kt:410)
  at androidx.compose.foundation.lazy.LazyListItemProviderKt$rememberLazyListItemProvider$1$itemProviderState$1.invoke (LazyListItemProvider.kt:54)
  at androidx.compose.foundation.lazy.LazyListItemProviderKt$rememberLazyListItemProvider$1$itemProviderState$1.invoke (LazyListItemProvider.kt:53)
  at androidx.compose.runtime.snapshots.Snapshot$Companion.observe (Snapshot.kt:2200)
  at androidx.compose.runtime.DerivedSnapshotState.currentRecord (DerivedState.kt:161)
  at androidx.compose.runtime.DerivedSnapshotState.getCurrentValue (DerivedState.kt:231)
  at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.recordInvalidation (SnapshotStateObserver.kt:523)
  at androidx.compose.runtime.snapshots.SnapshotStateObserver.drainChanges (SnapshotStateObserver.kt:66)
  at androidx.compose.runtime.snapshots.SnapshotStateObserver.access$drainChanges (SnapshotStateObserver.kt:38)
  at androidx.compose.runtime.snapshots.SnapshotStateObserver$applyObserver$1.invoke (SnapshotStateObserver.kt:45)
  at androidx.compose.runtime.snapshots.SnapshotStateObserver$applyObserver$1.invoke (SnapshotStateObserver.kt:43)
  at androidx.compose.runtime.snapshots.MutableSnapshot.apply (Snapshot.kt:748)
  at androidx.compose.runtime.Recomposer.applyAndCheck (Recomposer.kt:1124)
  at androidx.compose.runtime.Recomposer.performRecompose (Recomposer.kt:1483)
  at androidx.compose.runtime.Recomposer.access$performRecompose (Recomposer.kt:124)
  at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke (Recomposer.kt:541)
  at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke (Recomposer.kt:510)
  at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame (AndroidUiFrameClock.android.kt:34)
  at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch (AndroidUiDispatcher.android.kt:109)
  at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch (AndroidUiDispatcher.android.kt:41)
  at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame (AndroidUiDispatcher.android.kt:69)
  at android.view.Choreographer$CallbackRecord.run (Choreographer.java:996)
  at android.view.Choreographer.doCallbacks (Choreographer.java:796)
  at android.view.Choreographer.doFrame (Choreographer.java:727)
  at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:983)
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:246)
  at android.app.ActivityThread.main (ActivityThread.java:7690)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:593)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:995)
```

**Comment by slovdahl** [comment]
Happened for me in the development environment too:

```
2023-08-17 22:15:21.478 21395-21395 AndroidRuntime          io....stant.companion.android.debug  E  FATAL EXCEPTION: main
                                                                                                    Process: io.homeassistant.companion.android.debug, PID: 21395
                                                                                                    java.util.ConcurrentModificationException
                                                                                                    	at androidx.compose.runtime.snapshots.StateListIterator.validateModification(SnapshotStateList.kt:295)
                                                                                                    	at androidx.compose.runtime.snapshots.StateListIterator.next(SnapshotStateList.kt:274)
                                                                                                    	at io.homeassistant.companion.android.home.views.MainViewKt$MainView$1$3$1.invoke(MainView.kt:263)
                                                                                                    	at io.homeassistant.companion.android.home.views.MainViewKt$MainView$1$3$1.invoke(MainView.kt:77)
                                                                                                    	at androidx.wear.compose.material.ScalingLazyColumnKt$ScalingLazyColumn$1$1$2$1.invoke(ScalingLazyColumn.kt:425)
                                                                                                    	at androidx.wear.compose.material.ScalingLazyColumnKt$ScalingLazyColumn$1$1$2$1.invoke(ScalingLazyColumn.kt:410)
                                                                                                    	at androidx.compose.foundation.lazy.LazyListItemProviderKt$rememberLazyListItemProvider$1$itemProviderState$1.invoke(LazyListItemProvider.kt:54)
                                                                                                    	at androidx.compose.foundation.lazy.LazyListItemProviderKt$rememberLazyListItemProvider$1$itemProviderState$1.invoke(LazyListItemProvider.kt:53)
                                                                                                    	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2200)
                                                                                                    	at androidx.compose.runtime.DerivedSnapshotState.currentRecord(DerivedState.kt:161)
                                                                                                    	at androidx.compose.runtime.DerivedSnapshotState.getCurrentValue(DerivedState.kt:231)
                                                                                                    	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.recordInvalidation(SnapshotStateObserver.kt:523)
                                                                                                    	at androidx.compose.runtime.snapshots.SnapshotStateObserver.drainChanges(SnapshotStateObserver.kt:66)
                                                                                                    	at androidx.compose.runtime.snapshots.SnapshotStateObserver.access$drainChanges(SnapshotStateObserver.kt:38)
                                                                                                    	at androidx.compose.runtime.snapshots.SnapshotStateObserver$applyObserver$1.invoke(SnapshotStateObserver.kt:45)
                                                                                                    	at androidx.compose.runtime.snapshots.SnapshotStateObserver$applyObserver$1.invoke(SnapshotStateObserver.kt:43)
                                                                                                    	at androidx.compose.runtime.snapshots.SnapshotKt.advanceGlobalSnapshot(Snapshot.kt:1768)
                                                                                                    	at androidx.compose.runtime.snapshots.SnapshotKt.advanceGlobalSnapshot(Snapshot.kt:1779)
                                                                                                    	at androidx.compose.runtime.snapshots.SnapshotKt.access$advanceGlobalSnapshot(Snapshot.kt:1)
                                                                                                    	at androidx.compose.runtime.snapshots.GlobalSnapshot.notifyObjectsInitialized$runtime_release(Snapshot.kt:1337)
                                                                                                    	at androidx.compose.runtime.snapshots.Snapshot$Companion.notifyObjectsInitialized(Snapshot.kt:551)
                                                                                                    	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:641)
                                                                                                    	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:510)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:34)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:996)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:727)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:983)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:246)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7690)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:593)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@8127c81, androidx.compose.ui.platform.MotionDurationScaleImpl@e948126, StandaloneCoroutine{Cancelling}@df8c167, AndroidUiDispatcher@a81eb14]
```

**Comment by JBou** [comment]
This problem is already reported in the compose issue tracker:
https://issuetracker.google.com/issues/272334463

Maybe you can add a +1 vote there in the upper right, or even better add a comment that it affects this app and a few thousand users, so the issue gets a bit more attention and the suggested solution gets implemented.

**Comment by dshokouhi** [comment]
here are 2 most recent crashes in prod that point to 2 different variables modified only in the method mentioned above:

```
Exception java.util.ConcurrentModificationException:
  at androidx.compose.runtime.snapshots.StateListIterator.validateModification (SnapshotStateList.kt:369)
  at androidx.compose.runtime.snapshots.StateListIterator.next (SnapshotStateList.kt:345)
  at io.homeassistant.companion.android.home.views.MainViewKt$MainView$1.invoke$lambda$6$lambda$5 (MainView.kt:250)
  at io.homeassistant.companion.android.home.views.MainViewKt$MainView$1.$r8$lambda$uUo1j9REYSfJi_bIMBaTLg9TcVw (Unknown Source)
  at io.homeassistant.companion.android.home.views.MainViewKt$MainView$1$$ExternalSyntheticLambda0.invoke (D8$$SyntheticClass)
  at androidx.wear.compose.foundation.lazy.ScalingLazyColumnKt$ScalingLazyColumn$2$1$2$1.invoke (ScalingLazyColumn.kt:588)
  at androidx.wear.compose.foundation.lazy.ScalingLazyColumnKt$ScalingLazyColumn$2$1$2$1.invoke (ScalingLazyColumn.kt:571)
  at androidx.compose.foundation.lazy.LazyListIntervalContent.<init> (LazyListIntervalContent.kt:39)
  at androidx.compose.foundation.lazy.LazyListItemProviderKt$rememberLazyListItemProviderLambda$1$intervalContentState$1.invoke (LazyListItemProvider.kt:51)
  at androidx.compose.foundation.lazy.LazyListItemProviderKt$rememberLazyListItemProviderLambda$1$intervalContentState$1.invoke (LazyListItemProvider.kt:50)
  at androidx.compose.runtime.snapshots.Snapshot$Companion.observe (Snapshot.kt:2489)
  at androidx.compose.runtime.DerivedSnapshotState.currentRecord (DerivedState.kt:210)
  at androidx.compose.runtime.DerivedSnapshotState.current (DerivedState.kt:176)
  at androidx.compose.runtime.DerivedSnapshotState$ResultRecord.readableHash (DerivedState.kt:152)
  at androidx.compose.runtime.DerivedSnapshotState$ResultRecord.isValid (DerivedState.kt:123)
  at androidx.compose.runtime.DerivedSnapshotState.currentRecord (DerivedState.kt:184)
  at androidx.compose.runtime.DerivedSnapshotState.getCurrentRecord (DerivedState.kt:292)
  at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.recordInvalidation (SnapshotStateObserver.kt:544)
  at androidx.compose.runtime.snapshots.SnapshotStateObserver.drainChanges (SnapshotStateObserver.kt:72)
  at androidx.compose.runtime.snapshots.SnapshotStateObserver.access$drainChanges (SnapshotStateObserver.kt:44)
  at androidx.compose.runtime.snapshots.SnapshotStateObserver$applyObserver$1.invoke (SnapshotStateObserver.kt:51)
  at androidx.compose.runtime.snapshots.SnapshotStateObserver$applyObserver$1.invoke (SnapshotStateObserver.kt:49)
  at androidx.compose.runtime.snapshots.SnapshotKt.advanceGlobalSnapshot (Snapshot.kt:1988)
  at androidx.compose.runtime.snapshots.SnapshotKt.advanceGlobalSnapshot (Snapshot.kt:2002)
  at androidx.compose.runtime.snapshots.SnapshotKt.access$advanceGlobalSnapshot (Snapshot.kt:1)
  at androidx.compose.runtime.snapshots.Snapshot$Companion.sendApplyNotifications (Snapshot.kt:680)
  at androidx.compose.ui.platform.GlobalSnapshotManager$ensureStarted$1.invokeSuspend (GlobalSnapshotManager.android.kt:48)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (ContinuationImpl.kt:33)
  at kotlinx.coroutines.DispatchedTask.run (DispatchedTask.kt:101)
  at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch (AndroidUiDispatcher.android.kt:79)
  at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch (AndroidUiDispatcher.android.kt:41)
  at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run (AndroidUiDispatcher.android.kt:57)
  at android.os.Handler.handleCallback (Handler.java:959)
  at android.os.Handler.dispatchMessage (Handler.java:100)
  at android.os.Looper.loopOnce (Looper.java:232)
  at android.os.Looper.loop (Looper.java:317)
  at android.app.ActivityThread.main (ActivityThread.java:8592)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:580)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:878)
```

and

```
Exception java.util.ConcurrentModificationException:
  at androidx.compose.runtime.snapshots.StateListIterator.validateModification (SnapshotStateList.kt:371)
  at androidx.compose.runtime.snapshots.StateListIterator.next (SnapshotStateList.kt:347)
  at io.homeassistant.companion.android.home.views.MainViewKt$MainView$1.invoke$lambda$6$lambda$5 (MainView.kt:208)
  at io.homeassistant.companion.android.home.views.MainViewKt$MainView$1.$r8$lambda$uUo1j9REYSfJi_bIMBaTLg9TcVw (Unknown Source)
  at io.homeassistant.companion.android.home.views.MainViewKt$MainView$1$$ExternalSyntheticLambda0.invoke (D8$$SyntheticClass)
  at androidx.wear.compose.foundation.lazy.ScalingLazyColumnKt$ScalingLazyColumn$2$1$2$1.invoke (ScalingLazyColumn.kt:590)
  at androidx.wear.compose.foundation.lazy.ScalingLazyColumnKt$ScalingLazyColumn$2$1$2$1.invoke (ScalingLazyColumn.kt:573)
  at androidx.compose.foundation.lazy.LazyListIntervalContent.<init> (LazyListIntervalContent.kt:39)
  at androidx.compose.foundation.lazy.LazyListItemProviderKt$rememberLazyListItemProviderLambda$1$intervalContentState$1.invoke (LazyListItemProvider.kt:51)
  at androidx.compose.foundation.lazy.LazyListItemProviderKt$rememberLazyListItemProviderLambda$1$intervalContentState$1.invoke (LazyListItemProvider.kt:50)
  at androidx.compose.runtime.snapshots.Snapshot$Companion.observe (Snapshot.kt:2426)
  at androidx.compose.runtime.DerivedSnapshotState.currentRecord (DerivedState.kt:203)
  at androidx.compose.runtime.DerivedSnapshotState.current (DerivedState.kt:169)
  at androidx.compose.runtime.DerivedSnapshotState$ResultRecord.readableHash (DerivedState.kt:145)
  at androidx.compose.runtime.DerivedSnapshotState$ResultRecord.isValid (DerivedState.kt:116)
  at androidx.compose.runtime.DerivedSnapshotState.currentRecord (DerivedState.kt:177)
  at androidx.compose.runtime.DerivedSnapshotState.getCurrentRecord (DerivedState.kt:285)
  at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.recordInvalidation (SnapshotStateObserver.kt:544)
  at androidx.compose.runtime.snapshots.SnapshotStateObserver.drainChanges (SnapshotStateObserver.kt:72)
  at androidx.compose.runtime.snapshots.SnapshotStateObserver.access$drainChanges (SnapshotStateObserver.kt:44)
  at androidx.compose.runtime.snapshots.SnapshotStateObserver$applyObserver$1.invoke (SnapshotStateObserver.kt:51)
  at androidx.compose.runtime.snapshots.SnapshotStateObserver$applyObserver$1.invoke (SnapshotStateObserver.kt:49)
  at androidx.compose.runtime.snapshots.SnapshotKt.advanceGlobalSnapshot (Snapshot.kt:1938)
  at androidx.compose.runtime.snapshots.SnapshotKt.advanceGlobalSnapshot (Snapshot.kt:1952)
  at androidx.compose.runtime.snapshots.SnapshotKt.access$advanceGlobalSnapshot (Snapshot.kt:1)
  at androidx.compose.runtime.snapshots.GlobalSnapshot.notifyObjectsInitialized$runtime_release (Snapshot.kt:1491)
  at androidx.compose.runtime.snapshots.Snapshot$Companion.notifyObjectsInitialized (Snapshot.kt:651)
  at androidx.compose.runtime.DerivedSnapshotState.currentRecord (DerivedState.kt:245)
  at androidx.compose.runtime.DerivedSnapshotState.current (DerivedState.kt:169)
  at androidx.compose.runtime.DerivedSnapshotState$ResultRecord.readableHash (DerivedState.kt:145)
  at androidx.compose.runtime.DerivedSnapshotState$ResultRecord.isValid (DerivedState.kt:116)
  at androidx.compose.runtime.DerivedSnapshotState.currentRecord (DerivedState.kt:177)
  at androidx.compose.runtime.DerivedSnapshotState.getCurrentRecord (DerivedState.kt:285)
  at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.recordInvalidation (SnapshotStateObserver.kt:544)
  at androidx.compose.runtime.snapshots.SnapshotStateObserver.drainChanges (SnapshotStateObserver.kt:72)
  at androidx.compose.runtime.snapshots.SnapshotStateObserver.access$drainChanges (SnapshotStateObserver.kt:44)
  at androidx.compose.runtime.snapshots.SnapshotStateObserver$applyObserver$1.invoke (SnapshotStateObserver.kt:51)
  at androidx.compose.runtime.snapshots.SnapshotStateObserver$applyObserver$1.invoke (SnapshotStateObserver.kt:49)
  at androidx.compose.runtime.snapshots.SnapshotKt.advanceGlobalSnapshot (Snapshot.kt:1938)
  at androidx.compose.runtime.snapshots.SnapshotKt.advanceGlobalSnapshot (Snapshot.kt:1952)
  at androidx.compose.runtime.snapshots.SnapshotKt.access$advanceGlobalSnapshot (Snapshot.kt:1)
  at androidx.compose.runtime.snapshots.Snapshot$Companion.sendApplyNotifications (Snapshot.kt:665)
  at androidx.compose.ui.platform.GlobalSnapshotManager$ensureStarted$1.invokeSuspend (GlobalSnapshotManager.android.kt:48)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (ContinuationImpl.kt:33)
  at kotlinx.coroutines.DispatchedTask.run (DispatchedTask.kt:101)
  at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch (AndroidUiDispatcher.android.kt:79)
  at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch (AndroidUiDispatcher.android.kt:41)
  at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run (AndroidUiDispatcher.android.kt:57)
  at android.os.Handler.handleCallback (Handler.java:942)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loopOnce (Looper.java:201)
  at android.os.Looper.loop (Looper.java:288)
  at android.app.ActivityThread.main (ActivityThread.java:7894)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:548)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:936)
```
