### ISSUE TITLE
Unable to toggle (activate or deactivate) any Sensors in WearOS Companion App

### ISSUE THREAD

**Issue by frod0r** [home-assistant/android#3523]
**Home Assistant Android version:**
2023.3.0-3260

Android version:
Android 11/  Wear OS 3.5

Phone model:
Samsung Galaxy Watch 5 (HCYT)

Home Assistant version:
2023.5.2

**Last working Home Assistant release (if known):** None

**Description of problem, include YAML if issue is related to notifications:**

In the WearOS companion App I am unable to activate or deactivate any sensors.
But the sensors that are already activated (like battery level) get reported just fine.

I tried this with the 2023.3.0-3260  and beta-9972-8b32f9bf release version.
In both cases I ensured all permissions are enabled and background activity is allowed.

The logs provided were recorded with the 2023.3.0-3260 version

**Companion App Logs:**

The Relevant Part appears to be the following, as the appeared in the logs every time I tried to toggle a sensor
```
05-10 10:20:07.284  4757  6970 E SensorReceiver: Error while getting core config to sync sensor status
05-10 10:20:07.284  4757  6970 E SensorReceiver: io.homeassistant.companion.android.common.data.integration.IntegrationException: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
05-10 10:20:07.284  4757  6970 E SensorReceiver:  at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 1, column: 0]
05-10 10:20:07.284  4757  6970 E SensorReceiver:        at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl.getConfig(IntegrationRepositoryImpl.kt:493)
05-10 10:20:07.284  4757  6970 E SensorReceiver:        at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl$getConfig$1.invokeSuspend(Unknown Source:14)
05-10 10:20:07.284  4757  6970 E SensorReceiver:        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
05-10 10:20:07.284  4757  6970 E SensorReceiver:        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
05-10 10:20:07.284  4757  6970 E SensorReceiver:        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
05-10 10:20:07.284  4757  6970 E SensorReceiver:        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
05-10 10:20:07.284  4757  6970 E SensorReceiver:        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
05-10 10:20:07.284  4757  6970 E SensorReceiver:        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
05-10 10:20:07.284  4757  6970 E SensorReceiver:        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
05-10 10:20:07.284  4757  6970 E SensorReceiver:        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
05-10 10:20:07.284  4757  6970 E SensorReceiver: Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
05-10 10:20:07.284  4757  6970 E SensorReceiver:  at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 1, column: 0]

```

But I have also uploaded full logs here
[homasssistant-wearos-log.txt](https://github.com/home-assistant/android/files/11439722/homasssistant-wearos-log.txt)

**Screenshot or video of problem:**

https://github.com/home-assistant/android/assets/37292429/20fd2b06-7f67-4188-be02-5fdcc8fd30ee

**Additional information:**

**Comment by jpelgrom** [comment]
The log fragment you've posted shouldn't prevent you from enabling sensors, though it does indicate that when it tries to connect to your server to register it is unable to connect (empty response).

> In both cases I ensured all permissions are enabled

Could you try not enabling all permissions, and see if the app prompts you for permission when trying to toggle a sensor that requires permissions?

> But the sensors that are already activated (like battery level) get reported just fine.

That's unexpected given the log error about connecting to the server. Have you tried enabling/disabling sensors from the server to see if that works?

**Comment by frod0r** [comment]
First of all thank you for your reply this already helped a lot

> Could you try not enabling all permissions, and see if the app prompts you for permission when trying to toggle a sensor that requires permissions?

I tried this. The interaction went as follows (Disabled permission for Sensors)
* Go to heart rate (toggle is shown as disabled)
* Tap on toggle -> Prompt shows
* Accept promt -> Toggle still shows as disabled.
* Checking on the server showed that the heart rate sensor is actually enabled

> That's unexpected given the log error about connecting to the server. Have you tried enabling/disabling sensors from the server to see if that works?

Good idea! I tried this and enabling the sensors on the server works. If I enable a sensor on the Server I get its value ~30 seconds later.
However the companion app still shows those sensors as disabled.
Similarly, if I disable a sensor on the server that is shown as enabled on the watch, it is still shown as enabled on the watch.


**My suspicion is, that enabling/ disabling the sensors works, but that the UI on the companion doesn't update.**
This is corroborated by the following interaction:

* Initial: Companion shows Battery Level as enabled, server shows battery-level sensor as enabled and shows the correct value
* Tap on toggle: on the companion, nothing happens, battery level is still indicated as enabled. On the server battery level almost instantly becomes unavailable and current value is shown as unknown. The server shows the entity is disabled

This way I can (from the watch) disable any sensors that are shown as enabled on the watch, and enable sensors that are shown as disabled on the watch.

However the companion on the watch never changes which sensors are shown as enabled or disabled. Irregardless of which ones are actually enabled or disabled  (I tried restarting the app and the whole watch)

**Comment by jpelgrom** [comment]
> My suspicion is, that enabling/ disabling the sensors works, but that the UI on the companion doesn't update.

Fits with what you've described. I'm not seeing the same thing though on the app versions you've mentioned.

Maybe it has something to do with data migration - have you set up the app recently or is this an 'old' install? If you don't mind setting up the app again, could you sign out and back in to see if that resolves the issue (this will set most of your settings back to the default)?

**Comment by frod0r** [comment]
> have you set up the app recently or is this an 'old' install?

I set up the app on the watch the first time yesterday, noticed the issue described, installed the newest beta, uninstalled the beta again and reinstalled the 2023.3.0-3260 version 

The app on the phone I've had set up a long while ago (~2Years)

> If you don't mind setting up the app again, could you sign out and back in to see if that resolves the issue (this will set most of your settings back to the default)?

This did actually resolve issue, i am now able to enable and disable sensors on the watch and see it toggle

**Comment by jpelgrom** [comment]
> Note when i reinstall the app on the watch, the problem re-appears and is presented until i sign out and back in again 1-2 times.

That's odd. Trying to replicate this but toggling 'just works' here. It might be that Android is restoring an old back-up when you reinstall the app that includes the data that is deleted when signing out 🤔

Another thought: the app reloads the enabled state when opening the sensors screen. When enabling sensors appears to do nothing on your watch, could you close the sensor settings and re-open them to see if that 'fixes' it?

**Comment by frod0r** [comment]
> It might be that Android is restoring an old back-up when you reinstall the app that includes the data that is deleted when signing out thinking

It seems to have something to do with the sync with the phone app. I tried reinstalling the phone app and the watch app at the same time and now everything works

> Another thought: the app reloads the enabled state when opening the sensors screen. When enabling sensors appears to do nothing on your watch, could you close the sensor settings and re-open them to see if that 'fixes' it?

I tried this before reinstalling the phone app, and this didn't do anything


---

But since reinstalling the app on the phone fixed it, I assume that your thought about data migration has been right.

**Comment by slovdahl** [comment]
I'm having the exact same problem (on a Samsung Galaxy Watch 5 too), and similarly, my HA phone app has been installed 2-3 years ago and the Wear app 2 days ago. I have not yet reinstalled the phone app and I would prefer to not do that (I assume any custom widgets would be lost e.g.). Anything I can do to help pinpoint the problem?

**Comment by slovdahl** [comment]
Interesting, the sensors do seem to become active in HA eventually, despite the lack of visual feedback in the Wear app. They still show as inactive in the Wear app.

**Comment by slovdahl** [comment]
Getting back to this I'm now seeing lots of exceptions logged every time I start the HA app on my watch that seem related to this. If I just keep the app open on the screen it's opened on it eventually crashes.

```
2023-07-26 21:32:21.993 SensorReceiver          io.homeassistant.companion.android   E  Issue re-registering sensor android_os_version
                                                                                        io.homeassistant.companion.android.common.data.integration.IntegrationException: Error calling integration request register_sensor
                                                                                        	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl.registerSensor(IntegrationRepositoryImpl.kt:691)
                                                                                        	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl$registerSensor$1.invokeSuspend(Unknown Source:15)
                                                                                        	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                        	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
                                                                                        	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
                                                                                        	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
                                                                                        	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                                                                                        	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
                                                                                        	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
                                                                                        	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

Is it even trying to request anything in these specific cases? :thinking: I get the feeling it isn't because the root cause exception is missing (looking at `io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl#updateRegistration` and [the exception handling in the end of it](https://github.com/home-assistant/android/blob/2023.7.5/common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt#L140)).

Not sure about the relevance, but first of all this is logged though:

```
2023-07-26 21:32:21.374 IntegrationRepository   io.homeassistant.companion.android   E  Issue getting new version from core.
                                                                                        io.homeassistant.companion.android.common.data.integration.IntegrationException: retrofit2.HttpException: HTTP 404 
                                                                                        	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl.getConfig(IntegrationRepositoryImpl.kt:502)
                                                                                        	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl$getConfig$1.invokeSuspend(Unknown Source:14)
                                                                                        	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                        	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                        	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
                                                                                        	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
                                                                                        	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                                                                                        	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
                                                                                        	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
                                                                                        	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
                                                                                        Caused by: retrofit2.HttpException: HTTP 404 
                                                                                        	at retrofit2.KotlinExtensions$await$2$2.onResponse(KotlinExtensions.kt:53)
                                                                                        	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:161)
                                                                                        	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
                                                                                        	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                        	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                        	at java.lang.Thread.run(Thread.java:923)
```

Followed by: 

```
2023-07-26 21:32:21.762 SensorReceiver          io.homeassistant.companion.android   E  Error while getting core config to sync sensor status
                                                                                        io.homeassistant.companion.android.common.data.integration.IntegrationException: retrofit2.HttpException: HTTP 404
                                                                                        	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl.getConfig(IntegrationRepositoryImpl.kt:502)
                                                                                        	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl$getConfig$1.invokeSuspend(Unknown Source:14)
                                                                                        	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                        	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                        	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
                                                                                        	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
                                                                                        	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                                                                                        	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
                                                                                        	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
                                                                                        	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
                                                                                        Caused by: retrofit2.HttpException: HTTP 404
                                                                                        	at retrofit2.KotlinExtensions$await$2$2.onResponse(KotlinExtensions.kt:53)
                                                                                        	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:161)
                                                                                        	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
                                                                                        	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                        	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                        	at java.lang.Thread.run(Thread.java:923)
```

I also get the feeling that all requests from my watch go through Home Assistant Cloud and not directly to my local Home Assistant instance. :thinking:

**Comment by dshokouhi** [comment]
> If I just keep the app open on the screen it's opened on it eventually crashes.

unrelated to this issue, most likely you are seeing #3325 


> io.homeassistant.companion.android.common.data.integration.IntegrationException: retrofit2.HttpException: HTTP 404

hmm a 404 error? strange. Maybe something happened to device registration on the watch? Could always try to log out and back in from Settings. Although I typically see a 410 error when device registration is missing.



> I also get the feeling that all requests from my watch go through Home Assistant Cloud and not directly to my local Home Assistant instance. 🤔

we only use the external URL for Wear OS, the watch does not handle any URL switching.

**Comment by slovdahl** [comment]
> > If I just keep the app open on the screen it's opened on it eventually crashes.
> 
> unrelated to this issue, most likely you are seeing #3325
> 
> > io.homeassistant.companion.android.common.data.integration.IntegrationException: retrofit2.HttpException: HTTP 404
> 
> hmm a 404 error? strange. Maybe something happened to device registration on the watch? Could always try to log out and back in from Settings. Although I typically see a 410 error when device registration is missing.
> 

Yeah, strange one indeed.. I did log out now, but before I did that, I also edited "Home Assistant URL" in my HA phone app. It was manually set to the long cloud URL, and instead I enabled the "Use Home Assistant Cloud" switch. This far, it seems like there are no more exceptions logged. :open_mouth:

> > I also get the feeling that all requests from my watch go through Home Assistant Cloud and not directly to my local Home Assistant instance. thinking
> 
> we only use the external URL for Wear OS, the watch does not handle any URL switching.

Ah, ok. Missing feature or is there something blocking it from being implemented?

**Comment by dshokouhi** [comment]
> Ah, ok. Missing feature or is there something blocking it from being implemented?

feature depends on reading the WiFi SSID, no watch stays connected long enough to make it reliable.

**Comment by jpelgrom** [comment]
(As you recently submitted a PR, if you didn't change the device name while testing this may have messed up your device entry in HA resulting in these errors.)

> I also edited "Home Assistant URL" in my HA phone app

These settings do not affect the Wear app.

**Comment by slovdahl** [comment]
> > Ah, ok. Missing feature or is there something blocking it from being implemented?
> 
> feature depends on reading the WiFi SSID, no watch stays connected long enough to make it reliable.

True that.. 🤔 Could the watch ask the phone about it instead?

> (As you recently submitted a PR, if you didn't change the device name while testing this may have messed up your device entry in HA resulting in these errors.)
> 

I did try use a different name at least. But I logged in a few times over the past few days so it's surely a possibility that I messed up. I cannot recall seeing these crashes before at least.

> > I also edited "Home Assistant URL" in my HA phone app
> 
> These settings do not affect the Wear app.

Doesn't the Wear app use it for getting the URL to use? But ok, most likely the log out+in fixed it then.

I can actually toggle sensors now and see them immediately get enabled both on the watch and in HA 👍

**Comment by dshokouhi** [comment]
> > > Ah, ok. Missing feature or is there something blocking it from being implemented?
> > 
> > 
> > feature depends on reading the WiFi SSID, no watch stays connected long enough to make it reliable.
> 
> True that.. 🤔 Could the watch ask the phone about it instead?

we dont do any of that logic now, lets try to stick to the topic of the issue here :)



> Doesn't the Wear app use it for getting the URL to use?

We only send the external/cloud URL in the request.

**Comment by slovdahl** [comment]
> we dont do any of that logic now, lets try to stick to the topic of the issue here :)

Absolutely, sorry for that. Let's continue in #3773.

**Comment by dshokouhi** [comment]
Trying to get back on topic here, for those experiencing this issue can you confirm that logging out and back in to the Wear OS app solves teh issue? If not we may need to try clearing data and starting fresh. I am personally unable to reproduce this and in fact recently setup the app and did not encounter this issue as I enabled most sensors.

**Comment by dshokouhi** [comment]
Closing due to lack of response

**Comment by hheimbuerger** [comment]
I just experienced this issue, pretty much precisely as described above.

Versions:
HA: v2025.3.3 (docker container)
Companion app: v2025.1.2-full (Android)
wearOS app: v2025.1.2-14946

Again, the HA instance exists since maybe two years, but it's my very first wearOS watch and this occured on the initial setup phase of the watch.

I was unable to activate or deactivate any sensors. They're all listed on the `Manage Sensors` screen under the various categories, but not a single one can be toggled. I believe I had managed to toggle a few before (not all), and they would 'kinda' show up in HA (with a state of `unknown`), but it quickly stopped working (not sure what changed) and I ended up in a state where I tried every single one and none was toggleable.

Resetting the wearOS app and logging in again seems to have fixed the issue.

**Comment by Segilmez06** [comment]
> Trying to get back on topic here, for those experiencing this issue can you confirm that logging out and back in to the Wear OS app solves the issue? If not we may need to try clearing data and starting fresh. I am personally unable to reproduce this and in fact recently setup the app and did not encounter this issue as I enabled most sensors.

I'm experiencing the same issue. Everything is up-to-date as the time I'm writing this comment. I first installed the app on my watch nearly a year ago (03.2024). I was able to toggle them after a long struggle. I haven't messed with it until last week. I needed to toggle some other options and now everything is gone. I can't toggle any of them and I can't get any sensor data. It also seems like it's not saving the toggled options. I'm experiencing the exact same issue with @hheimbuerger. Some of them sometimes show up as entities but has weird state. Resetting or logging in again didn't fixed in my case.

> Closing due to lack of response

@dshokouhi I can provide any more info if needed, any chance to reopen this issue?



Home Assistant: 2025.5.3
Phone: Galaxy A32 (`Android 13`)
Watch: Galaxy Watch 4 (`Android 14`, `Wear OS 5.0`)
