### ISSUE TITLE
The Android app can't connect to home-assistant anymore

### ISSUE THREAD

**Issue by HyperCriSiS** [home-assistant/android#3569]
**Home Assistant Android app version(s):2023.3.0-full**

**Android version(s):LinageOS 18.1**

**Device model(s):Asus Zenfone 8**

**Home Assistant version: 2023.5.4**

**Last working Home Assistant release (if known):2023.5.4**

**Description of problem, include YAML if issue is related to notifications:**
The Android app can't connect to home-assistant anymore. The webinterface works without issues, also from the problem device.

Error message is: 
error code: -8
net::ERR_CONNECTION_TIMED_OUT

Is there any other way I can get the companion error logs without the app connecting anymore?
These are my HA logs:

```
2023-06-01 21:55:30.054 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration powercalc which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-06-01 21:55:30.055 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration openweathermap_all which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-06-01 21:55:30.057 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration dwd_weather which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-06-01 21:55:30.059 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration composite which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-06-01 21:55:30.060 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration sonoff which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-06-01 21:55:30.062 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration feedparser which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-06-01 21:55:30.064 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration frigate which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-06-01 21:55:30.066 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration magic_areas which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-06-01 21:55:30.067 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration saver which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-06-01 21:55:30.069 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration auto_backup which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-06-01 21:55:30.070 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-06-01 21:55:30.072 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration watchman which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-06-01 21:55:30.073 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration entity_controller which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-06-01 21:58:17.084 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: analytics
2023-06-01 21:58:36.544 WARNING (Recorder) [homeassistant.components.recorder.util] The system could not validate that the sqlite3 database at //mnt/dietpi_userdata/homeassistant/home-assistant_v2.db was shutdown cleanly
2023-06-01 22:15:09.330 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: ssdp
2023-06-01 22:22:39.611 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: webostv
2023-06-01 22:23:57.111 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: forecast_solar
2023-06-01 22:31:27.344 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: dwd_weather
2023-06-01 22:31:46.899 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Canvas 2CFF' for nanoleaf integration not ready yet; Retrying in background
2023-06-01 22:31:58.552 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Kyocera ECOSYS M5521cdn' for ipp integration not ready yet: Invalid response from API: Error occurred while communicating with IPP server.; Retrying in background
2023-06-01 22:39:15.001 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: plex
2023-06-01 22:39:44.627 WARNING (MainThread) [homeassistant.config_entries] Config entry 'https://5-9-119-110.80b7ac3b3edd4efcae77905dec917188.plex.direct:32400' for plex integration not ready yet: HTTPSConnectionPool(host='5-9-119-110.80b7ac3b3edd4efcae77905dec917188.plex.direct', port=32400): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xefa03e80>, 'Connection to 5-9-119-110.80b7ac3b3edd4efcae77905dec917188.plex.direct timed out. (connect timeout=30)')); Retrying in background
2023-06-01 22:40:21.091 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: default_config
2023-06-01 22:40:30.924 WARNING (MainThread) [homeassistant.setup] Setup of default_config is taking over 10 seconds.
2023-06-01 22:41:32.189 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: default_config
2023-06-01 22:42:08.191 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({{ state_attr('sensor.android_wlan_state', 'bssid', '02:00:00:00:00:00') }}) renders=2>
Traceback (most recent call last):
  File "/home/homeassistant/.pyenv/versions/3.10.11/lib/python3.10/site-packages/homeassistant/helpers/template.py", line 544, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
  File "/home/homeassistant/.pyenv/versions/3.10.11/lib/python3.10/site-packages/homeassistant/helpers/template.py", line 2164, in _render_with_context
    return template.render(**kwargs)
  File "/home/homeassistant/.pyenv/versions/3.10.11/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/homeassistant/.pyenv/versions/3.10.11/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/home/homeassistant/.pyenv/versions/3.10.11/lib/python3.10/site-packages/jinja2/sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
  File "/home/homeassistant/.pyenv/versions/3.10.11/lib/python3.10/site-packages/homeassistant/helpers/template.py", line 2375, in wrapper
    return func(hass, *args, **kwargs)
TypeError: state_attr() takes 3 positional arguments but 4 were given

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/homeassistant/.pyenv/versions/3.10.11/lib/python3.10/site-packages/homeassistant/helpers/template.py", line 665, in async_render_to_info
    render_info._result = self.async_render(variables, strict=strict, **kwargs)
  File "/home/homeassistant/.pyenv/versions/3.10.11/lib/python3.10/site-packages/homeassistant/helpers/template.py", line 546, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: TypeError: state_attr() takes 3 positional arguments but 4 were given
2023-06-01 22:42:08.202 ERROR (MainThread) [homeassistant.helpers.template_entity] TemplateError('TypeError: state_attr() takes 3 positional arguments but 4 were given') while processing template 'Template<template=({{ state_attr('sensor.android_wlan_state', 'bssid', '02:00:00:00:00:00') }}) renders=4>' for attribute '_state' in entity 'binary_sensor.wlan_status'
2023-06-01 22:42:12.074 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.flur_1_energy_daily (kWh) cannot be converted to the unit of previously compiled statistics (None). Generation of long term statistics will be suppressed unless the unit changes back to None or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
2023-06-01 22:42:12.097 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.flur_1_energy_weekly (kWh) cannot be converted to the unit of previously compiled statistics (None). Generation of long term statistics will be suppressed unless the unit changes back to None or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
2023-06-01 22:42:12.102 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.flur_1_energy_monthly (kWh) cannot be converted to the unit of previously compiled statistics (None). Generation of long term statistics will be suppressed unless the unit changes back to None or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
2023-06-01 22:42:12.107 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.schlafzimmer_energy_daily (kWh) cannot be converted to the unit of previously compiled statistics (None). Generation of long term statistics will be suppressed unless the unit changes back to None or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
2023-06-01 22:42:12.112 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.schlafzimmer_energy_weekly (kWh) cannot be converted to the unit of previously compiled statistics (None). Generation of long term statistics will be suppressed unless the unit changes back to None or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
2023-06-01 22:42:12.117 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.schlafzimmer_energy_monthly (kWh) cannot be converted to the unit of previously compiled statistics (None). Generation of long term statistics will be suppressed unless the unit changes back to None or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
2023-06-01 22:42:12.122 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.flur_2_energy_daily (kWh) cannot be converted to the unit of previously compiled statistics (None). Generation of long term statistics will be suppressed unless the unit changes back to None or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
2023-06-01 22:42:12.127 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.flur_2_energy_weekly (kWh) cannot be converted to the unit of previously compiled statistics (None). Generation of long term statistics will be suppressed unless the unit changes back to None or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
2023-06-01 22:42:12.132 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.flur_2_energy_monthly (kWh) cannot be converted to the unit of previously compiled statistics (None). Generation of long term statistics will be suppressed unless the unit changes back to None or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
2023-06-01 22:42:12.137 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.wohnzimmer_kugel_energy_daily (kWh) cannot be converted to the unit of previously compiled statistics (None). Generation of long term statistics will be suppressed unless the unit changes back to None or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
2023-06-01 22:42:12.142 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.wohnzimmer_kugel_energy_weekly (kWh) cannot be converted to the unit of previously compiled statistics (None). Generation of long term statistics will be suppressed unless the unit changes back to None or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
2023-06-01 22:42:12.152 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.wohnzimmer_kugel_energy_monthly (kWh) cannot be converted to the unit of previously compiled statistics (None). Generation of long term statistics will be suppressed unless the unit changes back to None or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
2023-06-01 22:42:12.157 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.bad_energy_daily (kWh) cannot be converted to the unit of previously compiled statistics (None). Generation of long term statistics will be suppressed unless the unit changes back to None or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
2023-06-01 22:42:12.160 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.bad_energy_weekly (kWh) cannot be converted to the unit of previously compiled statistics (None). Generation of long term statistics will be suppressed unless the unit changes back to None or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
2023-06-01 22:42:12.165 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.bad_energy_monthly (kWh) cannot be converted to the unit of previously compiled statistics (None). Generation of long term statistics will be suppressed unless the unit changes back to None or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
2023-06-01 22:42:12.170 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.wohnzimmer_strips_energy_daily (kWh) cannot be converted to the unit of previously compiled statistics (None). Generation of long term statistics will be suppressed unless the unit changes back to None or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
2023-06-01 22:42:12.175 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.wohnzimmer_strips_energy_weekly (kWh) cannot be converted to the unit of previously compiled statistics (None). Generation of long term statistics will be suppressed unless the unit changes back to None or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
2023-06-01 22:42:12.180 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.wohnzimmer_strips_energy_monthly (kWh) cannot be converted to the unit of previously compiled statistics (None). Generation of long term statistics will be suppressed unless the unit changes back to None or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
2023-06-01 22:42:12.186 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.beleuchtung_energy_daily (kWh) cannot be converted to the unit of previously compiled statistics (None). Generation of long term statistics will be suppressed unless the unit changes back to None or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
2023-06-01 22:42:12.191 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.beleuchtung_energy_weekly (kWh) cannot be converted to the unit of previously compiled statistics (None). Generation of long term statistics will be suppressed unless the unit changes back to None or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
2023-06-01 22:42:12.197 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.beleuchtung_energy_monthly (kWh) cannot be converted to the unit of previously compiled statistics (None). Generation of long term statistics will be suppressed unless the unit changes back to None or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
2023-06-01 22:42:12.204 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.tv_energy_daily (kWh) cannot be converted to the unit of previously compiled statistics (None). Generation of long term statistics will be suppressed unless the unit changes back to None or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
2023-06-01 22:42:12.209 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.tv_energy_weekly (kWh) cannot be converted to the unit of previously compiled statistics (None). Generation of long term statistics will be suppressed unless the unit changes back to None or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
2023-06-01 22:42:12.216 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.tv_energy_monthly (kWh) cannot be converted to the unit of previously compiled statistics (None). Generation of long term statistics will be suppressed unless the unit changes back to None or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
2023-06-01 22:50:54.788 WARNING (MainThread) [custom_components.powercalc.sensors.group] skipping state for sensor.flur_1_energy, probably erroneous value or sensor was reset
2023-06-01 23:28:22.529 ERROR (MainThread) [frontend.js.latest.202305033] http://192.168.0.100:8123/frontend_latest/app-26IZhTwuAxk.js:2:0 Error: Failed to execute 'define' on 'CustomElementRegistry': the name "lg-remote-control" has already been used with this registry
2023-06-01 23:28:30.245 ERROR (MainThread) [frontend.js.latest.202305033] http://192.168.0.100:8123/frontend_latest/app-26IZhTwuAxk.js:2:0 Error: Failed to execute 'define' on 'CustomElementRegistry': the name "lg-remote-control" has already been used with this registry
2023-06-02 05:09:25.100 WARNING (MainThread) [custom_components.powercalc.sensors.group] skipping state for sensor.bad_energy, probably erroneous value or sensor was reset
2023-06-02 05:10:54.887 WARNING (MainThread) [custom_components.powercalc.sensors.group] skipping state for sensor.schlafzimmer_energy, probably erroneous value or sensor was reset
2023-06-02 08:01:29.769 WARNING (MainThread) [homeassistant.helpers.entity] Updating state for sensor.weather_heilbronn (<class 'custom_components.dwd_weather.sensor.DWDWeatherForecastSensor'>) took 0.477 seconds. Please report it to the custom integration author.
2023-06-02 16:46:03.876 WARNING (MainThread) [custom_components.sonoff.core.ewelink.cloud] Cloud ERROR: {'error': 504, 'reason': 'Request Timeout', 'deviceid': '1000cd99e0', 'apikey': 'd6c25e68-4456-4eda-9969-740c770adae1', 'sequence': '1685717158000'}
2023-06-02 22:07:51.972 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.myip is taking over 10 seconds
2023-06-03 00:00:34.316 WARNING (MainThread) [homeassistant.helpers.entity] Updating state for sensor.wind_speed_heilbronn (<class 'custom_components.dwd_weather.sensor.DWDWeatherForecastSensor'>) took 0.477 seconds. Please report it to the custom integration author.
2023-06-03 00:25:07.094 ERROR (MainThread) [homeassistant.components.forecast_solar] Unexpected error fetching forecast_solar data: The Forecast.Solar API is unreachable, 
Traceback (most recent call last):
  File "/home/homeassistant/.pyenv/versions/3.10.11/lib/python3.10/site-packages/homeassistant/helpers/update_coordinator.py", line 258, in _async_refresh
    self.data = await self._async_update_data()
  File "/home/homeassistant/.pyenv/versions/3.10.11/lib/python3.10/site-packages/homeassistant/components/forecast_solar/coordinator.py", line 65, in _async_update_data
    return await self.forecast.estimate()
  File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.10/site-packages/forecast_solar/__init__.py", line 156, in estimate
    data = await self._request(
  File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.10/site-packages/forecast_solar/__init__.py", line 111, in _request
    raise ForecastSolarConnectionError(
forecast_solar.exceptions.ForecastSolarConnectionError: The Forecast.Solar API is unreachable, 
2023-06-03 03:25:39.880 ERROR (MainThread) [homeassistant.components.forecast_solar] Unexpected error fetching forecast_solar data: The Forecast.Solar API is unreachable, 
Traceback (most recent call last):
  File "/home/homeassistant/.pyenv/versions/3.10.11/lib/python3.10/site-packages/homeassistant/helpers/update_coordinator.py", line 258, in _async_refresh
    self.data = await self._async_update_data()
  File "/home/homeassistant/.pyenv/versions/3.10.11/lib/python3.10/site-packages/homeassistant/components/forecast_solar/coordinator.py", line 65, in _async_update_data
    return await self.forecast.estimate()
  File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.10/site-packages/forecast_solar/__init__.py", line 156, in estimate
    data = await self._request(
  File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.10/site-packages/forecast_solar/__init__.py", line 111, in _request
    raise ForecastSolarConnectionError(
forecast_solar.exceptions.ForecastSolarConnectionError: The Forecast.Solar API is unreachable, 
2023-06-03 04:29:23.787 ERROR (MainThread) [frontend.js.latest.202305033] http://192.168.0.100:8123/frontend_latest/app-26IZhTwuAxk.js:2:0 Error: Failed to execute 'define' on 'CustomElementRegistry': the name "lg-remote-control" has already been used with this registry
2023-06-03 07:21:36.499 WARNING (MainThread) [custom_components.sonoff.core.ewelink.cloud] Cloud ERROR: {'error': 504, 'reason': 'Request Timeout', 'deviceid': '1000cd99e0', 'apikey': 'd6c25e68-4456-4eda-9969-740c770adae1', 'sequence': '1685769690000'}
2023-06-03 07:39:33.778 WARNING (MainThread) [homeassistant.helpers.entity] Updating state for sensor.weather_report_heilbronn (<class 'custom_components.dwd_weather.sensor.DWDWeatherForecastSensor'>) took 0.484 seconds. Please report it to the custom integration author.
2023-06-03 12:21:37.680 WARNING (MainThread) [custom_components.sonoff.core.ewelink.cloud] Cloud ERROR: {'error': 504, 'reason': 'Request Timeout', 'deviceid': '1000cd99e0', 'apikey': 'd6c25e68-4456-4eda-9969-740c770adae1', 'sequence': '1685787691000'}
2023-06-03 13:53:07.927 WARNING (MainThread) [homeassistant.components.androidtv_remote.remote] Disconnected from HyperShield at 192.168.0.20
2023-06-03 14:21:38.276 WARNING (MainThread) [custom_components.sonoff.core.ewelink.cloud] Cloud ERROR: {'error': 504, 'reason': 'Request Timeout', 'deviceid': '1000cd99e0', 'apikey': 'd6c25e68-4456-4eda-9969-740c770adae1', 'sequence': '1685794891000'}
2023-06-03 15:40:36.420 WARNING (MainThread) [custom_components.sonoff.core.ewelink.cloud] Cloud ERROR: {'error': 504, 'reason': 'Request Timeout', 'deviceid': '1000cd99e0', 'apikey': 'd6c25e68-4456-4eda-9969-740c770adae1', 'sequence': '1685799630000'}
2023-06-03 18:26:57.887 ERROR (MainThread) [homeassistant.components.forecast_solar] Unexpected error fetching forecast_solar data: The Forecast.Solar API is unreachable, 
Traceback (most recent call last):
  File "/home/homeassistant/.pyenv/versions/3.10.11/lib/python3.10/site-packages/homeassistant/helpers/update_coordinator.py", line 258, in _async_refresh
    self.data = await self._async_update_data()
  File "/home/homeassistant/.pyenv/versions/3.10.11/lib/python3.10/site-packages/homeassistant/components/forecast_solar/coordinator.py", line 65, in _async_update_data
    return await self.forecast.estimate()
  File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.10/site-packages/forecast_solar/__init__.py", line 156, in estimate
    data = await self._request(
  File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.10/site-packages/forecast_solar/__init__.py", line 111, in _request
    raise ForecastSolarConnectionError(
forecast_solar.exceptions.ForecastSolarConnectionError: The Forecast.Solar API is unreachable, 
2023-06-04 06:41:09.260 WARNING (MainThread) [custom_components.sonoff.core.ewelink.cloud] Cloud ERROR: {'error': 504, 'reason': 'Request Timeout', 'deviceid': '1000cd99e0', 'apikey': 'd6c25e68-4456-4eda-9969-740c770adae1', 'sequence': '1685853663000'}
2023-06-04 14:32:42.779 WARNING (MainThread) [homeassistant.helpers.entity] Updating state for sensor.temperature_heilbronn (<class 'custom_components.dwd_weather.sensor.DWDWeatherForecastSensor'>) took 0.452 seconds. Please report it to the custom integration author.
2023-06-04 16:41:40.815 WARNING (MainThread) [custom_components.sonoff.core.ewelink.cloud] Cloud ERROR: {'error': 504, 'reason': 'Request Timeout', 'deviceid': '1000cd99e0', 'apikey': 'd6c25e68-4456-4eda-9969-740c770adae1', 'sequence': '1685889695000'}
2023-06-05 00:29:47.938 ERROR (MainThread) [homeassistant.components.forecast_solar] Unexpected error fetching forecast_solar data: The Forecast.Solar API is unreachable, 
Traceback (most recent call last):
  File "/home/homeassistant/.pyenv/versions/3.10.11/lib/python3.10/site-packages/homeassistant/helpers/update_coordinator.py", line 258, in _async_refresh
    self.data = await self._async_update_data()
  File "/home/homeassistant/.pyenv/versions/3.10.11/lib/python3.10/site-packages/homeassistant/components/forecast_solar/coordinator.py", line 65, in _async_update_data
    return await self.forecast.estimate()
  File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.10/site-packages/forecast_solar/__init__.py", line 156, in estimate
    data = await self._request(
  File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.10/site-packages/forecast_solar/__init__.py", line 111, in _request
    raise ForecastSolarConnectionError(
forecast_solar.exceptions.ForecastSolarConnectionError: The Forecast.Solar API is unreachable, 
2023-06-05 01:47:44.021 WARNING (MainThread) [homeassistant.helpers.entity] Updating state for sensor.humidity_heilbronn (<class 'custom_components.dwd_weather.sensor.DWDWeatherForecastSensor'>) took 0.411 seconds. Please report it to the custom integration author.
2023-06-05 20:22:47.832 ERROR (MainThread) [frontend.js.latest.202305033] http://192.168.0.100:8123/frontend_latest/app-26IZhTwuAxk.js:2:0 Error: Failed to execute 'define' on 'CustomElementRegistry': the name "lg-remote-control" has already been used with this registry
2023-06-05 20:22:57.926 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration powercalc which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-06-05 20:22:57.938 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration openweathermap_all which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-06-05 20:22:57.943 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration dwd_weather which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-06-05 20:22:57.948 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration composite which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-06-05 20:22:57.952 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration sonoff which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-06-05 20:22:57.957 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration feedparser which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-06-05 20:22:57.962 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration frigate which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-06-05 20:22:57.966 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration magic_areas which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-06-05 20:22:57.970 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration saver which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-06-05 20:22:57.975 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration auto_backup which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-06-05 20:22:57.979 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-06-05 20:22:57.983 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration watchman which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-06-05 20:22:57.988 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration entity_controller which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

```

**Additional information:**

Does somebody have an idea what could be wrong here?
I already reinstalled HA. No change.

Thanks,
Hyper

**Comment by dshokouhi** [comment]
@HyperCriSiS these are logs from HA core and will not be helpful here. We need the logs from Settings > Companion App > Show and Share Logs.

Given you see a timeout error most like the issue will be in your network side as the app is not getting any response from the server. Companion App logs may be more detailed.

**Comment by HyperCriSiS** [comment]
From the same device the Web interface loads properly, so the network should be OK.
How can I get those logs? I can't get into this menu without connection.

**Comment by dshokouhi** [comment]
When you get the cannot connect pop-up you will see an option to go to Settings. That will take you to the correct location to get the logs

**Comment by dshokouhi** [comment]
now wait about 10 seconds for the pop-up to show up. It takes that long for the app to determine it cannot connect to show the pop-up

**Comment by HyperCriSiS** [comment]
There's only an OK button.
![Screenshot_20230605-223447_Home_Assistant](https://github.com/home-assistant/android/assets/11708192/4e733683-bfaa-445f-9290-b011c013214c)

**Comment by dshokouhi** [comment]
oh I thought you were able to get past the login screen since you said it cant connect "anymore". Can you try the start fresh steps to rule out bad data?

https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app

**Comment by HyperCriSiS** [comment]
I already had done that.
I could solve it now by installing the beta companion app!

**Comment by dshokouhi** [comment]
Glad you were able to solve the issue. Will close this issue now as we do not have the actual error to correct.
