### ISSUE TITLE
NFC Tags not working when multiple servers are configured

### ISSUE THREAD

**Issue by ontje-dev** [home-assistant/android#3580]
**Home Assistant Android app version(s):** 2023.3.0-full

**Android version(s):** 11

**Device model(s):** OnePlus 7T (HD1903)

**Home Assistant version:** 2023.5.4

**Last working Home Assistant release (if known):**unknown

**Description of problem, include YAML if issue is related to notifications:**
- Only one server configured NFC Tag sacns were working (local home ip)
- Add 2nd Server (for me the vpn ip of the ha istance)
- After scanning the NFC a "processing screen" is hanging and nothing happens
- Delete the 2nd server again
- Now is seems to process something, but the it is not shown as "scanned" in the app and the linked automation is not triggered
- I need to delete all data and setup a single server to get it working again

This happens even if the second server is not activated.

**Companion App Logs:**

```
06-11 22:24:34.909  8087  8087 D TagReaderActivity: Tag ID: c8578b2a-9695-4b86-a4d0-d03b1baa8de8
06-11 22:24:34.910  8087  8087 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
06-11 22:24:34.915  8087  8087 D ViewRootImpl: support adaptive color gamut feature!
06-11 22:24:34.910  8087  8087 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
06-11 22:24:34.915  8087  8087 V ViewRootImpl: The specified message queue synchronization  barrier token has not been posted or has already been removed
06-11 22:24:34.936  8087  8087 W Choreographer: Already have a pending vsync event.  There should only be one at a time.
06-11 22:24:34.939  8087  8087 D TagReaderActivity: Tag scanned to HA successfully
06-11 22:24:34.977  8087  8087 D IntegrationRepository: isAppLocked(): false. (LockEnabled: false, appActive: false, expireMillis: 1686515075840, currentMillis: 1686515074977)
06-11 22:24:34.979  8087  8087 D DecorView: onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@2a70001[TagReaderActivity]
06-11 22:24:34.981  8087  8087 D ViewRootImpl[TagReaderActivity]: windowFocusChanged hasFocus=true inTouchMode=true
06-11 22:24:34.983  8087  8087 D ViewRootImpl[TagReaderActivity]: windowFocusChanged hasFocus=false inTouchMode=true
06-11 22:24:34.992  8087  8087 D DecorView: onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@318a0ff[SettingsActivity]
06-11 22:24:34.993  8087  8087 D ViewRootImpl[SettingsActivity]: windowFocusChanged hasFocus=true inTouchMode=true
06-11 22:24:34.994  8087  8087 D IntegrationRepository: isAppLocked(): false. (LockEnabled: false, appActive: false, expireMillis: 1686515075840, currentMillis: 1686515074994)
06-11 22:24:34.995  8087  8087 D IntegrationRepository: setAppActive(): true
06-11 22:24:42.309  8087  8087 E mpanion.androi: Invalid ID 0x00000000.
06-11 22:24:42.310  8087  8087 E mpanion.androi: Invalid ID 0x00000000.
06-11 22:24:42.372  8087 20833 D LogcatReader: Read logcat for pid 8087

```

**Screenshot or video of problem:**-

**Additional information:**
- Widgets are also not working when having a second server configured

**Comment by dshokouhi** [comment]
> * Widgets are also not working when having a second server configured

please file a separate issue for this as it is unrelated to NFC tags and will have a different error message

> `06-11 22:24:34.939  8087  8087 D TagReaderActivity: Tag scanned to HA successfully`

this suggests the tag was scanned to HA without any issues.

Your logs are not long enough to determine if something else is failing as the app should loop through your registered servers and send data. Our timeout is set to 10 seconds per call but can be longer depending on the response the server may or may not give.

https://github.com/home-assistant/android/blob/a2f85ef47529dcdcb6aec72965c1236c3fe85b5f/app/src/main/java/io/homeassistant/companion/android/nfc/TagReaderActivity.kt#L69-L76

I think a video may also be helpful here

**Comment by ontje-dev** [comment]
Thank you for the repsonse. 

Logs for more than 10 seconds: 

```
06-12 21:38:03.311  5816  5816 D TagReaderActivity: Tag ID: c8578b2a-9695-4b86-a4d0-d03b1baa8de8
06-12 21:38:03.312  5816  5816 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
06-12 21:38:03.316  5816  5816 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
06-12 21:38:03.326  5816  5816 I OPFD_Manager: Dark? false, OP Force ? false
--------- beginning of system
06-12 21:38:03.327  5816  5816 D ViewRootImpl: support adaptive color gamut feature!
06-12 21:38:03.328  5816  5816 V ViewRootImpl: The specified message queue synchronization  barrier token has not been posted or has already been removed
06-12 21:38:03.356  5816  5816 W mpanion.androi: Accessing hidden method Landroid/graphics/Canvas;->drawPatch(Landroid/graphics/NinePatch;Landroid/graphics/Rect;Landroid/graphics/Paint;)V (greylist-max-o, linking, denied)
06-12 21:38:03.356  5816  5816 W mpanion.androi: Accessing hidden method Landroid/graphics/Canvas;->drawPatch(Landroid/graphics/NinePatch;Landroid/graphics/RectF;Landroid/graphics/Paint;)V (greylist-max-o, linking, denied)
06-12 21:38:03.390  5816  5816 W Choreographer: Already have a pending vsync event.  There should only be one at a time.
06-12 21:38:03.398  5816  5816 D TagReaderActivity: Tag scanned to HA successfully
06-12 21:38:03.414  5816  5816 D DecorView: onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@54d517c[TagReaderActivity]
06-12 21:38:03.415  5816  5816 D ViewRootImpl[TagReaderActivity]: windowFocusChanged hasFocus=true inTouchMode=true
06-12 21:38:03.442  5816  5816 D ViewRootImpl[TagReaderActivity]: windowFocusChanged hasFocus=false inTouchMode=true
06-12 21:38:13.297  5816  7706 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
06-12 21:38:13.297  5816  7706 D ServerConnectionInfo: Using external URL
06-12 21:38:13.300  5816  7706 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
06-12 21:38:13.300  5816  7706 D ServerConnectionInfo: Using external URL
06-12 21:38:13.370  5816 13849 D WebSocketRepository: Websocket: onOpen
06-12 21:38:13.370  5816 13849 D WebSocketRepository: Websocket: onMessage (text)
06-12 21:38:13.372  5816 13849 D WebSocketRepository: Message number null received
06-12 21:38:13.372  5816  7706 D WebSocketRepository: Auth Requested
06-12 21:38:13.378  5816 13849 D WebSocketRepository: Websocket: onMessage (text)
06-12 21:38:13.379  5816 13849 D WebSocketRepository: Message number null received
06-12 21:38:13.381  5816  7706 D WebSocketRepository: Sending message 50: {type=supported_features, id=50, features={coalesce_messages=1}}
06-12 21:38:13.382  5816  7706 D WebSocketRepository: Resubscribing to active subscriptions...
06-12 21:38:13.382  5816  7706 D WebSocketRepository: Sending message 51: {type=subscribe_trigger, trigger={platform=state, entity_id=[sensor.solar_produktion]}, id=51}
06-12 21:38:13.383  5816  7706 D WebSocketRepository: Message number 51 sent
06-12 21:38:13.387  5816 13849 D WebSocketRepository: Websocket: onMessage (text)
06-12 21:38:13.388  5816 13849 D WebSocketRepository: Message number 50 received
06-12 21:38:13.394  5816 13849 D WebSocketRepository: Websocket: onMessage (text)
06-12 21:38:13.395  5816 13849 D WebSocketRepository: Message number 51 received
06-12 21:38:13.396  5816  7706 D WebSocketRepository: Sending message 52: {type=subscribe_trigger, trigger={platform=state, entity_id=[sensor.energymeter_power_curr]}, id=52}
06-12 21:38:13.396  5816  7706 D WebSocketRepository: Message number 52 sent
06-12 21:38:13.401  5816 13849 D WebSocketRepository: Websocket: onMessage (text)
06-12 21:38:13.402  5816 13849 D WebSocketRepository: Message number 52 received
06-12 21:38:25.680  5816  5816 D WebviewActivity: Matter commissioning status changed to NOT_STARTED
```

I did not made a video, since currently the phone only vibrates without any change or something happeing on the screen.

**Comment by dshokouhi** [comment]
anything you can tell us about the second server setup? hard to tell from the logs but is API access granted? do you see any errors in HA core on the second server? as of now i dont see any failures

**Comment by jpelgrom** [comment]
> > `06-11 22:24:34.939  8087  8087 D TagReaderActivity: Tag scanned to HA successfully`
> 
> this suggests the tag was scanned to HA without any issues.

Yes but also no; it should show success or failure for _each_ configured server in the logs (the log statement is inside the loop). If there are two servers where is the second entry?

**Comment by ontje-dev** [comment]
it is the same server only over vpn, i activate it when i am not at home

**Comment by dshokouhi** [comment]
> > > `06-11 22:24:34.939  8087  8087 D TagReaderActivity: Tag scanned to HA successfully`
> > 
> > 
> > this suggests the tag was scanned to HA without any issues.
> 
> Yes but also no; it should show success or failure for _each_ configured server in the logs (the log statement is inside the loop). If there are two servers where is the second entry?

thats why i was asking about hte second server setup, after 10 seconds we shoudlve seen a failure unless the server was taking longer to respond or something else which is why I requested HA core logs

**Comment by ontje-dev** [comment]
the logs are from a configuration with only ONE server, i deleted the second server after the scan did not work. but it still is not working anymore

**Comment by ontje-dev** [comment]
> Even after deleting the server, the app's registration/webhook might still be broken. To properly fix this, you have to [completely start over](https://companion.home-assistant.io/docs/troubleshooting/faqs#starting-fresh-with-the-android-app).
> 
> External URL and Home Assistant URL are the same, sorry for the confusion (it is called external internally). So you'd set your VPN URL as the Home Assistant URL, add the internal network, and the other URL as the internal URL.

thanks for the support, i did reset the app and configured the server with internal / external urls.

it seems to work now. the widgets are working again too.

thanks again for the nice app and the help! i thought i would be "smart" to have the same server twice with different urls without knowing the impact and the possible solution using external/internal url settings.

thanks again 👍 ❤️

**Comment by joskfg** [comment]
I have the same issue:

```
Jose Manuel, [10/9/23 21:00]
09-10 20:53:01.039  7253  7253 D TagReaderActivity: Tag ID: 1dc9de96-ac90-44ce-b8cb-087d4c31c663
09-10 20:53:01.039  7253  7253 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
09-10 20:53:01.040  7253  7253 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
09-10 20:53:01.040  7253  7253 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
09-10 20:53:01.043  7253  7253 D WindowManager: Add to mViews: DecorView@ca2c5b3[TagReaderActivity],pkg= io.homeassistant.companion.android
09-10 20:53:01.046  7253  7253 D InputEventReceiver: Input log is disabled
09-10 20:53:01.048  7253  7253 E OplusBracketLog: [OplusViewMirrorManager] updateHostViewRootIfNeeded, not support android.view.ViewRootImpl@7b0636e
09-10 20:53:01.049  7253  7253 D AutofillManager: Fill dialog is enabled:false, hints=[password, passwordAuto, creditCardNumber, creditCardSecurityCode, creditCardExpirationDate]
09-10 20:53:01.060  7253  7253 D BufferQueueConsumer: [](id:1c5500000015,api:0,p:-1,c:7253) connect: controlledByApp=false
09-10 20:53:01.060  7253  7253 E IPCThreadState: attemptIncStrongHandle(110): Not supported
09-10 20:53:01.060  7253 20032 D BufferQueueProducer: [VRI[TagReaderActivity]#21(BLAST Consumer)21](id:1c5500000015,api:1,p:7253,c:7253) connect: api=1 producerControlledByApp=true
09-10 20:53:01.061  7253  7253 D VRI[TagReaderActivity]: registerCallbacksForSync syncBuffer=false
09-10 20:53:01.063  7253 20032 D VRI[TagReaderActivity]: Received frameCommittedCallback lastAttemptedDrawFrameNum=1 didProduceBuffer=true syncBuffer=false
09-10 20:53:01.065  7253 20032 W Parcel  : Expecting binder but got null!
09-10 20:53:01.065  7253  7253 D VRI[TagReaderActivity]: draw finished.
09-10 20:53:01.066  7253  7253 I Quality : Skipped: false 2 cost 17.856625 refreshRate 8306600 bit true processName io.homeassistant.companion.android
09-10 20:53:01.069  7253  7253 E TagReaderActivity: Tag not scanned to HA
09-10 20:53:01.069  7253  7253 E TagReaderActivity: io.homeassistant.companion.android.common.data.integration.IntegrationException: Error calling integration request scan_tag
09-10 20:53:01.069  7253  7253 E TagReaderActivity:  at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl.scanTag(IntegrationRepositoryImpl.kt:308)
09-10 20:53:01.069  7253  7253 E TagReaderActivity:  at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl$scanTag$1.invokeSuspend(Unknown Source:15)
09-10 20:53:01.069  7253  7253 E TagReaderActivity:  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
09-10 20:53:01.069  7253  7253 E TagReaderActivity:  at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
09-10 20:53:01.069  7253  7253 E TagReaderActivity:  at android.os.Handler.handleCallback(Handler.java:942)
09-10 20:53:01.069  7253  7253 E TagReaderActivity:  at android.os.Handler.dispatchMessage(Handler.java:99)
09-10 20:53:01.069  7253  7253 E TagReaderActivity:  at android.os.Looper.loopOnce(Looper.java:240)
09-10 20:53:01.069  7253  7253 E TagReaderActivity:  at android.os.Looper.loop(Looper.java:351)
09-10 20:53:01.069  7253  7253 E TagReaderActivity:  at android.app.ActivityThread.main(ActivityThread.java:8422)
09-10 20:53:01.069  7253  7253 E TagReaderActivity:  at java.lang.reflect.Method.invoke(Native Method)
09-10 20:53:01.069  7253  7253 E TagReaderActivity:  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
09-10 20:53:01.069  7253  7253 E TagReaderActivity:  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
09-10 20:53:01.082  7253  7253 D VRI[TagReaderActivity]: registerCallbacksForSync syncBuffer=false
09-10 20:53:01.084  7253 20032 D VRI[TagReaderActivity]: Received frameCommittedCallback lastAttemptedDrawFrameNum=3 didProduceBuffer=true syncBuffer=false
09-10 20:53:01.084  7253  7253 D VRI[TagReaderActivity]: draw finished.
09-10 20:53:01.094  7253  7253 D VRI[TagReader

Jose Manuel, [10/9/23 21:00]
Activity]: onFocusEvent true
09-10 20:53:01.094  7253  7253 D VRI[TagReaderActivity]: send msg MSG_WINDOW_FOCUS_CHANGED with caller android.view.ViewRootImplExtImpl.markAndDumpWindowFocusChangeMsg:956 android.view.ViewRootImpl.windowFocusChanged:9837 android.view.ViewRootImpl$WindowInputEventReceiver.onFocusEvent:9550 android.os.MessageQueue.nativePollOnce:-2 android.os.MessageQueue.next:349 android.os.Looper.loopOnce:186 android.os.Looper.loop:351 android.app.ActivityThread.main:8422 java.lang.reflect.Method.invoke:-2 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run:584 com.android.internal.os.ZygoteInit.main:1013 <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> 
09-10 20:53:01.094  7253  7253 D VRI[TagReaderActivity]: handleWindowFocusChanged mWindowFocusChanged true mUpcomingWindowFocus true mAdded true
09-10 20:53:01.255  7253  7253 D TagReaderActivity: Tag scanned to HA successfully
09-10 20:53:01.268  7253 22451 D ColorModeChangeItem: preExecute mColorMode=0,token=android.os.BinderProxy@75ee776
09-10 20:53:01.280  7253  7253 D VRI[TagReaderActivity]: onFocusEvent false
09-10 20:53:01.280  7253  7253 D VRI[TagReaderActivity]: send msg MSG_WINDOW_FOCUS_CHANGED with caller android.view.ViewRootImplExtImpl.markAndDumpWindowFocusChangeMsg:956 android.view.ViewRootImpl.windowFocusChanged:9837 android.view.ViewRootImpl$WindowInputEventReceiver.onFocusEvent:9550 android.os.MessageQueue.nativePollOnce:-2 android.os.MessageQueue.next:349 android.os.Looper.loopOnce:186 android.os.Looper.loop:351 android.app.ActivityThread.main:8422 java.lang.reflect.Method.invoke:-2 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run:584 com.android.internal.os.ZygoteInit.main:1013 <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> 
09-10 20:53:01.280  7253  7253 I Quality : Skipped: true 1 cost 15.971736 refreshRate 8309578 bit true processName io.homeassistant.companion.android
09-10 20:53:01.281  7253  7253 D IntegrationRepository: isAppLocked(): false. (LockEnabled: false, appActive: false, expireMillis: 1694371982001, currentMillis: 1694371981281)
09-10 20:53:01.282  7253  7253 D VRI[TagReaderActivity]: handleWindowFocusChanged mWindowFocusChanged true mUpcomingWindowFocus false mAdded true
09-10 20:53:01.295  7253  7253 D VRI[SettingsActivity]: onFocusEvent true
09-10 20:53:01.295  7253  7253 D VRI[SettingsActivity]: send msg MSG_WINDOW_FOCUS_CHANGED with caller android.view.ViewRootImplExtImpl.markAndDumpWindowFocusChangeMsg:956 android.view.ViewRootImpl.windowFocusChanged:9837 android.view.ViewRootImpl$WindowInputEventReceiver.onFocusEvent:9550 android.os.MessageQueue.nativePollOnce:-2 android.os.MessageQueue.next:349 android.os.Looper.loopOnce:186 android.os.Looper.loop:351 android.app.ActivityThread.main:8422 java.lang.reflect.Method.invoke:-2 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run:584 com.android.internal.os.ZygoteInit.main:1013 <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> 
09-10 20:53:01.295  7253  7253 D VRI[SettingsActivity]: handleWindowFocusChanged mWindowFocusChanged true mUpcomingWindowFocus true mAdded true
09-10 20:53:01.295  7253  7253 D IntegrationRepository: isAppLocked(): false. (LockEnabled: false, appActive: false, expireMillis: 1694371982001, currentMillis: 1694371981295)
09-10 20:53:01.295  7253  7253 D IntegrationRepository: setAppActive(): true
09-10 20:53:01.886  7253 22446 D VRI[TagReaderActivity]: dispatchAppVisibility visible:false
09-10 20:53:01.900  7253  7253 D OpenGLRenderer: RenderProxy::destroy: this=0xb400007c78236e00, mContext=0xb400007c28c2fe40
09-10 20:53:01.900  7253 20032 D OpenGLRenderer: S

Jose Manuel, [10/9/23 21:00]
kiaOpenGLPipeline::setSurface: this=0xb400007c78a60900, surface=NULL
09-10 20:53:01.901  7253 20032 D BufferQueueProducer: [VRI[TagReaderActivity]#21(BLAST Consumer)21](id:1c5500000015,api:1,p:7253,c:7253) disconnect: api 1
09-10 20:53:01.908  7253  7253 D VRI[TagReaderActivity]: setWindowStopped stopped:true
09-10 20:53:01.911  7253  7253 D OplusScrollToTopManager: io.homeassistant.companion.android/io.homeassistant.companion.android.nfc.TagReaderActivity,window dying
09-10 20:53:01.911  7253  7253 D OplusScrollToTopManager: io.homeassistant.companion.android/io.homeassistant.companion.android.nfc.TagReaderActivity,unregisterSystemUIBroadcastReceiver 
09-10 20:53:01.911  7253  7253 D OplusScrollToTopManager: io.homeassistant.companion.android/io.homeassistant.companion.android.nfc.TagReaderActivity, unregisterSystemUIBroadcastReceiver failed java.lang.IllegalArgumentException: Receiver not registered: android.view.OplusScrollToTopManager$2@16a4084
09-10 20:53:01.912  7253  7253 D OpenGLRenderer: RenderProxy::destroy: this=0xb400007c78236e00, mContext=0xb400007c28c2fe40
09-10 20:53:01.912  7253 20032 D OpenGLRenderer: SkiaOpenGLPipeline::setSurface: this=0xb400007c78a60900, surface=NULL
09-10 20:53:01.915  7253 22446 D BufferQueueConsumer: [VRI[TagReaderActivity]#21(BLAST Consumer)21](id:1c5500000015,api:0,p:-1,c:7253) disconnect
09-10 20:53:02.297  7253  7253 D OplusScrollToTopManager: io.homeassistant.companion.android/io.homeassistant.companion.android.settings.SettingsActivity,This DecorView@7322d37[SettingsActivity] change focus to true
09-10 20:53:03.570  7253  7253 D LocBroadcastReceiver: Received location update.
09-10 20:53:03.573  7253  7253 D ForegrndServiceLauncher: Check if service HighAccuracyLocationService is running. Service running = false
09-10 20:53:03.574  7253 15192 D LocBroadcastReceiver: Last Location: 
09-10 20:53:03.574  7253 15192 D LocBroadcastReceiver: Coords:(41.4306835, 2.1804825)
09-10 20:53:03.574  7253 15192 D LocBroadcastReceiver: Accuracy: 100.0
09-10 20:53:03.574  7253 15192 D LocBroadcastReceiver: Bearing: 0.0
09-10 20:53:03.574  7253 15192 D LocBroadcastReceiver: Begin evaluating if location update should be skipped
09-10 20:53:03.574  7253 15192 D LocBroadcastReceiver: Received location that is 35 milliseconds old, 1694371983539 compared to 1694371983574 with source fused
09-10 20:53:03.574  7253 15192 D LocBroadcastReceiver: Duplicate location received, not sending to HA
09-10 20:53:03.666  7253  7253 D VRI[SettingsActivity]: handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
09-10 20:53:03.666  7253  7253 V AutofillManager: requestHideFillUi(null): anchor = null
09-10 20:53:03.679  7253  7253 D VRI[SettingsActivity]: handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
09-10 20:53:03.728  7253  7253 D VRI[SettingsActivity]: handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
09-10 20:53:03.729  7253  7253 D VRI[SettingsActivity]: handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
09-10 20:53:03.747  7253  7253 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
09-10 20:53:03.747  7253  7253 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
09-10 20:53:03.747  7253  7253 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
09-10 20:53:03.759  7253  7253 V TextView: notifyAutoFillManagerAfterTextChanged
09-10 20:53:03.759  7253  7253 V AutofillManager: notifyValueChanged(1073741838): ignoring on state UNKNOWN
09-10 20:53:03.778  7253 20032 D OpenGLRenderer: SkiaOpenGLPipeline::setSurface: this=0xb400007c78a60900, surface=NULL
09-10 20:53:05.175  7253  7253 D VRI[SettingsActivity]: handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
09-10 20:53:05.175  7253  7253 V AutofillManager: requestHideFillUi(null): anchor = null
09-10 20:53:05.188  7253  7253 D VRI[SettingsActivity]: handleWindowFocusChanged mWindowFocusC

Jose Manuel, [10/9/23 21:00]
hanged false mUpcomingWindowFocus true mAdded true
09-10 20:53:05.201  7253  7253 D VRI[SettingsActivity]: handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
09-10 20:53:05.212  7253  7253 D VRI[SettingsActivity]: handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
09-10 20:53:05.221  7253  7253 D VRI[SettingsActivity]: handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
09-10 20:53:05.222  7253  7253 D VRI[SettingsActivity]: handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
09-10 20:53:05.238  7253  7253 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
09-10 20:53:05.238  7253  7253 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
09-10 20:53:05.238  7253  7253 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
09-10 20:53:05.244  7253  7253 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
09-10 20:53:05.244  7253  7253 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
09-10 20:53:05.244  7253  7253 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
09-10 20:53:05.245  7253  7253 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
09-10 20:53:05.245  7253  7253 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
09-10 20:53:05.245  7253  7253 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
09-10 20:53:05.248  7253  7253 I Quality : Skipped: false 1 cost 11.162068 refreshRate 8270771 bit true processName io.homeassistant.companion.android
09-10 20:53:05.249  7253  7253 V TextView: notifyAutoFillManagerAfterTextChanged
09-10 20:53:05.249  7253  7253 V AutofillManager: notifyValueChanged(1073741839): ignoring on state UNKNOWN
09-10 20:53:05.249  7253  7253 V TextView: notifyAutoFillManagerAfterTextChanged
09-10 20:53:05.249  7253  7253 V AutofillManager: notifyValueChanged(1073741839): ignoring on state UNKNOWN
09-10 20:53:05.249  7253  7253 V TextView: notifyAutoFillManagerAfterTextChanged
09-10 20:53:05.249  7253  7253 V AutofillManager: notifyValueChanged(1073741839): ignoring on state UNKNOWN
09-10 20:53:05.251  7253  7253 V TextView: notifyAutoFillManagerAfterTextChanged
09-10 20:53:05.251  7253  7253 V AutofillManager: notifyValueChanged(1073741840): ignoring on state UNKNOWN
09-10 20:53:05.251  7253  7253 V TextView: notifyAutoFillManagerAfterTextChanged
09-10 20:53:05.251  7253  7253 V AutofillManager: notifyValueChanged(1073741840): ignoring on state UNKNOWN
09-10 20:53:05.251  7253  7253 V TextView: notifyAutoFillManagerAfterTextChanged
09-10 20:53:05.251  7253  7253 V AutofillManager: notifyValueChanged(1073741840):
```

In the logs I can see when the tag is triggered to the server that is expected to fail because it is not configured, it shows `TagReaderActivity: Tag not scanned to HA` and in the right one `TagReaderActivity: Tag scanned to HA successfully`. So it seems to work, but the automation is not triggered and I don't see any error in the Core Logs (I cleared them before the scan and they remain empty).

**Comment by jpelgrom** [comment]
@joskfg Please don't comment on old closed issues with limited information like this. It's really hard to help like this and probably unrelated.

> So it seems to work, but the automation is not triggered and I don't see any error in the Core Logs

Keep it simple: listen for `tag_scanned` events in developer tools, does anything show up when scanning the tag? If so, the app is working and something else may be wrong.

If nothing shows up in developer tools, please create a new issue and make sure to fill in the template.
