### ISSUE TITLE
Error when call "service: stop_cover_tilt" from widget

### ISSUE THREAD

**Issue by Philippe12** [home-assistant/android#3596]
**Home Assistant Android app version(s):** 2023.6.0-full

**Android version(s):** 13 

**Device model(s):** Pixel 6a

**Home Assistant version:** 2023.6.2

**Last working Home Assistant release (if known):** NA

**Description of problem, include YAML if issue is related to notifications:**

When I try to use widget to control my cover, I have a error. This functionnality is broken from Home Assistant Android app version 2023.1.1 

**Companion App Logs:**

```
06-19 08:54:25.569 14419 14419 D ButtonWidget: Broadcast received: 
06-19 08:54:25.569 14419 14419 D ButtonWidget: Broadcast action: io.homeassistant.companion.android.widgets.button.ButtonWidget.CALL_SERVICE_AUTH
06-19 08:54:25.569 14419 14419 D ButtonWidget: AppWidgetId: 14
06-19 08:54:25.570 14419 14419 D ButtonWidget: Calling authentication, then configured service
06-19 08:54:25.587 14419 14419 D WidgetAuthenticationA: onCreate in WidgetAuthenticationActivity called
06-19 08:54:26.661 14419 14668 D WebSocketRepository: Websocket: onMessage (text)
06-19 08:54:26.663 14419 15242 D WebSocketRepository: Message number 26 received
06-19 08:54:27.710 14419 14419 D WidgetAuthenticationA: Authentication successful, calling requested service
06-19 08:54:27.745 14419 14419 D ButtonWidget: Broadcast received: 
06-19 08:54:27.745 14419 14419 D ButtonWidget: Broadcast action: io.homeassistant.companion.android.widgets.button.ButtonWidget.CALL_SERVICE
06-19 08:54:27.745 14419 14419 D ButtonWidget: AppWidgetId: 14
06-19 08:54:27.746 14419 14419 D ButtonWidget: Calling widget service
06-19 08:54:27.753 14419 14419 D ButtonWidget: Service Call Data loaded:
06-19 08:54:27.753 14419 14419 D ButtonWidget: domain: cover
06-19 08:54:27.753 14419 14419 D ButtonWidget: service: stop_cover_tilt
06-19 08:54:27.753 14419 14419 D ButtonWidget: service_data: {"entity_id":["cover.porte_garage"]}
06-19 08:54:27.756 14419 14419 D ButtonWidget: Sending service call to Home Assistant
06-19 08:54:27.757 14419 14419 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: false
06-19 08:54:28.039 14419 17369 D TrafficStats: tagSocket(67) with statsTag=0xffffffff, statsUid=-1
06-19 08:54:28.288 14419 14419 E ButtonWidget: Could not send service call.
06-19 08:54:28.288 14419 14419 E ButtonWidget: io.homeassistant.companion.android.common.data.integration.IntegrationException: Error calling integration request call_service
06-19 08:54:28.288 14419 14419 E ButtonWidget: 	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl.callService(IntegrationRepositoryImpl.kt:279)
06-19 08:54:28.288 14419 14419 E ButtonWidget: 	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl$callService$1.invokeSuspend(Unknown Source:15)
06-19 08:54:28.288 14419 14419 E ButtonWidget: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
06-19 08:54:28.288 14419 14419 E ButtonWidget: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
06-19 08:54:28.288 14419 14419 E ButtonWidget: 	at android.os.Handler.handleCallback(Handler.java:942)
06-19 08:54:28.288 14419 14419 E ButtonWidget: 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-19 08:54:28.288 14419 14419 E ButtonWidget: 	at android.os.Looper.loopOnce(Looper.java:201)
06-19 08:54:28.288 14419 14419 E ButtonWidget: 	at android.os.Looper.loop(Looper.java:288)
06-19 08:54:28.288 14419 14419 E ButtonWidget: 	at android.app.ActivityThread.main(ActivityThread.java:7884)
06-19 08:54:28.288 14419 14419 E ButtonWidget: 	at java.lang.reflect.Method.invoke(Native Method)
06-19 08:54:28.288 14419 14419 E ButtonWidget: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
06-19 08:54:28.288 14419 14419 E ButtonWidget: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
06-19 08:54:28.290 14419 14419 D CompatibilityChangeReporter: Compat change id reported: 147798919; UID 10239; state: ENABLED
06-19 08:54:31.580 14419 14419 D IntegrationRepository: isAppLocked(): false. (LockEnabled: false, appActive: false, expireMillis: 1687157666265, currentMillis: 1687157671580)
06-19 08:54:32.271 14419 14419 I Choreographer: Skipped 40 frames!  The application may be doing too much work on its main thread.
06-19 08:54:32.282 14419 14419 D IntegrationRepository: isAppLocked(): false. (LockEnabled: false, appActive: false, expireMillis: 1687157666265, currentMillis: 1687157672282)
06-19 08:54:32.282 14419 14419 D IntegrationRepository: setAppActive(): true
06-19 08:54:32.520 14419 15242 D LogcatReader: Read logcat for pid 14419
```

**Screenshot or video of problem:**
![Screenshot_20230619-084503](https://github.com/home-assistant/android/assets/5462247/8d517838-183e-4979-92dd-f5fe5d72c85a)

**Additional information:**
NA

**Comment by jpelgrom** [comment]
Is there anything in your server logs when executing the call? 

> This functionnality is broken from Home Assistant Android app version 2023.1.1

Nothing changed in that release for widgets, interesting. I'm assuming it worked correctly in the stable release before that one (2022.12.0)?

**Comment by Philippe12** [comment]
I not see any log 
I have only on nginx log

'''
[19/Jun/2023:20:29:07 +0200] - 410 410 - POST https xxxx.xxxxx.duckdns.org "/api/webhook/9522c1a90aeb2517726765f6cfda02d3299a65a68b2e5dfa5b5275a2af62c3ac" [Client 172.30.32.1] [Length 0] [Gzip -] [Sent-to 192.168.1.2] "Home Assistant/2023.6.0-10170 (Android 13; Pixel 6a)" "-"
'''

**Comment by jpelgrom** [comment]
Code 410 corresponds to gone - your webhook probably isn't working.

Did you perhaps delete the device in Home Assistant? Do sensors and other service calls work correctly?

**Comment by Philippe12** [comment]
I have a widget with temperature display that it work correctly. But any button not work light, automation, cover or any test button

**Comment by Philippe12** [comment]
Thank for your reply.
I had to remove (untinstall) all Home assistant App from my phone and reinstall.
Now all look like ok
