### ISSUE TITLE
Android 14 Crash in onboarding when empty base url in auto-discovered ha instance

### ISSUE THREAD

**Issue by bgmeiner84** [home-assistant/android#3744]
**Home Assistant Android app version(s):**
2023-7.8-full
Manual build (6c8f67faad038918ba7b7657b556a429f6b8a4af)

**Android version(s):**
Android 14 Beta 4

**Device model(s):**
Pixel 7a, 

**Home Assistant version:**
2023.7.3

**Last working Home Assistant release (if known):**
It is working on a Galaxy S20 FE with Android 11 (same app version, same home assistant instance)

**Description of problem, include YAML if issue is related to notifications:**
During onboarding, the app will crash and since there is no way to skip discovery the app is basically deadlocked. A workaround is to leave the affected network (e.g. disable wifi) and then manually enter the server address.

**Companion App Logs:**

```
E  FATAL EXCEPTION: NsdManager
Process: io.homeassistant.companion.android, PID: 2249
      java.net.MalformedURLException: no protocol: 
      at java.net.URL.<init>(URL.java:601)
      at java.net.URL.<init>(URL.java:498)
      at java.net.URL.<init>(URL.java:447)
      at io.homeassistant.companion.android.onboarding.discovery.HomeAssistantSearcher$onServiceFound$1.onServiceResolved(HomeAssistantSearcher.kt:101)
      at android.net.nsd.NsdManager$ServiceHandler.lambda$handleMessage$11(NsdManager.java:920)
      at android.net.nsd.NsdManager$ServiceHandler$$ExternalSyntheticLambda2.run(Unknown Source:4)
      at android.net.nsd.NsdManager$$ExternalSyntheticLambda0.execute(Unknown Source:0)
      at android.net.nsd.NsdManager$ServiceHandler.handleMessage(NsdManager.java:920)
      at android.os.Handler.dispatchMessage(Handler.java:106)
      at android.os.Looper.loopOnce(Looper.java:205)
      at android.os.Looper.loop(Looper.java:294)
      at android.os.HandlerThread.run(HandlerThread.java:67)

```

**Screenshot or video of problem:**

https://github.com/home-assistant/android/assets/47703952/9bb7b2cb-1055-4f91-8bee-85e740957fdf

**Additional information:**
This happens because in HomeAssistantSearcher.kt (line 99), baseurl checks for null but gets an empty array and then crashes when it tries to convert it to an Url:
<img width="570" alt="baseurl_pixel7a_android13" src="https://github.com/home-assistant/android/assets/47703952/682ea826-bd09-4f43-af6d-8dab8a08ff53">

On an older Galaxy S20FE (Android 11), the same setup returns null which is handled in the code:
<img width="553" alt="baseurl_galaxys20fe_android11" src="https://github.com/home-assistant/android/assets/47703952/f5effa29-57e6-40e0-bf24-5c462eb1b18b">

I haven't figured out yet why my ha instance is not being auto-discovered but it's probably some misconfiguration with the ssl certificate: 
<img width="467" alt="baseurl_ha_url_config" src="https://github.com/home-assistant/android/assets/47703952/85e283a9-34e7-48d3-96b8-bb47e8f3bf1d">

A bit of a long shot, but it might be related to change 270306772 (https://developer.android.com/about/versions/14/reference/compat-framework-changes)

![image](https://github.com/home-assistant/android/assets/47703952/b919cb28-45c9-4104-b6c4-aa0abae6187d)

**Comment by dshokouhi** [comment]
> I haven't figured out yet why my ha instance is not being auto-discovered but it's probably some misconfiguration with the ssl certificate:

could be many reasons, my instance is not always detected either

> A bit of a long shot, but it might be related to change 270306772 (https://developer.android.com/about/versions/14/reference/compat-framework-changes)
> 
> ![image](https://user-images.githubusercontent.com/47703952/257344990-b919cb28-45c9-4104-b6c4-aa0abae6187d.png)

This is actually saying it impacts apps that target Android 14 however our app does not target it yet

**Comment by dshokouhi** [comment]
are there any other logs above this crash? we do ahve some debug statements which may be of use here

**Comment by jpelgrom** [comment]
Thanks for the detailed report. I've submitted a PR to fix this, linked above, but wasn't able to replicate the issue on the Android 14 beta on my device (Google Pixel 7a). Would you be willing to run the PR and see if it resolves the issue for you?

**Comment by bgmeiner84** [comment]
Wow that was fast... :) Sorry for not replying sooner, didn't have time today at work. I can confirm that the updated code prevents the crash, everything is working fine now. Funny how it has different behavior on the same device, but it's probably a good idea to be defensive here anyways. Now I just need to figure out what's wrong with my ha instance ;).

Thanks for the great work!
