### ISSUE TITLE
NFC Tags not triggering automations

### ISSUE THREAD

**Issue by joskfg** [home-assistant/android#3856]
**Home Assistant Android app version(s):** 2023.8.2-full

**Android version(s):** 13

**Device model(s):** OnePlus 9 Pro

**Home Assistant version:** 2023.9.1

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**

As described in https://github.com/home-assistant/android/issues/3580#issuecomment-1712913051 when a tag is scanned, the automations are not being triggered.

**Companion App Logs:**

```
09-10 20:53:01.039  7253  7253 D TagReaderActivity: Tag ID: 1dc9de96-ac90-44ce-b8cb-087d4c31c663
09-10 20:53:01.039  7253  7253 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
09-10 20:53:01.040  7253  7253 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
09-10 20:53:01.040  7253  7253 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
09-10 20:53:01.043  7253  7253 D WindowManager: Add to mViews: DecorView@ca2c5b3[TagReaderActivity],pkg= io.homeassistant.companion.android
09-10 20:53:01.046  7253  7253 D InputEventReceiver: Input log is disabled
09-10 20:53:01.048  7253  7253 E OplusBracketLog: [OplusViewMirrorManager] updateHostViewRootIfNeeded, not support android.view.ViewRootImpl@7b0636e
09-10 20:53:01.049  7253  7253 D AutofillManager: Fill dialog is enabled:false, hints=[password, passwordAuto, creditCardNumber, creditCardSecurityCode, creditCardExpirationDate]
09-10 20:53:01.060  7253  7253 D BufferQueueConsumer: [](id:1c5500000015,api:0,p:-1,c:7253) connect: controlledByApp=false
09-10 20:53:01.060  7253  7253 E IPCThreadState: attemptIncStrongHandle(110): Not supported
09-10 20:53:01.060  7253 20032 D BufferQueueProducer: [VRI[TagReaderActivity]#21(BLAST Consumer)21](id:1c5500000015,api:1,p:7253,c:7253) connect: api=1 producerControlledByApp=true
09-10 20:53:01.061  7253  7253 D VRI[TagReaderActivity]: registerCallbacksForSync syncBuffer=false
09-10 20:53:01.063  7253 20032 D VRI[TagReaderActivity]: Received frameCommittedCallback lastAttemptedDrawFrameNum=1 didProduceBuffer=true syncBuffer=false
09-10 20:53:01.065  7253 20032 W Parcel  : Expecting binder but got null!
09-10 20:53:01.065  7253  7253 D VRI[TagReaderActivity]: draw finished.
09-10 20:53:01.066  7253  7253 I Quality : Skipped: false 2 cost 17.856625 refreshRate 8306600 bit true processName io.homeassistant.companion.android
09-10 20:53:01.069  7253  7253 E TagReaderActivity: Tag not scanned to HA
09-10 20:53:01.069  7253  7253 E TagReaderActivity: io.homeassistant.companion.android.common.data.integration.IntegrationException: Error calling integration request scan_tag
09-10 20:53:01.069  7253  7253 E TagReaderActivity:  at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl.scanTag(IntegrationRepositoryImpl.kt:308)
09-10 20:53:01.069  7253  7253 E TagReaderActivity:  at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl$scanTag$1.invokeSuspend(Unknown Source:15)
09-10 20:53:01.069  7253  7253 E TagReaderActivity:  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
09-10 20:53:01.069  7253  7253 E TagReaderActivity:  at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
09-10 20:53:01.069  7253  7253 E TagReaderActivity:  at android.os.Handler.handleCallback(Handler.java:942)
09-10 20:53:01.069  7253  7253 E TagReaderActivity:  at android.os.Handler.dispatchMessage(Handler.java:99)
09-10 20:53:01.069  7253  7253 E TagReaderActivity:  at android.os.Looper.loopOnce(Looper.java:240)
09-10 20:53:01.069  7253  7253 E TagReaderActivity:  at android.os.Looper.loop(Looper.java:351)
09-10 20:53:01.069  7253  7253 E TagReaderActivity:  at android.app.ActivityThread.main(ActivityThread.java:8422)
09-10 20:53:01.069  7253  7253 E TagReaderActivity:  at java.lang.reflect.Method.invoke(Native Method)
09-10 20:53:01.069  7253  7253 E TagReaderActivity:  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
09-10 20:53:01.069  7253  7253 E TagReaderActivity:  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
09-10 20:53:01.082  7253  7253 D VRI[TagReaderActivity]: registerCallbacksForSync syncBuffer=false
09-10 20:53:01.084  7253 20032 D VRI[TagReaderActivity]: Received frameCommittedCallback lastAttemptedDrawFrameNum=3 didProduceBuffer=true syncBuffer=false
09-10 20:53:01.084  7253  7253 D VRI[TagReaderActivity]: draw finished.
09-10 20:53:01.094  7253  7253 D VRI[TagReader
Activity]: onFocusEvent true
09-10 20:53:01.094  7253  7253 D VRI[TagReaderActivity]: send msg MSG_WINDOW_FOCUS_CHANGED with caller android.view.ViewRootImplExtImpl.markAndDumpWindowFocusChangeMsg:956 android.view.ViewRootImpl.windowFocusChanged:9837 android.view.ViewRootImpl$WindowInputEventReceiver.onFocusEvent:9550 android.os.MessageQueue.nativePollOnce:-2 android.os.MessageQueue.next:349 android.os.Looper.loopOnce:186 android.os.Looper.loop:351 android.app.ActivityThread.main:8422 java.lang.reflect.Method.invoke:-2 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run:584 com.android.internal.os.ZygoteInit.main:1013 <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> 
09-10 20:53:01.094  7253  7253 D VRI[TagReaderActivity]: handleWindowFocusChanged mWindowFocusChanged true mUpcomingWindowFocus true mAdded true
09-10 20:53:01.255  7253  7253 D TagReaderActivity: Tag scanned to HA successfully
09-10 20:53:01.268  7253 22451 D ColorModeChangeItem: preExecute mColorMode=0,token=android.os.BinderProxy@75ee776
09-10 20:53:01.280  7253  7253 D VRI[TagReaderActivity]: onFocusEvent false
09-10 20:53:01.280  7253  7253 D VRI[TagReaderActivity]: send msg MSG_WINDOW_FOCUS_CHANGED with caller android.view.ViewRootImplExtImpl.markAndDumpWindowFocusChangeMsg:956 android.view.ViewRootImpl.windowFocusChanged:9837 android.view.ViewRootImpl$WindowInputEventReceiver.onFocusEvent:9550 android.os.MessageQueue.nativePollOnce:-2 android.os.MessageQueue.next:349 android.os.Looper.loopOnce:186 android.os.Looper.loop:351 android.app.ActivityThread.main:8422 java.lang.reflect.Method.invoke:-2 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run:584 com.android.internal.os.ZygoteInit.main:1013 <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> 
09-10 20:53:01.280  7253  7253 I Quality : Skipped: true 1 cost 15.971736 refreshRate 8309578 bit true processName io.homeassistant.companion.android
09-10 20:53:01.281  7253  7253 D IntegrationRepository: isAppLocked(): false. (LockEnabled: false, appActive: false, expireMillis: 1694371982001, currentMillis: 1694371981281)
09-10 20:53:01.282  7253  7253 D VRI[TagReaderActivity]: handleWindowFocusChanged mWindowFocusChanged true mUpcomingWindowFocus false mAdded true
09-10 20:53:01.295  7253  7253 D VRI[SettingsActivity]: onFocusEvent true
09-10 20:53:01.295  7253  7253 D VRI[SettingsActivity]: send msg MSG_WINDOW_FOCUS_CHANGED with caller android.view.ViewRootImplExtImpl.markAndDumpWindowFocusChangeMsg:956 android.view.ViewRootImpl.windowFocusChanged:9837 android.view.ViewRootImpl$WindowInputEventReceiver.onFocusEvent:9550 android.os.MessageQueue.nativePollOnce:-2 android.os.MessageQueue.next:349 android.os.Looper.loopOnce:186 android.os.Looper.loop:351 android.app.ActivityThread.main:8422 java.lang.reflect.Method.invoke:-2 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run:584 com.android.internal.os.ZygoteInit.main:1013 <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> 
09-10 20:53:01.295  7253  7253 D VRI[SettingsActivity]: handleWindowFocusChanged mWindowFocusChanged true mUpcomingWindowFocus true mAdded true
09-10 20:53:01.295  7253  7253 D IntegrationRepository: isAppLocked(): false. (LockEnabled: false, appActive: false, expireMillis: 1694371982001, currentMillis: 1694371981295)
09-10 20:53:01.295  7253  7253 D IntegrationRepository: setAppActive(): true
09-10 20:53:01.886  7253 22446 D VRI[TagReaderActivity]: dispatchAppVisibility visible:false
09-10 20:53:01.900  7253  7253 D OpenGLRenderer: RenderProxy::destroy: this=0xb400007c78236e00, mContext=0xb400007c28c2fe40
09-10 20:53:01.900  7253 20032 D OpenGLRenderer: S
kiaOpenGLPipeline::setSurface: this=0xb400007c78a60900, surface=NULL
09-10 20:53:01.901  7253 20032 D BufferQueueProducer: [VRI[TagReaderActivity]#21(BLAST Consumer)21](id:1c5500000015,api:1,p:7253,c:7253) disconnect: api 1
09-10 20:53:01.908  7253  7253 D VRI[TagReaderActivity]: setWindowStopped stopped:true
09-10 20:53:01.911  7253  7253 D OplusScrollToTopManager: io.homeassistant.companion.android/io.homeassistant.companion.android.nfc.TagReaderActivity,window dying
09-10 20:53:01.911  7253  7253 D OplusScrollToTopManager: io.homeassistant.companion.android/io.homeassistant.companion.android.nfc.TagReaderActivity,unregisterSystemUIBroadcastReceiver 
09-10 20:53:01.911  7253  7253 D OplusScrollToTopManager: io.homeassistant.companion.android/io.homeassistant.companion.android.nfc.TagReaderActivity, unregisterSystemUIBroadcastReceiver failed java.lang.IllegalArgumentException: Receiver not registered: android.view.OplusScrollToTopManager$2@16a4084
09-10 20:53:01.912  7253  7253 D OpenGLRenderer: RenderProxy::destroy: this=0xb400007c78236e00, mContext=0xb400007c28c2fe40
09-10 20:53:01.912  7253 20032 D OpenGLRenderer: SkiaOpenGLPipeline::setSurface: this=0xb400007c78a60900, surface=NULL
09-10 20:53:01.915  7253 22446 D BufferQueueConsumer: [VRI[TagReaderActivity]#21(BLAST Consumer)21](id:1c5500000015,api:0,p:-1,c:7253) disconnect
09-10 20:53:02.297  7253  7253 D OplusScrollToTopManager: io.homeassistant.companion.android/io.homeassistant.companion.android.settings.SettingsActivity,This DecorView@7322d37[SettingsActivity] change focus to true
09-10 20:53:03.570  7253  7253 D LocBroadcastReceiver: Received location update.
09-10 20:53:03.573  7253  7253 D ForegrndServiceLauncher: Check if service HighAccuracyLocationService is running. Service running = false
09-10 20:53:03.574  7253 15192 D LocBroadcastReceiver: Last Location: 
09-10 20:53:03.574  7253 15192 D LocBroadcastReceiver: Coords:(41.4306835, 2.1804825)
09-10 20:53:03.574  7253 15192 D LocBroadcastReceiver: Accuracy: 100.0
09-10 20:53:03.574  7253 15192 D LocBroadcastReceiver: Bearing: 0.0
09-10 20:53:03.574  7253 15192 D LocBroadcastReceiver: Begin evaluating if location update should be skipped
09-10 20:53:03.574  7253 15192 D LocBroadcastReceiver: Received location that is 35 milliseconds old, 1694371983539 compared to 1694371983574 with source fused
09-10 20:53:03.574  7253 15192 D LocBroadcastReceiver: Duplicate location received, not sending to HA
09-10 20:53:03.666  7253  7253 D VRI[SettingsActivity]: handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
09-10 20:53:03.666  7253  7253 V AutofillManager: requestHideFillUi(null): anchor = null
09-10 20:53:03.679  7253  7253 D VRI[SettingsActivity]: handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
09-10 20:53:03.728  7253  7253 D VRI[SettingsActivity]: handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
09-10 20:53:03.729  7253  7253 D VRI[SettingsActivity]: handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
09-10 20:53:03.747  7253  7253 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
09-10 20:53:03.747  7253  7253 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
09-10 20:53:03.747  7253  7253 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
09-10 20:53:03.759  7253  7253 V TextView: notifyAutoFillManagerAfterTextChanged
09-10 20:53:03.759  7253  7253 V AutofillManager: notifyValueChanged(1073741838): ignoring on state UNKNOWN
09-10 20:53:03.778  7253 20032 D OpenGLRenderer: SkiaOpenGLPipeline::setSurface: this=0xb400007c78a60900, surface=NULL
09-10 20:53:05.175  7253  7253 D VRI[SettingsActivity]: handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
09-10 20:53:05.175  7253  7253 V AutofillManager: requestHideFillUi(null): anchor = null
09-10 20:53:05.188  7253  7253 D VRI[SettingsActivity]: handleWindowFocusChanged mWindowFocusC
hanged false mUpcomingWindowFocus true mAdded true
09-10 20:53:05.201  7253  7253 D VRI[SettingsActivity]: handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
09-10 20:53:05.212  7253  7253 D VRI[SettingsActivity]: handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
09-10 20:53:05.221  7253  7253 D VRI[SettingsActivity]: handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
09-10 20:53:05.222  7253  7253 D VRI[SettingsActivity]: handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
09-10 20:53:05.238  7253  7253 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
09-10 20:53:05.238  7253  7253 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
09-10 20:53:05.238  7253  7253 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
09-10 20:53:05.244  7253  7253 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
09-10 20:53:05.244  7253  7253 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
09-10 20:53:05.244  7253  7253 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
09-10 20:53:05.245  7253  7253 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
09-10 20:53:05.245  7253  7253 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
09-10 20:53:05.245  7253  7253 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
09-10 20:53:05.248  7253  7253 I Quality : Skipped: false 1 cost 11.162068 refreshRate 8270771 bit true processName io.homeassistant.companion.android
09-10 20:53:05.249  7253  7253 V TextView: notifyAutoFillManagerAfterTextChanged
09-10 20:53:05.249  7253  7253 V AutofillManager: notifyValueChanged(1073741839): ignoring on state UNKNOWN
09-10 20:53:05.249  7253  7253 V TextView: notifyAutoFillManagerAfterTextChanged
09-10 20:53:05.249  7253  7253 V AutofillManager: notifyValueChanged(1073741839): ignoring on state UNKNOWN
09-10 20:53:05.249  7253  7253 V TextView: notifyAutoFillManagerAfterTextChanged
09-10 20:53:05.249  7253  7253 V AutofillManager: notifyValueChanged(1073741839): ignoring on state UNKNOWN
09-10 20:53:05.251  7253  7253 V TextView: notifyAutoFillManagerAfterTextChanged
09-10 20:53:05.251  7253  7253 V AutofillManager: notifyValueChanged(1073741840): ignoring on state UNKNOWN
09-10 20:53:05.251  7253  7253 V TextView: notifyAutoFillManagerAfterTextChanged
09-10 20:53:05.251  7253  7253 V AutofillManager: notifyValueChanged(1073741840): ignoring on state UNKNOWN
09-10 20:53:05.251  7253  7253 V TextView: notifyAutoFillManagerAfterTextChanged
09-10 20:53:05.251  7253  7253 V AutofillManager: notifyValueChanged(1073741840):
```

**Screenshot or video of problem:**

https://github.com/home-assistant/android/assets/524887/9d7f7fed-a273-4d46-ba08-39ae66296564

**Additional information:**
I have two servers and the tag is only active in one of them, it is actually shown in the logs, but the server is not getting the event. I tried the scan checking the events in the developer tools but it is not received. I recorded a video test with a new tag, the behavior is the same.

**Comment by dshokouhi** [comment]
Can you please force stop the app, open it again, reproduce the issue, then grab the fresh state of logs?  I see an error but it's generic and the logs don't look like there is anything before it and it's possible there is another error occurring earlier.

```
09-10 20:53:01.069 7253 7253 E TagReaderActivity: Tag not scanned to HA 09-10 20:53:01.069 7253 7253 E TagReaderActivity: io.homeassistant.companion.android.common.data.integration.IntegrationException: Error calling integration request scan_tag 09-10 20:53:01.069 7253 7253 E TagReaderActivity: at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl.scanTag(IntegrationRepositoryImpl.kt:308)
```

**Comment by joskfg** [comment]
Full log after force stop, run and just scan the tag. Doing the minimum possible.

[homeassistant_companion_log_8-11-2023_16-41-39.txt](https://github.com/home-assistant/android/files/12577495/homeassistant_companion_log_8-11-2023_16-41-39.txt)

**Comment by jpelgrom** [comment]
Your logs suggest the app's webhook, which is used for communication with your server, is broken (HTTP 410 response codes). As a result, the tag scanned event may be ignored by the server. This can happen when the device name is re-used on the same server.

To fix this issue, log out from the app (profile menu) and log in again. If you know there are 2 registrations with the same name, make sure to use another one :) Then, after logging in, scan the tag again and it should now work correctly.

**Comment by joskfg** [comment]
It worked! It seems the management of the devices can be improved :sweat_smile:

Thanks
