### ISSUE TITLE
No sound response in Assist

### ISSUE THREAD

**Issue by amaciuc** [home-assistant/android#3897]
**Home Assistant Android app version(s):**
`2023.9.2-full`
**Android version(s):**
`12`
**Device model(s):**
`Samsung Note 10+`
**Home Assistant version:**
`2023.9.3`
**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
When I am using the Voice Assistant, text-to-speech doesn't work somehow. Assistant responses with a text message, but without audio. 
I checked the `tts` notifications by calling a `notify` service, the audio works. 
In Assist pipeline (in configuration popup), at `Text-to-speech` section I tried the voices, they sound. Only when I trigger the Assist popup, the audio doesn't work.

I also tried on another Samsung smartphone (S20 FE), same issue.

Am I missing something? Do I have to change some special setting ?

**Companion App Logs:**

```
09-28 17:54:46.632 14049 14049 D WebSocketRepository: Sending message 9: {type=assist_pipeline/run, start_stage=stt, end_stage=tts, input={sample_rate=44100}, conversation_id=null, pipeline=01h9j6x70v6kxqnct5kpy3e5tj, id=9}
09-28 17:54:46.632 14049 14049 D WebSocketRepository: Message number 9 sent
09-28 17:54:46.676 14049 14270 D WebSocketRepository: Websocket: onMessage (text)
09-28 17:54:46.682 14049 14130 D WebSocketRepository: Message number 8 received
09-28 17:54:46.719 14049 14270 D WebSocketRepository: Websocket: onMessage (text)
09-28 17:54:46.721 14049 14270 D WebSocketRepository: Websocket: onMessage (text)
09-28 17:54:46.721 14049 14130 D WebSocketRepository: Message number 9 received
09-28 17:54:46.723 14049 14130 D WebSocketRepository: Message number 9 received
09-28 17:54:46.724 14049 14130 D WebSocketRepository: Message number 9 received
09-28 17:54:47.015 14049 14270 D WebSocketRepository: Websocket: onMessage (text)
09-28 17:54:47.017 14049 14134 D WebSocketRepository: Message number 9 received
09-28 17:54:48.547 14049 14270 D WebSocketRepository: Websocket: onMessage (text)
09-28 17:54:48.550 14049 14134 D WebSocketRepository: Message number 9 received
09-28 17:54:48.744 14049 14057 I mpanion.androi: Background concurrent copying GC freed 337769(11MB) AllocSpace objects, 0(0B) LOS objects, 49% free, 10MB/21MB, paused 69us,51us total 110.438ms
09-28 17:54:49.111 14049 14049 D LocBroadcastReceiver: Got single accurate location update: Location[fused 47.637310,26.237262 hAcc=17.792 et=+3d6h11m53s829ms alt=400.6999816894531 vAcc=2.04897 vel=0.27292114 bear=237.83426]
09-28 17:54:49.111 14049 14049 D LocBroadcastReceiver: Location accurate enough, all done with high accuracy.
09-28 17:54:49.112 14049 14049 D LocBroadcastReceiver: Last Location: 
09-28 17:54:49.112 14049 14049 D LocBroadcastReceiver: Coords:(47.63731, 26.2372618)
09-28 17:54:49.112 14049 14049 D LocBroadcastReceiver: Accuracy: 17.792
09-28 17:54:49.112 14049 14049 D LocBroadcastReceiver: Bearing: 237.83426
09-28 17:54:49.113 14049 14049 D LocBroadcastReceiver: Begin evaluating if location update should be skipped
09-28 17:54:49.113 14049 14049 D LocBroadcastReceiver: Received location that is 114 milliseconds old, 1695912888999 compared to 1695912889113 with source fused
09-28 17:54:49.119 14049 14152 D ServerConnectionInfo: localUrl is: true, usesInternalSsid is: false, usesWifi is: false
09-28 17:54:49.122 14049 14049 D LocBroadcastReceiver: Received location update.
09-28 17:54:49.124 14049 14049 D ForegrndServiceLauncher: Check if service HighAccuracyLocationService is running. Service running = false
09-28 17:54:49.125 14049 14134 D LocBroadcastReceiver: Last Location: 
09-28 17:54:49.125 14049 14134 D LocBroadcastReceiver: Coords:(47.63731, 26.2372618)
09-28 17:54:49.125 14049 14134 D LocBroadcastReceiver: Accuracy: 17.792
09-28 17:54:49.125 14049 14134 D LocBroadcastReceiver: Bearing: 237.83426
09-28 17:54:49.126 14049 14152 D LocBroadcastReceiver: Last Location: 
09-28 17:54:49.126 14049 14152 D LocBroadcastReceiver: Coords:(47.63731, 26.2372618)
09-28 17:54:49.126 14049 14152 D LocBroadcastReceiver: Accuracy: 17.792
09-28 17:54:49.126 14049 14152 D LocBroadcastReceiver: Bearing: 237.83426
09-28 17:54:49.127 14049 14134 D LocBroadcastReceiver: Begin evaluating if location update should be skipped
09-28 17:54:49.127 14049 14134 D LocBroadcastReceiver: Skipping old location update since time is before the last one we sent, received: 1695912888999 last sent: {2=1695912856271, 5=1695912889113}
09-28 17:54:49.128 14049 14152 D LocBroadcastReceiver: Begin evaluating if location update should be skipped
09-28 17:54:49.128 14049 14152 D LocBroadcastReceiver: Received location that is 129 milliseconds old, 1695912888999 compared to 1695912889128 with source fused
09-28 17:54:49.130 14049 14152 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: false
09-28 17:54:49.178 14049 14152 E LocBroadcastReceiver: Could not update location for 2.
09-28 17:54:49.178 14049 14152 E LocBroadcastReceiver: io.homeassistant.companion.android.common.data.integration.IntegrationException: Error calling integration request update_location
09-28 17:54:49.178 14049 14152 E LocBroadcastReceiver: 	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl.updateLocation(IntegrationRepositoryImpl.kt:246)
09-28 17:54:49.178 14049 14152 E LocBroadcastReceiver: 	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl$updateLocation$1.invokeSuspend(Unknown Source:15)
09-28 17:54:49.178 14049 14152 E LocBroadcastReceiver: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
09-28 17:54:49.178 14049 14152 E LocBroadcastReceiver: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
09-28 17:54:49.178 14049 14152 E LocBroadcastReceiver: 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
09-28 17:54:49.178 14049 14152 E LocBroadcastReceiver: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
09-28 17:54:49.178 14049 14152 E LocBroadcastReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
09-28 17:54:49.178 14049 14152 E LocBroadcastReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
09-28 17:54:49.178 14049 14152 E LocBroadcastReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
09-28 17:54:49.178 14049 14152 E LocBroadcastReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
09-28 17:54:49.205 14049 14152 D LocBroadcastReceiver: Location update sent successfully for 5 as exact
09-28 17:54:49.477 14049 14270 D WebSocketRepository: Websocket: onMessage (text)
09-28 17:54:49.483 14049 14152 D WebSocketRepository: Message number 9 received
09-28 17:54:49.487 14049 14270 D WebSocketRepository: Websocket: onMessage (text)
09-28 17:54:49.495 14049 14134 D WebSocketRepository: Message number 9 received
09-28 17:54:49.510 14049 14152 D WebSocketRepository: Message number 9 received
09-28 17:54:49.571 14049 14134 D WebSocketRepository: Message number 9 received
09-28 17:54:49.571 14049 14134 D WebSocketRepository: Message number 9 received
09-28 17:54:49.611 14049 14134 D WebSocketRepository: Message number 9 received
09-28 17:54:49.629 14049 14049 D ServerConnectionInfo: localUrl is: true, usesInternalSsid is: false, usesWifi is: false
09-28 17:54:49.629 14049 14049 D ServerConnectionInfo: Using external URL
09-28 17:54:49.630 14049 14150 V MediaPlayer-JNI: native_setup
09-28 17:54:49.630 14049 14150 V MediaPlayerNative: constructor
09-28 17:54:49.631 14049 14150 V MediaPlayerNative: setListener
09-28 17:54:49.632 14049 14133 D WebSocketRepository: Unsubscribing from assist_pipeline/run with data {start_stage=stt, end_stage=tts, input={sample_rate=44100}, conversation_id=null, pipeline=01h9j6x70v6kxqnct5kpy3e5tj}
09-28 17:54:49.633 14049 14133 D WebSocketRepository: Sending message 10: {type=unsubscribe_events, subscription=9, id=10}
09-28 17:54:49.634 14049 14133 D WebSocketRepository: Message number 10 sent
09-28 17:54:49.635 14049 14150 V MediaPlayer-JNI: setParameter: key 1400
09-28 17:54:49.635 14049 14150 V MediaPlayerNative: MediaPlayer::setParameter(1400)
09-28 17:54:49.637 14049 14150 V MediaHTTPService: MediaHTTPService(android.media.MediaHTTPService@a7fc9e2): Cookies: null
09-28 17:54:49.674 14049 14270 D WebSocketRepository: Websocket: onMessage (text)
09-28 17:54:49.677 14049 14133 D WebSocketRepository: Message number 10 received
09-28 17:54:49.695 14049 14150 V MediaPlayerNative: setVideoSurfaceTexture
09-28 17:54:49.696 14049 14150 V MediaPlayerNative: prepareAsync
09-28 17:54:49.705 14049 14061 V MediaHTTPService: makeHTTPConnection: CookieManager created: java.net.CookieManager@eb80173
09-28 17:54:49.705 14049 14061 V MediaHTTPService: makeHTTPConnection(android.media.MediaHTTPService@a7fc9e2): cookieHandler: java.net.CookieManager@eb80173 Cookies: null
09-28 17:54:49.717 14049 14061 I MediaHTTPConnection: setReadTimeout and setConnectTimeout with 8000ms
09-28 17:54:49.722 14049 14270 D WebSocketRepository: Websocket: onClosing code: 1000, reason: 
09-28 17:54:49.722 14049 14270 D WebSocketRepository: Websocket: onClosed
09-28 17:54:49.946 14049 14061 I MediaHTTPConnection: response code = 200
09-28 17:54:50.040 14049 14061 V MediaPlayerNative: message received msg=200, ext1=10973, ext2=0
09-28 17:54:50.040 14049 14061 W MediaPlayerNative: info/warning (10973, 0)
09-28 17:54:50.044 14049 14061 V MediaPlayerNative: message received msg=1, ext1=0, ext2=0
09-28 17:54:50.044 14049 14061 V MediaPlayerNative: MediaPlayer::notify() prepared
09-28 17:54:50.050 14049 14049 V MediaPlayerNative: invoke 76
09-28 17:54:50.052 14049 14049 V MediaPlayer-JNI: start
09-28 17:54:50.052 14049 14049 V MediaPlayerNative: start
09-28 17:54:50.140 14049 14061 V MediaPlayerNative: message received msg=3, ext1=100, ext2=0
09-28 17:54:50.140 14049 14061 V MediaPlayerNative: buffering 100
09-28 17:54:50.159 14049 14061 V MediaPlayerNative: message received msg=10000, ext1=13, ext2=3
09-28 17:54:50.159 14049 14061 V MediaPlayerNative: message received msg=10000, ext1=13, ext2=3
09-28 17:54:50.162 14049 14061 V MediaPlayerNative: message received msg=6, ext1=0, ext2=0
09-28 17:54:50.182 14049 14049 V MediaPlayer-JNI: getCurrentPosition: 0 (msec)
09-28 17:54:50.404 14049 14061 V MediaPlayerNative: message received msg=211, ext1=0, ext2=0
09-28 17:54:50.404 14049 14061 V MediaPlayerNative: message received msg=211, ext1=0, ext2=0
09-28 17:54:52.119 14049 14049 I ViewRootImpl@32b6f81[AssistActivity]: ViewPostIme pointer 0
09-28 17:54:52.119 14049 14049 I MSHandlerLifeCycle: isMultiSplitHandlerRequested: windowingMode=1 isFullscreen=true isPopOver=false isHidden=false skipActivityType=false isHandlerType=true this: DecorView@7ee4302[AssistActivity]
09-28 17:54:52.156 14049 14049 I MSHandlerLifeCycle: isMultiSplitHandlerRequested: windowingMode=1 isFullscreen=true isPopOver=false isHidden=false skipActivityType=false isHandlerType=true this: DecorView@7ee4302[AssistActivity]
09-28 17:54:52.173 14049 14049 I MSHandlerLifeCycle: isMultiSplitHandlerRequested: windowingMode=1 isFullscreen=true isPopOver=false isHidden=false skipActivityType=false isHandlerType=true this: DecorView@7ee4302[AssistActivity]
09-28 17:54:52.189 14049 14049 I MSHandlerLifeCycle: isMultiSplitHandlerRequested: windowingMode=1 isFullscreen=true isPopOver=false isHidden=false skipActivityType=false isHandlerType=true this: DecorView@7ee4302[AssistActivity]
09-28 17:54:52.194 14049 14049 I MSHandlerLifeCycle: isMultiSplitHandlerRequested: windowingMode=1 isFullscreen=true isPopOver=false isHidden=false skipActivityType=false isHandlerType=true this: DecorView@7ee4302[AssistActivity]
09-28 17:54:52.194 14049 14049 I ViewRootImpl@32b6f81[AssistActivity]: ViewPostIme pointer 1
09-28 17:54:52.194 14049 14049 I MSHandlerLifeCycle: isMultiSplitHandlerRequested: windowingMode=1 isFullscreen=true isPopOver=false isHidden=false skipActivityType=false isHandlerType=true this: DecorView@7ee4302[AssistActivity]
09-28 17:54:52.240 14049 14049 V MediaPlayer-JNI: stop
09-28 17:54:52.240 14049 14049 V MediaPlayerNative: stop
09-28 17:54:52.240 14049 14049 V MediaPlayer: resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
09-28 17:54:52.240 14049 14049 V MediaPlayer: cleanDrmObj: mDrmObj=null mDrmSessionId=null
09-28 17:54:52.240 14049 14049 V MediaPlayer-JNI: release
09-28 17:54:52.240 14049 14049 V MediaPlayerNative: setListener
09-28 17:54:52.240 14049 14049 V MediaPlayerNative: disconnect
09-28 17:54:52.241 14049 14289 V MediaPlayerNative: message received msg=8, ext1=0, ext2=0
09-28 17:54:52.241 14049 14289 V MediaPlayerNative: notify(8, 0, 0) callback on disconnected mediaplayer
09-28 17:54:52.241 14049 14289 V MediaPlayerNative: message received msg=211, ext1=0, ext2=0
09-28 17:54:52.241 14049 14289 V MediaPlayerNative: notify(211, 0, 0) callback on disconnected mediaplayer
09-28 17:54:52.243 14049 14049 V MediaPlayerNative: destructor
09-28 17:54:52.243 14049 14049 V MediaPlayerNative: disconnect
```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
I think you also need a speech to text engine configured as well? Have you set one up too?

**Comment by amaciuc** [comment]
> I think you also need a speech to text engine configured as well? Have you set one up too?

Yes

![image](https://github.com/home-assistant/android/assets/19391765/9ab67fb3-905b-4d32-9536-ed934a10a05f)

**Comment by jpelgrom** [comment]
Your log files do suggest it is playing back audio for the response (17:54:50-17:54:52). Is the media volume on? Does it work correctly if you use another voice?

Your device's STT/TTS isn't used for Assist, so text-to-speech notifications are unrelated to Assist.

**Comment by amaciuc** [comment]
I found the problem -> `Bixby Voice`

![image](https://github.com/home-assistant/android/assets/19391765/375e84e1-5207-4706-b4e6-e66860459d70)

From unknown reason, the volume of Bixby Voice was off. The volume slider shown only when I try to have a conversation in Assist (so stupid). After the sound is delivered, the volume slider for Bixby disappears.  

Thank you guys for helping me and sorry that I bothered you with a problem that actually came from my fault.

**Comment by jpelgrom** [comment]
Really odd that Samsung renamed it to Bixby Voice while it is in fact for any assistant app... Glad you figured it out!
