### ISSUE TITLE
Android widget works slowly and fail randomic over 4G, works flawlessly on local WiFi and personal VPN 4G 

### ISSUE THREAD

**Issue by razorbac91** [home-assistant/android#3950]
**Home Assistant Android app version(s):**
2023.10.2-full
**Android version(s):**
12
**Device model(s):**
Samsung a10e
**Home Assistant version:**
2023.10.3
**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
My Android widgets are very slow over 4G. I created various widget (script, call service switch on, etc) everyone work flawlessly if i'm connected via local wifi and when i'm on 4G connected to my personal Wireguard server that runs on the same host of Home assistant. 
If i try to trigger them when i'm on 4G they take almost 10 sec to triggers and sometimes doesn't work at all. 
As test i tried to replicate the API command with RESTer from a local PC (9ms response) and from a pc connected in tethering to my phone (92ms response) and both seams to be ok.
The companion app has all the authorizations, allowed background activity, data saver is disabled, etc.

**Companion App Logs:**

```
10-18 20:53:36.593  5723  5786 D ServerConnectionInfo: localUrl is: true, usesInternalSsid is: false, usesWifi is: false
10-18 20:53:36.603  5723  5786 D ServerConnectionInfo: localUrl is: true, usesInternalSsid is: false, usesWifi is: false
10-18 20:53:36.611  5723  5786 D ServerConnectionInfo: localUrl is: true, usesInternalSsid is: false, usesWifi is: false
10-18 20:53:36.623  5723  5786 D ServerConnectionInfo: localUrl is: true, usesInternalSsid is: false, usesWifi is: false
10-18 20:53:36.625  5723  5762 D WebSocketRepository: Sending message 15: {type=ping, id=15}
10-18 20:53:36.626  5723  5762 D WebSocketRepository: Message number 15 sent
10-18 20:53:36.676  5723  8064 D WebSocketRepository: Websocket: onMessage (text)
10-18 20:53:36.677  5723  5786 D WebSocketRepository: Message number 15 received
10-18 20:53:39.895  5723  5723 D ButtonWidget: Broadcast received: 
10-18 20:53:39.895  5723  5723 D ButtonWidget: Broadcast action: io.homeassistant.companion.android.widgets.button.ButtonWidget.CALL_SERVICE
10-18 20:53:39.895  5723  5723 D ButtonWidget: AppWidgetId: 12
10-18 20:53:39.902  5723  5723 D ButtonWidget: Calling widget service
10-18 20:53:39.903  5723  5723 D AppWidgetManager: partiallyUpdateAppWidget() appWidgetIds = [12]
10-18 20:53:39.911  5723  5723 D ButtonWidget: Service Call Data loaded:
10-18 20:53:39.911  5723  5723 D ButtonWidget: domain: script
10-18 20:53:39.911  5723  5723 D ButtonWidget: service: pc_wol_fisso
10-18 20:53:39.911  5723  5723 D ButtonWidget: service_data: {}
10-18 20:53:39.931  5723  5723 D ButtonWidget: Sending service call to Home Assistant
10-18 20:53:39.939  5723  5723 D ServerConnectionInfo: localUrl is: true, usesInternalSsid is: false, usesWifi is: false
10-18 20:53:50.427  5723  5723 D ButtonWidget: Service call sent successfully
10-18 20:53:50.427  5723  5723 D AppWidgetManager: partiallyUpdateAppWidget() appWidgetIds = [12]
10-18 20:53:51.460  5723  5723 I AppWidgetManager: updateAppWidget() appWidgetIds = [12]
10-18 20:53:53.994  5723  8064 E WebSocketRepository: Websocket: onFailure
10-18 20:53:53.994  5723  8064 E WebSocketRepository: java.net.SocketException: Software caused connection abort
10-18 20:53:53.994  5723  8064 E WebSocketRepository: 	at java.net.SocketInputStream.socketRead0(Native Method)
10-18 20:53:53.994  5723  8064 E WebSocketRepository: 	at java.net.SocketInputStream.socketRead(SocketInputStream.java:119)
10-18 20:53:53.994  5723  8064 E WebSocketRepository: 	at java.net.SocketInputStream.read(SocketInputStream.java:176)
10-18 20:53:53.994  5723  8064 E WebSocketRepository: 	at java.net.SocketInputStream.read(SocketInputStream.java:144)
10-18 20:53:53.994  5723  8064 E WebSocketRepository: 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:945)
10-18 20:53:53.994  5723  8064 E WebSocketRepository: 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:909)
10-18 20:53:53.994  5723  8064 E WebSocketRepository: 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:824)
10-18 20:53:53.994  5723  8064 E WebSocketRepository: 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:797)
10-18 20:53:53.994  5723  8064 E WebSocketRepository: 	at okio.InputStreamSource.read(JvmOkio.kt:94)
10-18 20:53:53.994  5723  8064 E WebSocketRepository: 	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:125)
10-18 20:53:53.994  5723  8064 E WebSocketRepository: 	at okio.RealBufferedSource.request(RealBufferedSource.kt:206)
10-18 20:53:53.994  5723  8064 E WebSocketRepository: 	at okio.RealBufferedSource.require(RealBufferedSource.kt:199)
10-18 20:53:53.994  5723  8064 E WebSocketRepository: 	at okio.RealBufferedSource.readByte(RealBufferedSource.kt:209)
10-18 20:53:53.994  5723  8064 E WebSocketRepository: 	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.kt:119)
10-18 20:53:53.994  5723  8064 E WebSocketRepository: 	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:102)
10-18 20:53:53.994  5723  8064 E WebSocketRepository: 	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
10-18 20:53:53.994  5723  8064 E WebSocketRepository: 	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
10-18 20:53:53.994  5723  8064 E WebSocketRepository: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
10-18 20:53:53.994  5723  8064 E WebSocketRepository: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-18 20:53:53.994  5723  8064 E WebSocketRepository: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-18 20:53:53.994  5723  8064 E WebSocketRepository: 	at java.lang.Thread.run(Thread.java:920)
10-18 20:53:55.362  5723  5723 D ButtonWidget: Broadcast received: 
10-18 20:53:55.362  5723  5723 D ButtonWidget: Broadcast action: io.homeassistant.companion.android.widgets.button.ButtonWidget.CALL_SERVICE
10-18 20:53:55.362  5723  5723 D ButtonWidget: AppWidgetId: 12
10-18 20:53:55.362  5723  5723 D ButtonWidget: Calling widget service
10-18 20:53:55.362  5723  5723 D AppWidgetManager: partiallyUpdateAppWidget() appWidgetIds = [12]
10-18 20:53:55.365  5723  5723 D ButtonWidget: Service Call Data loaded:
10-18 20:53:55.365  5723  5723 D ButtonWidget: domain: script
10-18 20:53:55.365  5723  5723 D ButtonWidget: service: pc_wol_fisso
10-18 20:53:55.365  5723  5723 D ButtonWidget: service_data: {}
10-18 20:53:55.366  5723  5723 D ButtonWidget: Sending service call to Home Assistant
10-18 20:53:55.370  5723  5723 D ServerConnectionInfo: localUrl is: true, usesInternalSsid is: false, usesWifi is: false
10-18 20:53:55.492  5723  5723 D ButtonWidget: Service call sent successfully
10-18 20:53:55.493  5723  5723 D AppWidgetManager: partiallyUpdateAppWidget() appWidgetIds = [12]
10-18 20:53:56.499  5723  5723 I AppWidgetManager: updateAppWidget() appWidgetIds = [12]
10-18 20:53:59.995  5723  5723 I ViewRootImpl@5436103[WebViewActivity]: handleAppVisibility mAppVisible=false visible=true
10-18 20:54:00.001  5723  5723 I SurfaceView@73ba888: onWindowVisibilityChanged(4) false android.view.SurfaceView{73ba888 G.E...... ......I. 0,0-0,0} of ViewRootImpl@5436103[WebViewActivity]
10-18 20:54:00.002  5723  5819 D OpenGLRenderer: setSurface called with nullptr
10-18 20:54:00.007  5723  5723 I ViewRootImpl@5436103[WebViewActivity]: Relayout returned: old=(0,0,1080,2280) new=(0,0,1080,2280) req=(1080,2280)4 dur=3 res=0x1 s={false 0} ch=false fn=-1
10-18 20:54:00.008  5723  5723 I ViewRootImpl@5436103[WebViewActivity]: stopped(false) old=true
10-18 20:54:00.027  5723  5723 D WebviewActivity: Matter commissioning status changed to NOT_STARTED
10-18 20:54:00.029  5723  5723 I ViewRootImpl@5436103[WebViewActivity]: stopped(false) old=false
10-18 20:54:00.034  5723  5723 D ServerConnectionInfo: localUrl is: true, usesInternalSsid is: false, usesWifi is: false
10-18 20:54:00.040  5723  5723 D ServerConnectionInfo: localUrl is: true, usesInternalSsid is: false, usesWifi is: false
10-18 20:54:00.042  5723  5723 D IntegrationRepository: isAppLocked(): false. (LockEnabled: false, appActive: false, expireMillis: 0, currentMillis: 1697655240041)
10-18 20:54:00.045  5723  5723 I DecorView: notifyKeepScreenOnChanged: keepScreenOn=false
10-18 20:54:00.073  5723  5768 D ConnectivityManager: StackLog: [android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:3925)] [android.net.ConnectivityManager.registerDefaultNetworkCallbackForUid(ConnectivityManager.java:4489)] [android.net.ConnectivityManager.registerDefaultNetworkCallback(ConnectivityManager.java:4456)] [android.net.ConnectivityManager.registerDefaultNetworkCallback(ConnectivityManager.java:4430)] [androidx.media3.exoplayer.drm.FrameworkMediaDrm$$ExternalSyntheticApiModelOutline0.m(Unknown Source:0)] [androidx.work.impl.utils.NetworkApi24.registerDefaultNetworkCallbackCompat(NetworkApi24.kt:28)] [androidx.work.impl.constraints.trackers.NetworkStateTracker24.startTracking(NetworkStateTracker.kt:139)] [androidx.work.impl.constraints.trackers.ConstraintTracker.addListener(ConstraintTracker.kt:57)] [androidx.work.impl.constraints.controllers.ConstraintController.replace(ConstraintController.kt:82)] [androidx.work.impl.constraints.WorkConstraintsTrackerImpl.replace(WorkConstraintsTracker.kt:92)] [androidx.work.impl.background.greedy.GreedyScheduler.schedule(GreedyScheduler.java:170)] [androidx.work.impl.Schedulers.schedule(Schedulers.java:119)] [androidx.work.impl.utils.EnqueueRunnable.scheduleWorkInBackground(EnqueueRunnable.java:135)] [androidx.work.impl.utils.EnqueueRunnable.run(EnqueueRunnable.java:95)] [androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)] [java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)] [java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)] [java.lang.Thread.run(Thread.java:920)]
10-18 20:54:00.099  5723  5723 I DecorView: notifyKeepScreenOnChanged: keepScreenOn=false
10-18 20:54:00.100  5723  5723 I SurfaceView@73ba888: onWindowVisibilityChanged(0) false android.view.SurfaceView{73ba888 G.E...... ......I. 0,0-0,0} of ViewRootImpl@5436103[WebViewActivity]
10-18 20:54:00.100  5723  5819 D OpenGLRenderer: setSurface called with nullptr
10-18 20:54:00.100  5723  5723 I DecorView: notifyKeepScreenOnChanged: keepScreenOn=false
10-18 20:54:00.107  5723  5723 I ViewRootImpl@5436103[WebViewActivity]: Relayout returned: old=(0,0,1080,2280) new=(0,0,1080,2280) req=(1080,2280)0 dur=5 res=0x7 s={true 508582448336} ch=true fn=-1
10-18 20:54:00.107  5723  5723 I SurfaceView@73ba888: windowStopped(false) false android.view.SurfaceView{73ba888 G.E...... ......I. 0,0-0,0} of ViewRootImpl@5436103[WebViewActivity]
10-18 20:54:00.108  5723  5723 I ViewRootImpl@5436103[WebViewActivity]: [DP] dp(1) 1 android.view.ViewRootImpl.reportNextDraw:11442 android.view.ViewRootImpl.performTraversals:4198 android.view.ViewRootImpl.doTraversal:2924 
10-18 20:54:00.108  5723  5723 D ViewRootImpl@5436103[WebViewActivity]: Creating frameDrawingCallback nextDrawUseBlastSync=false reportNextDraw=true hasBlurUpdates=false
10-18 20:54:00.108  5723  5723 D ViewRootImpl@5436103[WebViewActivity]: Creating frameCompleteCallback
10-18 20:54:00.108  5723  5819 D OpenGLRenderer: eglCreateWindowSurface
10-18 20:54:00.113  5723  5833 D ViewRootImpl@5436103[WebViewActivity]: Received frameDrawingCallback frameNum=1. Creating transactionCompleteCallback=false
10-18 20:54:00.136  5723  5819 D ViewRootImpl@5436103[WebViewActivity]: Received frameCompleteCallback  lastAcquiredFrameNum=1 lastAttemptedDrawFrameNum=1
10-18 20:54:00.139  5723  5723 I ViewRootImpl@5436103[WebViewActivity]: [DP] pdf(0) 1 android.view.ViewRootImpl.lambda$addFrameCompleteCallbackIfNeeded$3$ViewRootImpl:5000 android.view.ViewRootImpl$$ExternalSyntheticLambda16.run:6 android.os.Handler.handleCallback:938 
10-18 20:54:00.139  5723  5723 I ViewRootImpl@5436103[WebViewActivity]: [DP] rdf()
10-18 20:54:00.139  5723  5723 D ViewRootImpl@5436103[WebViewActivity]: reportDrawFinished (fn: -1) 
10-18 20:54:00.140  5723  5723 D InsetsSourceConsumer: ensureControlAlpha: for ITYPE_NAVIGATION_BAR on io.homeassistant.companion.android/io.homeassistant.companion.android.webview.WebViewActivity
10-18 20:54:00.141  5723  5723 D InsetsSourceConsumer: ensureControlAlpha: for ITYPE_STATUS_BAR on io.homeassistant.companion.android/io.homeassistant.companion.android.webview.WebViewActivity
10-18 20:54:00.149  5723  5767 I WM-Processor: Moving WorkSpec (b686a2f9-fdfe-4a45-9e58-604057caae9c) to the foreground
10-18 20:54:00.153  5723  5723 I ViewRootImpl@5436103[WebViewActivity]: MSG_WINDOW_FOCUS_CHANGED 1 1
10-18 20:54:00.158  5723  5723 D ServerConnectionInfo: localUrl is: true, usesInternalSsid is: false, usesWifi is: false
10-18 20:54:00.159  5723  5723 D IntegrationRepository: isAppLocked(): false. (LockEnabled: false, appActive: false, expireMillis: 0, currentMillis: 1697655240159)
10-18 20:54:00.176  5723  5786 D SensorWorker: Updating all Sensors in foreground.
10-18 20:54:00.178  5723  5786 D ServerConnectionInfo: localUrl is: true, usesInternalSsid is: false, usesWifi is: false
10-18 20:54:00.200  5723  5723 D InputMethodManager: startInputInner - Id : 0
10-18 20:54:00.200  5723  5723 I InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
10-18 20:54:00.211  5723  5723 D ServerConnectionInfo: localUrl is: true, usesInternalSsid is: false, usesWifi is: false
10-18 20:54:00.211  5723  5723 D ServerConnectionInfo: Using external URL
10-18 20:54:00.215  5723  5723 D ServerConnectionInfo: localUrl is: true, usesInternalSsid is: false, usesWifi is: false
10-18 20:54:00.215  5723  5941 D WebviewActivity: External bus {"type":"connection-status","payload":{"event":"disconnected"},"id":4}
10-18 20:54:00.215  5723  5723 D ServerConnectionInfo: Using external URL
10-18 20:54:00.221  5723  5723 I WM-SystemFgDispatcher: Started foreground service Intent { act=ACTION_START_FOREGROUND cmp=io.homeassistant.companion.android/androidx.work.impl.foreground.SystemForegroundService (has extras) }
10-18 20:54:00.284  5723  5735 I mpanion.androi: Background concurrent copying GC freed 365953(15MB) AllocSpace objects, 15(636KB) LOS objects, 49% free, 12MB/24MB, paused 7.052ms,50us total 187.873ms
10-18 20:54:00.305  5723  5786 D ServerConnectionInfo: localUrl is: true, usesInternalSsid is: false, usesWifi is: false
10-18 20:54:00.307  5723  5786 D ServerConnectionInfo: localUrl is: true, usesInternalSsid is: false, usesWifi is: false
10-18 20:54:00.308  5723  5819 D OpenGLRenderer: setSurface called with nullptr
10-18 20:54:00.618  5723  5941 D WebviewActivity: External bus {"type":"connection-status","payload":{"event":"connected"},"id":5}
10-18 20:54:00.624  5723  5723 D ServerConnectionInfo: localUrl is: true, usesInternalSsid is: false, usesWifi is: false
10-18 20:54:00.781  5723  5941 D WebviewActivity: External bus {"type":"theme-update","id":6}
10-18 20:54:00.810  5723  5723 D WebviewActivity: Color from webview is "#101e24-SPACER-#111111"
10-18 20:54:00.810  5723  5723 D WebviewActivity: Color from webview is "#101e24-SPACER-#111111"
10-18 20:54:00.810  5723  5786 D WebViewPresenterImpl: Try getting color from webview color "#101e24".
10-18 20:54:00.811  5723  5786 I WebViewPresenterImpl: Found color -15720924.
10-18 20:54:00.812  5723  5786 D WebViewPresenterImpl: Try getting color from webview color "#111111".
10-18 20:54:00.812  5723  5786 I WebViewPresenterImpl: Found color -15658735.
10-18 20:54:00.832  5723  5723 I ViewRootImpl@5436103[WebViewActivity]: ViewPostIme pointer 0
10-18 20:54:00.882  5723  5723 I ViewRootImpl@5436103[WebViewActivity]: ViewPostIme pointer 1
10-18 20:54:00.949  5723  5723 D InputMethodManager: startInputInner - Id : 0
10-18 20:54:00.949  5723  5723 I InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
10-18 20:54:01.544  5723  5723 I ViewRootImpl@5436103[WebViewActivity]: ViewPostIme pointer 0
10-18 20:54:01.643  5723  5723 I ViewRootImpl@5436103[WebViewActivity]: ViewPostIme pointer 1
10-18 20:54:03.554  5723  5723 I ViewRootImpl@5436103[WebViewActivity]: ViewPostIme pointer 0
10-18 20:54:03.611  5723  5723 I ViewRootImpl@5436103[WebViewActivity]: ViewPostIme pointer 1
10-18 20:54:04.019  5723  5786 D ServerConnectionInfo: localUrl is: true, usesInternalSsid is: false, usesWifi is: false
10-18 20:54:04.019  5723  5786 D ServerConnectionInfo: Using external URL
10-18 20:54:04.026  5723  5786 D ServerConnectionInfo: localUrl is: true, usesInternalSsid is: false, usesWifi is: false
10-18 20:54:04.026  5723  5786 D ServerConnectionInfo: Using external URL
10-18 20:54:04.372  5723  8064 D WebSocketRepository: Websocket: onOpen
10-18 20:54:04.372  5723  8064 D WebSocketRepository: Websocket: onMessage (text)
10-18 20:54:04.374  5723  5786 D WebSocketRepository: Message number null received
10-18 20:54:04.374  5723  5786 D WebSocketRepository: Auth Requested
10-18 20:54:04.446  5723  8064 D WebSocketRepository: Websocket: onMessage (text)
10-18 20:54:04.447  5723  5786 D WebSocketRepository: Message number null received
10-18 20:54:04.448  5723  5786 D WebSocketRepository: Sending message 16: {type=supported_features, id=16, features={coalesce_messages=1}}
10-18 20:54:04.448  5723  5786 D WebSocketRepository: Resubscribing to active subscriptions...
10-18 20:54:04.449  5723  5786 D WebSocketRepository: Sending message 17: {type=mobile_app/push_notification_channel, webhook_id=403af983685c20e181365c2f5343c900a50631a8afdfa159de85a55fb40fec0f, support_confirm=true, id=17}
10-18 20:54:04.449  5723  5786 D WebSocketRepository: Message number 17 sent
10-18 20:54:04.506  5723  8064 D WebSocketRepository: Websocket: onMessage (text)
10-18 20:54:04.508  5723  5786 D WebSocketRepository: Message number 16 received
10-18 20:54:04.584  5723  8064 D WebSocketRepository: Websocket: onMessage (text)
10-18 20:54:04.586  5723  5763 D WebSocketRepository: Message number 17 received
10-18 20:54:04.887  5723  5723 I ViewRootImpl@5436103[WebViewActivity]: ViewPostIme pointer 0
10-18 20:54:04.965  5723  5723 I ViewRootImpl@5436103[WebViewActivity]: ViewPostIme pointer 1
10-18 20:54:04.976  5723  5941 D WebviewActivity: External bus {"type":"config_screen/show","id":7}
10-18 20:54:04.990  5723  5723 D IntegrationRepository: setAppActive(): false
10-18 20:54:04.992  5723  5723 D IntegrationRepository: setAppActive(): false
10-18 20:54:05.012  5723  5723 I DecorView: [INFO] isPopOver=false, config=true
10-18 20:54:05.012  5723  5723 I DecorView: updateCaptionType >> DecorView@8bd5fe2[], isFloating=false, isApplication=true, hasWindowControllerCallback=true, hasWindowDecorCaption=false
10-18 20:54:05.012  5723  5723 D DecorView: setCaptionType = 0, this = DecorView@8bd5fe2[]
10-18 20:54:05.012  5723  5723 I DecorView: getCurrentDensityDpi: from real metrics. densityDpi=420 msg=resources_loaded
10-18 20:54:05.206  5723  5723 D IntegrationRepository: isAppLocked(): false. (LockEnabled: false, appActive: false, expireMillis: 0, currentMillis: 1697655245206)
10-18 20:54:05.210  5723  5723 I ViewRootImpl@512a8d8[SettingsActivity]: setView = com.android.internal.policy.DecorView@8bd5fe2 TM=true
10-18 20:54:05.211  5723  5723 D SensorReceiver: Received intent: io.homeassistant.companion.android.UPDATE_SENSORS
10-18 20:54:05.215  5723  5762 D ServerConnectionInfo: localUrl is: true, usesInternalSsid is: false, usesWifi is: false
10-18 20:54:05.224  5723  5723 I ViewRootImpl@512a8d8[SettingsActivity]: Relayout returned: old=(0,0,1080,2280) new=(0,0,1080,2280) req=(1080,2280)0 dur=7 res=0x7 s={true 508581846656} ch=true fn=-1
10-18 20:54:05.224  5723  5819 D OpenGLRenderer: eglCreateWindowSurface
10-18 20:54:05.271  5723  5723 I ViewRootImpl@512a8d8[SettingsActivity]: [DP] dp(1) 1 android.view.ViewRootImpl.reportNextDraw:11442 android.view.ViewRootImpl.performTraversals:4198 android.view.ViewRootImpl.doTraversal:2924 
10-18 20:54:05.271  5723  5723 D ViewRootImpl@512a8d8[SettingsActivity]: Creating frameDrawingCallback nextDrawUseBlastSync=false reportNextDraw=true hasBlurUpdates=false
10-18 20:54:05.271  5723  5723 D ViewRootImpl@512a8d8[SettingsActivity]: Creating frameCompleteCallback
10-18 20:54:05.272  5723  5762 D ServerConnectionInfo: localUrl is: true, usesInternalSsid is: false, usesWifi is: false
10-18 20:54:05.273  5723  5835 D ViewRootImpl@512a8d8[SettingsActivity]: Received frameDrawingCallback frameNum=1. Creating transactionCompleteCallback=false
10-18 20:54:05.280  5723  5762 D ServerConnectionInfo: localUrl is: true, usesInternalSsid is: false, usesWifi is: false
10-18 20:54:05.317  5723  5819 D ViewRootImpl@512a8d8[SettingsActivity]: Received frameCompleteCallback  lastAcquiredFrameNum=1 lastAttemptedDrawFrameNum=1
10-18 20:54:05.318  5723  5723 I ViewRootImpl@512a8d8[SettingsActivity]: [DP] pdf(0) 1 android.view.ViewRootImpl.lambda$addFrameCompleteCallbackIfNeeded$3$ViewRootImpl:5000 android.view.ViewRootImpl$$ExternalSyntheticLambda16.run:6 android.os.Handler.handleCallback:938 
10-18 20:54:05.318  5723  5723 I ViewRootImpl@512a8d8[SettingsActivity]: [DP] rdf()
10-18 20:54:05.318  5723  5723 D ViewRootImpl@512a8d8[SettingsActivity]: reportDrawFinished (fn: -1) 
10-18 20:54:05.325  5723  5762 D ServerConnectionInfo: localUrl is: true, usesInternalSsid is: false, usesWifi is: false
10-18 20:54:05.326  5723  5723 I ViewRootImpl@5436103[WebViewActivity]: MSG_WINDOW_FOCUS_CHANGED 0 1
10-18 20:54:05.344  5723  5723 D InsetsSourceConsumer: ensureControlAlpha: for ITYPE_NAVIGATION_BAR on io.homeassistant.companion.android/io.homeassistant.companion.android.settings.SettingsActivity
10-18 20:54:05.344  5723  5723 D InsetsSourceConsumer: ensureControlAlpha: for ITYPE_STATUS_BAR on io.homeassistant.companion.android/io.homeassistant.companion.android.settings.SettingsActivity
10-18 20:54:05.352  5723  5723 I ViewRootImpl@512a8d8[SettingsActivity]: MSG_WINDOW_FOCUS_CHANGED 1 1
10-18 20:54:05.352  5723  5723 D IntegrationRepository: isAppLocked(): false. (LockEnabled: false, appActive: false, expireMillis: 0, currentMillis: 1697655245352)
10-18 20:54:05.353  5723  5723 D IntegrationRepository: setAppActive(): true
10-18 20:54:05.353  5723  5723 D InputMethodManager: startInputInner - Id : 0
10-18 20:54:05.353  5723  5723 I InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
10-18 20:54:05.725  5723  5723 I ViewRootImpl@5436103[WebViewActivity]: handleAppVisibility mAppVisible=true visible=false
10-18 20:54:05.738  5723  5723 I SurfaceView@73ba888: onWindowVisibilityChanged(8) false android.view.SurfaceView{73ba888 G.E...... ......I. 0,0-0,0} of ViewRootImpl@5436103[WebViewActivity]
10-18 20:54:05.740  5723  5819 D OpenGLRenderer: setSurface called with nullptr
10-18 20:54:05.740  5723  5819 D OpenGLRenderer: setSurface() destroyed EGLSurface
10-18 20:54:05.740  5723  5819 D OpenGLRenderer: destroyEglSurface
10-18 20:54:05.747  5723  5723 I ViewRootImpl@5436103[WebViewActivity]: Relayout returned: old=(0,0,1080,2280) new=(0,0,1080,2280) req=(1080,2280)8 dur=5 res=0x5 s={false 0} ch=true fn=56
10-18 20:54:05.747  5723  5723 I SurfaceView@73ba888: windowStopped(true) false android.view.SurfaceView{73ba888 G.E...... ......I. 0,0-0,0} of ViewRootImpl@5436103[WebViewActivity]
10-18 20:54:05.748  5723  5723 I ViewRootImpl@5436103[WebViewActivity]: stopped(true) old=false
10-18 20:54:05.760  5723  5723 I ViewRootImpl@5436103[WebViewActivity]: Relayout returned: old=(0,0,1080,2280) new=(0,0,1080,2280) req=(1080,2280)8 dur=5 res=0x5 s={false 0} ch=false fn=-1
10-18 20:54:06.178  5723  5723 I ViewRootImpl@512a8d8[SettingsActivity]: ViewPostIme pointer 0
10-18 20:54:06.295  5723  5723 I ViewRootImpl@512a8d8[SettingsActivity]: ViewPostIme pointer 1
10-18 20:54:06.634  5723  6873 D ServerConnectionInfo: localUrl is: true, usesInternalSsid is: false, usesWifi is: false
10-18 20:54:06.636  5723  6873 D ServerConnectionInfo: localUrl is: true, usesInternalSsid is: false, usesWifi is: false
10-18 20:54:06.639  5723  6873 D ServerConnectionInfo: localUrl is: true, usesInternalSsid is: false, usesWifi is: false
10-18 20:54:06.641  5723  6873 D ServerConnectionInfo: localUrl is: true, usesInternalSsid is: false, usesWifi is: false
10-18 20:54:06.641  5723  6873 D WebSocketRepository: Sending message 18: {type=ping, id=18}
10-18 20:54:06.642  5723  6873 D WebSocketRepository: Message number 18 sent
10-18 20:54:06.713  5723  8064 D WebSocketRepository: Websocket: onMessage (text)
10-18 20:54:06.714  5723  6873 D WebSocketRepository: Message number 18 received
10-18 20:54:08.276  5723  5723 I ViewRootImpl@512a8d8[SettingsActivity]: ViewPostIme pointer 0
10-18 20:54:09.208  5723  5723 I ViewRootImpl@512a8d8[SettingsActivity]: ViewPostIme pointer 1
10-18 20:54:10.669  5723  6873 D ServerConnectionInfo: localUrl is: true, usesInternalSsid is: false, usesWifi is: false
10-18 20:54:10.695  5723  5723 I ViewRootImpl@512a8d8[SettingsActivity]: ViewPostIme pointer 0
10-18 20:54:10.878  5723  5723 I ViewRootImpl@512a8d8[SettingsActivity]: ViewPostIme pointer 1
10-18 20:54:11.254  5723  5723 I ViewRootImpl@512a8d8[SettingsActivity]: ViewPostIme pointer 0
10-18 20:54:11.614  5723  5723 I ViewRootImpl@512a8d8[SettingsActivity]: ViewPostIme pointer 1
10-18 20:54:12.350  5723  5723 I ViewRootImpl@512a8d8[SettingsActivity]: ViewPostIme pointer 0
10-18 20:54:12.459  5723  5723 I ViewRootImpl@512a8d8[SettingsActivity]: ViewPostIme pointer 1
10-18 20:54:12.502  5723  5723 I DecorView: notifyKeepScreenOnChanged: keepScreenOn=false
10-18 20:54:12.507  5723  5723 I ViewRootImpl@512a8d8[SettingsActivity]: Relayout returned: old=(0,0,1080,2280) new=(0,0,1080,2280) req=(1080,2280)0 dur=3 res=0x1 s={true 508581846656} ch=false fn=288
10-18 20:54:14.243  5723  5723 I ViewRootImpl@512a8d8[SettingsActivity]: ViewPostIme pointer 0
10-18 20:54:14.333  5723  5723 I ViewRootImpl@512a8d8[SettingsActivity]: ViewPostIme pointer 1
10-18 20:54:14.388  5723  5723 D ScrollView: initGoToTop
10-18 20:54:14.420  5723  5723 I DecorView: notifyKeepScreenOnChanged: keepScreenOn=false
10-18 20:54:14.435  5723  5723 I ViewRootImpl@512a8d8[SettingsActivity]: Relayout returned: old=(0,0,1080,2280) new=(0,0,1080,2280) req=(1080,2280)0 dur=4 res=0x1 s={true 508581846656} ch=false fn=296
10-18 20:54:14.435  5723  5723 D ScrollView:  onsize change changed 
10-18 20:54:14.437  5723  6873 D LogcatReader: Read logcat for pid 5723

```

**Screenshot or video of problem:**

https://github.com/home-assistant/android/assets/10536718/3a564dc7-12da-433f-95dd-88d34ad1094b

![widget problem 2](https://github.com/home-assistant/android/assets/10536718/4415e701-85c3-4e3d-9608-5af64131b80c)

**Additional information:**

**Comment by dshokouhi** [comment]
First one took about 10 seconds and no issues reported, this is normal and not something the app can fix.

```
10-18 20:53:39.902  5723  5723 D ButtonWidget: Calling widget service
10-18 20:53:39.903  5723  5723 D AppWidgetManager: partiallyUpdateAppWidget() appWidgetIds = [12]
10-18 20:53:39.911  5723  5723 D ButtonWidget: Service Call Data loaded:
10-18 20:53:39.911  5723  5723 D ButtonWidget: domain: script
10-18 20:53:39.911  5723  5723 D ButtonWidget: service: pc_wol_fisso
10-18 20:53:39.911  5723  5723 D ButtonWidget: service_data: {}
10-18 20:53:39.931  5723  5723 D ButtonWidget: Sending service call to Home Assistant
10-18 20:53:39.939  5723  5723 D ServerConnectionInfo: localUrl is: true, usesInternalSsid is: false, usesWifi is: false
10-18 20:53:50.427  5723  5723 D ButtonWidget: Service call sent successfully
```

The delay may be on the server end as all we do send the call out and wait for a response. I do not see any failure in the logs so we can determine if its something the app can fix. Please share the log of a call that fails, the slow update call is not something the app can fix.

**Comment by razorbac91** [comment]
I'm actually unable to reproduce a failure. Anyway i actually "patched" the problem putting HA companion app always under VPN doing a split tutnneling... still i can't understand why the app slow it down when on nomal 4G.
I also tried to send API command with API Tester app directly from my phone WITHOUT active VPN and they works as expected, triggering switch and scripts in terms of ms (way far from 10s of the ha companion app widget)
