### ISSUE TITLE
Device Tracker is not updating in Android app when connected to Cloud URL (Nabu Casa)

### ISSUE THREAD

**Issue by sartenaer** [home-assistant/android#3972]
**Home Assistant Android app version(s):**
2023.9.2-full
**Android version(s):**
13
**Device model(s):**
FP3 (FairPhone 3)
**Home Assistant version:**
Home Assistant 2023.10.5
**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**

**Companion App Logs:**

```
--------- beginning of main
10-25 11:22:04.999 12861 12861 D LocBroadcastReceiver: Received location update.
10-25 11:22:05.028 12861 12861 D ForegrndServiceLauncher: Check if service HighAccuracyLocationService is running. Service running = false
10-25 11:22:05.028 12861 16505 D LocBroadcastReceiver: Last Location: 
10-25 11:22:05.028 12861 16505 D LocBroadcastReceiver: Coords:(50.4018536, 4.4183193)
10-25 11:22:05.028 12861 16505 D LocBroadcastReceiver: Accuracy: 12.709
10-25 11:22:05.028 12861 16505 D LocBroadcastReceiver: Bearing: 0.0
10-25 11:22:05.029 12861 16505 D LocBroadcastReceiver: Begin evaluating if location update should be skipped
10-25 11:22:05.029 12861 16505 D LocBroadcastReceiver: Received location that is 148 milliseconds old, 1698225724881 compared to 1698225725029 with source fused
10-25 11:22:05.031 12861 16505 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: false
10-25 11:22:05.034 12861 17292 D TrafficStats: tagSocket(99) with statsTag=0xffffffff, statsUid=-1
10-25 11:22:10.200 12861 16505 E SensorReceiver: Error while getting core config to sync sensor status
10-25 11:22:10.200 12861 16505 E SensorReceiver: io.homeassistant.companion.android.common.data.integration.IntegrationException: java.net.SocketTimeoutException: failed to connect to /192.168.0.14 (port 8123) from /10.247.106.193 (port 38098) after 10000ms
10-25 11:22:10.200 12861 16505 E SensorReceiver: 	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl.getConfig(IntegrationRepositoryImpl.kt:512)
10-25 11:22:10.200 12861 16505 E SensorReceiver: 	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl$getConfig$1.invokeSuspend(Unknown Source:14)
10-25 11:22:10.200 12861 16505 E SensorReceiver: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
10-25 11:22:10.200 12861 16505 E SensorReceiver: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
10-25 11:22:10.200 12861 16505 E SensorReceiver: 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
10-25 11:22:10.200 12861 16505 E SensorReceiver: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
10-25 11:22:10.200 12861 16505 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
10-25 11:22:10.200 12861 16505 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
10-25 11:22:10.200 12861 16505 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
10-25 11:22:10.200 12861 16505 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
10-25 11:22:10.200 12861 16505 E SensorReceiver: Caused by: java.net.SocketTimeoutException: failed to connect to /192.168.0.14 (port 8123) from /10.247.106.193 (port 38098) after 10000ms
10-25 11:22:10.200 12861 16505 E SensorReceiver: 	at libcore.io.IoBridge.connectErrno(IoBridge.java:235)
10-25 11:22:10.200 12861 16505 E SensorReceiver: 	at libcore.io.IoBridge.connect(IoBridge.java:179)
10-25 11:22:10.200 12861 16505 E SensorReceiver: 	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
10-25 11:22:10.200 12861 16505 E SensorReceiver: 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
10-25 11:22:10.200 12861 16505 E SensorReceiver: 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
10-25 11:22:10.200 12861 16505 E SensorReceiver: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
10-25 11:22:10.200 12861 16505 E SensorReceiver: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
10-25 11:22:10.200 12861 16505 E SensorReceiver: 	at java.net.Socket.connect(Socket.java:646)
10-25 11:22:10.200 12861 16505 E SensorReceiver: 	at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
10-25 11:22:10.200 12861 16505 E SensorReceiver: 	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
10-25 11:22:10.200 12861 16505 E SensorReceiver: 	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
10-25 11:22:10.200 12861 16505 E SensorReceiver: 	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
10-25 11:22:10.200 12861 16505 E SensorReceiver: 	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
10-25 11:22:10.200 12861 16505 E SensorReceiver: 	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
10-25 11:22:10.200 12861 16505 E SensorReceiver: 	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
10-25 11:22:10.200 12861 16505 E SensorReceiver: 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
10-25 11:22:10.200 12861 16505 E SensorReceiver: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
10-25 11:22:10.200 12861 16505 E SensorReceiver: 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
10-25 11:22:10.200 12861 16505 E SensorReceiver: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
10-25 11:22:10.200 12861 16505 E SensorReceiver: 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
10-25 11:22:10.200 12861 16505 E SensorReceiver: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
10-25 11:22:10.200 12861 16505 E SensorReceiver: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
10-25 11:22:10.200 12861 16505 E SensorReceiver: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
10-25 11:22:10.200 12861 16505 E SensorReceiver: 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
10-25 11:22:10.200 12861 16505 E SensorReceiver: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
10-25 11:22:10.200 12861 16505 E SensorReceiver: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
10-25 11:22:10.200 12861 16505 E SensorReceiver: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
10-25 11:22:10.200 12861 16505 E SensorReceiver: 	at java.lang.Thread.run(Thread.java:1012)


```

**Screenshot or video of problem:**

**Additional information:**
From log file analysis, problem seems to be : "failed to connect to /192.168.0.14 (port 8123) from /10.247.106.193 (port 38316) after 10000ms". The local IP address of my HA server is indeed /192.168.0.14 (port 8123), but when not home I'm on my 4G connection and the HA companion App is supposed to use HA Cloud URL (via Nabu Casa). This Cloud URL works fine (connection to my HA server via 4G works perfectly), except for location update which seems to be blocked on Local URL.
I already applied all recommendations listed here: https://companion.home-assistant.io/docs/troubleshooting/faqs/

**Comment by sartenaer** [comment]
Solved after reinstallation of companion app
