### ISSUE TITLE
Entity sensor.****_ringer_mode cannot be added as the entity category is set to config

### ISSUE THREAD

**Issue by hmmbob** [home-assistant/android#3973]
**Home Assistant Android app version(s):**
2023.10.2-full

**Android version(s):**
13

**Device model(s):**
Samsung A52 5G (but also other devices)

**Home Assistant version:**
2023.11.0b0

**Last working Home Assistant release (if known):**
2023.10

**Description of problem, include YAML if issue is related to notifications:**
On latest beta, getting errors on all devices with the ringer mode. 
https://discord.com/channels/330944238910963714/427516175237382144/1167069411279126538

**Additional information:**
Logs in ha:
```
2023-10-26 13:49:36.084 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform mobile_app
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1021, in add_to_platform_finish
await self.async_internal_added_to_hass()
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 279, in async_internal_added_to_hass
raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity sensor.sm_a526b_ringer_mode cannot be added as the entity category is set to config
2023-10-26 13:49:36.102 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up mobile_app platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 367, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1021, in add_to_platform_finish
await self.async_internal_added_to_hass()
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 279, in async_internal_added_to_hass
raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity sensor.sm_a526b_ringer_mode cannot be added as the entity category is set to config
2023-10-26 13:49:36.112 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform mobile_app
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1021, in add_to_platform_finish
await self.async_internal_added_to_hass()
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 279, in async_internal_added_to_hass
raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity sensor.schaduwspeler_belmodus cannot be added as the entity category is set to config
2023-10-26 13:49:36.127 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up mobile_app platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 367, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1021, in add_to_platform_finish
await self.async_internal_added_to_hass()
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 279, in async_internal_added_to_hass
raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity sensor.schaduwspeler_belmodus cannot be added as the entity category is set to config
```

**Comment by dshokouhi** [comment]
We haven't set this for the sensor in a long time

https://github.com/home-assistant/android/blob/master/common/src/main/java/io/homeassistant/companion/android/common/sensors/AudioSensorManager.kt#L16

**Comment by dshokouhi** [comment]
We may or may not close this one in favor of the issue filed in HA core

**Comment by hmmbob** [comment]
Looks like it's a core issue after your comments, will indeed close this one
