### ISSUE TITLE
History graph card does not show graph in companion app (works in browser)

### ISSUE THREAD

**Issue by erlanger** [home-assistant/android#3983]
**Home Assistant Android app version(s):**
2023.10.2-minimal

**Android version(s):**
Android 9

**Device model(s):**

**Home Assistant version:**
2023.10.5
**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**

* The history graph card does not show the graph, also the markdown card does not show.
* this only happens with the companion app, if I open home assistant on the browser (on the same phone) everything works fine.
* the cause of the error is clear from the logs

**Companion App Logs:**

```
10-28 13:43:53.719 22062 22073 I android.minima: Background concurrent copying GC freed 110472(6MB) AllocSpace objects, 65(1680KB) LOS objects, 49% free, 8MB/17MB, paused 340us total 156.149ms
10-28 13:44:02.386 22062 22062 I chromium: [INFO:CONSOLE(2)] "Uncaught (in promise) Error: Canvas is already in use. Chart with ID '2' must be destroyed before the canvas with ID '' can be reused.", source: https://<redacted>/frontend_latest/98357-zlvMPZ-huOs.js (2)
10-28 13:44:02.749 22062 22062 I chromium: [INFO:CONSOLE(2)] "Uncaught (in promise) Error: Canvas is already in use. Chart with ID '3' must be destroyed before the canvas with ID '' can be reused.", source: https://<redacted>/frontend_latest/98357-zlvMPZ-huOs.js (2)
10-28 13:44:03.119 22062 22062 I chromium: [INFO:CONSOLE(2)] "Uncaught (in promise) Error: Canvas is already in use. Chart with ID '4' must be destroyed before the canvas with ID '' can be reused.", source: https://<redacted>/frontend_latest/98357-zlvMPZ-huOs.js (2)
10-28 13:44:03.470 22062 22062 I chromium: [INFO:CONSOLE(2)] "Uncaught (in promise) Error: Canvas is already in use. Chart with ID '5' must be destroyed before the canvas with ID '' can be reused.", source: https://<redacted>/frontend_latest/98357-zlvMPZ-huOs.js (2)
10-28 13:44:03.792 22062 22062 I chromium: [INFO:CONSOLE(2)] "Uncaught (in promise) Error: Canvas is already in use. Chart with ID '6' must be destroyed before the canvas with ID '' can be reused.", source: https://<redacted>/frontend_latest/98357-zlvMPZ-huOs.js (2)
10-28 13:44:04.113 22062 22062 I chromium: [INFO:CONSOLE(2)] "Uncaught (in promise) Error: Canvas is already in use. Chart with ID '7' must be destroyed before the canvas with ID '' can be reused.", source: https://<redacted>/frontend_latest/98357-zlvMPZ-huOs.js (2)
10-28 13:44:04.401 22062 22062 I chromium: [INFO:CONSOLE(2)] "Uncaught (in promise) Error: Canvas is already in use. Chart with ID '0' must be destroyed before the canvas with ID '' can be reused.", source: https://<redacted>/frontend_latest/98357-zlvMPZ-huOs.js (2)
10-28 13:44:04.715 22062 22062 I chromium: [INFO:CONSOLE(2)] "Uncaught (in promise) Error: Canvas is already in use. Chart with ID '1' must be destroyed before the canvas with ID '' can be reused.", source: https://<redacted>/frontend_latest/98357-zlvMPZ-huOs.js (2)
10-28 13:44:05.927 22062 22062 I chromium: [INFO:CONSOLE(2)] "Failure writing unhandled promise rejection to system log: ReferenceError: AggregateError is not defined", source: https://<redacted>/frontend_latest/app-RHnFPWv3eEE.js (2)
10-28 13:44:05.929 22062 22062 I chatty  : uid=10161(io.homeassistant.companion.android.minimal) identical 6 lines
10-28 13:44:05.930 22062 22062 I chromium: [INFO:CONSOLE(2)] "Failure writing unhandled promise rejection to system log: ReferenceError: AggregateError is not defined", source: https://<redacted>/frontend_latest/app-RHnFPWv3eEE.js (2)
10-28 13:44:06.999 22062 22062 I chromium: [INFO:CONSOLE(2)] "Failure writing unhandled promise rejection to system log: ReferenceError: AggregateError is not defined", source: https://<redacted>/frontend_latest/app-RHnFPWv3eEE.js (2)
10-28 13:44:06.999 22062 22062 I chromium: [INFO:CONSOLE(2)] "Uncaught (in promise) TypeError: Failed to construct 'Worker': Module scripts are not supported on DedicatedWorker yet. You can try the feature with '--enable-experimental-web-platform-features' flag (see https://crbug.com/680046)", source: https://<redacted>/frontend_latest/51282-HwWfYloJHps.js (2)
10-28 13:44:08.754 22062 22062 I chromium: [INFO:CONSOLE(2)] "Failure writing unhandled promise rejection to system log: ReferenceError: AggregateError is not defined", source: https://<redacted>/frontend_latest/app-RHnFPWv3eEE.js (2)
10-28 13:44:08.754 22062 22062 I chromium: [INFO:CONSOLE(2)] "Uncaught (in promise) Error: Canvas is already in use. Chart with ID '2' must be destroyed before the canvas with ID '' can be reused.", source: https://<redacted>/frontend_latest/98357-zlvMPZ-huOs.js (2)
10-28 13:44:09.066 22062 22062 I chromium: [INFO:CONSOLE(2)] "Failure writing unhandled promise rejection to system log: ReferenceError: AggregateError is not defined", source: https://<redacted>/frontend_latest/app-RHnFPWv3eEE.js (2)
10-28 13:44:09.066 22062 22062 I chromium: [INFO:CONSOLE(2)] "Uncaught (in promise) Error: Canvas is already in use. Chart with ID '3' must be destroyed before the canvas with ID '' can be reused.", source: https://<redacted>/frontend_latest/98357-zlvMPZ-huOs.js (2)
10-28 13:44:09.363 22062 22062 I chromium: [INFO:CONSOLE(2)] "Failure writing unhandled promise rejection to system log: ReferenceError: AggregateError is not defined", source: https://<redacted>/frontend_latest/app-RHnFPWv3eEE.js (2)
10-28 13:44:09.363 22062 22062 I chromium: [INFO:CONSOLE(2)] "Uncaught (in promise) Error: Canvas is already in use. Chart with ID '4' must be destroyed before the canvas with ID '' can be reused.", source: https://<redacted>/frontend_latest/98357-zlvMPZ-huOs.js (2)


```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
As you are using the minimal version of the app you probably have an outdated version of WebView preinstalled on the custom ROM. Please try installing Google's version of Android system WebView and set as the default WebView in your device settings and try again.

**Comment by erlanger** [comment]
i am using the latest version, installed two days ago.

**Comment by dshokouhi** [comment]
Can you please force stop the app and open it again and check the logs? We print the WebView being used so that can help determine what version is used.

**Comment by erlanger** [comment]
hmmm... when i set the new WebView as the default the companion app does not connect to home assistant, it shows the usual screen: "unable to connect to Home Assistant ... settings / refresh external url / wait"

As soon as I switch to the old webview version everything works except the history graph cards

**Comment by dshokouhi** [comment]
What's the error in the logs? If you click on settings > troubleshooting > show and share logs you can see the logs with the error.

A up to date WebView is required for the HA frontend

**Comment by erlanger** [comment]
hmm..strange, it seems the underlying server connects, but the frontend does not start, this is the only error i see in the logs;
```
SensorReceiver: Nothing to update for server 1 (<redacted>)
10-29 18:42:21.125  2739  3270 I SensorReceiver: Sensor updates and sync completed
10-29 18:42:22.000  2739  2739 E WindowManager: 
10-29 18:42:22.000  2739  2739 E WindowManager: android.view.WindowLeaked: Activity io.homeassistant.companion.android.webview.WebViewActivity has leaked window DecorView@8348fcc[WebViewActivity] that was originally added here
10-29 18:42:22.000  2739  2739 E WindowManager: 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:511)
10-29 18:42:22.000  2739  2739 E WindowManager: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:346)
10-29 18:42:22.000  2739  2739 E WindowManager: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
10-29 18:42:22.000  2739  2739 E WindowManager: 	at android.app.Dialog.show(Dialog.java:329)
10-29 18:42:22.000  2739  2739 E WindowManager: 	at io.homeassistant.companion.android.webview.WebViewActivity.showError(WebViewActivity.kt:1318)
10-29 18:42:22.000  2739  2739 E WindowManager: 	at io.homeassistant.companion.android.webview.WebView$DefaultImpls.showError$default(WebView.kt:23)
10-29 18:42:22.000  2739  2739 E WindowManager: 	at io.homeassistant.companion.android.webview.WebViewActivity.waitForConnection$lambda$39(WebViewActivity.kt:1418)
10-29 18:42:22.000  2739  2739 E WindowManager: 	at io.homeassistant.companion.android.webview.WebViewActivity.$r8$lambda$UOgyrQvkWCJCmRIMyReGxrtCgH4(Unknown Source:0)
10-29 18:42:22.000  2739  2739 E WindowManager: 	at io.homeassistant.companion.android.webview.WebViewActivity$$ExternalSyntheticLambda11.run(Unknown Source:2)
10-29 18:42:22.000  2739  2739 E WindowManager: 	at android.os.Handler.handleCallback(Handler.java:873)
10-29 18:42:22.000  2739  2739 E WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-29 18:42:22.000  2739  2739 E WindowManager: 	at android.os.Looper.loop(Looper.java:193)
10-29 18:42:22.000  2739  2739 E WindowManager: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
10-29 18:42:22.000  2739  2739 E WindowManager: 	at java.lang.reflect.Method.invoke(Native Method)
10-29 18:42:22.000  2739  2739 E WindowManager: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
10-29 18:42:22.000  2739  2739 E WindowManager: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
10-29 18:42:22.135  2739  2739 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@703c92a
10-29 18:42:22.214  2739  2739 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: true, usesWifi is: true
10-29 18:42:22.215  2739  2739 D ServerConnectionInfo: Using external URL
10-29 18:42:22.216  2739  2739 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: true, usesWifi is: true
10-29 18:42:22.221  2739  2739 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: true, usesWifi is: true
10-29 18:42:22.221  2739  2739 D ServerConnectionInfo: Using external URL
```

**Comment by dshokouhi** [comment]
That's strange. Can you share the log line where we print the WebView package and version so we can see what it's using. That only gets printed once when the app starts so you may need to force stop and open again to see the log line.

**Comment by erlanger** [comment]
Here it is (its the new version):
```
10-29 18:44:20.450  2739  2739 D WebviewActivity: Current webview package com.google.android.webview and version 118.0.5993.80
10-29 18:44:20.454  2739  2739 D WebviewActivity: Matter commissioning status changed to NOT_STARTED
```

**Comment by erlanger** [comment]
Everthing works fine if I open in a browser on the phone

**Comment by dshokouhi** [comment]
Hmmm can you try restarting the device now that the correct WebView is used. The error is strange but maybe it's holding on to a process no longer there.

**Comment by erlanger** [comment]
I did restart it before I copied that log (and after setting the new webview as default)

**Comment by erlanger** [comment]
the notification says "Connected to home assistant" but no front end shows

**Comment by dshokouhi** [comment]
Ok can you get us more complete logs instead of the small sections. We have some debug logs to look at. The actual error message is about the pop-up itself but the pop-up gets triggered for a different reason.

The app works a bit different than the browser as we rely on API calls and the external bus that's only available to the app and not in a browser.

**Comment by erlanger** [comment]
ok, I have to go to a meeting, but I will post more later

**Comment by erlanger** [comment]
this is very strange. Everything is working fine now, it is as if the new Webview took 20 minutes to "settle" down. I restarted the phone to make sure it was not a fluke, and everything continues to work fine. So I will close this issue, although it still remains a mystery to me. Just for others, the symptoms were:
- The background server always connected (the persistent notification said "connected to home assistant")
- The frontend, however did not connect
- Sometimes the frontend screen simply would freeze (it never showed the "Loading data...")
- Other times it would show the "unable to connect to Home Assisant" dialog
- In the end, everything started working by itself in about 30 minutes. Strange.
