### ISSUE TITLE
Request for `com.termux.permission.RUN_COMMAND`

### ISSUE THREAD

**Issue by bilogic** [home-assistant/android#4080]
**Is your feature request related to a problem? Please describe.**

I wish to run a command on my Android phone from HA, but there isn't a built-in way, so I resorted to calling `RUN_COMMAND`, but was also not possible as it requires the calling app to request permission first.

**Describe the solution you'd like**

Be able to run a command (similar to `command_launch_app`) or request for the `com.termux.permission.RUN_COMMAND`

**Describe alternatives you've considered, if any**

Many, include those of tasker, but they don't fully meet requirements, e.g. the tasker solution can only work on the home network

**Additional context**

N/A

**Comment by dshokouhi** [comment]
Sorry we will not be adding 3rd party permissions for other apps. We tried in the past and it was not accepted.

**Comment by bilogic** [comment]
Thanks, may I ask, not accepted by whom?

**Comment by marazmarci** [comment]
@bilogic, you can try running `adb shell pm grant io.homeassistant.companion.android com.termux.permission.RUN_COMMAND` on your computer

**Comment by bilogic** [comment]
@marazmarci I tried that `pm grant ...` command on my phone's termux, will it be different via `adb`?

**Comment by dshokouhi** [comment]
> Thanks, may I ask, not accepted by whom?

the project, see https://github.com/home-assistant/android/pull/1149 as an example

We need to add things in a way that benefits all apps and not just some apps

**Comment by bilogic** [comment]
> @bilogic, you can try running `adb shell pm grant io.homeassistant.companion.android ```
com.termux.permission.RUN_COMMAND` on your computer

E:\temp\platform-tools>adb shell pm grant io.homeassistant.companion.android com.termux.permission.RUN_COMMAND
Security exception: Package io.homeassistant.companion.android has not requested permission com.termux.permission.RUN_COMMAND

java.lang.SecurityException: Package io.homeassistant.companion.android has not requested permission com.termux.permission.RUN_COMMAND
        at com.android.server.pm.permission.BasePermission.enforceDeclaredUsedAndRuntimeOrDevelopment(BasePermission.java:433)
        at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:2931)
        at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:2895)
        at com.android.server.pm.permission.PermissionManagerService.access$1200(PermissionManagerService.java:156)
        at com.android.server.pm.permission.PermissionManagerService$PermissionManagerServiceInternalImpl.grantRuntimePermission(PermissionManagerService.java:3966)
        at com.android.server.pm.PackageManagerService.grantRuntimePermission(PackageManagerService.java:6861)
        at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShellCommand.java:1955)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:230)
        at android.os.ShellCommand.exec(ShellCommand.java:104)
        at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:26853)
        at android.os.Binder.shellCommand(Binder.java:881)
        at android.os.Binder.onTransact(Binder.java:765)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:5452)
        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:5036)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)

E:\temp\platform-tools>
```

Same as termux

**Comment by bilogic** [comment]
> > Thanks, may I ask, not accepted by whom?
> 
> the project, see #1149 as an example
> 
> We need to add things in a way that benefits all apps and not just some apps

Hmm, I don't see any `details on how we will accommodate 3rd party integrations` and I think it would be much clearer to say that this app will not be adding 3rd party permissions.

**Comment by dshokouhi** [comment]
yea pretty sure we need to add the permission to the app manifest but thats where the issue comes. If we add 1 app the expectation is that we add all apps requested.



> I don't see any `details on how we will accommodate 3rd party integrations`

https://companion.home-assistant.io/docs/notifications/notification-commands#broadcast-intent

https://companion.home-assistant.io/docs/core/sensors#last-update-trigger-sensor

both of these features take care of sending data to apps and receiving data from apps

**Comment by bilogic** [comment]
@dshokouhi thanks, is there a way to get HA to run a command, almost like how we type commands in the CLI?

**Comment by dshokouhi** [comment]
if you can use tasker to achieve it, send an intent to tasker using the first link up above and once tasker receives that intent you can perform whatever action you want
