### ISSUE TITLE
Wear OS: All sensors unavailable

### ISSUE THREAD

**Issue by damiaorocha** [home-assistant/android#4141]
Home Assistant Android app version(s): 2024.1.2-full

Android version(s): 13

Device model(s): Samsung Galaxy S22 Ultra/Galaxy watch 4

Home Assistant version: 2023.12.4

All sensors linked to my watch are unavailable. On the watch, in sensor management I can see the status of all of them. The Home assistant log shows this:

Logger: homeassistant.config_entries
Source: config_entries.py:557
First occurred: January 16, 2024 at 07:22:23 (9 occurrences)
Last logged: 09:03:12

Error unloading entry watch4 for sensor
Error unloading entry watch4 for binary_sensor
Error unloading entry watch4 for device_tracker
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 557, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 136, in async_unload_entry
    return await component.async_unload_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 203, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!

**Comment by damiaorocha** [comment]
I followed the script and it worked again. Thanks.
