### ISSUE TITLE
"Problem loading widget" for entity widget on some launchers

### ISSUE THREAD

**Issue by arthurrump** [home-assistant/android#4183]
**Home Assistant Android app version(s):** 2024.1.5-full

**Android version(s):** 14

**Device model(s):** Samsung A52s

**Home Assistant version:** 2024.1.6

**Last working Home Assistant release (if known):** Previous version of the app

**Description of problem, include YAML if issue is related to notifications:**

This issue is split off from #4180.

Entity widgets are showing a "Problem loading widget" error. This only happens in some launchers.

It is broken in 
- Lawnchair (play store version)

But works fine in
- One UI Launcher (Samsung)
- Lawnchair (alpha from F-droid)
- Action Launcher
- Nova Launcher
- Niagara Launcher
- Pear Launcher
- Rootless Pixel Launcher

**Companion App Logs:**

See https://github.com/home-assistant/android/issues/4180#issuecomment-1924252203 and https://github.com/home-assistant/android/issues/4180#issuecomment-1924454279. (They weren't useful, so no need to copy it here.) 

**Screenshot or video of problem:**

**Additional information:**

**Comment by arthurrump** [comment]
> its quite possible that the app logs do not contain the relevant data, are you by chance familiar with logcat? If you are able to setup Android Studio and connect your phone you may be able to pull more logs to see where the issue comes from to see if we can fix it.

@dshokouhi I have logcat running over adb, but not much of a clue what I'm looking at or searching for :sweat_smile: What would you like to see?

**Comment by arthurrump** [comment]
@dshokouhi Does this look relevant?

```
02-02 20:42:21.741  1395  5480 W InputManager-JNI: Input channel object 'eb7e56b io.homeassistant.companion.android/io.homeassistant.companion.android.widgets.entity.EntityWidgetConfigureActivity (client)' was disposed without first being removed with the input manager!
02-02 20:42:21.743  5707  6111 E FrameEvents: updateAcquireFence: Did not find frame.
02-02 20:42:21.789  5707  8449 W RemoteViews: inflate error, layoutId = 2131558571
02-02 20:42:21.789  5707  8449 W RemoteViews: [0], io.homeassistant.companion.android : ApkAssets{path=<empty> and /system/framework/framework-res.apk}
02-02 20:42:21.789  5707  8449 W RemoteViews: [1], io.homeassistant.companion.android : ApkAssets{path=/vendor/overlay/framework-res__auto_generated_rro_vendor.apk}
02-02 20:42:21.789  5707  8449 W RemoteViews: [2], io.homeassistant.companion.android : ApkAssets{path=/product/overlay/CaptivePortalLoginFrameworkOverlay.apk}
02-02 20:42:21.789  5707  8449 W RemoteViews: [3], io.homeassistant.companion.android : ApkAssets{path=/product/overlay/GmsConfigOverlayASI.apk}
02-02 20:42:21.789  5707  8449 W RemoteViews: [4], io.homeassistant.companion.android : ApkAssets{path=/product/overlay/GmsConfigOverlayCommon.apk}
02-02 20:42:21.789  5707  8449 W RemoteViews: [5], io.homeassistant.companion.android : ApkAssets{path=/product/overlay/GmsConfigOverlayGSA.apk}
02-02 20:42:21.789  5707  8449 W RemoteViews: [6], io.homeassistant.companion.android : ApkAssets{path=/product/overlay/GmsConfigOverlayGeotz.apk}
02-02 20:42:21.789  5707  8449 W RemoteViews: [7], io.homeassistant.companion.android : ApkAssets{path=/product/overlay/GmsConfigOverlaySearchSelector.apk}
02-02 20:42:21.789  5707  8449 W RemoteViews: [8], io.homeassistant.companion.android : ApkAssets{path=/product/overlay/GoogleExtServicesConfigOverlay.apk}
02-02 20:42:21.789  5707  8449 W RemoteViews: [9], io.homeassistant.companion.android : ApkAssets{path=/product/overlay/GooglePermissionControllerFrameworkOverlay.apk}
02-02 20:42:21.789  5707  8449 W RemoteViews: [10], io.homeassistant.companion.android : ApkAssets{path=/product/overlay/ModuleMetadataGoogleOverlay.apk}
02-02 20:42:21.789  5707  8449 W RemoteViews: [11], io.homeassistant.companion.android : ApkAssets{path=/product/overlay/framework-res__auto_generated_rro_product.apk}
02-02 20:42:21.789  5707  8449 W RemoteViews: [12], io.homeassistant.companion.android : ApkAssets{path=/system/system_ext/overlay/smartfaceservice_overlay.apk}
02-02 20:42:21.789  5707  8449 W RemoteViews: [13], io.homeassistant.companion.android : ApkAssets{path=<empty> and /data/app/~~MXAty6VtIozDNZU0KrMLfA==/ch.deletescape.lawnchair.plah-lyfUHl0mFJW5yVjq-EWVWg==/base.apk}
02-02 20:42:21.789  5707  8449 W RemoteViews: [14], io.homeassistant.companion.android : ApkAssets{path=/product/overlay/NavigationBarMode3Button/NavigationBarMode3ButtonOverlay.apk}
02-02 20:42:21.790  5707  5707 W AppWidgetHostView: Error inflating RemoteViews
02-02 20:42:21.790  5707  5707 W AppWidgetHostView: android.view.InflateException: Binary XML file line #7 in io.homeassistant.companion.android:layout/widget_static_wrapper_dynamiccolor: Binary XML file line #28 in io.homeassistant.companion.android:layout/widget_static: Error inflating class TextView
02-02 20:42:21.790  5707  5707 W AppWidgetHostView: Caused by: android.view.InflateException: Binary XML file line #28 in io.homeassistant.companion.android:layout/widget_static: Error inflating class TextView
02-02 20:42:21.790  5707  5707 W AppWidgetHostView: Caused by: java.lang.NumberFormatException: For input string: "@2132018277"
02-02 20:42:21.790  5707  5707 W AppWidgetHostView: 	at java.lang.Integer.parseInt(Integer.java:797)
02-02 20:42:21.790  5707  5707 W AppWidgetHostView: 	at com.android.internal.util.XmlUtils.convertValueToInt(XmlUtils.java:348)
02-02 20:42:21.790  5707  5707 W AppWidgetHostView: 	at android.content.res.TypedArray.getInt(TypedArray.java:435)
02-02 20:42:21.790  5707  5707 W AppWidgetHostView: 	at ch.deletescape.lawnchair.font.CustomFontManager.loadCustomFont(CustomFontManager.kt:3)
02-02 20:42:21.790  5707  5707 W AppWidgetHostView: 	at ch.deletescape.lawnchair.LawnchairLayoutInflater.onViewCreated(LawnchairLayoutInflater.kt:3)
02-02 20:42:21.790  5707  5707 W AppWidgetHostView: 	at ch.deletescape.lawnchair.LawnchairLayoutInflater.onCreateView(LawnchairLayoutInflater.kt:2)
02-02 20:42:21.790  5707  5707 W AppWidgetHostView: 	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:978)
02-02 20:42:21.790  5707  5707 W AppWidgetHostView: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1032)
02-02 20:42:21.790  5707  5707 W AppWidgetHostView: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:989)
02-02 20:42:21.790  5707  5707 W AppWidgetHostView: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1151)
02-02 20:42:21.790  5707  5707 W AppWidgetHostView: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1112)
02-02 20:42:21.790  5707  5707 W AppWidgetHostView: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1154)
02-02 20:42:21.790  5707  5707 W AppWidgetHostView: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1112)
02-02 20:42:21.790  5707  5707 W AppWidgetHostView: 	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1291)
02-02 20:42:21.790  5707  5707 W AppWidgetHostView: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1147)
02-02 20:42:21.790  5707  5707 W AppWidgetHostView: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1112)
02-02 20:42:21.790  5707  5707 W AppWidgetHostView: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:700)
02-02 20:42:21.790  5707  5707 W AppWidgetHostView: 	at ch.deletescape.lawnchair.LawnchairLayoutInflater.inflate(LawnchairLayoutInflater.kt:1)
02-02 20:42:21.790  5707  5707 W AppWidgetHostView: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:544)
02-02 20:42:21.790  5707  5707 W AppWidgetHostView: 	at android.widget.RemoteViews.inflateView(RemoteViews.java:6194)
02-02 20:42:21.790  5707  5707 W AppWidgetHostView: 	at android.widget.RemoteViews.-$$Nest$minflateView(Unknown Source:0)
02-02 20:42:21.790  5707  5707 W AppWidgetHostView: 	at android.widget.RemoteViews$AsyncApplyTask.doInBackground(RemoteViews.java:6331)
02-02 20:42:21.790  5707  5707 W AppWidgetHostView: 	at android.widget.RemoteViews$AsyncApplyTask.doInBackground(RemoteViews.java:6293)
02-02 20:42:21.790  5707  5707 W AppWidgetHostView: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
02-02 20:42:21.790  5707  5707 W AppWidgetHostView: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
02-02 20:42:21.790  5707  5707 W AppWidgetHostView: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
02-02 20:42:21.790  5707  5707 W AppWidgetHostView: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
02-02 20:42:21.790  5707  5707 W AppWidgetHostView: 	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by dshokouhi** [comment]
quite possible, we are not sure what to be looking for as we didnt make any changes to widgets lately asides from a small change to the Picture Widget. Does seem to be an issue with the launcher. The error you are seeing is actually not coming from the app but the launcher itself. I wonder if we need to file a bug with the launcher to correct this. The only other change I can foresee causing this is a dependency update  🤔

**Comment by arthurrump** [comment]
I did some more tests, and it's only happening in Lawnchair 2, so that indeed suggests it's a bug, or at least some weird incompatibility, with the launcher. I was looking through the changes for this release and a dependency update is indeed the only thing I can imagine being the cause here. Given that Lawnchair 2 wasn't updated since 2019, there might well be something incompatible going on.

It's working on the latest alpha releases of Lawnchair, so I don't think we need to file a bug over there. (There have been updates to Lawnchair, they just haven't been able to release anything stable in the last five years...)

Is the `""@2132018277"` value coming from the Home Assistant app? Or is that coming from somewhere else?

**Comment by jpelgrom** [comment]
`@2132018277` is a reference to a specific resource. Whether it is looking in Lawnchair's resources or the Home Assistant app: no idea.

Converting it to hex (`7F140465`) and checking with the latest HA release we end up at... `Widget.MaterialComponents.ChipGroup`?
![resources.asrc showing ID 0x7f140465](https://github.com/home-assistant/android/assets/8148535/12341ede-d594-49c9-abda-1720ba3fde69)

Might be good to see what happens on the next (beta) release of the app when these resource IDs may change.

**Comment by morgantic** [comment]
Same issue. It was working fine before the last update to the Home Assistant Android app. Did something change? I'm also using lawnchair launcher.

**Comment by dshokouhi** [comment]
after receiving confirmation from the author in #4180 I am going to close this issue as it is a duplicate, please track the other bug for recent updates
