### ISSUE TITLE
High battery usage when endpoint is unavailable

### ISSUE THREAD

**Issue by danirebollo** [home-assistant/android#4543]
**Home Assistant Android app version(s):**
2024.7.3-full

**Android version(s):**
15

**Device model(s):**
Pixel 8

**Home Assistant version:**

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
From time to time I have my Home Assistant instance down and my Home Assistant Android App can't found it.
Instead a simple "Caution, endpoint not found" or something like this, the app tryes to connect much more times than before.
In fact I can see battery usage of 30% in a day. I don't know if it is because wakelocks or any other connection, but I think this can be handled in a better way. Also whould be fine to have an option to temporary disable the endpoint to avoid this anoying notificarions all time.

Greetings

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
duplicate of either #2933 or #3464

and yes the app will keep trying to send data as it normally does until it starts to send, its not that its retrying its just that data gets sent that often and some servers end up in a bad state causing this drain to happen. A shut down server actually does not produce drain like this. If you check the companion app logs I suspect the calls are timing out instead of failing immediately.

**Comment by danirebollo** [comment]
Hi, this are part of ny logs:

`
--------- beginning of main

08-01 16:47:38.376 23106  3620 E SensorReceiver: Issue re-registering sensor nfc_state

08-01 16:47:38.376 23106  3620 E SensorReceiver: io.homeassistant.companion.android.common.data.integration.IntegrationException: Error calling integration request register_sensor

08-01 16:47:38.376 23106  3620 E SensorReceiver: 	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl.registerSensor(IntegrationRepositoryImpl.kt:753)

08-01 16:47:38.376 23106  3620 E SensorReceiver: 	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl$registerSensor$1.invokeSuspend(Unknown Source:15)

08-01 16:47:38.376 23106  3620 E SensorReceiver: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)

08-01 16:47:38.376 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)

08-01 16:47:38.376 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)

08-01 16:47:38.376 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)

08-01 16:47:38.376 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)

08-01 16:47:38.376 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)

08-01 16:47:38.376 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)

08-01 16:47:38.376 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)

08-01 16:47:38.381 23106  3620 D ServerConnectionInfo: localUrl is: true, usesInternalSsid is: false, usesWifi is: false

08-01 16:47:38.446 23106  3620 E SensorReceiver: Issue re-registering sensor next_alarm

08-01 16:47:38.446 23106  3620 E SensorReceiver: io.homeassistant.companion.android.common.data.integration.IntegrationException: Error calling integration request register_sensor

08-01 16:47:38.446 23106  3620 E SensorReceiver: 	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl.registerSensor(IntegrationRepositoryImpl.kt:753)

08-01 16:47:38.446 23106  3620 E SensorReceiver: 	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl$registerSensor$1.invokeSuspend(Unknown Source:15)

08-01 16:47:38.446 23106  3620 E SensorReceiver: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)

08-01 16:47:38.446 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)

08-01 16:47:38.446 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)

08-01 16:47:38.446 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)

08-01 16:47:38.446 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)

08-01 16:47:38.446 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)

08-01 16:47:38.446 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)

08-01 16:47:38.446 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)

08-01 16:47:38.450 23106  3620 D ServerConnectionInfo: localUrl is: true, usesInternalSsid is: false, usesWifi is: false

08-01 16:47:38.537 23106  3620 E SensorReceiver: Issue registering sensor last_notification

08-01 16:47:38.537 23106  3620 E SensorReceiver: io.homeassistant.companion.android.common.data.integration.IntegrationException: Error calling integration request register_sensor

08-01 16:47:38.537 23106  3620 E SensorReceiver: 	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl.registerSensor(IntegrationRepositoryImpl.kt:753)

08-01 16:47:38.537 23106  3620 E SensorReceiver: 	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl$registerSensor$1.invokeSuspend(Unknown Source:15)

08-01 16:47:38.537 23106  3620 E SensorReceiver: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)

08-01 16:47:38.537 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)

08-01 16:47:38.537 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)

08-01 16:47:38.537 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)

08-01 16:47:38.537 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)

08-01 16:47:38.537 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)

08-01 16:47:38.537 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)

08-01 16:47:38.537 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)

08-01 16:47:38.545 23106  3620 D ServerConnectionInfo: localUrl is: true, usesInternalSsid is: false, usesWifi is: false

08-01 16:47:38.626 23106  3620 E SensorReceiver: Issue re-registering sensor last_removed_notification

08-01 16:47:38.626 23106  3620 E SensorReceiver: io.homeassistant.companion.android.common.data.integration.IntegrationException: Error calling integration request register_sensor

08-01 16:47:38.626 23106  3620 E SensorReceiver: 	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl.registerSensor(IntegrationRepositoryImpl.kt:753)

08-01 16:47:38.626 23106  3620 E SensorReceiver: 	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl$registerSensor$1.invokeSuspend(Unknown Source:15)

08-01 16:47:38.626 23106  3620 E SensorReceiver: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)

08-01 16:47:38.626 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)

08-01 16:47:38.626 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)

08-01 16:47:38.626 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)

08-01 16:47:38.626 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)

08-01 16:47:38.626 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)

08-01 16:47:38.626 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)

08-01 16:47:38.626 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)

08-01 16:47:38.636 23106  3620 D ServerConnectionInfo: localUrl is: true, usesInternalSsid is: false, usesWifi is: false

08-01 16:47:38.804 23106  3620 E SensorReceiver: Issue registering sensor active_notification_count

08-01 16:47:38.804 23106  3620 E SensorReceiver: io.homeassistant.companion.android.common.data.integration.IntegrationException: Error calling integration request register_sensor

08-01 16:47:38.804 23106  3620 E SensorReceiver: 	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl.registerSensor(IntegrationRepositoryImpl.kt:753)

08-01 16:47:38.804 23106  3620 E SensorReceiver: 	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl$registerSensor$1.invokeSuspend(Unknown Source:15)

08-01 16:47:38.804 23106  3620 E SensorReceiver: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)

08-01 16:47:38.804 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)

08-01 16:47:38.804 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)

08-01 16:47:38.804 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)

08-01 16:47:38.804 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)

08-01 16:47:38.804 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)

08-01 16:47:38.804 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)

08-01 16:47:38.804 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)

08-01 16:47:38.807 23106  3620 D ServerConnectionInfo: localUrl is: true, usesInternalSsid is: false, usesWifi is: false

08-01 16:47:39.010 23106  3620 E SensorReceiver: Issue re-registering sensor media_session

08-01 16:47:39.010 23106  3620 E SensorReceiver: io.homeassistant.companion.android.common.data.integration.IntegrationException: Error calling integration request register_sensor

08-01 16:47:39.010 23106  3620 E SensorReceiver: 	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl.registerSensor(IntegrationRepositoryImpl.kt:753)

08-01 16:47:39.010 23106  3620 E SensorReceiver: 	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl$registerSensor$1.invokeSuspend(Unknown Source:15)

08-01 16:47:39.010 23106  3620 E SensorReceiver: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)

08-01 16:47:39.010 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)

08-01 16:47:39.010 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)

08-01 16:47:39.010 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)

08-01 16:47:39.010 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)

08-01 16:47:39.010 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)

08-01 16:47:39.010 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)

08-01 16:47:39.010 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)

08-01 16:47:39.013 23106  3620 D ServerConnectionInfo: localUrl is: true, usesInternalSsid is: false, usesWifi is: false

08-01 16:47:39.084 23106  3620 E SensorReceiver: Issue re-registering sensor phone_state

08-01 16:47:39.084 23106  3620 E SensorReceiver: io.homeassistant.companion.android.common.data.integration.IntegrationException: Error calling integration request register_sensor

08-01 16:47:39.084 23106  3620 E SensorReceiver: 	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl.registerSensor(IntegrationRepositoryImpl.kt:753)

08-01 16:47:39.084 23106  3620 E SensorReceiver: 	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl$registerSensor$1.invokeSuspend(Unknown Source:15)

08-01 16:47:39.084 23106  3620 E SensorReceiver: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)

08-01 16:47:39.084 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)

08-01 16:47:39.084 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)

08-01 16:47:39.084 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)

08-01 16:47:39.084 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)

08-01 16:47:39.084 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)

08-01 16:47:39.084 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)

08-01 16:47:39.084 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)

08-01 16:47:39.091 23106  3620 D ServerConnectionInfo: localUrl is: true, usesInternalSsid is: false, usesWifi is: false

08-01 16:47:39.169 23106  3620 E SensorReceiver: Issue re-registering sensor sim_1

08-01 16:47:39.169 23106  3620 E SensorReceiver: io.homeassistant.companion.android.common.data.integration.IntegrationException: Error calling integration request register_sensor

08-01 16:47:39.169 23106  3620 E SensorReceiver: 	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl.registerSensor(IntegrationRepositoryImpl.kt:753)

08-01 16:47:39.169 23106  3620 E SensorReceiver: 	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl$registerSensor$1.invokeSuspend(Unknown Source:15)

08-01 16:47:39.169 23106  3620 E SensorReceiver: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)

08-01 16:47:39.169 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)

08-01 16:47:39.169 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)

08-01 16:47:39.169 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)

08-01 16:47:39.169 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)

08-01 16:47:39.169 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)

08-01 16:47:39.169 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)

08-01 16:47:39.169 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)

08-01 16:47:39.175 23106  3620 D ServerConnectionInfo: localUrl is: true, usesInternalSsid is: false, usesWifi is: false

08-01 16:47:39.253 23106  3620 E SensorReceiver: Issue re-registering sensor sim_2

08-01 16:47:39.253 23106  3620 E SensorReceiver: io.homeassistant.companion.android.common.data.integration.IntegrationException: Error calling integration request register_sensor

08-01 16:47:39.253 23106  3620 E SensorReceiver: 	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl.registerSensor(IntegrationRepositoryImpl.kt:753)

08-01 16:47:39.253 23106  3620 E SensorReceiver: 	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl$registerSensor$1.invokeSuspend(Unknown Source:15)

08-01 16:47:39.253 23106  3620 E SensorReceiver: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)

08-01 16:47:39.253 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)

08-01 16:47:39.253 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)

08-01 16:47:39.253 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)

08-01 16:47:39.253 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)

08-01 16:47:39.253 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)

08-01 16:47:39.253 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)

08-01 16:47:39.253 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)

08-01 16:47:39.261 23106  3620 D ServerConnectionInfo: localUrl is: true, usesInternalSsid is: false, usesWifi is: false

08-01 16:47:39.358 23106  3620 E SensorReceiver: Issue registering sensor is_interactive

08-01 16:47:39.358 23106  3620 E SensorReceiver: io.homeassistant.companion.android.common.data.integration.IntegrationException: Error calling integration request register_sensor

08-01 16:47:39.358 23106  3620 E SensorReceiver: 	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl.registerSensor(IntegrationRepositoryImpl.kt:753)

08-01 16:47:39.358 23106  3620 E SensorReceiver: 	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl$registerSensor$1.invokeSuspend(Unknown Source:15)

08-01 16:47:39.358 23106  3620 E SensorReceiver: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)

08-01 16:47:39.358 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)

08-01 16:47:39.358 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)

08-01 16:47:39.358 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)

08-01 16:47:39.358 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)

08-01 16:47:39.358 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)

08-01 16:47:39.358 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)

08-01 16:47:39.358 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)

08-01 16:47:39.366 23106  3620 D ServerConnectionInfo: localUrl is: true, usesInternalSsid is: false, usesWifi is: false

08-01 16:47:39.460 23106  3620 E SensorReceiver: Issue registering sensor is_idle

08-01 16:47:39.460 23106  3620 E SensorReceiver: io.homeassistant.companion.android.common.data.integration.IntegrationException: Error calling integration request register_sensor

08-01 16:47:39.460 23106  3620 E SensorReceiver: 	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl.registerSensor(IntegrationRepositoryImpl.kt:753)

08-01 16:47:39.460 23106  3620 E SensorReceiver: 	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl$registerSensor$1.invokeSuspend(Unknown Source:15)

08-01 16:47:39.460 23106  3620 E SensorReceiver: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)

08-01 16:47:39.460 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)

08-01 16:47:39.460 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)

08-01 16:47:39.460 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)

08-01 16:47:39.460 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)

08-01 16:47:39.460 23106  3620 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)

08-01 16:47:39.460 23106  3620 E SensorReceiver: 	at k
`

**Comment by dshokouhi** [comment]
actually those errors are incomplete the very first failure will contain the actual traceback
