### ISSUE TITLE
Crash caused by Health Connect rate limiting

### ISSUE THREAD

**Issue by marazmarci** [home-assistant/android#4829]
**Home Assistant Android app version(s):**
`2024.11.5-full`

**Android version(s):**
Android 13

**Device model(s):**
Samsung S20 FE 5G

**Home Assistant version:**
`2024.8.1`

**Last working Home Assistant release (if known):**
I first observed this crash on this version, but it may have crashed earlier in the background.

**Description of problem, include YAML if issue is related to notifications:**

**Companion App Logs:**

```
FATAL EXCEPTION: main
Process: [io.homeassistant.companion.android](http://io.homeassistant.companion.android/)
android.os.RemoteException: Request rejected. Rate limited request quota has been exceeded. Please wait until quota has replenished before making further requests.
    at androidx.health.connect.client.impl.HealthConnectClientImpl.getGrantedPermissions(HealthConnectClientImpl.kt:301)
    at androidx.health.connect.client.impl.HealthConnectClientImpl$getGrantedPermissions$1.invokeSuspend(Unknown Source:14)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:99)
    at android.os.Handler.handleCallback(Handler.java:942)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8762)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
    Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@64cf3d, Dispatchers.Main.immediate]
Caused by: android.os.RemoteException: Request rejected. Rate limited request quota has been exceeded. Please wait until quota has replenished before making further requests.
    at androidx.health.platform.client.impl.error.ErrorStatusConverterKt.toException(ErrorStatusConverter.kt:49)
    at androidx.health.platform.client.impl.FilterGrantedPermissionsCallback.onError(FilterGrantedPermissionsCallback.kt:34)
    at androidx.health.platform.client.service.IFilterGrantedPermissionsCallback$Stub.onTransact(IFilterGrantedPermissionsCallback.java:73)
    at android.os.Binder.execTransactInternal(Binder.java:1321)
    at android.os.Binder.execTransact(Binder.java:1280)
```

**Screenshot or video of problem:**

**Additional information:**
This issue causes the app to crash repeatedly and can't be opened until the rate limit cools down.

The `RemoteException` was thrown by `getGrantedPermissions()` which is called here: https://github.com/home-assistant/android/blob/9c63abd7c48961dea17356a37f5358245db0ea0d/app/src/full/java/io/homeassistant/companion/android/sensors/HealthConnectSensorManager.kt#L437

Google's guide about Health Connect rate limiting:
https://developer.android.com/health-and-fitness/guides/health-connect/plan/rate-limiting

**Comment by dshokouhi** [comment]
Do you have background access granted for the app? I have yet to see this on my end. I think it's related to background reads but foreground should be fine which is what it should be doing

**Comment by dshokouhi** [comment]
looks like in play console this only impacts versions below android 14 which would explain why we did not see it. Still curious to see if background access was granted and if these were all foreground reads. At least on android 15 it updates just fine, even updating once a minute over night without crashes or rate limit complaints:

![image](https://github.com/user-attachments/assets/caf68490-3737-4860-9b07-6499744bc0e5)

thanks for reporting @marazmarci ! We anticipated we may need to add try/catch but as we did not see it during initial development we thought it was not as important but seems we were wrong lol do you happen to know how often your sensors were updating at the time this happened?

**Comment by marazmarci** [comment]
> Do you have background access granted for the app? I have yet to see this on my end. I think it's related to background reads but foreground should be fine which is what it should be doing

Yes, I have background access granted.

**Comment by marazmarci** [comment]
Ohh, sorry, I forgot to answer your second question 🤦🏻‍♂️ It may be very late, but here's my answer 😅

> do you happen to know how often your sensors were updating at the time this happened?

My sensor update frequency is set to `Fast while charging`, and I often leave my phone on the charger.
