### ISSUE TITLE
Support download snapshot feature from HA core 2024.12.x (blob: uri downloads)

### ISSUE THREAD

**Issue by dshokouhi** [home-assistant/android#4888]
**Is your feature request related to a problem? Please describe.**

a new feature was added taht would be nice for us to support

https://github.com/home-assistant/frontend/pull/22704

**Describe the solution you'd like**

add support so the snapshot can download

**Describe alternatives you've considered, if any**

**Additional context**

Currently user sees a toast message saying not supported so the error is handled

```
12-06 18:28:44.420  2133  2133 D WebviewActivity: WebView requested download of blob:https://DOMAIN:8123/f7915b23-34d0-46bc-8e56-ff6412613a40
12-06 18:28:44.420  2133  2133 D WebviewActivity: Received download request for unsupported scheme, forwarding to system
12-06 18:28:44.422  2133  2133 E WebviewActivity: Unable to forward download request to system
12-06 18:28:44.422  2133  2133 E WebviewActivity: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=blob: flg=0x10000000 }
12-06 18:28:44.422  2133  2133 E WebviewActivity: 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2432)
12-06 18:28:44.422  2133  2133 E WebviewActivity: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:2007)
12-06 18:28:44.422  2133  2133 E WebviewActivity: 	at android.app.Activity.startActivityForResult(Activity.java:5882)
12-06 18:28:44.422  2133  2133 E WebviewActivity: 	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.kt:704)
12-06 18:28:44.422  2133  2133 E WebviewActivity: 	at android.app.Activity.startActivityForResult(Activity.java:5839)
12-06 18:28:44.422  2133  2133 E WebviewActivity: 	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.kt:683)
12-06 18:28:44.422  2133  2133 E WebviewActivity: 	at android.app.Activity.startActivity(Activity.java:6342)
12-06 18:28:44.422  2133  2133 E WebviewActivity: 	at android.app.Activity.startActivity(Activity.java:6309)
12-06 18:28:44.422  2133  2133 E WebviewActivity: 	at io.homeassistant.companion.android.webview.WebViewActivity.downloadFile(WebViewActivity.kt:1600)
12-06 18:28:44.422  2133  2133 E WebviewActivity: 	at io.homeassistant.companion.android.webview.WebViewActivity.onCreate$lambda$9$lambda$8(WebViewActivity.kt:502)
12-06 18:28:44.422  2133  2133 E WebviewActivity: 	at io.homeassistant.companion.android.webview.WebViewActivity.$r8$lambda$nYX8gkl9SVz7fuvLglWRpV-BpVU(Unknown Source:0)
12-06 18:28:44.422  2133  2133 E WebviewActivity: 	at io.homeassistant.companion.android.webview.WebViewActivity$$ExternalSyntheticLambda36.onDownloadStart(D8$$SyntheticClass:0)
12-06 18:28:44.422  2133  2133 E WebviewActivity: 	at WV.g7.handleMessage(chromium-TrichromeWebViewGoogle6432.aab-stable-677803933:483)
12-06 18:28:44.422  2133  2133 E WebviewActivity: 	at android.os.Handler.dispatchMessage(Handler.java:109)
12-06 18:28:44.422  2133  2133 E WebviewActivity: 	at android.os.Looper.loopOnce(Looper.java:232)
12-06 18:28:44.422  2133  2133 E WebviewActivity: 	at android.os.Looper.loop(Looper.java:317)
12-06 18:28:44.422  2133  2133 E WebviewActivity: 	at android.app.ActivityThread.main(ActivityThread.java:8787)
12-06 18:28:44.422  2133  2133 E WebviewActivity: 	at java.lang.reflect.Method.invoke(Native Method)
12-06 18:28:44.422  2133  2133 E WebviewActivity: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
12-06 18:28:44.422  2133  2133 E WebviewActivity: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:871)
```

**Comment by ruralsysadmin** [comment]
Adding in that on the Android app (Ver 2025.1.2-full on Pixel 7 Android 15), I get the "not supported" message when attempting to download data via the three dot menu. When using Chrome web browser on the same phone, attempting to download data functions and a CSV is downloaded.
