### ISSUE TITLE
Implement ability to launch intents from app

### ISSUE THREAD

**Issue by klejejs** [home-assistant/android#569]
**Home Assistant Android version:**
1.8.0-159
**Android version:**
10.0
**Phone model:**
Pixel 4
**Home Assistant version:**
0.107
**Last working Home Assistant release (if known):**

**Description of problem:**
Currently clicking on a URL that has intent inside it crashes the app. It would be nice if it opened another app in the intent.
**Traceback (if applicable):**

```

```

**Screenshot of problem:**

**Additional information:**
The intent URL I am using: [intent://qremote/#Intent;component=com.qnap.qremote/com.qnap.qremote.SplashActivity;end](intent://qremote/#Intent;component=com.qnap.qremote/com.qnap.qremote.SplashActivity;end)

**Comment by klejejs** [comment]
I am sorry, but I think you you misunderstood the issue. I don't think it is related to notifications. The problem is related to "weblink" entities in Lovelace dashboard.

**Comment by dshokouhi** [comment]
@klejejs that would then be a frontend request and not for the android app.  You are referring to a lovelace card.  The app just displays the card.  Please open a request in the frontend repo.

**Comment by klejejs** [comment]
Frontend supports it except it opens Google Play Store, not the app itself. For opening another app, intents should be supported in the android app, not frontend. Also, the app straight up crashes, when you click on that link, it doesn't even open Play Store, so I think this is a valid issue and should be reopened.

**Comment by klejejs** [comment]
I have added the intent URL to the original issue post and can confirm, that this is working in [Kiosk Browser](https://play.google.com/store/apps/details?id=de.ozerov.fully)

**Comment by klejejs** [comment]
I am not very familiar with Kotlin, so I am not sure how to fix this, but here are the crash logs.
As far as I understand, the app should support the handling of "intent:" url's.

```
ActivityTaskManager: START u0 {act=android.intent.action.VIEW dat=intent://qremote/} from uid 10157
Shutting down VM
FATAL EXCEPTION: main
Process: io.homeassistant.companion.android, PID: 16658
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=intent://qremote/ }
       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2058)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1716)
       at android.app.Activity.startActivityForResult(Activity.java:5210)
       at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:676)
       at android.app.Activity.startActivityForResult(Activity.java:5168)
       at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:663)
       at android.app.Activity.startActivity(Activity.java:5539)
       at android.app.Activity.startActivity(Activity.java:5507)
       at io.homeassistant.companion.android.webview.WebViewActivity$onCreate$$inlined$apply$lambda$1.shouldOverrideUrlLoading(WebViewActivity.kt:151)
       at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(PG:16)
       at android.os.MessageQueue.nativePollOnce(Native Method)
       at android.os.MessageQueue.next(MessageQueue.java:336)
       at android.os.Looper.loop(Looper.java:174)
       at android.app.ActivityThread.main(ActivityThread.java:7356)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by klejejs** [comment]
Still relevant.

**Comment by dshokouhi** [comment]
@klejejs i think this is now possible since https://github.com/home-assistant/android/pull/1129 was merged, can you check on your end? if you still have issues let me know what command you sent in the notification.

Docs: https://companion.home-assistant.io/docs/notifications/notification-commands#broadcast-intent

If you need to launch an app that is also possible via actionable notifications: https://companion.home-assistant.io/docs/notifications/actionable-notifications#building-automations-for-notification-actions

**Comment by dshokouhi** [comment]
this new command might do the trick here...I hope lol

https://companion.home-assistant.io/docs/notifications/notification-commands#activity

let me know if were good to close this now or if we need to do something more specific here.

**Comment by dshokouhi** [comment]
@klejejs when the debug APK for #1344 is done you can test your intent URL and hopefully it will work.... I believe this is what you were looking to do right? lol
