### ISSUE TITLE
java.lang.SecurityException: Client must have ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION permission to perform any location operations.

### ISSUE THREAD

**Issue by balloob** [home-assistant/android#630]
This issue has 10376 crashes affecting 1133 users.

Introduced in 1.9.0-167 (167).

https://console.firebase.google.com/u/0/project/home-assistant-mobile-apps/crashlytics/app/android:io.homeassistant.companion.android/issues/573d46a422bfd9f00acad582368da78b?time=last-seven-days&sessionId=5EE98FF501340001179701F0DB1018C9_DNE_0_v2

```
Caused by java.lang.SecurityException: Client must have ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION permission to perform any location operations.
       at android.os.Parcel.readException(Parcel.java:1945)
       at android.os.Parcel.readException(Parcel.java:1891)
       at com.google.android.gms.internal.location.zza.transactAndReadException(:10)
       at com.google.android.gms.internal.location.zzap.zza(:9)
       at com.google.android.gms.internal.location.zzas.getLastLocation(:19)
       at com.google.android.gms.internal.location.zzaz.getLastLocation(:2)
       at com.google.android.gms.location.zzl.doExecute(:2)
       at com.google.android.gms.common.api.internal.zag.zaa(:6)
       at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zac(:167)
       at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zab(:139)
       at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zabi(:99)
       at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zabg(:40)
       at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.onConnected(:19)
       at com.google.android.gms.common.internal.zaf.onConnected(:2)
       at com.google.android.gms.common.internal.BaseGmsClient$zzf.zzm(:24)
       at com.google.android.gms.common.internal.BaseGmsClient$zza.zza(:12)
       at com.google.android.gms.common.internal.BaseGmsClient$zzc.zzo(:11)
       at com.google.android.gms.common.internal.BaseGmsClient$zzb.handleMessage(:49)
       at android.os.Handler.dispatchMessage(Handler.java:108)
       at com.google.android.gms.internal.common.zze.dispatchMessage(:8)
       at android.os.Looper.loop(Looper.java:166)
       at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by balloob** [comment]
Similar issue: https://console.firebase.google.com/u/0/project/home-assistant-mobile-apps/crashlytics/app/android:io.homeassistant.companion.android/issues/089bf9f106e83a657a5d630bd02b2548?time=last-seven-days&sessionId=5EE9B8E7003D000178A161D600CD2345_DNE_0_v2

Seems related to Wifi getScanResults

**Comment by balloob** [comment]
Captured this with adb logcat. This one was logged when I opened the app brand new. It has no auth yet:

```
06-16 23:31:28.605   915   945 E WifiService: Permission violation - getScanResults not allowed for uid=10195, packageName=io.homeassistant.companion.android, reason=java.lang.SecurityException: UID 10195 has no location permission
```
