### ISSUE TITLE
App crashed when reading an un-written/blank NFC tag

### ISSUE THREAD

**Issue by jesserockz** [home-assistant/android#735]
**Home Assistant Android version:** 2.1.1-4-g7b0e28f-253-full

**Android version:** 10

**Phone model:** Motorola Moto One Vision

**Home Assistant version:** 0.114.0b4

**Last working Home Assistant release (if known):**

**Description of problem:** Home Assistant Companion either crashes or goes back to the App Configuration screen when trying to **read** an NFC tag that has not had a uuid tag_id written to it.  
The same tag works fine after it has been written to.

**Traceback (if applicable):**

```
08-12 13:00:34.069 28114 28114 E AndroidRuntime: FATAL EXCEPTION: main
08-12 13:00:34.069 28114 28114 E AndroidRuntime: Process: io.homeassistant.companion.android, PID: 28114
08-12 13:00:34.069 28114 28114 E AndroidRuntime: java.lang.IllegalStateException: rawMessages must not be null
08-12 13:00:34.069 28114 28114 E AndroidRuntime: 	at io.homeassistant.companion.android.nfc.NfcSetupActivity.onNewIntent(NfcSetupActivity.kt:74)
08-12 13:00:34.069 28114 28114 E AndroidRuntime: 	at android.app.Activity.performNewIntent(Activity.java:7824)
08-12 13:00:34.069 28114 28114 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1428)
08-12 13:00:34.069 28114 28114 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1441)
08-12 13:00:34.069 28114 28114 E AndroidRuntime: 	at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:3687)
08-12 13:00:34.069 28114 28114 E AndroidRuntime: 	at android.app.ActivityThread.handleNewIntent(ActivityThread.java:3699)
08-12 13:00:34.069 28114 28114 E AndroidRuntime: 	at android.app.servertransaction.NewIntentItem.execute(NewIntentItem.java:53)
08-12 13:00:34.069 28114 28114 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
08-12 13:00:34.069 28114 28114 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
08-12 13:00:34.069 28114 28114 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2183)
08-12 13:00:34.069 28114 28114 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
08-12 13:00:34.069 28114 28114 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:241)
08-12 13:00:34.069 28114 28114 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7617)
08-12 13:00:34.069 28114 28114 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-12 13:00:34.069 28114 28114 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
08-12 13:00:34.069 28114 28114 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
```

**Screenshot of problem:**

**Additional information:**

**Comment by pergolafabio** [comment]
hi, do you also need 114 for this? wrote a tag, created an automation, but recieve error below:
[homeassistant.components.mobile_app.webhook] Received invalid webhook type: scan_tag

is 114 also needed?

**Comment by jesserockz** [comment]
The code on the HA core side was only just merged in, so I don't actually think it will even make it into 0.114 and you will need to wait until 0.115. I could be wrong though. 🤷‍♂️ 
I received the same error on 0.114.0b4 but I am now running 0.115.0.dev20200812 and its working nicely (apart from the above crash)

**Comment by pergolafabio** [comment]
Ow ok ;) need to wait a month longer then ;)

**Comment by dshokouhi** [comment]
HA core was updated in 0.114 to allow mobile apps to work while we wait for the main integration in 0.115

**Comment by pergolafabio** [comment]
Hey @jesserockz , can you show me your working automation, my tag is scanned, but automation is not fired at all
