### ISSUE TITLE
Fatal crash while using the app debug and beta version

### ISSUE THREAD

**Issue by dshokouhi** [home-assistant/android#751]
**Home Assistant Android version:**
Latest master branch changes
**Android version:**
10
**Phone model:**
Pixel 4 XL
**Home Assistant version:**
0.115dev
**Last working Home Assistant release (if known):**
N/A
**Description of problem:**

While testing other new features I keep seeing the following traceback.  It seems to occur randomly and not related to an intent.  It looks like both apps crash together, maybe this is a side effect of having both apps installed at the same time with the new listeners?

The changes I am testing do not involve new listeners so I don't think its related to anything I have done yet?

**Traceback (if applicable):**

```
2020-08-13 17:16:27.875 8784-8784/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.homeassistant.companion.android, PID: 8784
    java.lang.RuntimeException: Unable to start receiver io.homeassistant.companion.android.sensors.SensorReceiver: java.lang.ClassCastException: android.app.ReceiverRestrictedContext cannot be cast to io.homeassistant.companion.android.common.dagger.GraphComponentAccessor
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3797)
        at android.app.ActivityThread.access$1400(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1870)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.ClassCastException: android.app.ReceiverRestrictedContext cannot be cast to io.homeassistant.companion.android.common.dagger.GraphComponentAccessor
        at io.homeassistant.companion.android.sensors.SensorReceiver.onReceive(SensorReceiver.kt:48)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3788)
        at android.app.ActivityThread.access$1400(ActivityThread.java:219) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1870) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
2020-08-13 17:16:27.882 8481-8481/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.homeassistant.companion.android.debug, PID: 8481
    java.lang.RuntimeException: Unable to start receiver io.homeassistant.companion.android.sensors.SensorReceiver: java.lang.ClassCastException: android.app.ReceiverRestrictedContext cannot be cast to io.homeassistant.companion.android.common.dagger.GraphComponentAccessor
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3797)
        at android.app.ActivityThread.access$1400(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1870)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.ClassCastException: android.app.ReceiverRestrictedContext cannot be cast to io.homeassistant.companion.android.common.dagger.GraphComponentAccessor
        at io.homeassistant.companion.android.sensors.SensorReceiver.onReceive(SensorReceiver.kt:49)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3788)
        at android.app.ActivityThread.access$1400(ActivityThread.java:219) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1870) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
Seeing the exact same crash and error on my wifes Pixel 3 XL which is on the latest beta `2.1.1-14`
