### ISSUE TITLE
Writing NFC tags doesn't work

### ISSUE THREAD

**Issue by bramkragten** [home-assistant/android#785]
**Home Assistant Android version:**
2.2.1

**Android version:**
10

**Phone model:**
Xiaomi 9SE

**Home Assistant version:**
0.115.dev

**Last working Home Assistant release (if known):**

**Description of problem:**
Writing my NFC tag results in a `Error while writing nfc tag`
Reading does work fine.

I ended up writing them with the [NFC Tools app](https://play.google.com/store/apps/details?id=com.wakdev.wdnfc&hl=en) and that worked fine.
![Screenshot_2020-08-19-13-29-42-798_com wakdev wdnfc](https://user-images.githubusercontent.com/5662298/90629838-515b7300-e220-11ea-82cc-5f1cf259c627.jpg)

**Traceback (if applicable):**

```

```

**Screenshot of problem:**
![Screenshot_2020-08-19-13-07-52-257_io homeassistant companion android](https://user-images.githubusercontent.com/5662298/90629892-646e4300-e220-11ea-8d6f-65b19de11dd0.jpg)

**Additional information:**

**Comment by dshokouhi** [comment]
Unable to reproduce this on my pixel 4 with 0.115 latest changes.  Seems we are hitting some exception here for this device:

https://github.com/home-assistant/android/blob/master/app/src/main/java/io/homeassistant/companion/android/nfc/NfcSetupActivity.kt#L93

I wonder if we need the ADB logs to see what the actual cause was?

**Comment by bramkragten** [comment]
Tried to get logs, and now it successfully wrote them... Might it be that it had problems with writing the first time? When it is empty?

**Comment by bramkragten** [comment]
```
2020-08-19 20:39:59.562 29454-29454/? E/NfcSetupActivity: Unable to write tag.
    java.lang.Exception: Failed to format tag
        at io.homeassistant.companion.android.nfc.NFCUtil.writeMessageToTag(NFCUtil.kt:74)
        at io.homeassistant.companion.android.nfc.NFCUtil.createNFCMessage(NFCUtil.kt:22)
        at io.homeassistant.companion.android.nfc.NfcSetupActivity.onNewIntent(NfcSetupActivity.kt:85)
        at android.app.Activity.performNewIntent(Activity.java:7912)
        at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1407)
        at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1420)
        at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:3506)
        at android.app.ActivityThread.handleNewIntent(ActivityThread.java:3518)
        at android.app.servertransaction.NewIntentItem.execute(NewIntentItem.java:53)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2040)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7520)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: java.io.IOException
        at android.nfc.tech.NdefFormatable.format(NdefFormatable.java:131)
        at android.nfc.tech.NdefFormatable.format(NdefFormatable.java:94)
        at io.homeassistant.companion.android.nfc.NFCUtil.writeMessageToTag(NFCUtil.kt:69)
        at io.homeassistant.companion.android.nfc.NFCUtil.createNFCMessage(NFCUtil.kt:22) 
        at io.homeassistant.companion.android.nfc.NfcSetupActivity.onNewIntent(NfcSetupActivity.kt:85) 
        at android.app.Activity.performNewIntent(Activity.java:7912) 
        at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1407) 
        at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1420) 
        at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:3506) 
        at android.app.ActivityThread.handleNewIntent(ActivityThread.java:3518) 
        at android.app.servertransaction.NewIntentItem.execute(NewIntentItem.java:53) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2040) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:224) 
        at android.app.ActivityThread.main(ActivityThread.java:7520) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950) 
2020-08-19 20:39:59.679 4029-30427/? E/BrcmNfcJni: nativeNfcTag_doDisconnect: tag already deactivated
```

**Comment by bramkragten** [comment]
But it is working way better now, most writes work now... not sure what changed

**Comment by dshokouhi** [comment]
Thanks for the logs!!! When I did my test earlier I used a new tag, one thing I noticed is that some tags are very picky about the side that is used to write on.  I found I had to mark the side so I was able to tell :)

**Comment by nadworny** [comment]
Same issue here with a very old NFC tag which works fine using another app. In which logs can I find some stack trace? I couldn't find anything under supervisor / core logs.

**Comment by nadworny** [comment]
@bramkragten did you manage to set it up manually? Would you be do kind to share how?

**Comment by bramkragten** [comment]
Write the url `https://www.home-assistant.io/tag/<TAG_ID>` to your tag.

**Comment by nadworny** [comment]
Thanks a lot. I guess i need to buy another tags as it says message exceeds max tag size
