### ISSUE TITLE
Fatal error on first launch of latest master

### ISSUE THREAD

**Issue by klejejs** [home-assistant/android#811]
**Home Assistant Android version:**
Latest master: 5e1d275
**Android version:**
9.0
**Phone model:**
Pixel 3 emulator
**Home Assistant version:**
0.114
**Last working Home Assistant release (if known):**

**Description of problem:**

**Traceback (if applicable):**

```
E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-3
    Process: io.homeassistant.companion.android.debug, PID: 11954
    android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: sensors.unique_id (code 1555 SQLITE_CONSTRAINT_PRIMARYKEY)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:796)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
        at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeInsert(FrameworkSQLiteStatement.java:51)
        at androidx.room.EntityInsertionAdapter.insert(EntityInsertionAdapter.java:64)
        at io.homeassistant.companion.android.database.sensor.SensorDao_Impl.add(SensorDao_Impl.java:89)
        at io.homeassistant.companion.android.sensors.SensorManager$DefaultImpls.getEnabledSensorData(SensorManager.kt:64)
        at io.homeassistant.companion.android.sensors.AudioSensorManager.getEnabledSensorData(AudioSensorManager.kt:9)
        at io.homeassistant.companion.android.sensors.SensorReceiver.updateSensors(SensorReceiver.kt:91)
        at io.homeassistant.companion.android.sensors.SensorReceiver$onReceive$1.invokeSuspend(SensorReceiver.kt:66)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Screenshot of problem:**

**Additional information:**

**Comment by klejejs** [comment]
Might be fixed with #809. Debug apk didn't have the issue.

**Comment by dshokouhi** [comment]
I just had a device update to `2.2.1-18` which is still before #809 (even before the commit this issue mentions) and it experienced the same crash and error on a different sensor. I will keep an eye on when the latest beta gets to my account in the play store and report back if I see any more crashes or not.

```
08-25 20:47:29.783 32264-32315/? E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-2
    Process: io.homeassistant.companion.android, PID: 32264
    android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: sensors.unique_id (code 1555)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
        at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeInsert(FrameworkSQLiteStatement.java:51)
        at androidx.room.EntityInsertionAdapter.insert(EntityInsertionAdapter.java:64)
        at io.homeassistant.companion.android.database.sensor.SensorDao_Impl.add(SensorDao_Impl.java:89)
        at io.homeassistant.companion.android.sensors.SensorManager$DefaultImpls.getEnabledSensorData(SensorManager.kt:64)
        at io.homeassistant.companion.android.sensors.PressureSensorManager.getEnabledSensorData(PressureSensorManager.kt:12)
        at io.homeassistant.companion.android.sensors.SensorReceiver.updateSensors(SensorReceiver.kt:89)
        at io.homeassistant.companion.android.sensors.SensorReceiver$updateSensors$1.invokeSuspend(SensorReceiver.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```

**Comment by klejejs** [comment]
Didn't have the error anymore on the latest master in emulator.

**Comment by dshokouhi** [comment]
Yup all my devices updated to latest release and I did not see anymore of this crash.  I think we are good to close this one?

**Comment by dshokouhi** [comment]
Lets close this for now, if we see it again we can always re-open or create a new one.
