### ISSUE TITLE
Fatal error on devices without bluetooth

### ISSUE THREAD

**Issue by klejejs** [home-assistant/android#812]
**Home Assistant Android version:**
Latest build
**Android version:**
9
**Phone model:**
Pixel 3 emulator
**Home Assistant version:**
0.114
**Last working Home Assistant release (if known):**

**Description of problem:**

**Traceback (if applicable):**

```
E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-2
    Process: io.homeassistant.companion.android.debug, PID: 19624
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.bluetooth.IBluetoothManager android.bluetooth.BluetoothAdapter.getBluetoothManager()' on a null object reference
        at android.bluetooth.BluetoothManager.getConnectedDevices(BluetoothManager.java:133)
        at io.homeassistant.companion.android.sensors.BluetoothSensorManager.getBluetoothConnectionSensor(BluetoothSensorManager.kt:56)
        at io.homeassistant.companion.android.sensors.BluetoothSensorManager.getSensorData(BluetoothSensorManager.kt:36)
        at io.homeassistant.companion.android.sensors.SensorManager$DefaultImpls.getEnabledSensorData(SensorManager.kt:71)
        at io.homeassistant.companion.android.sensors.BluetoothSensorManager.getEnabledSensorData(BluetoothSensorManager.kt:11)
        at io.homeassistant.companion.android.sensors.SensorReceiver.updateSensors(SensorReceiver.kt:91)
        at io.homeassistant.companion.android.sensors.SensorReceiver$onReceive$1.invokeSuspend(SensorReceiver.kt:66)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Screenshot of problem:**

**Additional information:**

**Comment by klejejs** [comment]
No crash on latest master. There is still an error but that I think is logical.

**Comment by dshokouhi** [comment]
My bad linked the issue and realized its for an older app version...don't see crashes in 2.3.0
