### ISSUE TITLE
Fatal crash for geocoded sensor

### ISSUE THREAD

**Issue by dshokouhi** [home-assistant/android#830]
**Home Assistant Android version:**

2.2.1-29

**Android version:**

Android 7

**Phone model:**

Fire HD8 with google services

**Home Assistant version:**

0.114

**Last working Home Assistant release (if known):**

N/A

**Description of problem:**

After updating to the latest play store beta I am seeing teh following crash

**Traceback (if applicable):**

```
2020-08-27 06:06:47.297 1566-25967/? E/AMZ-MAPS-ERROR-MSP_104: Unknown exception in getFromLocation for AppPackage[io.homeassistant.companion.android]. Reason: No Key data found for package: io.homeassistant.companion.android mapControlVersion: 1.0 while Reverse Geocoding.
2020-08-27 06:06:47.391 7575-7575/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.homeassistant.companion.android, PID: 7575
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:801)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:801) 
     Caused by: java.io.IOException: Geocoding failed, please look into the logs for more details!
        at android.location.Geocoder.getFromLocation(Geocoder.java:136)
        at io.homeassistant.companion.android.sensors.GeocodeSensorManager$updateGeocodedLocation$1.onSuccess(GeocodeSensorManager.kt:57)
        at io.homeassistant.companion.android.sensors.GeocodeSensorManager$updateGeocodedLocation$1.onSuccess(GeocodeSensorManager.kt:11)
        at com.google.android.gms.tasks.zzn.run(Unknown Source)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6188)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:801) 
```

**Screenshot of problem:**

**Additional information:**
Previously I was at commit #806 and I did not have this issue

**Comment by dshokouhi** [comment]
Tried to add a try/catch block but after enabling geocoded sensor it continues to crash with the same error

**Comment by JBassett** [comment]
Could you check if this is returning true?  We might need to add this check.
https://developer.android.com/reference/android/location/Geocoder#isPresent()

**Comment by dshokouhi** [comment]
Looks like it is returning true 

`Log.d(TAG, "GEOCODER ${Geocoder.isPresent()}")`

`2020-08-27 06:31:57.036 11394-11394/io.homeassistant.companion.android.debug D/GeocodeSM: GEOCODER true`

**Comment by dshokouhi** [comment]
my temporary work around is to just disable location permissions for the app so the sensor is disabled, then the app will launch i can enable sensors like wifi without having a crash. I can also re-enable the location ones.  The issue seems to be just with the geocoded sensor.
