### ISSUE TITLE
Fatal crash upon granting location permissions during onboarding on devices that do not do battery optimizations

### ISSUE THREAD

**Issue by dshokouhi** [home-assistant/android#833]
**Home Assistant Android version:**

2.2.1-29

**Android version:**

7.1.2

**Phone model:**

Fire HD8

**Home Assistant version:**

0.114

**Last working Home Assistant release (if known):**

N/A

**Description of problem:**

I have always seen this crash but finally realized I should really be opening an issue here.  This only occurs during onboarding on what I assume are devices that do not do battery optimization stuff.  After the crash I am still able to use the app.

**Traceback (if applicable):**

```


2020-08-27 07:55:28.626 18781-18808/io.homeassistant.companion.android.debug V/FA: Recording user engagement, ms: 4149
2020-08-27 07:55:28.637 18781-18808/io.homeassistant.companion.android.debug V/FA: Activity paused, time: 2698912
2020-08-27 07:55:30.054 569-798/? I/ActivityManager: START u0 {act=android.settings.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS dat=package:io.homeassistant.companion.android.debug} from uid 10179 on display 0
2020-08-27 07:55:30.055 18781-18781/io.homeassistant.companion.android.debug D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
2020-08-27 07:55:30.061 18781-18781/io.homeassistant.companion.android.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.homeassistant.companion.android.debug, PID: 18781
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=131072, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {io.homeassistant.companion.android.debug/io.homeassistant.companion.android.onboarding.OnboardingActivity}: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.settings.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS dat=package:io.homeassistant.companion.android.debug }
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4144)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4187)
        at android.app.ActivityThread.-wrap20(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1544)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6188)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:801)
     Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.settings.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS dat=package:io.homeassistant.companion.android.debug }
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1809)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1523)
        at android.app.Activity.startActivityForResult(Activity.java:4234)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:675)
        at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:234)
        at androidx.fragment.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:795)
        at androidx.fragment.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:932)
        at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java:1278)
        at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java:1266)
        at io.homeassistant.companion.android.onboarding.integration.MobileAppIntegrationFragment.requestBackgroundAccess(MobileAppIntegrationFragment.kt:231)
        at io.homeassistant.companion.android.onboarding.integration.MobileAppIntegrationFragment.onRequestPermissionsResult(MobileAppIntegrationFragment.kt:200)
        at androidx.fragment.app.FragmentActivity.onRequestPermissionsResult(FragmentActivity.java:768)
        at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7126)
        at android.app.Activity.dispatchActivityResult(Activity.java:6978)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4140)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4187) 
        at android.app.ActivityThread.-wrap20(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1544) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6188) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:801) 
2020-08-27 07:55:30.172 569-1440/? W/ActivityManager:   Force finishing activity io.homeassistant.companion.android.debug/io.homeassistant.companion.android.onboarding.OnboardingActivity
2020-08-27 07:55:30.189 18781-18781/io.homeassistant.companion.android.debug I/Process: Sending signal. PID: 18781 SIG: 9
2020-08-27 07:55:30.296 569-18144/? I/WindowManager: WIN DEATH: Window{ffeffe3 u0 io.homeassistant.companion.android.debug/io.homeassistant.companion.android.onboarding.OnboardingActivity}
2020-08-27 07:55:30.297 569-5380/? I/ActivityManager: Process io.homeassistant.companion.android.debug (pid 18781) has died
2020-08-27 07:55:30.306 569-669/? W/Eve: MEMORY_LEVEL: [18781,199]
      top=io.homeassistant.companion.android.debug/io.homeassistant.companion.android.onboarding.OnboardingActivity launching=false
      prev=com.android.packageinstaller/.permission.ui.GrantPermissionsActivity screen_on=true thermal=0
      adb=true downloading=false
      memory=200 available=360708KB free=83264KB
2020-08-27 07:55:32.571 569-988/? I/ActivityManager: Force stopping io.homeassistant.companion.android.debug appid=10179 user=0: from pid 19311
2020-08-27 07:55:32.590 2708-2708/? D/ECS_TimeoutManager: Clearing timeout for io.homeassistant.companion.android.debug due to android.intent.action.PACKAGE_RESTARTED
```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
Was attempting to implement the recommendation here: https://stackoverflow.com/a/33114136

However not having much luck :)
